### ISSUE TITLE
Android: Persistent notification no longer displayed when Tailscale is enabled since 1.52.0

### ISSUE THREAD

**Issue by praneetloke** [tailscale/tailscale#10104]
### What is the issue?

I don't know if it's a mistake that it was removed starting with 1.52.0? The Tailscale notification icon is not visible anymore when it is enabled. Note that the Tailscale VPN does seem to be active as I see my exit node's IP. So at least the service seems to be working fine despite the missing notification.

I've also reinstalled the app just to be sure and the notification is still missing when the service is enabled.

### Steps to reproduce

- Install version 1.52.0 for Android from the Play Store
- Launch the app and start the service

### OS

Android

### OS version

14

### Tailscale version

1.52.0

### Bug report

BUG-377951e970d89c8a751d22029ecda09efa7f67f057335bcd32a37e767a0911f3-20231103072509Z-52fd44f994d0128d

**Comment by DentonGentry** [comment]
Oddly, the persistent notification does work on an Android 12 device here. This is the one you mean?

![Screenshot_20231103-063505](https://github.com/tailscale/tailscale/assets/1140756/262bc86d-a6d3-4727-9b83-caba28111d58)

**Comment by praneetloke** [comment]
Nope not that one. That's the Android OS icon for an active VPN connection. I am referring to app notifications that show up to the left side where your other notifications are in that screenshot (GMail, LinkedIn, GH etc.) There used to be a persistent notification there with the Tailscale logo there. If you rollback to 1.50 you'd see it. (I would rollback myself if the Play Store offered a way but it doesn't unfortunately.)

**Comment by acutbal** [comment]
Hello,
I also have noticed that on my two Android devices, a Samsung tablet and a Poco phone. Furthermore, I've realized that the notifications are disabled, there's no possibility to enable it. 
I attach some screenshots.
![Screenshot_20231105_121853_Settings](https://github.com/tailscale/tailscale/assets/2278584/d583c53c-95cd-459a-b0eb-67782307444d)
![Screenshot_20231105_122956_One UI Home](https://github.com/tailscale/tailscale/assets/2278584/638c8813-c325-4821-8ef6-307b8455e988)
![Screenshot_20231105_121853_Settings](https://github.com/tailscale/tailscale/assets/2278584/720013ae-0cf9-4784-8b44-3515701d77d3)
![Screenshot_20231105_122747](https://github.com/tailscale/tailscale/assets/2278584/dd78db8d-e2ff-4bb2-888c-44d2f35b56ca)
![Screenshot_20231105_122931_One UI Home](https://github.com/tailscale/tailscale/assets/2278584/c39b1473-e96f-411a-bfc5-2ab5a70d54ba)

Best regards!!

**Comment by praneetloke** [comment]
@acutbal I actually don't see any of the notification categories/channels under "Notifications" for this app in 1.52.1. I am on Android 14 though.

**Comment by undulattice** [comment]
Same issue here.
V 1.52.0

![Screenshot_20231107-131317.png](https://github.com/tailscale/tailscale/assets/63560223/244bf769-0aa3-4150-b2c4-73763e1e7cd1)

**Comment by ladfrombrad** [comment]
![Screenshot_2023-11-08-20-35-22-166_com miui securitycenter](https://github.com/tailscale/tailscale/assets/96320569/7282d53d-8586-40fc-bd7e-88922d48accd)

Same over here even on prior built Fdroid builds (1.48 does, ask for Notification Access on opening), but oddly doesn't seem to affect my Chromebook notification/foreground service?

**Comment by prsu12395** [comment]
Same issue on Pixel 5, Android 14.
Version 1.52
It is quite annoying the push notification is not showing. It used to be the sign when the connection is created and I can click on the notification to turn VPN off when I'm done. Without it, I keep forgetting the VPN is on.

**Comment by RaheelJameel** [comment]
Same issue on Android 13.
No notification is shown and in the system notification settings for Tailscale, the notification enable option is disabled.
Downgrading Tailscale to 1.48.2 shows the notification but not on 1.51.207 or 1.53.115.

This seems to be a problem with the app not able to target newer Android versions.
Because on an Android 11 device with Tailscale 1.53.115, the notifications are showing.

**Comment by DhruvaSambrani** [comment]
Its worse than that. Since Taildrop needs the notifications to work, Taildrop now doesn't work when sending to android

**Comment by abunasar** [comment]
Any update on this? Same issue on android 14 (Samsung)

**Comment by nuentes** [comment]
I'm having this issue as well on my pixel 6A with Android 14. I actually thought this was intentional for some reason, because I'm a newer Tailscale customer. However I recently installed tailscale on my tablet, which is running FireOS, and I see the persistent notification on that device.

**Comment by pjdubya** [comment]
Same issue here. Pixel 7 Pro, Android 14, everything up to date. It's a problem for me because when I forget that the tunnel is active, my battery dies very quickly. The persistent notification is annoying but it's better than an unexpectedly dead battery. If users who don't want the persistent notification can just turn it off via the app settings, everyone wins.

**Comment by TrishenSuresh** [comment]
Same issue with my Samsung Fold running Android 14

**Comment by PRSXFENG** [comment]
> Why has this issue not been fixed yet? It's not like it is a rare case, this is affecting Android phones with the recent versions of Android, 13 and 14 confirmed.

It has been tagged as "L1 Very Few" which is clearly not the case as it affects everyone on a modern version of Android

Was there no testing done on a modern Android device as it would be seen immediately

Here's some docs from Google
https://source.android.com/docs/core/display/notification-perm

**Comment by alex-ball-bluewaters** [comment]
Same issue for us - we have a pilot currently running with approximately a dozen android users. All have running Android 13/14 and none get the reauth notification and therefore forget to reauth each week (we have reauth set to 7 days). 

So +1 customer for fixing this - assume it's all Android users on 1.52.0 and Android 13+

**Comment by praneetloke** [comment]
@DentonGentry I opened a PR to fix this issue. It would be great to have this restored without further delays.

**Comment by barnstar** [comment]
@praneetloke The patch will have to be rebased.  We are in the process of updating the code base to use modern android APIs for the UI side of things. We've preserved the existing client in /android_legacy so we can continue to push updates to the current app while that work is in progress.  The changes on the Java side will have to be applied there (instead of in /android).  I'll take a look when that's done.

**Comment by vvirtues** [comment]
Ive had this issue for a while with the notifications force disabled thinking i had messed up my system
Good to know Im not alone

**Comment by praneetloke** [comment]
@barnstar @kari-ts while the beta version is nicer to use I had to leave it because of bugs. I noticed that there hasn't been a release for the current release version with the fixes from https://github.com/tailscale/tailscale-android/pull/178. Will it not receive a patch release at all at this point?

**Comment by pjdubya** [comment]
> @barnstar @kari-ts while the beta version is nicer to use I had to leave it because of bugs. I noticed that there hasn't been a release for the current release version with the fixes from [tailscale/tailscale-android#178](https://github.com/tailscale/tailscale-android/pull/178). Will it not receive a patch release at all at this point?

Actually check the play store for updates again. My phone updated yesterday with the May 6 update and I only noticed it because I hadn't even opened Tailscale myself but the old notification appeared. So it's there again finally. I don't know if it's working correctly though. For me (P7P, latest Android), if i enable the connection, the notification will correctly show "Connected", but if I select that notification it'll just silently disconnect the Tailscale connection. The notification icon remains how it was but the label changes to Not Connected. The app never comes into the foreground to tell you that that's how it's interpreting the click of the notification. I thought that it used to just take you to the main Tailscale app view so you could see the more detailed status of your Connected network, rather than what I just described. No?

**Comment by praneetloke** [comment]
> Actually check the play store for updates again.

Oh you are right. I just checked the Play Store and it looks like the new UI is now the latest release version? But it's quite buggy for me. The VPN status sometimes gets stuck and never toggling. The notification, although visible, isn't persistent like it was in the old version. And if I disconnect, a notification is created for the disconnect while I have the app in the foreground which seems redundant to me. I can understand if the app was in the background and the VPN disconnected but it would be nice in that case to use a different icon to clearly distinguish between a connect/disconnect event.

In addition to that, starting Tailscale from quick tile action sometimes works and sometimes doesn't for me.

**Comment by pjdubya** [comment]
Oh I see what you mean about the quick tile. It's strange because that used to work fine for me in the previous version of the app on this new code base,, at least I am fairly sure it did. But now it only works to toggle it off. If it's not connected already when I hit that tile it takes me to the main app where it shows the disconnected state, rather than quickly toggling on like it should. 

I agree that I think a different icon would help to distinguish connected vs not connected states.

**Comment by kari-ts** [comment]
We are working on further improvements to Quick Settings tile and the persistent notification. Thank you for your feedback and for your patience with us as we continue to work on this!

**Comment by pjdubya** [comment]
> We are working on further improvements to Quick Settings tile and the persistent notification. Thank you for your feedback and for your patience with us as we continue to work on this!

Awesome, glad to hear it! You guys are the best. Shout if you need us to beta test anything.

**Comment by xcpn** [comment]
> We are working on further improvements to Quick Settings tile and the persistent notification. Thank you for your feedback and for your patience with us as we continue to work on this!

Any updates on this? I think persistent notification when Tailscale is active is an absolute must.

Currently on latest version via Play Store and the notification can easily be swiped away even though Tailscale is active.
