### ISSUE TITLE
Restoring/migrating iOS settings to a new device duplicates Tailscale IPs

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1016]
**Describe the bug**
When we migrate the iOS device with Tailscale installed, it assigns the same IP address to both the iOS devices you migrate from and migrate to.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Install Tailscale and authenticate the iOS device.
2. Migrate the IOS device to another iOS device using the backup.
3. try to re-authenticate both the device. Getting the same IP address.
4.Try to delete and reinstall the app, still get the same Tailscale IP addresses.

**Expected behaviour**

**Version information:**
 - Device: iOS Device

Additional Notes:
Deleting and resetting the application and VPN certificate to no avail.

**Comment by bradfitz** [comment]
Dup of #969

**Comment by Syzygies** [comment]
Instead of "closed" you could perhaps reveal the one-linker to actually uninstall Tailscale so a reinstall chooses a new ip address? I'm having the same problem. I just want to understand how to get Tailscale to start from scratch. This bug is not resolved.

**Comment by DentonGentry** [comment]
> It would be easy enough to invalidate a saved IP address when the machine identity changes. Why not?

Because in most cases when one clones a machine intending it to take over the old machine, having it take over the Tailscale identity is the desired outcome. I understand that for your case it was not.

You also commented on https://github.com/tailscale/tailscale/issues/969#issuecomment-1207280040, we'll handle anything else there.

**Comment by Syzygies** [comment]
Huh. I thought most tailscale users had more than one machine. I can touch four from my chair right now.

**Comment by DentonGentry** [comment]
Many users have more than one machine, and had you installed the app on those four machines each would get its own node key and IP address. We're talking about cloning an existing system.

If you want help in recovering you can use https://github.com/tailscale/tailscale/issues/969, which this issue was closed as a duplicate of, or email support@tailscale.com.

**Comment by Syzygies** [comment]
I'm not being clear. I bought a new M2 MacBook Air. I reluctantly use Migration Assistant because I have a complicated setup and starting from scratch costs me several days. I cloned another Apple Silicon machine rather than the Intel machine I'm replacing, so that any binaries and layouts (such as homebrew) tuned to the architecture would match.
