### ISSUE TITLE
macOS TCC dialog for Downloads folder access opens without reason

### ISSUE THREAD

**Issue by winterqt** [tailscale/tailscale#10180]
### What is the issue?

When waking my computer from sleep, Tailscale requested access to my Downloads folder, without me having ever sent a file through Taildrop. (I have never used Taildrop.)

### Steps to reproduce

1. ???
2. Receive TCC prompt for Downloads folder access without reason

### OS

macOS

### OS version

macOS Ventura 13.6.1

### Tailscale version

1.52.0 from the Mac App Store

### Bug report

BUG-5838ce15b45694611512a069cbfee39fe19e8cb51f28af4ff6fc581a2b1cb9dd-20231109025032Z-ba61b020a369fb95

**Comment by DentonGentry** [comment]
[Taildrop](https://tailscale.com/kb/1106/taildrop/) will only write to the Downloads folder (and trigger an access request) the first time a file is sent to a Mac. However there is a background cleaner which reads from the Downloads folder to detect partially completed Taildrop files, and it runs even if no file has ever been sent. It does this because when Tailscale.app starts, it doesn't know whether there might be a partially completed file from a previous run of the app.

In testing this didn't turn up as a problem, but even reading from the Downloads folder is triggering the access request. We're going to make the cleaner only run after the first file is sent to the Mac.

**Comment by winterqt** [comment]
Thank you for the clear explanation about what is going on.

Does the cleaner run irregularly in between restarts? (Does it make sense that I would have only received it once, a few days ago, and not any time before that?)

Or is this impossible to determine without adequately verbose logs, which can't be retroactively enabled?

**Comment by agottardo** [comment]
1.54.0 should have fixed this, as reported in the [changelog](https://tailscale.com/changelog/#2023-11-15-service).
