### ISSUE TITLE
FR: Android autostart

### ISSUE THREAD

**Issue by A2Sumie** [tailscale/tailscale#10244]
### What are you trying to do?

Letting tailscale autostart and autoconfigure on Android devices.
Already tried Always On VPN mentioned in #510 but Tailscale will just not connect unless manually altered.
As there is no config or settings for this in the Android client, I'm requesting this feature.

### How should we solve this?

Adding settings and wizards for Tailscale android autostart. 
Or maybe just letting Tailscale work with always on vpn, as it had worked in #510 .

**Comment by Johnny-Larue** [comment]
Same as #9428

**Comment by agottardo** [comment]
Just a heads-up that this issue has been fixed in our new Android app. Tailscale will automatically restart upon a system restart when set to always-on. You can try the new version by joining the [beta testing track](https://play.google.com/apps/testing/com.tailscale.ipn) on the Play Store. 

If you're still experiencing this issue, please let us know.
