### ISSUE TITLE
FR: SCIM provisioning based on if user is assigned to app

### ISSUE THREAD

**Issue by DariB123** [tailscale/tailscale#10383]
### What are you trying to do?

I've done some tests and currently with Microsoft EntraID users and groups not assigned to Tailscale can still authenticate and have an account created for them. 

This isn't ideal because some users in my tenant have no need to use Tailscale and therefore shouldn't be able to log in to it.

### How should we solve this?

This should be changed to that only users assigned to the app or in a group that is assigned to the app can log in and have  an account created.

### What is the impact of not solving this?

From a securtity standpoint this puts me off using tailscale at all.

**Comment by DentonGentry** [comment]
Okta provides that functionality, but to my knowledge AzureAD/Entra does not. Any user in the tenant will be sent to the OIDC redirect URL of any client.

**Comment by DariB123** [comment]
@DentonGentry Sorry my knowledge of OIDC isn't great. Are you saying this functionality isn't possible due to a limitation in EntraID? Seems pointless to have authentication if you are going to let anyone log into an app regardless of permissions.

**Comment by DentonGentry** [comment]
> Are you saying this functionality isn't possible due to a limitation in EntraID?

I'm saying that to my knowledge, Entra does not provide a way to allow only certain users to use an OIDC app like Tailscale. Entra will redirect any user to the Tailscale app.

This is not a choice which Tailscale gets to make. What we can do within Tailscale is control what those users are allowed to access.

> Seems pointless to have authentication if you are going to let anyone log into an app regardless of permissions.

SCIM provisions users and groups from the identity provider to Tailscale. The main purpose of Group sync is to be used in access controls: https://tailscale.com/blog/sync-azuread-groups/

The point of authenticating with SCIM is:
- to be able to allow or deny access to users based on what group they are in.
- to disable a user's access to the tailnet automatically when they are disabled in Entra.

**Comment by DariB123** [comment]
Thanks for the explanation @DentonGentry. 

I know to lock down the tailnet by using groups in the policy.

I do think that restricting users from signing up to tailscale will be useful as it saves seats being occupied by individuals that don't need accounts.

**Comment by DentonGentry** [comment]
> saves seats being occupied by individuals that don't need accounts.

Users are billed if they actively use the service to transfer data:
https://tailscale.com/kb/1251/pricing-faq/#how-are-monthly-active-users-defined
If they are blocked from access to anything, they will be inactive users.

> I do think that restricting users from signing up to tailscale will be useful as it

The difficulty we have with preventing the user from signing up based on group memberships is a chicken-vs-egg problem:
- we need to create the user in order to fetch their Group memberships
- only after we fetch the Group memberships do we find out that we should not have created the User

Other IdPs like Okta handle permissions to access the Tailscale app all the way back in the identity provider. If the user does not have access to the Tailscale app, Okta does not redirect them to the Tailscale OAuth endpoint at all. Tailscale is never told about their existence and does not need to fetch group memberships.

**Comment by DariB123** [comment]
It isn't perfect but could you check group memberships after creation and delete the account if they aren't in one of the assigned groups?

**Comment by DariB123** [comment]
Hi Again.

So it looks like Entra does support this through the "Assignment required?" toggle which is default off. I have tested and it does restirct access to only assigned groups.

**Comment by DentonGentry** [comment]
Oh, that's great.

We'll add that to documentation as well.

**Comment by DentonGentry** [comment]
We added https://tailscale.com/kb/1249/sso-entra-id-scim/#restricting-access-to-the-tailscale-application to describe how to do this.
