### ISSUE TITLE
GitOps ACL seems to break Mullvad Exit Node functionality

### ISSUE THREAD

**Issue by heywoodlh** [tailscale/tailscale#10610]
### What is the issue?

I use GitHub Actions to apply an ACL as described here: https://tailscale.com/kb/1204/gitops-acls

I also have the Mullvad exit node functionality enabled.

When a new change is applied to my ACL via GitOps, it breaks my Mullvad exit node configuration and I have to re-add all the devices I want to use Mullvad for.

I.E. here's my Mullvad panel after a new ACL was applied via GitHub Actions (previously, had three devices):

![image](https://github.com/tailscale/tailscale/assets/18178614/ca329c58-56b6-420a-a9bb-be637345bc6a)

And here's the "unknown device" error in the Tailscale iOS app
![tailscale-issue](https://github.com/tailscale/tailscale/assets/18178614/fe503d45-88ca-40b3-a456-76583a87391c)

### Steps to reproduce

1. Enable Mullvad integration
2. Add devices that you'd like to use
3. Apply new ACL via GitOps
4. Exit node stops working, in mobile app observe that Exit Node has now become "unknown device"

### OS

Linux, iOS

### Tailscale version

1.56.0 (iOS), 1.54.0 (Linux)

### Bug report

BUG-d6c46804f2a1fae0f37b53c328d491186ca380766670c93a98151c63ab80e266-20231215033546Z-6846b3490087b40f

**Comment by catzkorn** [comment]
If you are using ACLs managed by GitOps, you will need to declare the devices to be used with Mullvad in the [ACL configuration](https://tailscale.com/kb/1258/mullvad-exit-nodes#configuration-for-teams) and not via the device selector on the admin panel - otherwise they will be overwritten as you are experiencing.

There should be a banner that indicates this on the device selector page, however it does not seem to be present in your screenshots. Has it ever been present?

**Comment by catzkorn** [comment]
To give some further context - the device selector in the admin panel is a GUI to add Mullvad devices into your ACL file. If you are overwriting that with a configuration via having your ACLs managed by GitOps or similar, anything configured via the device selector will be lost.

**Comment by heywoodlh** [comment]
@catzkorn using NodeAttributes as described in that doc seems to have fixed it, thank you!

Now, an issue with this, is that there's no devices listed with the web UI. Would be nice to see the targeted devices populate in the web UI -- along with the projected cost.

But, I'm going to close this as my original issue is taken care of.

**Comment by catzkorn** [comment]
Hi! 

Thanks for the feedback, I will discuss it with the team.

Just to follow up on the missing banner, we do display a warning as well as disable the ability to use the GUI when this comment is in the ACLs:

`// This tailnet's ACLs are maintained in <link to the repo>`.

It has to match that string exactly. Do you have that in your ACLs/does it match? I know we have previously had users who have either done `tailnets` instead of `tailnet's` and `ACL's` instead of `ACLs` which unfortunately breaks the warning but it is a very subtle difference.

**Comment by heywoodlh** [comment]
> Just to follow up on the missing banner, we do display a warning as well as disable the ability to use the GUI when this comment is in the ACLs

I do have this in my ACL, but to clarify, what I meant by “no devices in the web UI” is that there are no devices in the UI listed as using the Mullvad integration:

![image](https://github.com/tailscale/tailscale/assets/18178614/3ece4c1f-3dcd-4291-acc9-ab0bc2499c85)

I do have it turned on about 4 of my devices — it would be nice if I could see that in the Web UI and know what my Mullvad costs are :smile:

(This is a very minor thing, and I understand if it’s not possible to populate this when using GitOps ACLs — but it would be nice!)
