### ISSUE TITLE
Admin console UI Machines tab should have the sorting enabled on Last Seen tab

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1061]
Admin console UI Machines tab should have the sorting enabled on Last Seen tab

![image](https://user-images.githubusercontent.com/75628398/103038090-89125880-453b-11eb-922a-306c6c51623a.png)

**Comment by rosszurowski** [comment]
Wait, @darshinimashar can you explain more? You're asking for the ability to sort by the "last seen" column?

I'd like to avoid sortable tables for as long as possible because (a) they're annoying to implement and maintain and (b) they're usually a proxy for a better kind of sorting/filtering that I think we could answer with a query system. For example, "show me machines that are offline" (i.e. haven't been seen in several days/weeks).

**Comment by rosszurowski** [comment]
Closing this out since we now have the start of a filtering system which is a better solution to this problem.

**Comment by soniaappasamy** [comment]
> Closing this out since we now have the start of a filtering system which is a better solution to this problem.

+1
