### ISSUE TITLE
FR: Move code to GitLab or Codeberg

### ISSUE THREAD

**Issue by julianfairfax** [tailscale/tailscale#10715]
### What are you trying to do?

GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

### How should we solve this?

It would be nice if the app's code were moved to GitLab or Codeberg.

**Comment by bradfitz** [comment]
If we moved to X, we'd have even more people filing bugs asking us to move back to Y. (I know, because I remember this from before Go was hosted on GitHub. See also: https://www.pypy.org/posts/2023/12/pypy-moved-to-git-github.html)

We're going to stay at GitHub until there's a compelling enough reason to move away from the largest audience of developers.
