### ISSUE TITLE
No 1.58.0 for macOS on pkgs.tailscale.com

### ISSUE THREAD

**Issue by wahjava** [tailscale/tailscale#10926]
### What is the issue?

It seems that https://pkgs.tailscale.com/stable/#macos only lists 1.56.1 as of this moment, while App Store carries 1.58.0, perhaps someone failed to update it, or some update job fail(ed|ing) ?

Thanks!

### OS

macOS

### OS version

macOS

### Tailscale version

1.56.1

**Comment by DentonGentry** [comment]
https://tailscale.com/changelog#2024-01-18-client
"Note: Rollout of 1.58.0 paused on 21-Jan-2024 while we investigate reports of a regression with portmapping."

The App Store rollout was paused at 5%. We don't have a non-destructive way to pull the release down from the App Store. If we do pull it down we have to submit a new binary which will not match the original in timestamps and so on.

The https://pkgs.tailscale.com/stable/#macos version was removed from the site altogether while we investigate.

**Comment by DentonGentry** [comment]
The issue is https://github.com/tailscale/tailscale/issues/10911, which manifests when there is a UPnP response containing no usable <service> blocks. We can reproduce it using very, very old home routers from when UPnP was a DSLForum spec. Modern home routers contain one or more services.

This was a regression which in aggregate causes user pain, but is very specific to the deployment. We'll be building a 1.58.1 with a fix, probably tomorrow. I imagine you'll be able to roll forward to 1.58.1 in roughly the same timeframe as rolling back to 1.56.1.

**Comment by wahjava** [comment]
Sure, if it's coming out tomorrow, then I guess we can wait.
