### ISSUE TITLE
No Helm chart published for latest version

### ISSUE THREAD

**Issue by bkonicek** [tailscale/tailscale#10951]
### What is the issue?

The latest version of the Helm chart in https://pkgs.tailscale.com/helmcharts is `v1.56.1` when Tailscale `1.58.2` is now out. Since the published charts are relatively new I'm not sure if there's a manual process behind the scenes or if there's some automation in place that should be doing it.

### Steps to reproduce

```
> helm repo update
> helm search repo tailscale --versions
NAME                        	CHART VERSION	APP VERSION	DESCRIPTION
tailscale/tailscale-operator	1.56.1       	v1.56.1    	A Helm chart for Tailscale Kubernetes operator
tailscale/tailscale-operator	1.56.0       	v1.56.0    	A Helm chart for Tailscale Kubernetes operator
```

### Are there any recent changes that introduced the issue?

N/A

### OS

macOS

### OS version

MacOS Big Sur 11.7

### Tailscale version

1.56.1

### Bug report

N/A

**Comment by DentonGentry** [comment]
The container images have not been published yet, which includes the Helm chart. Because so many workflows update the container the instant a new version appears, the container images are pushed a couple days after the RPM and deb images go live to give time to look for unexpected behaviors or weirdness.

**Comment by bkonicek** [comment]
Ah that explains it, I hadn't noticed there were no container images published yet either. Thanks!
