### ISSUE TITLE
Latest 1.58 not released for docker

### ISSUE THREAD

**Issue by seanob86** [tailscale/tailscale#10963]
### What is the issue?

dockerhub and ghcr, latest and/or stable tag corresponds to version 1.56.1

[ghcr](https://github.com/tailscale/tailscale/pkgs/container/tailscale)

[dockerhub](https://hub.docker.com/r/tailscale/tailscale/tags)

1.58.2 has been released 4 days ago according to [github](https://github.com/tailscale/tailscale/releases/tag/v1.58.2)

### Steps to reproduce

Any of the following pull commands will only pull down version 1.56.1
```
docker pull tailscale/tailscale:latest
docker pull ghcr.io/tailscale/tailscale:latest
```

### OS

Other

### OS version

Docker on Debian 12

### Tailscale version

1.56.1

**Comment by DentonGentry** [comment]
Because so many sites automate deployment of container images the instant they appear, we routinely wait at least a day after release to look for anything unexpected that didn't turn up in testing.

There was something unexpected after 1.58.0, a regression in portmapping with very old router devices: https://github.com/tailscale/tailscale/issues/10911.

1.58.2 was released on Friday, containing a fix for that issue. We do not do releases on the weekend, so the container 1.58.2 release would be sometime next week.

**Comment by irbekrm** [comment]
Thanks for your patience folks!

`v1.58.2` images have now been released to both Dockerhub and ghcr.io.
