### ISSUE TITLE
Tailscale is not in the Apple App Store in Hong Kong

### ISSUE THREAD

**Issue by kellytrinh** [tailscale/tailscale#1104]
As per subject - a search on app store or going via link from download page from admin console on tailscale.com doesn't work anymore.

**Comment by danderson** [comment]
We're not able to reproduce here, both the Android and iOS app stores continue to offer the Tailscale app.

Did you by any chance travel recently? Due to local laws about VPN apps, Tailscale is not available in a few geographic areas (most notably China and Hong Kong). If you can share the country you're accessing from, we can check the app publication settings in more detail.

**Comment by kellytrinh** [comment]
I am accessing from HK. This is incredibly vexing as it is correct that I
just relocated recently and now cannot use tailscale on new devices.

Can mark as solved but is it possible to share why HK is out of scope?
There are plenty of VPN apps available

**Comment by danderson** [comment]
Looking into this, I think we can indeed publish Tailscale in Hong Kong. I just updated our app store listing to publish there, although I'm not sure when exactly that will take effect. Can you try again and see if the app is available now?

**Comment by kellytrinh** [comment]
Can confirm now your fix works.  Issue resolved.
