### ISSUE TITLE
Failed to connect to Tailscale service

### ISSUE THREAD

**Issue by sholland-bamboohealth** [tailscale/tailscale#11209]
### What is the issue?

---------------------------
Tailscale Error
---------------------------
Failed to connect to Tailscale service.

Version 1.60.0 (tb36943c9b-g99e84774b)

LogID: 35acbfdd8f6b8513d85a2ef15fe9acc983f10b402451535c8bdbb079227b1a78

(Ctrl-C to copy this text)

---------------------------
OK   
---------------------------

### Steps to reproduce

restart and wait a few days

### Are there any recent changes that introduced the issue?

No

### OS

Windows

### OS version

Edition	Windows 10 Pro Version	22H2 OS build	19045.4046

### Tailscale version

Version 1.60.0 (tb36943c9b-g99e84774b)

**Comment by raggi** [comment]
Outbound connections are being denied by a policy engine in your system network stack. Typically this is some software such as Zscaler or Crowdstrike. Tailscale can be integrated alongside these products, but it does not attempt to actively circumvent policies that are blocking connections.

You will need to adjust the policy that is blocking network connections in order to use the Tailscale client.
