### ISSUE TITLE
FR: Share a node with all Tailscale users

### ISSUE THREAD

**Issue by levidurfee** [tailscale/tailscale#11413]
### What are you trying to do?

I would like to create a service that I can share with anyone using Tailscale without having to individually share the node with each user or Tailnet.

**Comment by raggi** [comment]
How would you envisage this feature to work exactly - how would users opt in to seeing your service?

**Comment by levidurfee** [comment]
I think I would create a node that I designate as being a public internal Tailscale node. I don't think users would opt in to seeing my service, but it would be available to them. I think IP address conflicts would be the biggest challenge.

In order to give a little more context to the request. I was thinking about running a logging service that listens for UDP packets and how I could secure their transit across the internet. While I could share a node on a case-by-case basis, I thought this idea sounded interesting.

**Comment by raggi** [comment]
The challenge is that membership in a tailnet, even as a shared in node exposes some amount of data about those other users nodes, so that the two sides can communicate with each other. This would mean your service would be granted details of every single node in tailscale, which would likely be untenable for your node, but also it would expose lots of users data in an undesirable way.

You can however create a re-usable sharing link, and users can opt-in to using your service. You can create a simple web service that users can enter their emails into, and it would simply send another invite to those users.

**Comment by levidurfee** [comment]
Thank you for taking the time to have a conversation with me about this. I love Tailscale :)
