### ISSUE TITLE
Kubernetes operator: clean up proxy firewall rules

### ISSUE THREAD

**Issue by irbekrm** [tailscale/tailscale#11941]
### What is the issue?

Currently, when state changes whilst the proxy `Pod` is running (i.e proxy's target backend's IP changes), we install new rules on top of the existing ones (with higher priority). No-longer valid rules can stay on top if the state has changed in a way that a valid rule can no longer be produced (i.e the proxy cannot determine the backend's IP address), which can result in confusing errors for users.

We should ensure that old rules are always removed when they don't apply.
In case of iptables, we'd probably need to flush the whole chain- this should be fine to do as in containers we don't expect anything else to touch those chains.

(cc @oxtoacart )

**Comment by oxtoacart** [comment]
We had hoped to be able to handle this by flushing whole chains. This won't work. Our firewall changes include three changes:

- Add MSS into the `ts-clamp` chain. Nothing else uses this, so we could flush it.
- Add a DNAT rule to the `PREROUTING` chain. Nothing else uses this, so we could flush it.
- Add an SNAT rule to the `POSTROUTING` chain. Unfortunately, this is also used by tailscaled for some other things, so we can't flush it.

The alternative to flushing whole chains would be to refer to specific rules by some kind of ID. We could do this in nftables using handles or maybe userdata, but we can't do this in the iptables implementation because of [this open bug](https://github.com/coreos/go-iptables/issues/97).

So for now, we're going to close this.
