### ISSUE TITLE
[Bug]: Forwarding stopped working in v1.66

### ISSUE THREAD

**Issue by kroese** [tailscale/tailscale#12069]
### What is the issue?

In the release notes it was written that changes were made for packet-filtering nodes.

But in my case, a Tailnet WITHOUT any exit-nodes or subnet-routers or LAN, version 1.66 breaks my working setup. 

My setup is that I have machine A, which accepts packets from the internet (WAN) and forwards them to the Tailscale IP of machine B using `firewalld` rules.

This works fine in v1.64 but not on v1.66. 

So it seems this new release should have been tested more, because even without exit-nodes or subnet-routers or LAN, it can still break existing systems without warning.

### Steps to reproduce

- Forward internet (WAN) traffic to a Tailscale IP
- Upgrade to v1.66

### Are there any recent changes that introduced the issue?

Upgrade to v1.66

### OS

Linux

### OS version

Ubuntu 24.04

### Tailscale version

1.66

### Bug report

BUG-01f173494e22c373b404d5d60dd4e2ee695746f2882b0e5d821b48484d022dba-20240509095143Z-b385147b7075346e

**Comment by knyar** [comment]
> Yes, I am running up and it says I must specify all non-default flags and suggests me to use:
> tailscale up --stateful-filtering=false  --advertise-exit-node

This means that your node is currently configured to [advertise](https://tailscale.com/kb/1103/exit-nodes#advertise-a-device-as-an-exit-node) an exit node (even if it's not approved in Admin Console or used by any other nodes). If you don't want that, you can re-run the command with `--reset` flag added, e.g. `tailscale up --stateful-filtering=false --reset`.

**Comment by knyar** [comment]
I understand your frustration, and I am sorry that introduction of stateful filtering resulted in unexpected dropping of your forwarded traffic. As you might be aware, this was part of [a set of coordinated changes](https://tailscale.com/security-bulletins#ts-2024-005) we released to address a potential security issue. Manually forwarding internet traffic to another Tailscale node using `iptables` is not something that a Tailscale client is currently designed to accommodate automatically, and for now I would recommend keeping stateful filtering disabled. We'll discuss this internally to explore whether we can handle this use case better.

I agree that the way stateful filtering has been documented in [the changelog](https://tailscale.com/changelog) does not make it clear that it will be enabled on Linux nodes that are not being used as exit nodes or subnet routers. We will make sure to address that.

**Comment by awly** [comment]
@kroese first of all, sorry about breaking your setup!

When deciding on a fix for https://tailscale.com/security-bulletins#ts-2024-005 we discussed the possibility that some users rely on the existing behavior of forwarding packets from outside into their tailnet, even though it was not intended. To be on the safe side, we made Tailsacle exit nodes and subnet routers block inbound connections by default. Users that are less well-versed in routing than yourself would find it unexpected when external hosts could reach their supposedly "isolated" tailnet.

Your setup is even more advanced, with custom iptables rules to enable forwarding. Unfortunately, we can't reliably parse pre-existing iptables rules to figure out whether a system is intentionally configured to route connections into the tailnet. From tailscaled's perspective, your intended traffic flow is indistinguishable from the attack scenarios we described in the bulletin.

Can you confirm that `tailsacle up --stateful-filtering=false --reset` fixes the issue on 1.66 for you?
If yes, we will document this case somewhere, but otherwise leave the behavior unchanged for the benefit of other users.

**Comment by asavageiv** [comment]
Does anyone have this working today? I'm trying to forward traffic for a game through my VPS to a server in my Tailnet and even with stateful-filtering=false and ACLS with the `autogroup:danger-all` I can't get it working.
