### ISSUE TITLE
FR: One tap on main UI to connect tailnet for Android 

### ISSUE THREAD

**Issue by mkevinstever** [tailscale/tailscale#12124]
### What are you trying to do?

Current, Android version have two buttons for two different features:
enable --> use exit node. 
slide block --> connect to tailnet. 

It's awful for some users. it's not user-friendly enough.

### How should we solve this?

if it is possible, only need keep a button use to connect tailnet.
for select exit node, use second layer UI to do that, select none to disable. instead of need a button on main UI to disable or enable. 
![1](https://github.com/tailscale/tailscale/assets/84697424/383fbe77-738e-48cb-a154-615d3fd6bb91)

### What is the impact of not solving this?

Actually, if not change this, it only affect users who don't skill for use phone. such as grandmother.

### Anything else?

This Inspire from this article, I think it would be a great decision: https://tailscale.com/blog/reimagining-tailscale-for-ios

**Comment by sonovawolf** [comment]
Hey @mkevinstever, what I'm hearing is:

1. You want a button for connecting/disconnecting Tailscale.
2. You do not want a toggle for the exit node, you want it to be a dropdown where selecting any exit node uses the selected exit node, and selecting "none" stop using any exit node.

On which version of the Android client are you on?

**Comment by sonovawolf** [comment]
I see. We designed the new Android app to mostly match the UI patterns of the iOS app, because many of our users use both platforms. iOS has the same "problem" you are describing as Android.

What you see in the image you posted (which I'm assuming is from the iOS blog post) is an old iteration where the connect/disconnect Tailscale control is visible only when tapping the connection status. The toggle enables/disables the exit node just like it does today (except that its form factor changed to a button). It has never been exactly like what you are describing.

While we were prototyping the iOS app for the first time, it became apparent that people often reuse their last used exit node. Having a button for enable/disable allows them to do that without having to find their exit node again and again. This is also something that many users praised since then, so I believe you might be in the minority in not finding it useful.

Can you share more about why you think showing both controls is "awful for some users"? I'm especially curious about what kind of users you are talking about.

**Comment by sonovawolf** [comment]
Thank you for the extra context! Having two toggles definitely increases the complexity of the UI, which comes at the cost of intuitiveness for some, but benefits others. It's always a balance. I'll keep in mind what you said and an eye out for this type of users. 

I'll go ahead and close this, but I will get notified if there is activity, in case other folks want to chime in.
