### ISSUE TITLE
[BUG]: Auto Update not working in Debian LXC on Proxmox 

### ISSUE THREAD

**Issue by LeaderbotX400** [tailscale/tailscale#12193]
### What is the issue?

the command `tailscale set --auto-update` returns `automatic updates are not supported on this platform`

### Steps to reproduce

1. Set up a Debian LXC on a proxmox instance
2. Install Tailscale
3. Run the command `tailscale set --auto-update`

### OS

Linux

### OS version

Linux homeserver 6.5.13-5-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.13-5 (2024-04-05T11:03Z) x86_64 GNU/Linux

### Tailscale version

1.66.3

### Bug report

BUG-0238996429885e2ec568d259a8debcb88b8cc8faecc4ffe5a411946a5c909df4-20240519194559Z-b81e3675b503c2e3

**Comment by awly** [comment]
@LeaderbotX400 we disabled support for auto-updates in containers recently: https://github.com/tailscale/tailscale/issues/11544.
Most of the time, containers run immutable infrastructure and automatic updates (especially when they get enabled by default) can be unexpected to some users. I realize that it's not always the case, and sometimes containers are treated as mutable VMs.

As a workaround, you could configure [unattended-upgrades](https://wiki.debian.org/UnattendedUpgrades) to update Tailscale for you.

**Comment by LeaderbotX400** [comment]
> @LeaderbotX400 we disabled support for auto-updates in containers recently: https://github.com/tailscale/tailscale/issues/11544.
> Most of the time, containers run immutable infrastructure and automatic updates (especially when they get enabled by default) can be unexpected to some users. I realize that it's not always the case, and sometimes containers are treated as mutable VMs.
> 
> As a workaround, you could configure [unattended-upgrades](https://wiki.debian.org/UnattendedUpgrades) to update Tailscale for you.

Oh, well that makes sense.

Funnily enough I actual set up unattended upgrades already for this.

Thanks for the info!

**Comment by emigrating** [comment]
> [@LeaderbotX400](https://github.com/LeaderbotX400) we disabled support for auto-updates in containers recently: [#11544](https://github.com/tailscale/tailscale/issues/11544). Most of the time, containers run immutable infrastructure and automatic updates (especially when they get enabled by default) can be unexpected to some users. I realize that it's not always the case, and sometimes containers are treated as mutable VMs.
> 
> As a workaround, you could configure [unattended-upgrades](https://wiki.debian.org/UnattendedUpgrades) to update Tailscale for you.

So, since this isn't made clear anywhere in the docs (at least the ones I have found over the past year or so), that should be fixed. More to the point, you say [you] disabled support for auto-updates in containers recently, which is fair enough, as Docker containers are generally used for immutable services. However, this issue never mentioned Docker containers; what it mentioned was LXC containers running under Proxmox. LXC containers are often used to create environments that resemble full standalone Linux systems, which can very often be mutable.

While LXC containers can be used in an immutable fashion, it's not their inherent design principle. They are commonly employed for system-level virtualization, where the environment can be modified as needed. For example, LXC containers might be used to run full Linux distributions with various services that require regular updates and changes.

I believe it would be beneficial to distinguish between these container types in the documentation and consider supporting auto-updates for LXC containers given their different use cases and flexibility. At the very least, document the automatic disallowance or resetting of the auto-update flag and throw an error or warning message when you set this manually from the CLI. As it is right now, it shows no output whatsoever, and you are led to believe everything went fine, only to find out in a month's time that it has not.
