### ISSUE TITLE
EdgeRouter X Can't have release file

### ISSUE THREAD

**Issue by zjean** [tailscale/tailscale#12237]
### What is the issue?

When calling a sudo apt-get update on a EdgeRouter X:
E: The repository 'https://pkgs.tailscale.com/stable/debian stretch Release' does no longer have a Release file.

### Steps to reproduce

Used this guide months ago (https://github.com/jamesog/tailscale-edgeos), and today updating Tailscale does fail with the above error

### OS

Other

### OS version

Edgerouter X

**Comment by ams72** [comment]
I was able to put 1.60.0 on my ER-X's (plural) last month following the same guide as linked. The tailscale admin console advises updating, but the procedure outlined in the guide, copied from Tailscale's own instructions (https://tailscale.com/kb/1067/update?tab=linux#manual-updates) was failing with the error:
```
~$ sudo apt-get update
Ign:1 https://pkgs.tailscale.com/stable/debian stretch InRelease
Err:2 https://pkgs.tailscale.com/stable/debian stretch Release
  gnutls_handshake() failed: An unexpected TLS packet was received.
Reading package lists... Done
E: The repository 'https://pkgs.tailscale.com/stable/debian stretch Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Fortunately, one of my ER-X's did not fail and updated straight away. After comparing, it turned out to be a storage issue. hotfix 6 was still there.
```
~$ delete system image
The system currently has the following image(s) installed:

v2.0.9-hotfix.7.5622731.230615.0857 (running image) (default boot)
v2.0.9-hotfix.6.5574651.221230.1015

You are about to delete image [v2.0.9-hotfix.6.5574651.221230.1015]
Are you sure you want to delete ? (Yes/No) [Yes]:
Removing old image... Done
```
This was reproducible on all 5 of the 7 ER-X's exhibiting this behavior. I hope this helps.
