### ISSUE TITLE
FR: tailscale set --auto-update=force

### ISSUE THREAD

**Issue by lane-ftw** [tailscale/tailscale#12292]
### What are you trying to do?

In https://github.com/tailscale/tailscale/commit/bff527622d597048c401d42da6cded255f01a48e Tailscale now looks to see if it's running in a docker container or a LXC via `hostinfo.go`, specifically using `func inContainer()` https://github.com/tailscale/tailscale/blob/main/hostinfo/hostinfo.go#L278
When asked why, the response was "Auto-updates were always meant to be disallowed in containers, but we missed that for GA... This is primarily for corporate infrastructure..." https://www.reddit.com/r/Tailscale/comments/1coirr3/comment/l3gbw9y/
I understand this decision. However, I see no reason why users can't choose to have auto updates in containers.

### How should we solve this?

Rather than throwing a middle finger to anyone that uses tailscale on docker/LXC, let us choose to auto update, and keep it off for containers by default.
Give the option of `tailscale set --auto-update=force`, which would bypass the `inContainer` function. Every other check still runs, and everyone gets auto updates (or doesn't)!

### What is the impact of not solving this?

Updates are a crucial part of running an internet connected device, and "Tailscale makes secure networking easy" https://tailscale.com/ you obviously want auto updates to be the default, as it's on in all new tailnets by default. Let's keep everyone up to date in the easiest manner possible.

### Anything else?

You can do it! I believe in you!

**Comment by noncombatant** [comment]
We'll consider this FR. We have some high-priority work going on at the moment so I can't promise a specific timeline.

**Comment by awly** [comment]
I think this is reasonable. For context, the reason this happens is because enabling auto-updates follows the same code path for both `tailscale set --auto-update=true` and for handling the tailnet-wide default [set in the admin panel](https://tailscale.com/kb/1067/update#configure-auto-updates-in-your-tailnet). We don't want people to have to opt-out of auto-updates if they run immutable containers in production.

The ideal behavior should be:
* `tailscale set --auto-update=true` allows enabling auto-updates in containers
* the tailnet-wide default does not automatically enable auto-updates in new nodes running in containers

So we should essentially move the inContainer check out of the[ shared code path](https://github.com/tailscale/tailscale/blob/72f0f53ed01e48bdd18ced74f4fbcc8f2f366e05/clientupdate/clientupdate.go#L166) and into [the latter path](https://github.com/tailscale/tailscale/blob/72f0f53ed01e48bdd18ced74f4fbcc8f2f366e05/ipn/ipnlocal/local.go#L2557) only.

**Comment by lane-ftw** [comment]
Thanks Y'all!
