### ISSUE TITLE
Connection issue on GrapheneOS

### ISSUE THREAD

**Issue by BashBandito** [tailscale/tailscale#12399]
### What is the issue?

While connected to Tailscale, when I leave my house and my connection switches from Wi-Fi to mobile data, despite the app saying I am still connected, I cannot connect to any of my tailnet devices. The only way to fix the connection issue is to disconnect from my tailnet and re-connect. Then it suddenly works just fine.

### Steps to reproduce

Using GrapheneOS, connect to tailscale on Wi-Fi. Then switch from Wi-Fi to mobile data and the connection to tailnet devices should stop working.

### Are there any recent changes that introduced the issue?

I'm not sure. I am new to GrapheneOS so I can't remember if it worked fine before switching to GrapheneOS or not.

### OS

Android

### OS version

GrapheneOS latest version.

### Tailscale version

1.66.3-teae73f821-g63a2bbc8e71

### Other software

Pi-Hole is on my tailnet.

### Bug report

BUG-beda928a68057863f43c81f7e1191a165a773dc28779f34f6f886b62c1a0c80c-20240607164226Z-77407a0b5a61e02b

**Comment by sugarfunk** [comment]
Not exactly the same but similar. Same OS and TS versions.
Mine says connected on Android and dashboard but cannot reach any other devices. Have taillock and needed to manually sign key, but it accepted. Def not working though saying connected.

**Comment by luboszima** [comment]
Solution:
✅ Settings - Network & Internet -> VPN -> Tailscale -> Block connections without VPN [unselect]

Then you can login via Tailscale

**Comment by B0geyDope** [comment]
The above didn't fully resolve the issue for me, possibly because I log into Tailscale using Github credentials..? 

When attempting to log into tailscale using github login/pw, it then asks to authorize (OAuth?). When I tapped on the Authorize button, nothing happens -- the process wouldn't move forward. I installed the github app on my phone & logged into my acct, hoping I could bypass the issue this way. Didn't quite work.  What did work was switching to "desktop site" mode (browser window). 

At the tailscale login screen -- after it routes me to github, I turned on desktop site and logged in. But then it wanted me to authorize github and tailscale getting connected, except the authorize screen would reset to mobile browser mode, which forced the process all over again. After a few tries, I figured out that on the authorize screen -- if I tap the "desktop site" mode (browser setting) then _very_ quickly tap the "authorize" button (on the site) _before_ the screen could reload, I was able to get logged into tailscale and complete the setup.
