### ISSUE TITLE
Received invalid response message from DERP ip:port

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#124]
```
73.5M/305.5M Received invalid response message from 127.3.3.40:1
73.5M/305.5M Received invalid response message from 127.3.3.40:1
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171687264724813) by [Unito](https://www.unito.io/learn-more)

**Comment by crawshaw** [comment]
I think this makes sense.

It's reporting a DERP IP here because when ReceiveIPv4 gets a packet from DERP, it reports the *net.UDPAddr for DERP to the caller, wireguard-go. Here WireGuard is trying to process a HandshakeResponse message, but cannot find a handshake by receiver index for the peer (a bit like a port number embedded in the packet). It probably can't find it because the HandshakeResponse has come in over a direct connection faster than DERP, been processed and the handshake removed.

**Comment by crawshaw** [comment]
Just to clarify: I'm not sure this message is a bug. I think if our magicsock spray code is working as intended, we should see duplicate handshake responses dropped something like this.

**Comment by bradfitz** [comment]
We should modify wireguard-go enough to give us enough info in magicsock (or get enough information from magicsock via some registered hook) about whether to suppress that log line.

Eventually we need to get our logspam under control. It's hard to find real problems.

**Comment by bradfitz** [comment]
I forget when exactly, but pretty sure we fixed this some time ago.
