### ISSUE TITLE
FR: Android 5 support

### ISSUE THREAD

**Issue by antonlyap** [tailscale/tailscale#12436]
### What are you trying to do?

I'm trying to connect old Android 5.1.1 phones to Tailscale. The test device is Samsung Galaxy J3 (SM-J320H).

### What is the impact of not solving this?

Currently there is no working version of the Tailscale app for some Android 5 devices:
- the old app has issues with OpenGL ES2
- the new app only supports Android 8+
- Magisk is partially broken on the device (rooting works, but the manager app doesn't), so using the Tailscale Magisk module doesn't seem to be possible

**Comment by bradfitz** [comment]
To set expectations: as a security product, we're very unlikely to support devices that are no longer supported by their manufacturer and no longer receive security updates (https://endoflife.date/android).

But as it's open source, you're more than welcome to try to make it work.

**Comment by antonlyap** [comment]
@bradfitz Thank you for your reply. One could argue that Tailscale does a lot more than just securing communications, but your point makes sense.

I ended up running Tailscale for Linux in a Debian chroot (some devices need `ln -s /dev/tun /dev/net/tun`). It appears to handle Android's source-based routing correctly, which is a pleasant surprise.

**Comment by drogers0** [comment]
@antonlyap — the answer here was that you're welcome to try to make it work, so I took bradfitz up on it.

https://github.com/drogers0/tailscale-firetv-fireos5 — the Compose app built from upstream source with the API floor put back to 22, for Android 5.1 / GLES 2.0 hardware. Verified on 1.98.8 on a Fire TV Stick 2nd gen, including exit-node routing.

On why it works at all: the OpenGL ES 2 crash was fixed by the Gio → Compose rewrite, which has no GLES 3 requirement. `minSdkVersion` went 22 → 26 in `bf0e56469f`, one commit later, so the two never shipped together. Nothing about the fix needs Android 8.

This may be simpler than the Debian chroot for the J3, though I've only tested Fire OS 5. The prebuilt APK is armeabi-v7a; `MIN_SDK=22 GOMOBILE_TARGET=android ./scripts/build.sh` builds all ABIs.
