### ISSUE TITLE
Tailscale has detected a mismatch between the application and vpn extension version

### ISSUE THREAD

**Issue by sreekanthabacusai** [tailscale/tailscale#12461]
### What is the issue?

All our company devices have Mobile Device Management software installed. When a user opens the TailScale app on macOS device, the System Configuration Inspector throwing an error "Tailscale has detected a mismatch between the application and vpn extension version".

### Steps to reproduce

Open the TailScale app.

### Are there any recent changes that introduced the issue?

No

### OS

macOS

### OS version

13.2.1

### Tailscale version

1.68.0

**Comment by agottardo** [comment]
Firstly, I warmly recommend updating to macOS Sonoma.

Rebooting your Mac should be sufficient to resolve this issue. If not, there is likely some configuration profile installed on your Mac preventing the extension from getting updated.

I would like to collect additional diagnostics to figure out why this is happening. Diagnostic data may contain confidential company information and should not be posted here. Can you please take a sysdiagnose from an affected Mac while the issue is verifying, and then email it to support@tailscale.com? Mention this issue number in your email. Thanks.

**Comment by kelivel** [comment]
Hi @sreekanthabacusai, our Support team received your email. Can you generate a sysdiagnose file (`sudo sysdiagnose`) and attach it to your next reply? We'll be able to take a closer look from there.

----

Conversation http://go/tss/40559 (internal).
