### ISSUE TITLE
cmd/tailscaled: don't block sending IPN messages to clients with mutex held

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1254]
The tailscaled part of https://github.com/tailscale/tailscale/issues/1234#issuecomment-771834707 ...

We shouldn't send an IPN message to a client (and block forever) while holding a mutex. We should probably release the mutex before the writes, and also have a deadline on the writes.

**Comment by DentonGentry** [comment]
I think the original impetus for this issue was resolved in https://github.com/tailscale/tailscale/commit/71b13b5ac2a077b41174a08faa890f4f11e15041

In the 2.5 years since this was filed, we haven't used it for additional work in the client. I think this can be closed a fixed, we should open new, specific issues for other instances of a similar problem.
