### ISSUE TITLE
Windows : Cloning windows VM , clone the Tailscale keys.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1260]
Cloning Windows VM with having Tailscale install, clone the keys which make new device detected as old and get the same IP for both devices.

Workaround:

Go to 'C:\Program Files (x86)\Tailscale IPN' click on Uninstall-Tailscale.
Go to C:\Users\darshini\AppData\Local ... delete the Tailscale folder.
Go to C:\Windows\System32\config\systemprofile\AppData\Local delete Tailscale folder.

After this, reinstall the Tailscale and login with your credentials; your new VM should be detected as a new Device in your network with different IP and name.

**Comment by bradfitz** [comment]
So the bug here is that uninstalling Tailscale should also delete the machine key?

@apenwarr, @crawshaw, thoughts?

**Comment by DentonGentry** [comment]
Noting https://github.com/tailscale/tailscale/issues/392 as a consequence if both systems use the same key.

**Comment by peske** [comment]
In my opinion, although causing headaches, this is not a bug but expected behavior when the machine is cloned. We could never know if the machine is cloned to be run as a duplicate, or for a backup, for example. It would probably be a bigger problem if we delete the machine key on cloning, and the user who cloned it (justifiably) expects that everything is cloned, including the Tailscale machine key.

What I'm trying to say is that there is some responsibility on the user who does the cloning takes care of such things. This problem doesn't affect only Tailscale, but also some other things (different IDs) in the cloned machine. For example, Microsoft doesn't support cloning Windows machines without previous `sysprep` in order to avoid duplicate machine IDs, SSID, etc.

But what we can and should do in Windows machines is to delete the machine key during `sysprep` (attach custom action somehow). This definitely makes sense. `sysprep`-ed machine definitely should not contain our machine key.

**Comment by peske** [comment]
To be more precise about what I suggest about this problem:

1. Implement `tailscale-ipn.exe /remove-keys` flag that would delete all the machine keys, for all the users on that machine;
2. Optionally add custom action to `C:\Windows\System32\sysprep\ActionFiles\Generalize.xml` that will execute `tailscale-ipn.exe /remove-keys` in generalize phase of `sysprep`. This can be bit tricky because `Generalize.xml` cannot be edited as regular admin account because it's owned by `TrustedInstaller` account, so to edit it I would have to change the ownership first, than grant permission to local admins, then edit... And some users may be unhappy if we do so. Alternatively we may just add to docs that `tailscale-ipn.exe /remove-keys` should be executed before cloning the machine.

In order to implement `tailscale-ipn.exe /remove-keys` in an appropriate way I would probably have to also add some logic that will keep the catalog of all keys on the machine, probably in `C:\ProgramData\Tailscale`. The catalog would be a simple map username->pref.conf. Then on `/remove-keys` go through the catalog and delete all the keys. It is true that almost always the keys will be stored in `C:\Users\<uname>\AppData\Local\Tailscale\prefs.conf`, but it is not guaranteed to be the case. It is possible in Windows to change user's home directory for a particular user to some custom location other than `C:\Users\<uname>`, and for that reason it is better to implement the catalog.

Pls let me know what do you think.

**Comment by fowl2** [comment]
There is also the concept of a "[VM Generation ID](https://docs.microsoft.com/en-us/windows/win32/hyperv_v2/virtual-machine-generation-identifier)" which might help.

**Comment by DentonGentry** [comment]
Root cause is the same as https://github.com/tailscale/tailscale/issues/506, with the same solution likely of automatic node key rotation.

Dup of https://github.com/tailscale/tailscale/issues/506

**Comment by AFDevMike** [comment]
I am here searching for how to handle this when having cloned a VM.  

I tried the OP's Workaround and still show the Machine when I subsequently install Tailscale.

> Workaround:
> 
> Go to 'C:\Program Files (x86)\Tailscale IPN' click on Uninstall-Tailscale.
> Go to C:\Users\darshini\AppData\Local ... delete the Tailscale folder.
> Go to C:\Windows\System32\config\systemprofile\AppData\Local delete Tailscale folder.

How do I clean Tailscale state from the VM?
