### ISSUE TITLE
Customer should get the notification for reauth before the key expiry.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1261]
Customer suddenly got key expired and cannot connect to Tailscale network, as there was no explicit notification for key expiry or before key expiry for reauth, he got misguided.

There should be reauth notification before the key got expire or during the temporary key allowed timeline of 30 mins.

**Comment by DentonGentry** [comment]
Given the ability to extend the keys using the admin panel, tagging this as potentially widespread but not severe impact.

**Comment by parkr** [comment]
> Given the ability to extend the keys using the admin panel, tagging this as potentially widespread but not severe impact.

While I can remedy this quite easily via the admin panel or by running `sudo tailscale up`, **I don't know that it's happened until the key has already expired**. The (speedy and easy!) ability to renew is not really at issue – the issue is that I have no head's up that the key is expiring. The admin panel doesn't even show expiration date, so it's not like I can put a reminder in my calendar for the day before.

**Comment by DentonGentry** [comment]
We're likely to handle this by providing a way to call a webhook when a device is approaching its node key expiration.

**Comment by DentonGentry** [comment]
To be handled as part of https://github.com/tailscale/tailscale/issues/312

**Comment by baruchiro** [comment]
I have a Tailscale container, which expired and now I can't access it even if I extend it from the admin console.

So it is essential.
