### ISSUE TITLE
wgengine/magicsock: updateNetInfo: invalid concurrent call to GetReport

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#12643]
Seen in bugreport 77a6ecc8b964cf275067ecd844d4f927876d407ff2c8935fd3bae1fe77e26c11 of Windows 1.68.1-tf02ad8397-g8f9cb4763

```
2024-06-24 10:53:42.3036086 +0000 UTC: magicsock.Conn.GetLastNetcheckReport: updateNetInfo: invalid concurrent call to GetReport
```

@andrew-d, can you look into this?

**Comment by andrew-d** [comment]
It looks like that code calls `GetLastNetcheckReport`, which calls through to `updateNetInfo` if there's no report stored. That calls the `netcheck` `GetReport` function without doing any synchronization, which thus errors because netcheck doesn't support concurrent calls to `GetReport`. The other caller is `updateEndpoints`, which synchronizes based on `c.mu` and `c.endpointsUpdateActive`, to prevent concurrent callers of that function. However, `GetLastNetcheckReport` doesn't check that.

I think this is working as intended from the perspective of the `netcheck` code, and `GetReport` is documented to not support concurrent callers. The `GetLastNetcheckReport` and related code should probably be synchronizing calls to `GetReport` along with `updateEndpoints`.

**Comment by bradfitz** [comment]
@agottardo was just hitting this again now at head.

/cc @sailorfrag
