### ISSUE TITLE
Tailscale refuses to start on Mac, automatically killing itself after startup

### ISSUE THREAD

**Issue by mattaq31** [tailscale/tailscale#12668]
### What is the issue?

Hi,

Similar to https://github.com/tailscale/tailscale/issues/12665, I have suddenly encountered an issue where Tailscale simply refuses to start, no matter what I do.  I used to have 1.68.1 installed from the App Store (Mac) where it has been working fine for 6 months.  Now, it simply refuses to start, flashing its GUI momentarily before crashing.  I attempted to switch to the standalone package version, cleaned out all Tailscale-related files from my Mac and the same thing keeps on happening.  Updating to the unstable 1.69.104 results in the exact same behavior.  I cannot even generate a bug report as I am getting the following response:

```
/Applications/Tailscale.app/Contents/MacOS/Tailscale bugreport
Backoff(BackendManager.startTunnel): trying again in 0.0s
Backoff(BackendManager.startTunnel): trying again in 0.1s
Backoff(BackendManager.startTunnel): trying again in 0.4s
[1] 17471 killed /Applications/Tailscale.app/Contents/MacOS/Tailscale bugreport 
```

Does anyone have any idea what could be going wrong?  Many thanks in advance for your help!

### Steps to reproduce

Install any version on Mac, then attempt to run.

### Are there any recent changes that introduced the issue?

N/A

### OS

macOS

### OS version

14.5

### Tailscale version

1.68.1

### Bug report

N/A

**Comment by agottardo** [comment]
> 17471 killed /Applications/Tailscale.app/Contents/MacOS/Tailscale

That's what's happening, another process with process ID 17471 on your Mac is killing Tailscale upon seeing it. Is this a work computer? Do you have any security or management software running that could be causing this?

**Comment by mattaq31** [comment]
Hi @agottardo thanks for replying so quickly!  Yes actually, this is a work computer and it is running CrowdStrike Falcon.  I was promised that this shouldn't affect or prevent the function of an applications, but from what you've described it seems like this could be the problem.  Do you know how I could trace who the killer PID belongs to?  Every time I re-run Tailscale, the PID that is killing it is changing, so I can't preemptively log outputs from that PID using `log`.  

Thanks again - in the meantime I'll reach out to my work support to see what they have to say about this..

**Comment by agottardo** [comment]
Sorry, there is also a chance that that's the PID of Tailscale itself, hence it is constantly changing. My strategy would be to look in Console.app for any other process that references killing Tailscale around the time it dies.

We have definitely seen customers in the past with Falcon configurations that were causing it to be killed. Another tool that does this is Netskope. It might have been installed by your IT department without you even knowing about it. In general, this is definitely something else on your system terminating Tailscale. I also recommend that you try the Standalone variant of the client instead of the one distributed via the App Store. It has a different bundle identifier and its networking code runs as the root user, so it might be less prone to blocking by an overstepping EDR tool on your Mac.

**Comment by mattaq31** [comment]
Unfortunately issue confirmed to be Tailscale being shut down by Crowdstrike so no bug here - thanks again @agottardo!
