### ISSUE TITLE
I confused with documentation how to register hundred devices with one key, when machines deploys from backed image. 

### ISSUE THREAD

**Issue by garry-t** [tailscale/tailscale#12694]
### What is the issue?

I need to register hundred VMs with one key since all these VMs deploys from backed image. 
I have provisioned ephemeral , reusable auth key and for test tried deploy 2 machine I see error in Admin page `Duplicate node key`
I checked https://tailscale.com/kb/1111/ephemeral-nodes  this and seems like I have valid configuration in same time I see 
https://tailscale.com/kb/1085/auth-keys so which option is correct for me? 

### Steps to reproduce

1. Create VM 
2. Install tailscale with auth key with tag assigned to disable expiration, auth key should be ephemeral , reusable also
3. Take snapshot of volume. 
4. Deploy new VMs based on snapshot

### OS

Linux

### OS version

Ubuntu 22.04

### Tailscale version

1.68.2

**Comment by irbekrm** [comment]
You can re-use auth key, but not tailscale state- each of your VMs would have to be a separate device. Tailscale stores its state on filesystem, so if you created a snapshot from the initial VM with tailscale already running, you probably picked up the state and the errors are there because you now have multiple VMs trying to authenticate as the same device.

Depending on your workflow, you probably want to pass the auth key to each VM separately and run and authenticate tailscale on VM start. Don't clone VMs with already running/authenticated tailscale.

**Comment by garry-t** [comment]
Ok, my workaround is following. Install `tailscale` craft start command for `tailscale` with token and possible other parameters and create cron job for each boot system event. In this case I got registered all devices successfully. 
It was easiest solution for me since I can reuse `ansible` role for classic VMs and bare metal hosts.

**Comment by agottardo** [comment]
Looks like this was fixed, close? @irbekrm

**Comment by garry-t** [comment]
workaround found => closing
