### ISSUE TITLE
The subnet route has disappeared from the route table

### ISSUE THREAD

**Issue by imafov** [tailscale/tailscale#12753]
### What is the issue?

There is a subnet 10.90.0.0/16, a router that advertises this network, and servers on this network. The subnet router works with the --snat-subnet-routes=false key.
There are also servers with a tailscale client.

Previously, if you specified access in the ACL for example 10.90.1.0 -> tailscale client (server), then route 10.90.0.0/16 appeared on the server with the tailscale client (in table52). This is not happening now.

It started on 07/08/2024.

### Steps to reproduce

As a temporary solution, I had to add “tailscale client -> 10.90.1.0 (or any other address from the subnet)” access to the ACL. After this, the route appeared in the client’s tailscale table.

### OS

Linux, Windows

**Comment by jfmontanaro** [comment]
I'm having the same problem, in fact I opened a separate issue about it because I didn't see this one until now: #12767

In my testing it appears that Tailscale has stopped adding subnet routes to the route table unless the device in question has access going _into_ the subnet, not just coming _out_ of the subnet.

I've been able to work around it without having to open up the whole tailnet by adding a route that gives the server (the non-subnet Tailscale device) access to a non-functional address in the subnet. In your case, I think something like this should work:

```
{
    "action": "accept",
    "src": ["your_server_tag_or_ip"],
    "dst": ["10.90.0.0:1"],
}
```

Since 10.90.0.0 is technically in that subnet, the whole subnet gets added to the route table on your server. But since `.0.0` isn't an address that anyone is ever going to actually have, there's no security concern.

**Comment by fate8383** [comment]
exact the same problem... almost spent 3 hours with iptables...and came across to this...it makes no sense, clearly a bug and logs dont show anything, in fact it says it is connected SNAT or no SNAT... but it is not connecting.

**Comment by imafov** [comment]
> I'm having the same problem, in fact I opened a separate issue about it because I didn't see this one until now: #12767
> 
> In my testing it appears that Tailscale has stopped adding subnet routes to the route table unless the device in question has access going _into_ the subnet, not just coming _out_ of the subnet.
> 
> I've been able to work around it without having to open up the whole tailnet by adding a route that gives the server (the non-subnet Tailscale device) access to a non-functional address in the subnet. In your case, I think something like this should work:
> 
> ```
> {
>     "action": "accept",
>     "src": ["your_server_tag_or_ip"],
>     "dst": ["10.90.0.0:1"],
> }
> ```
> 
> Since 10.90.0.0 is technically in that subnet, the whole subnet gets added to the route table on your server. But since `.0.0` isn't an address that anyone is ever going to actually have, there's no security concern.

Yeah, that's pretty much what we're doing now. Only we have 3 subnets and a bunch of servers with a tailscale client. I don’t want to greatly inflate the already large ACL.

**Comment by imafov** [comment]
> Just gave it a try: still happening w/ [v1.70.0](https://github.com/tailscale/tailscale/releases/tag/v1.70.0)

As far as I understand, this bug does not depend on the version. The problem is in the cloud (route injection occurs through the cloud). We have different versions on our servers, from the oldest to the newest, and the bug is reproduced everywhere.

**Comment by imafov** [comment]
The issue is no longer reproducible. Route injection works as before.
