### ISSUE TITLE
FR: is there client for windows 7?

### ISSUE THREAD

**Issue by youxiaojie** [tailscale/tailscale#12777]
### What are you trying to do?

need windows 7 client

**Comment by nickkhyl** [comment]
@youxiaojie: Windows 7 support has been discontinued. Any existing installation should continue working on Windows 7 for the time being, but we will no longer offer Windows 7 packages for download. As Microsoft no longer provides security updates for Windows 7, with the extended security updates program having expired on January 10, 2023, we advise upgrading to a supported Windows version.

**Comment by youxiaojie** [comment]
can I compile it for win 7 by myself?

**Comment by nickkhyl** [comment]
@youxiaojie: unlike [`tailscaled`](https://github.com/tailscale/tailscale/tree/main/cmd/tailscaled), the cross-platform [CLI client](https://github.com/tailscale/tailscale/tree/main/cmd/tailscale), and our clients for open-source platforms, the GUI client for Windows is not open source.

If you're comfortable with using just the CLI, you should be able to compile it yourself. However, since we've discontinued support for Windows 7, we will not maintain compatibility with it. Doing so would unnecessarily complicate our codebase due to its lack of certain features and APIs in Windows 7, as we would need to use different implementations depending on the platform. Therefore, while you can _compile_ both the CLI client and `tailscaled`, it's not guaranteed to continue working on Windows 7.
