### ISSUE TITLE
PIKVM-Need to use in public network

### ISSUE THREAD

**Issue by reddeppa-eddala** [tailscale/tailscale#12878]
### What is the issue?

I have purchased PIKVM device through amazon and it is working fine  in local net work but my requirement would be it should work in public network and followed the steps as per this link [https://tailscale.com/kb/1292/pikvm] HTTPS link is getting generated and connected with tail scale. still i could not login with public net work. Could you please help me ,do i need follow anything or can some one support from your end.
Regards,
Reddeppa

### OS

Linux

**Comment by reddeppa-eddala** [comment]
If you could speed up this incident it would be a great help

**Comment by Erisa** [comment]
As that documentation page says:

> A Tailscale Serve server can only be access over your tailnet. It is not accessible from the public internet. Using [Tailscale Funnel](https://tailscale.com/kb/1223/funnel) would open your PiKVM device to the public internet, which is not recommended.

To use Funnel (and expose it publicly) despite the recommendation not to, replace the `tailscale serve` command with `tailscale funnel` instead.

I would strongly advise you setup secure authentication and 2FA on your PiKVM before exposing it to the public internet: https://docs.pikvm.org/auth/#changing-the-linux-password

**Comment by reddeppa-eddala** [comment]
is there any support from your end to call my  phone +469-473-5921 as i have many questions ?

Right now PIKVM is connected with local network which my home internet and i could connect my laptop remotely. when i want use different network which means different internet but it is not working and checked with PIKVM team and confirmed that using tail scale VPN  is possible and mentioned those steps and updated at os Level but no luck. 

Please refer this link -https://tailscale.com/kb/1292/pikvm. 

Now my question to you : Is it possible use PIKVM device with different network? if yes please share the steps and also i am ready for online support . 

phone +469-473-5921

**Comment by Erisa** [comment]
Tailscale does not offer phone support. If you need to contact the Tailscale Support team, you may do that here: https://tailscale.com/contact/support

I answered the question as it relates to Tailscale already and you can follow those instructions. To expose to devices not connected to Tailscale it's the same as on the guide you linked, just with `tailscale funnel` instead of `tailscale serve`. If you wish to access from other devices through Tailscale, ensure they are connected to the same Tailscale network. 

If you have questions not related to Tailscale, you may reach out to the PiKVM project staff. If you require detailed support with the Tailscale product, you can contact Tailscale Support.

**Comment by reddeppa-eddala** [comment]
Thank you so much for your support. Now I am able to use public network using tail scale.

Now my question to you. If tail scale is not possible to use in few laptop due to restrictions of website. in this case how  we can use public network.

**Comment by reddeppa-eddala** [comment]
Thank you so much for your support. Now I am able to use public network using tail scale.-my device -PIKVM

Now my question to you. If tail scale is not possible to use in few laptops due to restrictions of website. in this case how we can use public network which means i cant login with tailsacle.
