### ISSUE TITLE
create mechanism to annotate places/stacks we expect to block long, log others

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1288]
I'd like to be able to annotate places in the code that are known to block goroutines for long periods of time (there aren't many) and then have some background goroutine poller that looks to see if a goroutine not so marked as been blocked for a long period of time, and log.

I'd like to catch/prevent things like #1282 earlier.

IIRC there was a similar one in Tailscale earlier, but I've hit this many times in other Go projects.

/cc @josharian

**Comment by josharian** [comment]
Interesting. Seems pretty straightforward. Make a depaware-style tool that generates a such list for a package and drops in a new file that does the monitoring.

For ease of CI checks that the file is not stale, it'd be nice to be able to use embed to slurp it in.

Such a file could change all the time due to unrelated code changes. I don't see a clear way around that, but it could be annoying.

I'd be happy to prototype this near the end of next week, if you think it's a priority.

**Comment by josharian** [comment]
The crazier language-change way to do this is to allow associating strings with lines of code using magic comments (`//go:tag blocks`). Kinda similar to struct tags. Then you could expose as part of runtime.Frame, or maybe a package runtime (reflect?) function based on file/line or function name or the like.

Code generation for now, anyway.

**Comment by josharian** [comment]
Another option: instead of code generation, do runtime annotation.

```go
longblock.AllowNextLine()
<- c
```

Like testing.T.Helper, the call records the next line as being allowed to block indefinitely. It’ll be more expensive than code generation, but nicer to use.

Note that for any of these, allowing a line to block indefinitely either requires recognizing it in the middle of a stack or hard-coding a bunch of runtime information, because the top of stack will be things like runtime_semAquire.

**Comment by josharian** [comment]
Started playing with this, using the runtime annotation approach. Will probably finish up late this week...

**Comment by josharian** [comment]
Started on this. Pushed my WIP in https://github.com/tailscale/tailscale/pull/1326 in case I don't finish it prior to vacation. It's not feature complete and still very raw, but if someone else does pick this up while I'm away, they might find some useful code in there.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/pull/1326 is closed now but still available for future reference.

At this point I don't expect to implement this feature request.
