### ISSUE TITLE
atomicfile missing flush

### ISSUE THREAD

**Issue by jzelinskie** [tailscale/tailscale#13]
Congrats on open sourcing!

I just happened to open up the first package and noticed [the write a new file and rename trick](https://github.com/tailscale/tailscale/blob/fef254898178d100f25b98530499adcf07cfded3/atomicfile/atomicfile.go#L19).
I'm not sure this is safe because [`ioutil.WriteFile` doesn't call `f.Flush()`](https://github.com/golang/go/blob/go1.13.7/src/io/ioutil/ioutil.go#L79).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171687098878141) by [Unito](https://www.unito.io/learn-more)

**Comment by bradfitz** [comment]
I'm not sure the intended purpose of the atomicfile package was durability.

It might've only been to prevent races from concurrent access on the same machine.

When @apenwarr added it, he said:

```
    Add an atomicfile.WriteFile function and use it instead of ioutil.WriteFile.
    
    In case the program is interrupted or the disk is full,
    ioutil.WriteFile can be extremely destructive. I saw this happen on the
    logtail server at one point when the disk filled up. It could happen in
    the tailcontrol server too, or relaynode or the windows client.
```

So it sounds like atomicfile as written solves the problem it was meant to address.

I suppose it could document that it does not also Flush, but ioutil.WriteFile also doesn't document things that it doesn't do.

**Comment by apenwarr** [comment]
I assume we're actually talking about os.File.Sync() (the fsync() syscall)
rather than any .Flush() function.

There is some debate about when/how fsync() is necessary in different
situations. If it *is* necessary, then it's probably needed both before
renaming the file (after Close()) *and* after renaming the file, to catch
all possible edge cases. Usually the semantics people expect is that
write-close-rename either completes fully, or not at all. This is true on
virtually any unix system, except early variants of ext4. The "original"
ext4 debate about it is here: https://lwn.net/Articles/322823/

As a result, it should be safe to avoid fsync *if* we are okay with getting
the old data instead of the new data after a system crash. Actually that's
not ideal (especially when key rotation is involved), but just adding
.Sync() is not sufficient to completely resolve that problem. We'd have to
add a proper interlock with the server side so it knows for sure when the
new key has been committed to disk. Meanwhile, I guess there's a race
condition in case of key rotation followed immediately by a kernel crash.
