### ISSUE TITLE
Make it easier to update from Windows

### ISSUE THREAD

**Issue by bogosj** [tailscale/tailscale#1305]
**Is your feature request related to a problem? Please describe.**

When I see an update is available in https://login.tailscale.com/admin/machines I'd like an easier way to update a Windows machine.

**Describe the solution you'd like**

I'd like a right-click option on the tray icon that says "Update" when an update is available, which drives me to the [page to download](https://tailscale.com/download).

**Describe alternatives you've considered**

Perhaps a link on the device that needs updating to https://login.tailscale.com/admin/machines so I know where to go to update.

**Comment by bradfitz** [comment]
We already have that?

<img width="270" alt="Screen Shot 2021-02-09 at 12 10 21 PM" src="https://user-images.githubusercontent.com/2621/107422425-d9d01780-6acf-11eb-8bc2-afaa69016bbf.png">

<img width="336" alt="Screen Shot 2021-02-09 at 12 10 26 PM" src="https://user-images.githubusercontent.com/2621/107422438-ddfc3500-6acf-11eb-8ab9-95d633cd2d9f.png">

<img width="266" alt="Screen Shot 2021-02-09 at 12 10 32 PM" src="https://user-images.githubusercontent.com/2621/107422448-e05e8f00-6acf-11eb-8c7b-3cb2fd083f5e.png">

<img width="298" alt="Screen Shot 2021-02-09 at 12 11 14 PM" src="https://user-images.githubusercontent.com/2621/107422472-ec4a5100-6acf-11eb-876f-8131e3fd6a29.png">

**Comment by bradfitz** [comment]
cc @rosszurowski @soniaappasamy for admin panel

**Comment by bogosj** [comment]
That option was most definitely *not* available to me in the right-click dialog when I just went to go from 1.4.0 to .3. Nor was "Latest stable version: 1.4.3" in the about dialog...

**Comment by bogosj** [comment]
Next time I see a stable release is available I'll double check to make sure I'm not hallucinating...

**Comment by bradfitz** [comment]
The Windows client only checks every 12-24 hours and also on start-up. We juuust released 1.4.3 on windows so your client just hadn't fetched the new info yet.

**Comment by bradfitz** [comment]
I supposed we could push that to clients proactively. At least whenever an admin views the machines page perhaps.

**Comment by bogosj** [comment]
Ah, my silly expectation was that in the About dialog it would check the version onLoad and maybe offer the upgrade button in the About dialog.

I shall try to be more patient in the future. No promises.

**Comment by bradfitz** [comment]
Those are both reasonable suggestions but so far we spend all our available energy fighting Windows backend stuff. We don't focus much (yet?) on Windows UI issues.

**Comment by bogosj** [comment]
Neither matters if https://github.com/tailscale/tailscale/issues/1305#issuecomment-776253941 push were done, or the polling time was lowered.

Either way P4-S4 since I know it's just me being impatient.

**Comment by bogosj** [comment]
Confirmed I was just impatient as I saw the Update option in the right-click on the systray for 1.4.4. Thanks.

**Comment by bradfitz** [comment]
We should keep the 12-24 hour polling for users who don't care much (who aren't looking for the info), but for users who either (a) already saw that the update was available in the admin panel or (b) really want to know, we should be faster.

For (a), we know we told a user that an update was available, so we can push something down to their client to tell it.

For (b), we can do some Windows UI work to show a pop-up Window immediate in the About dialog with a "checking for update" spinny animation and asynchronously do an HTTP request to check for the latest version.

But it might just be easiest to always push it down from the server in all cases. That addresses all the cases.

For the slow rollout functionality, thought, we could have a separate bit in the pushed version info to say whether it should be actively advertised to users. (but currently we never do OS-level notifications on Windows about version updates anyway, so that's kinda moot)

**Comment by DentonGentry** [comment]
Looking into automatic updates for Windows applications, some references:
- Omaha, as used with Chrome (https://omaha-consulting.com/best-update-framework-for-windows-10-7 provides a hosted version)
- [Squirrel](https://github.com/Squirrel/Squirrel.Windows)
- [WinSparkle](https://winsparkle.org/) derived from the MacOS Sparkle
- [wireguard-windows](https://git.zx2c4.com/wireguard-windows/tree/updater) update service

**Comment by DentonGentry** [comment]
We're tracking the support for auto-update in the Windows client in https://github.com/tailscale/tailscale/issues/755
I don't think there is more to do for this issue.
