### ISSUE TITLE
Documentation for Linux optimizations for subnet routers and exit nodes is incorrect

### ISSUE THREAD

**Issue by shladek** [tailscale/tailscale#13117]
### What is the issue?

Following the code examples on the Performance Best Practices page located [here](https://tailscale.com/kb/1320/performance-best-practices) has the following code snippet for optimizing subnet routers and exit nodes.

```
NETDEV=$(ip route show 8.8.8.8 | cut -f5 -d' ')
sudo ethtool -K $NETDEV rx-udp-gro-forwarding on rx-gro-list off
```

This appears to be incorrect as NETDEV will be most likely empty if you were to 

`echo $NETDEV`

and doesn't mesh well with the 2nd code snippet to create a script using networkd-dispatcher:

```
printf '#!/bin/sh\n\nethtool -K %s rx-udp-gro-forwarding on rx-gro-list off \n' "$(ip route show 0/0 | cut -f5 -d" ")" | sudo tee /etc/networkd-dispatcher/routable.d/50-tailscale
sudo chmod 755 /etc/networkd-dispatcher/routable.d/50-tailscale
```

Note the ip route show 0/0 in that example.

The fix for this would be to change the documentation so that the first code snippet shows:

```
NETDEV=$(ip route show 0/0 | cut -f5 -d' ')
sudo ethtool -K $NETDEV rx-udp-gro-forwarding on rx-gro-list off
```
so that the first code example would work. 

### OS

Linux

**Comment by LizzardK1ng** [comment]
+1

Thanks for raising this @shladek

**Comment by jtykowski** [comment]
I was getting errors with the original code on the site, and the code here worked for me, however, I see on the [link](https://tailscale.com/kb/1320/performance-best-practices) they did the inverse of this suggestion and updated all code to include ip route show 8.8.8.8 instead of ip route show 0/0.  That code is also working for me.

**Comment by shladek** [comment]
Documentation was updated to be consistent, so closing this issue.

**Comment by jeremiah** [comment]
I ran into this issue as well and am documenting my solution and my proposal for the documentation here. 

The issue is that the command above is incorrect, at least in my instance. This is because the 'cut' command is cutting the wrong field. For example, the output of `ip -o route get 8.8.8.8` on my machine is `8.8.8.8 dev tailscale0 table 52 src 100.68.41.100 uid 1000 \    cache` which has the device name in the 3rd field, not the 5th. 

In addition to providing these commands, perhaps a simple note that says the "device name" might be found via other means and is likely to be "tailscale0". This might help those who, like me, get "52" when they run;
```
NETDEV=$(ip -o route get 8.8.8.8 | cut -f 5 -d " ")
echo $NETDEV
```
