### ISSUE TITLE
About Privacy Policy

### ISSUE THREAD

**Issue by lizhengaas** [tailscale/tailscale#13135]
### What is the issue?

The andorid version of tailscale should collect device MAC addresses, software installation lists, contacts, and SMS messages only after the initial interface (the initial interface prompts the user to explain the privacy policy).

### OS

Android

### Tailscale version

1.70

**Comment by udf2457** [comment]
One might ask what Taiscale is doing collecting "contacts, and SMS messages" in the first place ?

**Comment by agottardo** [comment]
We want to clarify that we do not collect contacts or SMS messages, and I’m curious about what might have led you to believe otherwise. Our APK doesn’t even include the permission to access this type of data in its [manifest](https://github.com/tailscale/tailscale-android/blob/main/android/src/main/AndroidManifest.xml), making it technically impossible for Tailscale to do so.

If and only if you access the app-based split tunneling settings, the app requests a list of installed applications from the Android OS. This allows us to show you a list of apps that you can exclude from the Tailscale tunnel by selecting them. However, this list of apps, whether installed or excluded, is never uploaded or shared.

Also, please note that both the UI and backend of our Android app are fully open-source, so you’re welcome to verify any of these details yourself.
