### ISSUE TITLE
Tailscale 1.7.2 Breaks tailnet lock

### ISSUE THREAD

**Issue by wingcomm** [tailscale/tailscale#13203]
### What is the issue?

We are unable to sign nodes on a signing node on Tailscale 1.7.2.

### Steps to reproduce

Upgrade to Tailscale to 1.7.2 on macOS 14.6.1 and try to sign a new node.
You will see the following:
<img width="260" alt="Screenshot 2024-08-21 at 2 49 23 AM" src="https://github.com/user-attachments/assets/34f94c2c-abfc-4170-a580-e19e799bb165">

### Are there any recent changes that introduced the issue?

We did recently re-authenticate the signing host since its key expired.

### OS

macOS

### OS version

14.6.1

### Tailscale version

1.7.2

### Bug report

BUG-4d6f318191634da6095a7f9b0fdf90f3a577115c961d233727e72314017c6843-20240821064952Z-08038d10effcfed8

**Comment by knyar** [comment]
Looking at the node and tailnet logs associated with the bug report, it seems that Tailnet Lock was disabled and re-enabled immediately after, with disablement state not getting a chance to propagate to some of the nodes (most probably because they were not online at the time). Those nodes are stuck with the previous TKA state, and are not able to get the latest valid TKA state because it’s not derived from the state they already have.

We have provided more details privately via a separate support case. This does not appear to be related to 1.72 release.
