### ISSUE TITLE
android: turn off VPN when screen off?

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1330]
The current behaviour is there is a toggle switch to start or stop Tailscale VPN in IOS or Android.

The customer suggests having; it automatically stops/starts as soon as the screen got off display.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2s9zl)

**Comment by bradfitz** [comment]
@eliasnaur, thoughts? This was a user request. AFAICT, it was motivated by preemptive battery concerns rather than actually observed battery problems. In Tailscale 1.4 we go pretty idle when idle, so I'm not sure how much win this would be for the various costs.

Can we even subscribe to the screen state?

**Comment by eliasnaur** [comment]
It seems possible to be notified when screen is turned on or off: https://stackoverflow.com/questions/1588061/android-how-to-receive-broadcast-intents-action-screen-on-off/1588267#1588267.

I'm not sure it's worth the complexity, though; I'd rather not debug issues where the tailscale VPN sometimes doesn't come online because of this heuristic. And what about users having apps in the background using the VPN?

Do other VPN apps disable themselves when the screen is turned off? For example, there are no matches for `SCREEN_` in the Wireguard app source code.

I'd rather fix battery problems first, if any remains.

**Comment by ignoramous** [comment]
Screens also turn off due to proximity sensors firing up (when someone's on a call, for example).  Probably, "device locked" and "user present" events are likely better suited for the task at hand.  Even then, it doesn't account for the fact that other apps (which may require a functioning VPN) could very well have acquired wake locks / wifi locks to run background tasks whilst the device is locked and now wouldn't work... Really tricky to get this one right given various modes the device can get into.

**Comment by DentonGentry** [comment]
At this point I really don't expect to do this. Once the VPN is turned on, especially if using an exit node, I do not believe we can turn it off without the user explicitly doing so.

In the next bug scrub if there are no comments to the contrary, we'll close the bug.
