### ISSUE TITLE
android: DNS unavailable warning

### ISSUE THREAD

**Issue by agottardo** [tailscale/tailscale#13314]
Some users are reporting 'DNS unavailable' spurious (?) warnings, especially on Android:

- https://old.reddit.com/r/Tailscale/comments/1f2ow3w/health_warning_dns_unavailable_on_tailscale/
- https://old.reddit.com/r/Tailscale/comments/1f3l2il/health_warnings_dns_unavailable_what_does_it_mean/ 

I suspect this is caused by having a too low `TimeToVisible` setting on the Warnable, which triggers the unhealthy state during slow network transitions. I don't have a clear repro scenario for now.

https://github.com/tailscale/tailscale/blob/e93c160a391a10c33f0aab336d63d39e7ece301d/net/dns/resolver/forwarder.go#L177-L185

**Comment by iluvatyr** [comment]
I constantly get shown DNS unavailable, although it works flawlessly on my android phone. (and everywhere else too)...

Would be nice if this could be fixed.

**Comment by fiddybux** [comment]
I get this too on Tailscale app on my Android 13 Xiaomi Redmi Note 11. Works fine, just shows a warning triangle error. Can be cleared by cycling connect. Reappears shortly afterwards (period unknown).

**Comment by cmmrandau** [comment]
Same here on a Motorola

**Comment by nebriv** [comment]
Also have this on Pixel 7, tailscale version 1.82.4.

**Comment by SHU-red** [comment]
Get this too on Pixel 8a
Tailscale exit node running on my TrueNAS via self managed docker (not using truenas apps)

**Comment by Ipherc** [comment]
Same issue here — it still persists. I've noticed it happens every time my phone switches between 5G data and Wi-Fi. To get Tailscale working again, I have to turn it off, close the app completely, then reopen it and reconnect.

Samsung S24ultra,
Android version 15

**Comment by asavageiv** [comment]
This is happening to me on a Pixel 6a, Android 14, Tailscale 1.82.4. @agottardo should this be re-opened or a new issue created?

**Comment by egpheel** [comment]
Same issue here. Running 1.90.2 on a pi zero 2 w (dietpi), with adguard home, and running 1.88.4 on a pixel 9 pro XL, android 16. Everything seems to be working perfectly fine. I'm getting queries from my phone's tailscale IP address on adguard, I can connect fine to the other services I've got running from everywhere - connected and disconnected from the pi's local network, but its showing that warning in the app.

Edit: forgot to add I'm running mullvad exit nodes on all devices

**Comment by mario-g98** [comment]
This issue is still happening.

**Comment by mich3dev** [comment]
The issue is consistent on my Z Fold 6, Xiaomi Pad and iPad, doesn't affect the network but the warning always appears 

Edit: not on the iPad, it seems it's an Android issue and maybe related to power saving / switching network

**Comment by RedCoder09** [comment]
happens to me as well, on a motorola razr 2025.

**Comment by bub88** [comment]
This issue is still occurring and appears to be a false-positive from the `dns-forward-failing` health check.

I am seeing the following warning on a Samsung S23 Ultra running Android 16:

> "Tailscale can't reach the configured DNS servers. Internet connectivity may be affected."

However, DNS connectivity is demonstrably working at the exact same time the warning is displayed.

My setup:

- Samsung S23 Ultra
- Android 16
- Tailscale Android client
- Tailscale subnet router
- Custom DNS server reachable through the tailnet
- Split DNS / custom nameserver configuration

I monitored the actual DNS traffic on the Tailscale interface with tcpdump. Even while the Android client was showing the "DNS unavailable" warning, DNS queries were continuously being sent through Tailscale and received successful responses.

For example:

    [ANDROID_TAILSCALE_IP] -> [TAILSCALE_DNS_IP]:53
    A? youtubei.googleapis.com

followed ~85 ms later by:

    [TAILSCALE_DNS_IP] -> [ANDROID_TAILSCALE_IP]:53
    A 172.217.x.x ...

The same behavior occurs for multiple domains. Queries continue to work after the phone has been idle for a long period and while connected over LTE.

This strongly suggests that `dns-forward-failing` is detecting a transient/internal health-check failure and then reporting it as if the configured DNS server were actually unreachable.

The particularly frustrating part is that the warning is misleading: from the user's perspective DNS is working normally, yet Android/Tailscale reports a DNS failure.

Please investigate and fix the `dns-forward-failing` health check so that:

1. A single/transient failed health-check query does not immediately trigger this warning.
2. The health state is cleared automatically once DNS connectivity is working again.
3. The health check reflects actual DNS availability rather than a stale/internal state.
4. Android does not continue displaying "DNS unavailable" when real DNS queries are succeeding.

This has been reported in several forms for a long time, and it is especially annoying on Android because the warning makes users believe their DNS configuration is broken when it is actually functioning.

In my case, packet captures provide direct evidence that the DNS server is reachable and responding while the warning is active.

Please fix this health check rather than requiring users to work around a false-positive by adding a public DNS server such as 1.1.1.1.
