### ISSUE TITLE
control/controlclient: use Mendoza for MapResponse deltas?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1333]
Rather than keep adding new manual bandwidth optimizations to our MapResponse minifier server-side and associated decoder client side, perhaps we should juse use Mendoza:

https://www.sanity.io/blog/mendoza
https://github.com/sanity-io/mendoza

It's in Go and MIT.

I'll do some experiments but it seems like exactly what we want.

/cc @crawshaw

**Comment by crawshaw** [comment]
Woah! That... might even work.

**Comment by DentonGentry** [comment]
It is not clear to me whether this is still relevant, we substantially completed the work in tailcontrol to compute only what is needed and send deltas.

Barring objection, we'll plan to close this during the next bug scrub.

**Comment by DentonGentry** [comment]
At this point I'm not clear on whether this is still viable. We've ended up tying the fastpaths in processing of tailnet updates to the output of deltas in the mapresponse. We no longer generate a full mapresponse which something like Mendoza could compare to the previous full mapresponse in order to generate a delta.

Barring further comment, we'll expect to close this during the next regular bug scrub.
