### ISSUE TITLE
iOS 1.74 cannot log out/in

### ISSUE THREAD

**Issue by bcookatpcsd** [tailscale/tailscale#13475]
iPhone the client is connected to two accounts.

I'm trying to log out of them and log back in.

Trying to log out I just got the red spinning circle and nothing seems to happen.

Tried to log into a third account after rebooting the phone, that also seems to not go anywhere ..

Again, I have established/pre-existing accounts .. not trying to sign in from zero

Latest iOS, etc.

**Comment by bcookatpcsd** [comment]
Toggling WiFi off on, disconnecting the vpn from iOS, etc got the local app to recognize no account were connected.. and reconnecting was just as weird.. several logins and re-logins.. on WiFi off WiFi (to cellular) connections are re-established..

Anyone else..

**Comment by agottardo** [comment]
Please attach a bug report identifier, as we cannot look at diagnostics otherwise. 

If you aren't able to generate one, it means the Tailscale backend on your phone is not getting starting by iOS entirely (it's an iOS bug). I recommend uninstalling the app and rebooting your iPhone if that's the case. If the issue persists, send a sysdiagnose from your iPhone to `andrea@tailscale.com` and I can look at your logs to understand what's going on.

**Comment by bcookatpcsd** [comment]
BUG-d88ca3d8b83c69a510217e97dae0a683369b92376c3a5789b06b55680c979cd4-20240917001600Z-4f79fad54d754f19

Will try uninstalling/re-installing..
