### ISSUE TITLE
Ability to generate pre-auth key and assign tag using API.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1369]
1) The customer is looking forward to adding a tag like "customer" to a pre-auth key when generating it. This way, they could enforce the ACL for the newly added host without interference from a 3rd party.

2) API for generating pre-auth keys.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2tq6p)

**Comment by DentonGentry** [comment]
Comment from Slack: "I really would like us to be able to make preauth keys that are attached to particular acl tags - that’s really important for all kinds of things. Part of the same bundle as making it so you can’t remove tags without reauthenticating. Not a huge amount of work, but no, not available yet."

**Comment by mnaser** [comment]
As a customer here, my main point is that the only person that can generate authkey's are admins, and admins generally have access to the entire network, making an authkey essentially access to the entire network...

It's super useful for a scenario where you'd like to setup a Tailscale relay node in an untrusted environment.

**Comment by dkerwin** [comment]
With the upcoming 1.6 and userspace networking it becomes very interesting for some Containers cases as well. Definitely something that could make our lives easier

**Comment by DentonGentry** [comment]
Work on this feature request is underway.

**Comment by mayakacz** [comment]
> Is this specifically just for pre-auth keys?

This issue is specifically about auth keys.

> Or will there be a way to generate new api keys as well? those need to get cycled and we'd love to have the ability for a CI system to automatically cycle those for us rather than requiring someone to manually do it every 90 days.

I think you're saying, you'd like to generate API keys without manual intervention. Can I propose filing a new FR for this? There are many potential solutions, and it would be good to understand what you're trying to do better, e.g., non-expiring API keys, renew API keys without manual intervention, or generate API keys without manual intervention.

**Comment by sylr** [comment]
Is there a schedule about this feature ? This is really something we are eager to see land.

**Comment by mayakacz** [comment]
As posted earlier, work on this is underway, and we hope to ship it soon. Thanks!

**Comment by DentonGentry** [comment]
Done.
- Authkey with tags assigned: https://tailscale.com/kb/1068/acl-tags/
- Generate authkey using API: https://github.com/tailscale/tailscale/blob/main/api.md#tailnet-keys-post

**Comment by michaelbeaumont** [comment]
> When re-tagging a device, including adding, changing, or removing tags, you will also be asked to authenticate.

I have nodes authenticated by an auth key generated by an admin _before_ this issue was closed (when the machine could still add and remove tags at will). Am I correct in interpreting the above quote from the docs to mean that if I now change the tags of that machine via the admin console, it _cannot_ use the fact that its auth key was created by/authenticated as an admin/tag owner to modify its tags or readvertise tags removed via the console?
