### ISSUE TITLE
FR: Open source the ios and macos gui wrappers

### ISSUE THREAD

**Issue by sevenrats** [tailscale/tailscale#13717]
https://tailscale.com/opensource

### What are you trying to do?

improve trust and transparency, review your code, see how tailscale works, benefit from what you have learned, participate in a shift toward considering what's possible in mesh networking, not be locked into or out of a specific platform, and provide tailscale with contributions and feedback.

### How should we solve this?

Open source all the gui wrapper irrespective of platform.  On your website you provide your reasons for supporting open source.  You should acknowledge that all of these reasons apply equally to ios and macos and the closed/open nature of the platform's licensing structure has no logical bearing on them.  The only differentiating factor you provide is 

```We enthusiastically support open source operating systems such as [Linux](https://github.com/tailscale/tailscale) and [Android](https://github.com/tailscale/tailscale-android), and we believe in directing time and energy to support the communities around these platforms.```

Ok, you are less enthusiastic about Apple.  Aren't we all?  What is the practical motivation for allowing tailscale to suffer from your relative lack of enthusiasm?  Why deny yourself, tailscale itself, and your users the benefits of open source that you so clearly delineate? 

### What is the impact of not solving this?

Have you considered the possibility that, given the above, this distinction might come across as tailscale engaging in pointless spite towards Apple at the expense of its users?

### Anything else?

Please either open source the code, or give us real material reasons for not doing so, because the explanation you have in place just does not feel good.

**Comment by bradfitz** [comment]
Our Windows GUI is also not open source, for the same reasons.

If users are comfortable running non-open operating systems or employers are comfortable with their employees running non-open operating systems, they should likewise be comfortable with Tailscale not being open on those platforms.

As I've written elsewhere, developing on macOS and iOS Network/System Extensions is a pain; it requires a bunch of Apple Entitlements and you need an XCode account in the right team that's been granted access to even compile the thing. We do not wish to support (answer questions) about all that. It's hard enough to support our own employees trying to compile our macOS app.

We let macOS and iOS and Windows users select alternate control plane servers (such as Headscale) and we're fine with that, but we have no plans to open source the macOS, iOS, or Windows GUI wrappers.

For a minimal open source GUI, see https://github.com/tailscale/tailscale/tree/main/cmd/systray which also works on macOS and Windows. It's new and rough, but patches welcome. We'd love to see some open source enthusiasm directed at that project.

**Comment by bradfitz** [comment]
> see how tailscale works

All the interesting bits are open source. The GUI wrappers are all roughly the same, in different languages, and don't contain any secret sauce.

**Comment by sevenrats** [comment]
that makes sense. Thank you for taking the time to explain.  having thought about it more, I think what I want, from my perspective, is a technical description of how a downstream implementer might use the code as it exists on these other platforms, right?  Something as simple as creating a document that described on a technical level how to go from the open source code to a barebones ios implementation may straddle that gap. maybe you could provide something, at the less complex level, like just some prose thats like "implement one of these, execute a this, enable the thing." at the more complex end, maybe you document an app skeleton that just gets the server running and then dont support it.  we do a similar thing with raspberry pi in jellyfin (we build for it but we don't answer support questions and automatically close tickets about it) and the support burden is minimal.  
is that something you would be comfortable with me bothering @agottardo with?

**Comment by raggi** [comment]
The android build provides most of the relevant insight you're asking for.

**Comment by agottardo** [comment]
Could you explain the final purpose of your request? What are you trying to build? You’re asking for proprietary information about our IP, but we don't know who you are, and you haven’t provided details about your ultimate goal.

The iOS app is fully built using native iOS, macOS, and tvOS technologies, developed with Swift and SwiftUI: no Kotlin or Jetpack Compose is involved. It bundles a network extension that runs the open-source version of Tailscale without any modification, similar to how `libtailscale` works on Android. We compile the open-source Go repo into a static library, linking it with a Swift wrapper that calls C code (very, very ugly stuff). CGo is used to bridge Swift and the Go codebase. Our proprietary code adds things _on top of_ the open-source code: we add support for Apple keychain APIs for encrypted data storage instead of files on disk, we have glue to convert Go network configurations into NetworkExtension.framework protocol configurations for network routes and DNS management, many workarounds for limitations in Apple’s VPN framework, and support for system policies through MDM for enterprise clients. None of this stuff is really specific to Tailscale, and you can find other open-source VPN apps that publish their iOS/macOS source code on GitHub (e.g. Mullvad) if you want a reference. 

Building a project like I just described requires an Apple developer account with a Team ID that was granted a network extension entitlement, as well as several other entitlements for privileged network information. Such entitlements must be requested from Apple and require a legitimate shipping product to get approved (a VPN app can snoop on traffic and DNS queries by definition, which is a significant privacy concern). Without the appropriate entitlements, the project cannot be compiled. Unless you are a Tailscale employee, it is so hard to even get started compiling the project that we would realistically get close to zero contributions from open-source enthusiasts. For context, our Android repo has essentially no barrier to entry for open-source contributions (anybody can just clone and build an APK off the repo in 5 minutes), yet we get no more than 10-15 PRs opened every year by OSS contributors. And the Android app is a much simpler project which uses Jetpack Compose and doesn't have to work around weird closed-source OS issues.

**Comment by Beshelmek** [comment]
I support this topic. There are no instructions or Makefile for iOS.

I would like to build my own iOS application, even without using "proprietary" gui libs.
Since our company does not use MDM, but we would like to brand or customize the application itself.

**Comment by sevenrats** [comment]
@Beshelmek the hard part is the network entitlements.  if your organization has those then it just needs some apple devs.  if it doesn't then there is really no hope.

**Comment by Beshelmek** [comment]
@sevenrats I think we would definitely have figured this out if we had at least the NetworkExtension source code

**Comment by Beshelmek** [comment]
@bradfitz @agottardo 

Back on topic, why can't you make it open source and warn people that you don't help with the build?
I think whoever needs to will figure it out.

**Comment by sevenrats** [comment]
@Beshelmek Do you understand what network entitlements are?  Having the source code wouldn't get you any closer to your goal.

**Comment by Beshelmek** [comment]
> @Beshelmek Do you understand what network entitlements are?  Having the source code wouldn't get you any closer to your goal.

Yes, I definitely understand.
