### ISSUE TITLE
Tailscale 1.76 setup fails on Windows 11 - 0x80070652 - Another installation is already in progress. 

### ISSUE THREAD

**Issue by usableweb** [tailscale/tailscale#13803]
### What is the issue?

Brand new Windows 11 system - newly activated - all available updates applied.  No existing Tailscale installation on system. 

Tailscale 1.76 setup fails with the error:

0x80070652 - Another installation is already in progress.  Complete that installation before proceeding with this install.

Log file contains:

[tailscale-error-log.txt](https://github.com/user-attachments/files/17352586/tailscale-error-log.txt)

### Steps to reproduce

Downloaded latest Tailscale setup for Windows from https://tailscale.com/download
Run setup.

### Are there any recent changes that introduced the issue?

No recent changes to the system.  Brand new Windows 11 system, recently activated and all available updates applied.

### OS

Windows

### OS version

Windows 11 Home 10.0.22631 Build 22631 (x64-based PC)

### Tailscale version

1.7.6

### Other software

No 3rd party anti-virus/security software installed - just what comes with Windows.

**Comment by nickkhyl** [comment]
@usableweb: Windows Installer allows only one product to be installed, changed, repaired, or uninstalled at a time.

The error you're seeing is from Windows Installer, rather than Tailscale, and indicates that Windows Installer cannot proceed with installing Tailscale because another installation is already in progress, likely for a completely unrelated product and not necessarily initiated by you. Since the system is brand new, it's possible that some drivers or OEM-bundled software are still being installed.

Waiting or rebooting your device might resolve the issue. You could also inspect the MSI Installer event log by opening Event Viewer, navigating to Windows Logs > Application, and filtering by event source. Look for any recent events that aren’t related to Tailscale. Events with ID 1040 that don’t have corresponding 1042 events for the same package might be particularly useful to investigate.

![image](https://github.com/user-attachments/assets/2a6989a5-9dd8-4d0d-b804-7b92f4f8f25d)

Lastly, if the issue persists, please consider installing Tailscale using the [.msi package](https://pkgs.tailscale.com/stable/#windows) to see if it makes any difference.

**Comment by usableweb** [comment]
Hi Nick -

Thanks for the rapid reply! You were right on it!

Looking at the Event Viewer, I found that the system was attempting to
install an update for the Intel Chipset Utility during startup, but was
never completing that task.  I removed the update from the package cache,
rebooted, and then Tailscale setup went just fine.

Thanks again!

-m
