### ISSUE TITLE
Android Errors don't disappear even after error condition resolved

### ISSUE THREAD

**Issue by erahhal** [tailscale/tailscale#14312]
### What is the issue?

I lost network connectivity, then joined a WiFi network with a captive portal. The android tailscale showed the red triangle error icon, and when I tapped it, there were two errors listed. After joining the network successfully, the tailscale client seemed to continue to work normally, but the errors were still there. It's been half a day and I'm back home, and the errors are still there, despite no apparent issues with the tailnet.

Not sure why Bug report ID is "BUG-NO-LOGS-NO-SUPPORT-this-node-has-had-its-logging-disabled". I didn't disable any logging.

![image](https://github.com/user-attachments/assets/9b2bc3ca-871f-4440-a7b0-350b715bf9f3)

### Steps to reproduce

Described in the issue above - lose connectivity, connect to wifi with a captive portal, notice errors, regain connectivity, errors don't go away.

### Are there any recent changes that introduced the issue?

No.

### OS

Android

### OS version

LineageOS 21 (Android 14)

### Tailscale version

1.76.6-t1edcf9d46-g

### Other software

No Google Play - running MicroG. Also Magisk. Otherwise a straightforward installation of Android.

Using with a personal Headscale node.

### Bug report

BUG-NO-LOGS-NO-SUPPORT-this-node-has-had-its-logging-disabled

**Comment by agottardo** [comment]
This should have been fixed in v1.78. Please refer to the [changelog](https://tailscale.com/changelog) for other changes, and ping me here if you still experience the issue after updating your client. You may not receive the update immediately because we do phased rollout, but you can download the same APK we distribute on the Play Store [here](https://pkgs.tailscale.com/stable/#android).

Logging is disabled because you're using Headscale.

**Comment by erahhal** [comment]
Thank you!
