### ISSUE TITLE
Macintosh HD and User Added Automatically As Shared Folders With Full Access

### ISSUE THREAD

**Issue by 621CRW** [tailscale/tailscale#14374]
### What is the issue?

So for some reason, Tailscale app has decided to share our Macintosh HD and User for which the server is being run from. I don't know how to remove these folders and I don't know how they are being shared. When connecting to a server via a Macbook, it asks if the Guest would like to mount "Macintosh HD" and "devilraiders" which is the only user on this Mac Studio computer. Can I get help removing these? 

### Steps to reproduce

No clue. I did update from Sequoia 15.1 to 15.2 and then these folders were added. That's when I noticed the issue.

### Are there any recent changes that introduced the issue?

The issue is ongoing. 

### OS

macOS

### OS version

Sequoia 15.2

### Tailscale version

1.78.1

### Bug report

BUG-98458a87bad1f4f52f3408852c4d0eb6838ef623f8f075e34aa319183a67f8eb-20241212181327Z-c4acc2cb6a84ece4

**Comment by agottardo** [comment]
This is not something that Tailscale caused.

Tailscale does include a folder sharing feature called Taildrive, which is currently in development and is not publicly available yet. It requires manual configuration via the client CLI/GUI, and every folder must be exactly shared individually. This feature is not causing what you're seeing.

You should check the configuration of the macOS built-in file server in the System Settings app, in order to disable it.
