### ISSUE TITLE
cmd/tailscale: CLI help text is confusing for booleans

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1529]
User writes:

>Hello,
>
> your client states "-accept-dns true" but this is not correct. In any way it would be
> "-accept-dns=true" as without the "=" it won't work with
> error "too many non-flag arguments".
```
USAGE
  up [flags]
...
FLAGS
  -accept-dns true                           accept DNS configuration from the admin panel
```

I replied:

> Oh, interesting. That's the default output from Go's flag parsing library showing the default value, not how to set the value.
>
> We'll modify that to be more clear.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2x769)

**Comment by willnorris** [comment]
This actually [comes from ff](https://github.com/peterbourgon/ff/blob/7f261dec7e12a43b784b972bde696d82249988e2/ffcli/command.go#L233).  

@peterbourgon, would you be open to changing the flag output format to make this clearer?  Looks like you intentionally deviated from the default flag package.

**Comment by peterbourgon** [comment]
So that's just the [DefaultUsageFunc](https://pkg.go.dev/github.com/peterbourgon/ff/v3/ffcli#DefaultUsageFunc), but you can implement your own, and provide it as the UsageFunc in a [Command](https://pkg.go.dev/github.com/peterbourgon/ff/v3/ffcli#Command).

But yes, this is ambiguous, I'll change it in a bit here, or you can PR if you feel up to it. Should it just put an `=` instead of a space for everything? Or should it special-case bools? 🤔

**Comment by willnorris** [comment]
maybe the `=` is sufficient?  Certainly the flag package's behavior of `(default true)` is the most explicit.

**Comment by bradfitz** [comment]
I'll just replace ours locally with something super explicit for people not familiar with the Go ecosystem.
