### ISSUE TITLE
Build a coordination server status page

### ISSUE THREAD

**Issue by rosszurowski** [tailscale/tailscale#1553]
A few users have written in asking for a status page indicating whether the coordination server is online or having issues. We've delayed on this, as [Tailscale is designed to function even without the control server](https://tailscale.com/kb/1091/what-happens-if-the-coordination-server-is-down), so rare outages already have minimal impact. The main restriction is you can't add _new_ devices to your network while the control server is down.

There's still value in having a status page: it's a chance to communicate our resiliency to users, can reassure them that the control server isn't down while they're debugging networking problems, and gives users a place to look when there _is_ an outage.

Our status page will need to distinguish between:

- Tailscale client communication outages (which, by design, should never happen en-masse)
- Tailscale control server outages (which only "freeze" network config, but don't affect traffic)
- Tailscale admin panel outages (which again, only "freeze" network config, but don't affect traffic)
- tailscale.com outages (which have no impact on our service at large)

**Comment by mnaser** [comment]
Question: wouldn't a relay server outage/issues result in client-facing problems that they might struggle to debug?

**Comment by benz2012** [comment]
+1 for this status page / communication stream (and +1 from my Team at [Crafty Apes](https://www.craftyapes.com/)) as the sanity check would be much appreciated when we see authentication issues like the ones caused by #4168

We force our users to re-authenticate daily, which, from what we've heard, makes us an outlier. Unfortunately, that also means we're heavily affected by these outages.

Also, because of the nature of our business, we frequently add new devices to the network, which would also be affected by the outages described in this issue's description.

**Comment by benz2012** [comment]
+1 for this status page / communication stream (and +1 from my Team) as the sanity check would be much appreciated when we see authentication issues like the ones caused by https://github.com/tailscale/tailscale/issues/4168

We force our users to re-authenticate daily, which, from what we've heard, makes us an outlier. Unfortunately, that also means we're heavily affected by these outages.

Also, because of the nature of our business, we frequently add new devices to the network, which would also be affected by the outages described in this issue's description.

**Comment by andrew-d** [comment]
We now have a status page at https://status.tailscale.com which tracks the current status of the main Tailscale components and has a section for ongoing and recent incidents.
