### ISSUE TITLE
Android uploaded log lines are truncated at ~244 bytes?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1625]
I'm looking at some Android logs and I see:

```
2021-03-30 17:56:16.590914954 +0000 UTC: 5.3M/114.6M netmap packet filter: [[0.0.0.0/2,64.0.0.0/3,96.0.0.0/6,100.0.0.0/10,100.64.0.0/11,100.96.0.0/12,100.112.0.0/13,100.120.0.0/14,100.124.0.0/18,100.124.64.0/21,100.124.72.0/22,100
.124.76.0/29,100.124.76.8/30,100.124.76.12/31,100.124.76.14/32,100.…
[...]
2021-03-30 17:56:17.135799277 +0000 UTC: 9.8M/119.0M magicsock: endpoints changed: 176.126.124.3:32867 (stun), 10.253.0.3:48597 (localAddresses), 192.168.41.196:48597 (localAddresses), [2a04:4a43:bb:8cc7:3937:fb90:21f3:b6]:48597 (localAddresses), [fd8f:c845:4e92:1:808c:affb:491b:5a03]:48597 (loca…
```

Notably, there's a little unicode `…` codepoint on many lines after ~244 bytes of log line (ignoring date).

Is there some 256 byte limit or something somewhere, @eliasnaur?

**Comment by crawshaw** [comment]
Android can only tweet logs?

**Comment by eliasnaur** [comment]
I believe the maximum log line size is device dependent; my emulator supports lines much longer than that. https://stackoverflow.com/questions/6321555/what-is-the-size-limit-for-logcat-and-how-to-change-its-capacity suggest the common limit is around 4000 bytes. https://android.googlesource.com/platform/system/core/+/jb-dev/include/android/log.h says ~1024 bytes, which is what Gio uses.

I'll lower the limit to 256 and do a release, along with an upgrade of the androidx.security Java dependency.

**Comment by bradfitz** [comment]
We need to do the opposite: figure out how to get our logs uploaded without truncation, even if they're truncated in logcat. I guess we'll have to rearrange how we wire up logging and the stderr interception.

**Comment by eliasnaur** [comment]
I found https://github.com/tailscale/tailscale/blob/a39d2403bcaf84557d8040831b6aad7b513a411b/logtail/logtail.go#L457 I'll release a version without LowMemory = true (cargo culted from the iOS app).

**Comment by bradfitz** [comment]
Hah, wow. I'd totally missed that, thanks!

@crawshaw, @apenwarr, do you remember the rationale for this? The 254 byte limit was making an Android issue undebuggable for me.

**Comment by apenwarr** [comment]
Crawshaw set it on iOS at some point when we were really tight on memory, probably so that we could easily guarantee that max_line_length * max_lines was below a certain memory usage threshold.

As time goes on, we might rely more on certain lines not getting dropped for security reasons (eg. firewall accept/drop lines). Even with a more flexible control over log line usage, it would be bad if a single huge line crowded everything else out of the log buffer.

We can probably afford to be a little more flexible though, since it seems clear nowadays that log buffer usage was probably never the main memory problem on iOS, and Android is AFAIK more flexible about RAM anyway.
