### ISSUE TITLE
Support split DNS in android

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1695]
The android client needs updating to support split-DNS:
 - update code to use net/dns and new router APIs. May have to use wgengine/router.CallbackRouter. Bunch of APIs moved around, so need to get it back to building successfully again.
 - Figure out how to read the "base" DNS config out of android, i.e. the config with no tailscale stuff in it. Might be as simple as reading /etc/resolv.conf from the app, if sandboxing hides tailscale's DNS settings from the app, or might be more complex.
 - Test. Right now split DNS requires a server side feature flag to get split configs, so if I'm not the one that ends up testing it, may need to toggle the flag on extra domains.

cc @eliasnaur FYI

**Comment by DentonGentry** [comment]
Android's API is not helpful in this:
- no notion of split DNS or ability to add a DNS server to use for specific domains
- cannot even read out the current DNS settings, in order to implement the support ourselves.

**Comment by DentonGentry** [comment]
Regarding the second point to read a DNS config out of Android, https://github.com/tailscale/tailscale/issues/2116 describes a method that may not be exactly accurate but should be close:
- use ConnectivityManager to determine the active link, and then ConnectivityManager->getLinkProperties->getDnsServers to retrieve the DNS servers for that link
- check Settings.Global.PRIVATE_DNS_MODE whether DNS-over-TLS is enabled, and Settings.Global.PRIVATE_DNS_SPECIFIER to retrieve the name of the DNS server if it is set to always-on.

**Comment by danderson** [comment]
Hmm, when I explored this last, I recall there were APIs for reading out DNS configs that had been removed from more recent Android versions... But the ConnectivityManager API doesn't seem to carry any such warning, it's just gated behind a permission we might already have.

**Comment by DentonGentry** [comment]
In Android prior to 8 there was an API to ask Android what DNS config it was currently using, by querying system properties net.dns1, net.dns2, etc. That API has been disabled, the net.dns* properties are now empty strings.

The ConnectivityManager APIs return correct values in current Android versions, but we'd be reverse engineering what Android does to assemble its DNS config rather than being able to ask Android directly.

**Comment by DentonGentry** [comment]
Android added Split DNS support some time ago.

Subsequent correspondence on this bug is about the need for Fallback DNS servers for Android. A plan to be able to retrieve the current DNS config for Android is described in https://github.com/tailscale/tailscale/issues/2116 and https://github.com/tailscale/tailscale/issues/1743

I'm going to close this one since Split DNS support for Android did ship.
