### ISSUE TITLE
Tailscale on ASUS Merlin AC86U ?

### ISSUE THREAD

**Issue by lemonsz15** [tailscale/tailscale#1705]
Is it possible to run Tailscale on ASUS Merlin AC86U ? As it was able to run wireguard via entware. Thanks !

**Comment by DentonGentry** [comment]
The ASUS Merlin AC68U is not a platform we directly support, however according to https://github.com/tailscale/tailscale/issues/1597 a Tailscale package has been added in Entware and may be suitable for your uses.

**Comment by lemonsz15** [comment]
Cool ! Thanks for the information. I've just successfully installed it via entware , while running 'tailscaled &' and logged in my account, and  also showed up at the admin console. But when I tried to run 'tailscale up' , it came up with the following error,   

[[[[ Failed to connect to tailscaled. (safesocket.Connect: dial unix /opt/var/run/tailscale/tailscaled.sock: connect: connection refused) ]]]]

Would you mind to help me to sort this out, although I understand that tailscale doesn't offer an official support right now for this platform. It would be great if you could advice. Thanks !

**Comment by lemonsz15** [comment]
FYI, I always got disconnected from putty after running ' tailscaled &' , and the last messages shows :

Switching ipn state NoState -> Starting (WantRunning=true)
magicsock: SetPrivateKey called (init)
wgengine: Reconfig: configuring userspace wireguard config (with 2/9 peers)
magicsock: CreateEndpoint: key=[dXgK5]: 6170df3cc64aa853ed7a400240a2416d720d2e23220f07edfd515cba106a8538.disco.tailscale:12345
magicsock: CreateEndpoint: key=[zMfzL]: a700491ca97e300c1e29cd35ed64652ce00d911aedb33a0e94d92436e825ee45.disco.tailscale:12345
wgengine: Reconfig: configuring router
router: dns: Set: {Nameservers:[8.8.8.8 1.1.1.1 114.114.114.114] Domains:[] PerDomain:false Proxied:false}
health("overall"): error: state=Starting, wantRunning=true

**Comment by DentonGentry** [comment]
The error about /opt/var/run/tailscale/tailscaled.sock means that tailscaled isn't running at that moment. Since it was started within the ssh session, when PuTTY disconnects tailscaled and any other background process would be automatically killed.

If the `nohup` command is present in the system, it might allow tailscaled to continue running even after ssh disconnects: `nohup tailscaled &`

However I suspect that the ASUS Merlin is running out of RAM, and that PuTTY disconnects because the kernel has to start killing processes to reclaim RAM. To be able to add tailscale you may have to give up some other service.

**Comment by DentonGentry** [comment]
I'm going to close this for now, as Entware isn't a platform we really support (though we'll help answer questions for people working on it). Please feel free to reopen if anything else needs clarification.
