### ISSUE TITLE
wgengine/netstack: logging binary data

### ISSUE THREAD

**Issue by josharian** [tailscale/tailscale#1757]
I see these while printing Avery's logs:

```
unable to recover from bad data: "{\"text\": \"{\\\"logtail\\\": {\\\"client_time\\\": \\\"2021-04-16T16:46:29.211772-04:00\\\"}, \\\"text\\\": \\\"2021/04/16 16:46:29 UDP ForwarderRequest: &{0xc00028c600 {51877 d]Ir 3544 (w\a�} 0xc0001083c0}\\\\n\\\"}\\n\"}\n"
```

The problem is invalid JSON, due to us logging binary data. The relevant log line is netstack.go:475:

```
	ns.logf("[v2] UDP ForwarderRequest: %v", r)
```

r is an `*udp.ForwarderRequest`, which contains a bunch of binary data. (And maybe some private data? I'm not sure.) In any case, this log output isn't very helpful. Let's either define a string method on `*udp.ForwarderRequest` or modify this log entry to log something clearer (and non-binary and non-private).

**Comment by namansood** [comment]
I don't think we can define a string method on `*udp.ForwarderRequest` since that type is made by netstack, not us.

Also, there is a similar call to printing a `*tcp.ForwarderRequest` as well, though that's hidden behind a `debugNetstack` flag that's never true in code pushed to main.

ForwarderRequests seem to have an `ID()` method that give some information about the origin and destination addresses, I could make a function to log that out for both TCP and UDP, as well as hide the UDP output behind the same debugNetstack flag.

Would appreciate @bradfitz's thoughts here too.

**Comment by josharian** [comment]
Using the `ID` method seems reasonable, if it serves the purposes for which you are logging.

**Comment by bradfitz** [comment]
We also probably just don't want to log that much, even for [v2], for all traffic. Imagine this is an exit node and a bunch of people are using it. We do not want logs of all those flows.

Change it to the ID method, but also put it behind the existing `if debugNetstack {` (which is `const debugNetstack = false`). People can enable it when hacking on netstack.
