### ISSUE TITLE
Customer is unable to downgrade their plan from admin console

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1801]
The customer is on the Tailscale "Security" plan and downgrade to the free "Solo" plan. He can access your billing URL, where he can see his current plan, and he can get as far as the "Downgrade my account" button. However, after clicking downgrade, nothing happens. 
<img width="960" alt="account" src="https://user-images.githubusercontent.com/75628398/116147089-490bdf80-a6ad-11eb-9241-a3a25e2fa7c4.png">
<img width="960" alt="downgrade" src="https://user-images.githubusercontent.com/75628398/116147095-4ad5a300-a6ad-11eb-99c1-4d83ea4f6bdb.png">

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_32mvl)

**Comment by rosszurowski** [comment]
What browser is this? Are there any errors in the browser console? I tested it earlier today and it downgraded without issue.

**Comment by gerrowadat** [comment]
Can confirm this has been happening a while - I had believed I downgraded to Solo about a month ago, but it didn't take (I had to go via support to do it today).

**Comment by gerrowadat** [comment]
![Screenshot from 2021-04-27 18-05-18](https://user-images.githubusercontent.com/381110/116282963-44b1f600-a783-11eb-9066-d4619180f8a0.png)

I see the following on the plan choice dialog screen, not sure if this is relevant.

**Comment by rosszurowski** [comment]
Interesting… I'll spin up a Linux VM with Chrome to see if I can replicate and post here with an update. Thanks for reporting this, and for your patience with this issue.

**Comment by 33b5e5** [comment]
I was unable to downgrade from Firefox 89 (beta) on Windows. After you click the red "Downgrade my account" button, it takes you back to the account/billing page but nothing has changed. Sorry, I didn't grab console logs before support downgraded the account. I think I tried on another browser, Edge (Chromium) 90, with the same result.

**Comment by rosszurowski** [comment]
After a bit of digging I think I uncovered the root cause: we use Turbolinks to speed up page navigations on tailscale.com, but it blows away some event handlers in some contexts if they're associated to the wrong element. The downgrade button was one of these elements.

I've fixed how we attach events and updated the button to not take you anywhere if the downgrade wasn't successful, so hopefully this problem is now resolved. In some testing on production, it seems to be… but please let me know if you see otherwise.

Sorry for the difficult in unsubscribing. It certainly wasn't intentional.
