### ISSUE TITLE
MagicDNS serves IPv6 AAAA records for nodes that do not support IPv6

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#1813]
Steps (perhaps not all necessary):
- Install tailscale 1.7.365 on Windows (glide)
- Downgrade to tailscale 1.4.5
- ping glide from a Linux box running 1.7.365

Expected:
Ping works

Actual:
Ping fails because it selects the IPv6 address of glide, but tailscale 1.4.5 did not support IPv6.
IPv4 ping works.
If I upgrade Windows to 1.6.0 or higher, the IPv6 ping works.

I'm not sure, but I think this is a regression from v1.6.0 because I don't think that one served IPv6 to MagicDNS. But the real cause is perhaps the fact that control serves IPv6 addresses in the netmap for old nodes anyway?

cc: @danderson

**Comment by bradfitz** [comment]
I just looked and confirmed that I'm seeing control send IPv6 addresses for even 1.0.x and 1.2.x nodes.

**Comment by danderson** [comment]
Yeah, for exit nodes it was fine to distribute v6 addrs for nodes that don't support v6, because we were relying on happy eyeballs to fix things up. Somewhere in the DNS rework, I accidentally made MagicDNS start serving AAAA records, which is not currently safe for us to do everywhere.

Let's turn off AAAA MagicDNS records for now. To turn them back on we need to report v6 capabilities to control, and have it generate the right address sets for nodes.
