### ISSUE TITLE
Android: VPN not set up automatically after device reboot

### ISSUE THREAD

**Issue by Profpatsch** [tailscale/tailscale#1844]
**Describe the bug**

On my Blackberry KeyOne, when I restart my device (with active tailscale connection beforehand), after restart the VPN connection will not be set up. When I open the app, it says “active”, but I need to disable and enable the button to actually make it connect.

**To Reproduce**
1. Activate tailscale
2. reboot
3. (no key-icon displayed in the menu bar, no VPN active)
4. go to tailscale app
5. uncheck button, check button
6. key icon displayed in menu bar

**Expected behavior**
tailscale should automatically reconnect after reboot, if it was enabled before.

**Version information:**
1.6.0-tddc975cb-g05212e770b0 (fdroid)
Android 8.1.0 (oreo)
Phone: BBB100-2 (blackberry keyone)
Security level: 5th of April 2019 (yes I know, Blackberry’s fault)
Rooted phone: no (default image)

**Comment by DentonGentry** [comment]
This is done in the Settings > Network & Internet > VPN.
With Tailscale connected, you can select the gear icon next to its name and enable "Always-on VPN"

VPN apps are not allowed to set themselves to be always-on, because that could be abused for unsavory practices. Instead Android allows the user to set it to be always on.

![Screenshot_20210720-213728](https://user-images.githubusercontent.com/1140756/126432545-b2ff413a-5cca-415b-8994-7bf9d3639841.png)

I'm going to close this, please reopen if it doesn't work or there are still issues.

**Comment by Profpatsch** [comment]
Ah, good to know, set it, restarted my system, seems to have autostarted tailscale.

Maybe the tailscale app should tell the user that this is possible and recommended.
