### ISSUE TITLE
No Auth URL being delivered by status --json after version 1.7.273

### ISSUE THREAD

**Issue by apocnz** [tailscale/tailscale#1858]
**Describe the bug**
The AuthURL value is not populated in the "tailscale status --json" output after version 1.7.273

**To Reproduce**
In versions 1.7.273 and higher

tailscale status --json 

**Expected behavior**

When status is "Login Needed", a auth url should be supplied in the status output

**Screenshots**

![tailscale-screenshot1](https://user-images.githubusercontent.com/38557583/117224708-3890fd00-ae43-11eb-9b0c-a0dad64a5dd5.png)

** Nothing in the log (log is empty), to give a clue about why

**Version information:**

HostInfo: {"IPNVersion":"1.7.403-tbf5fc8edd-ga86fe1ca2","BackendLogID":"411f207eeb0339be8a0f5f6a7df8fde53cf949ec0c0bc3e5165aa85f4b21da99","OS":"linux","OSVersion":"Other; kernel=3.18.20","Hostname":"endeco","GoArch":"arm"}

**Additional context**

Version 1.7.14 and below does not experience this issue. We use the json output to grab the auth url and
present a "Auth Now" button on our web ui.  No auth url = blank tab opens

Obviously this is on the unstable track stuff, but thought I'd give a heads up just in case something had slipped under the radar, given versions from 1.7.273 exhibit this issue.

**Comment by DentonGentry** [comment]
This should be addressed by https://github.com/tailscale/tailscale/commit/2f17a34242bd73036a3c55a02caf9ad07f60fb45 which went in 4/21. I'll need to check whether 1.7.403 contained that commit, though given the timing I think it should have.

**Comment by DentonGentry** [comment]
Well, shoot.

```
dgentry@ubuntu:~/Documents/Code/tailscale/tailscale$ tailscale version
1.7.446
  tailscale commit: 6d10655dc3887f1a161015514a8555c175802b4d
  other commit: d4cf942c9a99ca0d40f469e7a5f154c78ab0d667
  go version: go1.16.3-ts2c6ff2c
dgentry@ubuntu:~/Documents/Code/tailscale/tailscale$ sudo tailscale logout
dgentry@ubuntu:~/Documents/Code/tailscale/tailscale$ sudo tailscale status --json
{
  "Version": "1.7.446-t6d10655dc-gd4cf942c9",
  "BackendState": "NeedsLogin",
  "AuthURL": "",
```

**Comment by bradfitz** [comment]
I just went to bisect, but it's working as intended at all commits.

Version 1.7.14 predates lazy machine key generation (https://github.com/tailscale/tailscale/issues/1573) which was fixed in https://github.com/tailscale/tailscale/commit/9b57cd53baad8c6f75988475cfbf58f4731b011f and went out in 1.7.273, the version you report it stopped working.

"NeedsLogin" doesn't necessarily mean that there's an AuthURL available. It can also mean that `tailscaled` is sitting idle, never having contacted the control plane at all, in which case you need to do a `tailscale up` to start it up.

**Comment by apocnz** [comment]
Seems indeed, we were being lazy and not using tailscale up :) 

Cheers Brad.
