### ISSUE TITLE
acl: rename "users" and "ports" to "source" and "destination"

### ISSUE THREAD

**Issue by rosszurowski** [tailscale/tailscale#1931]
I was reviewing the ACL docs with @darshinimashar because several users have written in recently asking questions about ACLs that the docs answer. Among them are common questions around what values are supported in individual ACL rules: can you use IPs or subnets in "Users"? What about tags? And in ports too, are tags accepted? What about usernames?

We've tried to document this with [a list-based format](https://tailscale.com/kb/1018/acls/#acls) so it's easier to see. I have some updates planned to improve this too. But it made me realize that the core of the confusion is the field names: `"Users"` is no longer just users, and `"Ports"` is no longer just ports. We still need to document what values are accepted, but we can avoid a bunch of confusion by renaming them to more appropriate names like `"Source"` and `"Destination"` or `"Dest"`.

To migrate these field names, we could just copy existing Users/Ports values to the new field names and update the default template with the new names.

/cc @apenwarr

**Comment by apenwarr** [comment]
Yeah, I've thought of these before. We could alias the two sections, and merge them at read time. We could also reject any ACL with both Sources+Users or Ports+Destinations.

In the spirit of annoying name bikeshedding, we should also decide:
* whether they should be pluralized or not (since they are lists, the default answer should be yes, even though it feels a little weird when used with these terms)
* whether we should spell out long words (Sources/Destinations), or compress them (Source/Dest), or highly compress (Src/Dst). I would suggest copying iptables, but it helpfully provides both --destination and --dst as an alias.
* whether to try to emphasize the fact that sources have no port field, but destinations to have a port field. In the current naming (Users/Ports) this is somewhat more obvious. Technically it's something like SourceHosts and DestPorts, but that's really awkward.

**Comment by md-magenta** [comment]
This seems to have been done. The [documentation](https://tailscale.com/kb/1018/acls/) states:
> Previously we used `users` and `ports`, instead of `src` and `dst`, respectively. While both sets of terms are currently supported, we are using `src` and `dst` going forward.
