### ISSUE TITLE
Ephemeral Keys + SOCKS5 Proxy No Route

### ISSUE THREAD

**Issue by morgangallant** [tailscale/tailscale#1952]
Seems like switching to Ephemeral Keys (from Reusable) broke the SOCKS5 proxy functionality within `tailscaled`. I've been experimenting in [this repo](https://github.com/morgangallant/containerized-tailscale), and my entry script looks like [this](https://github.com/morgangallant/containerized-tailscale/blob/trunk/entrypoint.sh). After switching to Ephemeral Keys this morning, I started getting "no route" errors when making outgoing HTTP requests to machines on my Tailscale network via the SOCKS5 proxy. I might be doing something wrong, but I switched back and forth between using a Reusable Key and an Ephemeral Key, the former worked flawlessly and the latter didn't. Is this some sort of permissions or security choice possibly?

Error:
```
2021/05/19 00:54:54 socks5: client connection failed: connect tcp 100.73.249.25:80: no route
```

Currently running Tailscale v1.8.1 as per [this Dockerfile](https://github.com/morgangallant/containerized-tailscale/blob/trunk/Dockerfile). Happy to help test here and provide more information, I'm hugely excited about Ephemeral Keys , as my current solution to this problem relies on doing Tailscale API calls on SIGINT/SIGTERM to delete the machine from my Tailnet on shutdown.

**Comment by DentonGentry** [comment]
Ephemeral keys only allocate an IPv6 address, like fd7a:115c:a1e0:ab12:0102:0304:0506:0708. All tailscale nodes running v1.6 or later have an IPv6 address. You'll need your app to connect to the IPv6 address, instead of an IPv4 address like 100.73.249.25.

The IPv6 address of each node can be found from the CLI using `tailscale status --json`, or using the Magic DNS name to look up a AAAA record.

We do this because some of the use cases for ephemeral keys create and destroy containers at a relatively high rate, and IPv4 addresses are a limited resource.

**Comment by morgangallant** [comment]
Got it, this makes a lot of sense, wouldn't want to flood the IPv4 address space with a bunch of temporary machines :) I just pushed up a fix to my demo repository and it's working great now ([link](https://containerized-ts-production.up.railway.app/)). I broke prod this morning w/ the Ephemeral stuff, so hopefully this deployment goes a little bit better!
