### ISSUE TITLE
Exit node doesn't work in userspace networking mode

### ISSUE THREAD

**Issue by lewispeckover** [tailscale/tailscale#1970]
When running `tailscaled --tun=userspace-networking --socks5-server=localhost:1080` and ` tailscale up --exit-node=x.x.x.x`, `tailscale status` shows the exit node configured correctly.

I expect traffic sent through the socks proxy to go via the exit node, but it does not. (v1.8.5 AlpineLinux)

**Comment by rugwirobaker** [comment]
@lewispeckover have you managed to make this work?

**Comment by razielgn** [comment]
Any news on this? :)

**Comment by DentonGentry** [comment]
I don't believe that is the same issue. I think the issue you are running into is that in `userspace-networking` mode, tailscaled cannot support any arbitrary Linux sockets application. Apps have to be set to use a SOCKS5 or HTTP proxy.

This bug was resolved two years ago, I'd suggest to keep the discussion of the Action workflow you're working on in https://github.com/tailscale/github-action/issues/96
