### ISSUE TITLE
ACME DNS challenge fails when using Magic DNS

### ISSUE THREAD

**Issue by astrophena** [tailscale/tailscale#1972]
Recently I noticed that Caddy on my server fails to obtain certificates with this strange error message:

```
presenting for challenge: could not determine zone for domain \"_acme-challenge.feed.astrophena.name\": unexpected response code 'FORMERR' for _acme-challenge.feed.astrophena.name.
```

Disabling Magic DNS with `tailscale up --accept-dns=false` fixes this.

Tailscale IP of my server: `100.97.68.56` (`fd7a:115c:a1e0:ab12:4843:cd96:6261:4438`)

**Comment by blattersturm** [comment]
>added label: almost no one
>added label: minor usability

I would like to congratulate you on the perfect labelling for issues that break communication for people who don't even use your service.

I've been trying to contact an individual via Matrix, who has been hosting their own 'home server' as one calls it, but kept getting hit by the Synapse server returning 401 errors when delivering messages to their Synapse server.

Way, way later, I discovered this is because their system had somehow set `100.100.100.100` as DNS server, which magically (that's why you call ti 'Magic DNS', right?) decided to be unable to resolve my SRV record, citing a 'format error':

```
$ dig srv _matrix._tcp.matrix-fed.cfx.re

; <<>> DiG 9.16.15 <<>> srv _matrix._tcp.matrix-fed.cfx.re
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 31372
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; WARNING: EDNS query returned status FORMERR - retry with '+noedns'

;; QUESTION SECTION:
;_matrix._tcp.matrix-fed.cfx.re.  IN  SRV

;; Query time: 0 msec
;; SERVER: 100.100.100.100#53(100.100.100.100)
;; WHEN: Tue Jun 01 22:29:28 CEST 2021
;; MSG SIZE  rcvd: 48
```

Of course, this entry exists, but it then puzzled the recently-in-contact-again 'us' that this server was set.

Instinctively, we then ended up finding out it was this wonderful VC-backed proprietary-backend 'has a pricing page' pretending-to-be-open 'Tailscale' product of yours (@astrophena, @DentonGentry, et al.) hosting this server on the weirdest-sounding IP address, and tried to check the DNS servers set in the 'admin console'.

Of course, using `dig` on them directly, worked fine.

This means **your** beautiful product has been harming a non-user who will **never** use this product solely as it seems to pretend to be 'unmissable' while having the most toxic commercial behavior and broken code targeted towards VC series XYZ funding, rather than making a future for everyone.

And then you have the nerve to call this issue, which harmed me as a non-user, to affect 'almost no one'. What are you even basing this data on, Mr. Gentry, from what I would assume the wonderful Bay Area distortion field? Your affluent San Francisco compatriots who spend their days and nights dreaming of venture capital riches, while harming innocent bystanders?

Yeah, there's one label here I can agree on, and that's 'Aggravating'. Users who have no intent of ever using your product, users who have no intent on ever _thinking of using your product_ being harmed by this disgusting project 'magically' deciding a 'magic' feature should just corrupt and form-error SRV records.

Thanks for that. Hope you'll have a great IPO leading to many riches for your C*Os and stock options for all of you deciding a world-breaking issue hits 'almost no one', and breaking SRV records is a 'minor usability' issue.

**Comment by bradfitz** [comment]
Fixed by https://github.com/tailscale/tailscale/commit/caaefa00a0605834279bc01ec43b9e48e8588d72 for dup issue #2024. It'll be backported to the stable release.

Yes, the "almost no one" wording isn't the best. In the grand scheme of things numbers-wise it may be true, but it doesn't make reporters feel good. We can change that.

**Comment by blattersturm** [comment]
Thanks.

My reply was (obviously?) a bit hyperbolic, a little bit of venting at the long-winded diagnosis of this and a bit of note of how a bug can affect even unrelated people.

It's a shame that when coding defensively, such things do tend to slip through.

**Comment by DentonGentry** [comment]
The text on the labels was not great, and we've updated those.

We use the L1-L5, P1-P6, and T0-T8 levels to sort issues in the backlog. It is a fair point that because the impact of this issue extends well beyond the specific node where it occurs, L1 was not correct and it should have been higher. In any case, https://github.com/tailscale/tailscale/commit/caaefa00a0605834279bc01ec43b9e48e8588d72 should fix the issue and we'll get it delivered into the current release train.
