### ISSUE TITLE
Taildrop alpha  - needs port 61152 open in firewall

### ISSUE THREAD

**Issue by mheland** [tailscale/tailscale#2002]
Using ufw to restrict access to server over tailscale0 interface
Unable to use Taildrop if port 61152 is closed. 

Enable taildrop with `sudo ufw allow in on tailscale0 to any port 61152`
Ideally this information should be provided when assigning drop directory with `sudo tailscale file get /home/drop/directory/`

Also, a root crontab can drop the received files every five minutes and assign user group
`*\5 * * * * tailscale file get /home/drop/directory && chown magnus:magnus *`

**Comment by bradfitz** [comment]
The port is dynamic. It's not necessarily 61152.

**Comment by carlpett** [comment]
I just ran into this, although with `firewalld` instead of `ufw`. `firewalld` however does not log dropped connections in default configuration, so it took looking though all taildrop issues (naturally, this one is the last one in the listing...) to figure out this could be the problem.
I'd say finding this is fairly unintuitive - no errors are reported on the receiving side, and the iOS app I try to send from says I need to re-auth the receiving device.
