### ISSUE TITLE
[Bug or Question] Why I can't add global dns of 127.0.0.1, it cause that tailscale android 1.8.6-t28a8f9c90-g04890797712  won't start

### ISSUE THREAD

**Issue by diyism** [tailscale/tailscale#2033]
I installed 1.8.6-t28a8f9c90-g04890797712 on my android phone, but it won't start, when I click the switch button on the top left, it always switch back to "Stopped".

After I uninstall 1.8.6-t28a8f9c90-g04890797712 and download and install the 1.8.3 version from f-droid, it can switch to "Active" without go back to "Stopped".

But 1.8.3 has bug: #1991 

My exit node for example is : 100.71.153.10
My dns server run on exit node: ./mydns --listen 0.0.0.0:53          (ie: listen on both 100.71.153.10:53 and 127.0.0.1:53)
My global dns settings is:  100.71.153.10   and 127.0.0.1 with "Override local DNS" checked
My android phone has installed 1.8.6-t28a8f9c90-g04890797712
I want my android phone's traffic and dns query go through my exit node 100.71.153.10
The /etc/resolv.conf file in my exit node was overwriten by the tailscale,
I would like that the dns can fallback to 127.0.0.1 when tailscale failed to create the tailscale0 interface in my exit node(if without fallback dns, it maybe cause the exit node can't connect the tailscale mesh network again),
so the 127.0.0.1 should not be deleted in the global dns settings in the web page: https://login.tailscale.com/admin/dns

The android phone logcat:
06-02 14:01:31.657  2097  2138 I com.tailscale.ipn: 7.8M/80.4M dns: OScfg: {Nameservers:[100.71.153.10 127.0.0.1] SearchDomains:[] MatchDomains:[]}
06-02 14:01:31.659  2097  2138 I com.tailscale.ipn: 7.8M/80.4M peerapi disabled; no state directory
06-02 14:01:31.659  2097  2159 I com.tailscale.ipn: 7.8M/80.4M Switching ipn state Starting -> Running (WantRunning=true, nm=true)
06-02 14:01:31.684  2097  2159 I com.tailscale.ipn: 7.9M/80.4M netcheck: probePortMapServices: failed to look up gateway address
06-02 14:01:31.693  2097  2138 I com.tailscale.ipn: VPN update failed: VpnService.Builder.addDnsServer(127.0.0.1): java.lang.IllegalArgumentException: Bad address
 
Why the global dns setting overwrite the dns settings of my exit node? I think the global dns seetings should overwrite the dns seetings of all my phones, but it should not  overwrite the exit node's dns setting(/etc/resolv.conf)

**Comment by normanr** [comment]
btw, I "worked around" this sort of issue by adding `--accept-dns=false` to my `tailscale up` command on my exit node. I had to manually configure my dns server to use `100.100.100.100` to resolve all 67 tailscale zones, but it does work.

**Comment by diyism** [comment]
> btw, I "worked around" this sort of issue by adding `--accept-dns=false` to my `tailscale up` command on my exit node. I had to manually configure my dns server to use `100.100.100.100` to resolve all 66 tailscale zones, but it does work.

Thanks, it's a good work-around. I'll close the issue

**Comment by DentonGentry** [comment]
Reopening because I'd like us to consider why 127.0.0.1 isn't allowed and whether that should be changed.

**Comment by bradfitz** [comment]
Well, the meaning of the global DNS is that it's the DNS that everybody in the network should use, so all nodes in the tailnet would need a 127.0.0.1 DNS server, which seems unlikely. Seems like a footgun.

**Comment by normanr** [comment]
It looks like VpnService.Builder.addDnsServer isn't accepting 127.0.0.1, which isn't something tailscale has direct control over. This isn't too surprising because 127.0.0.1:53 is often reserved for a local caching resolver, and it's highly unlikely to be available for other applications.

Should tailscale on Android filter out addresses that VpnService.Builder.addDnsServer won't accept so that at least it can start?

Should tailscale (everywhere) filter out "self addresses"? That way exit nodes would not need to explicitly disable accepting of dns that would otherwise cause a "request loop" on the exit node. Although I can still imagine a horrible scenario where nodeA and nodeB are both listed as dns servers and end up using each other as the upstream resolver :-( Maybe handling that case is easier in documentation, where-as a single address is easier to get right automatically.

**Comment by bradfitz** [comment]
We've been filtering out 127.0.0.1 for quite some time now server-side, so closing.
