### ISSUE TITLE
Document how to detect/block tailscale, including port list

### ISSUE THREAD

**Issue by rothgar** [tailscale/tailscale#204]
Companies need to make sure their networks are secure and follow strict policies. It would be nice to have documentation at the least or firewall filters/IDS rules to detect if users have installed or are using tailscale in an enterprise network.

I think this would be an early step in gaining trust from companies.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171686810558210) by [Unito](https://www.unito.io/learn-more)

**Comment by matschges1cht** [comment]
IMO this is out of scope of Tailscales Documentation, since it's mostly related to Wireguard.  
Jason A. Donenfeld [wrote on the Wireguard Mailinglist](https://lists.zx2c4.com/pipermail/wireguard/2016-July/000185.html) regarding obfuscation.  

Also Wireguard uses `0400 0000` as a Type Indicator/Magic Number in the Data packets, so DPI should be trivial to set up.

**Comment by rothgar** [comment]
I opened the issue by request of @bradfitz 

Thank you for the information about the type number. It would still be useful to have Tailscale documentation when trying to get adoption from companies. From my experience you can't tell a company to RTFM and it should be trivial.

**Comment by danderson** [comment]
Oops, linked to bug in the wrong repo, which spuriously closed this.

**Comment by DentonGentry** [comment]
Port numbers and needed hostnames are documented in https://tailscale.com/kb/1082/firewall-ports/
