### ISSUE TITLE
Load-balanced services

### ISSUE THREAD

**Issue by aidansteele** [tailscale/tailscale#205]
Tailscale handles assigning permanent IP addresses to nodes very well. We can then use DNS to assign names, e.g. `john.device, `jane.device`, etc. However, I can't visualise how DNS for _services_ should be handled in an "ideal" Tailscale deployment.

In a transitional deployment, it's straight forward. Services can be registered with a classic load balancer and have a non-Tailscale private IP. DNS points to this IP and Tailscale routes to it using a subnet route with a Linux relay. This is suboptimal as it doesn't fully embrace the Tailscale vision of end-to-end encryption and authorisation.

In an ideal deployment, each instance of the service is registered to the Tailscale network. In a non-autoscaled, long-lived host scenario you could conceivably set up each host on the Tailscale network and add all of them to the DNS response. You'd use Tailscale's ACLs to allow traffic to each one of those hosts.

How would this work with containers that come and go on a regular basis? Or even autoscaling AWS EC2 instances that shouldn't require human intervention? Even if we assume that the app can somehow authenticate itself as a legitimate service X in Tailscale network Y, the ACL language would probably need to change as administrators would want to express "allow connections from user Z to service X".

--

I have no idea what the solution would look like, but I started a thread here as suggested on Hacker News. I hope I've adequately expressed the problem that I'd love to be solved.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171686863143848) by [Unito](https://www.unito.io/learn-more)

**Comment by DentonGentry** [comment]
I cannot access the Asana link, if there is more information there, but a couple things:

Tailscale doesn't really change the nature of load balancing. One can run a load balancer on a node which runs the Tailscale client, and have it divvy up incoming load to the 100.x.y.z address across N backend tasks. Those backends might also be running Tailscale, or could be on a local LAN accessed from the load balancer.

Containers which come and go have better support now than when this issue was filed. There is an [ephemeral node authkey](https://tailscale.com/kb/1111/ephemeral-nodes/) which will auto-remove nodes shortly after we lose contact with them. Tailscale works now with [Heroku](https://tailscale.com/kb/1107/heroku/) and [Google Cloud Run](https://tailscale.com/kb/1108/cloudrun/) and we expect to be able to work on AWS Lambda and other environments in the future.

Barring further updates, we'll expect to close this at the next bug scrub.

**Comment by DentonGentry** [comment]
I believe ephemeral node keys have addressed this.
