### ISSUE TITLE
dns forwarder: investigate remaining cases of DNS packet truncation

### ISSUE THREAD

**Issue by sailorfrag** [tailscale/tailscale#2067]
When we receive a DNS response that is larger than our maximum response size, there is usually an incomplete record at the end. That partial record should be removed so that the response is still well-formed (and the truncation flag should be set).

When #2066 is complete this should happen very infrequently (if ever).

**Comment by mayakacz** [comment]
Likely depends on https://github.com/tailscale/tailscale/issues/1123.

**Comment by twitchyliquid64** [comment]
Properly (ie: not through heuristics / assumptions about layout) tail-dropping the incomplete record seems to be quite difficult: `dnsmessage` (which we use for parsing) does not expose offsets or any such information in its API surface, and re-implementing question + record parsing + decompression just so we can remove a record or always find the edns OPT section seems like a waste if we aren't sure this problem still exists (this is necessary because the framing of a DNS packet requires parsing of earlier sections to determine the offset of later sections).

We could also try parsing + rebuilding every DNS request that we forward, but that seems like a big performance waste for something we aren't even sure is a problem + shouldnt happen in the regular case.

Given the above, I'm first going to make a change to count the number of truncated packets clients receive to determine if we need this.

**Comment by DentonGentry** [comment]
The metric counting truncated packets will appear in the 1.26 release.

**Comment by DentonGentry** [comment]
Over the last 60 days, truncated forwarded queries are typically 0.05% of all forwarded queries.

**Comment by DentonGentry** [comment]
Breaking it out by version:
- 1.26 had days of 0.2% truncated forwarded queries, albeit with substantial variation day to day
- 1.28 often goes a day with essentially no truncated forwarded queries, just occasional blips

In 1.26, iOS did not support DNS over TCP and always used UDP.
In 1.28, all platforms support DNS over TCP.

https://github.com/tailscale/tailscale/issues/2066 was fixed in 1.26 so we don't have data on how much of a difference it made. However my estimation is that remaining truncation in 1.26 was mostly iOS devices receiving a response too large for UDP, and that 1.28 allowed most such queries to switch to TCP.

I'm going to close this as resolved. I don't think we need to go to more effort to clean up the final fragment, the small amount remaining can be left to the client resolver library to handle by throwing the junk at the end away.

**Comment by sailorfrag** [comment]
Do we have a way to tell if some tailnets have a disproportionately large number of truncations? It seems plausible that a small number of users are having significant problems and most others never see it happening.

**Comment by DentonGentry** [comment]
Not from the metric. I think if we go back to the original logs and find the lines where dns_query_fwd_truncated is populated, we could find out which logIDs logged that line most frequently.

**Comment by mayakacz** [comment]
What happens if a DNS packet is truncated? It gets dropped?

To understand if this is blocking MagicDNS by default: if I create a new network, and install Tailscale nodes, I am presumably installing the latest version. Unless we have a reason to think that certain newer versions are also affected, I don't see how this blocks turning MagicDNS on by default for new tailnets.

**Comment by DentonGentry** [comment]
> What happens if a DNS packet is truncated? It gets dropped?

Truncation really only happens with DNS-over-UDP, when the answer is larger than the max response size (512 bytes by default, though EDNS can set it larger).

The client sees the truncated (TC) bit is set, drops the packet, and tries again using DNS-over-TCP and with a larger EDNS response size set. If it happens a lot for a sizable fraction of DNS requests, it leads to extra latency since every DNS lookup may have to incur two round trips.

After #2066 to set the EDNS size appropriately and after switching to netstack, there are very few truncated frames left. 0.05% of responses are truncated, if I did the math right.

This bug proposed investigating any remaining sources of truncation, and to consider cleaning up the DNS response to not leave a partially chopped off answer at the end. By cleaning up the response there would be a better chance that the client would choose to use answers which fit into the response it got: most DNS servers put the most important stuff like A and AAAA records at the front of the response, with increasingly less important answers following.

The downside of cleaning up the response packet is that DNS is an ancient protocol leftover from the primordial Internet with its own very special binary "compression" scheme (air quotes). If we unpack a response, drop the broken bits at the end, and repack the response, we can end up with differently packed contents from what the original DNS server sent. Maybe that would be ok, but the long tail of kindof broken DNS clients and servers benefit from not messing with the protocol when you don't have to.

**Comment by mayakacz** [comment]
> 0.05% of responses are truncated, if I did the math right.

I don't see this as blocking.

I would suggest documenting what cases we know fall in that 0.05%, however

> This bug proposed investigating any remaining sources of truncation

suggests we don't know what those are. If we learn, we can add later.

**Comment by nyghtowl** [comment]
@mihaip and I added tracking to identify the logtailIDs associated with dns_query_fwd_truncated in case this will help further assess this issue. This is found in the clientmetrics debug UI page.

Note the current expectation on this issue is that we will probably not make any changes due to its such a small truncation number.

**Comment by DentonGentry** [comment]
Looking at the client metrics, they seem to be a mishmash of sources and I don't see a pattern or correlation.

I don't expect to do more here.
