### ISSUE TITLE
Allow global username change/alias for MagicDNS

### ISSUE THREAD

**Issue by xSke** [tailscale/tailscale#2095]
I signed up on the Solo plan using github.com as an identity provider, and I've been assigned the domain `xske.github.beta.tailscale.net` based on that. Will it be possible to change the `xske.github` portion to something else in the future?

**Comment by DentonGentry** [comment]
We may eventually allow more control over the name, but not in the very near future. A couple notes:
- we also set a search domain, so `host1.xske.github.beta.tailscale.net` can typically be reached as just `host1` without having to see the whole thing.
- Some users run a small DNS server for their own domain with CNAMEs pointing `host1.example.com` to `host1.xske.github.beta.tailscale.net` https://tailscale.com/kb/1054/dns/
- once allocated, the Tailscale 100.x.y.z address will not change. You can also use A records instead of CNAMEs.
