### ISSUE TITLE
cmd/tailscale: add 'set' subcommand to change/edit specific 'up' options

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2096]
The customer is looking for the update option for advertise-routes, so that they do not have to mention all the routes again when they wanted to add or delete existing routes.

**Comment by bradfitz** [comment]
The new `tailscale up` design in 1.8 laid the foundation for much of what we'll need for `tailscale set`, which planned to include this.

I'll repurpose this bug about `tailscale set` in general.

**Comment by bradfitz** [comment]
Our old scratchpad notes from when designing the 1.8 CLI changes:

https://gist.github.com/bradfitz/bd7bd930b8c8b71076ca0a45f6b57bd0

(the 1.8 changes were that `tailscale up` by itself is just the opposite of `tailscale down`, but once you have any flags to `up`, nothing can change if it's not explicitly mentioned, otherwise it's an error. i.e. no surprises)

But as those notes hint at, the plan was to then add a `tailscale set` to modify settings. We hinted at modifying even existing values in those notes:

```
tailscale set advertise-tags+=tag:foo
```

But that syntax isn't great.

We weren't even sure about flags vs not flags there. (Is it like `sysctl` or does it match `tailscale up` with flags? or do we make the hyphens on `tailscale up` optional then?)

etc

/cc @danderson @rosszurowski

**Comment by DentonGentry** [comment]
Something which came up recently: similarly to the above about tags, being able to incrementally adjust advertised routes would be useful for some deployments.
```
tailscale set advertise-routes+=172.16.31.0/20
```

Otherwise, automation software has to keep track of all other routes added.

**Comment by DentonGentry** [comment]
Substantial overlap with https://github.com/tailscale/tailscale/issues/1436

**Comment by kpfleming** [comment]
This has been partially implemented, enough to allow me to control 'accept-routes' on the fly, so thanks for doing that work!

**Comment by bradfitz** [comment]
@kpfleming, thanks for the reminder. Tailscale 1.34 included `tailscale set`, so I think we can close this bug.

We can use #1436 for mutating advertised routes/tags with `tailscale set`.
