### ISSUE TITLE
iOS UI broken in 1.9.164

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#2122]
VPN starts and I can access Tailscale servers, but my app screen shows "Loading" and never prints out hostnames. Re-authentication from inside the app does work!

**Comment by bradfitz** [comment]
Same.

**Comment by shmsr** [comment]
I have a similar problem. Tailscale on iOS is stuck at the loading screen. On confirming with the admin console, I do not think it can even access Tailscale servers because it shows that it's offline.

Currently using: iOS 15 Beta 1 and latest Tailscale app
Note: But the problem was there with iOS 14.5 as well; I just reported late.

**Comment by DentonGentry** [comment]
Do we think this is resolved by https://github.com/tailscale/corp/pull/2027 ?

**Comment by crawshaw** [comment]
This was fixed by https://github.com/tailscale/corp/commit/9cba00d502c20f92df64804936aa1cbc01985e67. 

@shmsr this fix hasn’t been pushed to TestFlight beta yet, which you’ll need on iOS 15.
