### ISSUE TITLE
Use Synology DNS Server as Nameserver

### ISSUE THREAD

**Issue by yepecece** [tailscale/tailscale#2216]
Hi 

I have a DNS Server running on my Synology NAS which  would like to access via Tailscale by using the Nameservers settings (I guess).

I have tried implementing by enabling enable IP forwarding and following this exemple:
https://github.com/tailscale/tailscale-synology/issues/52#issuecomment-808840873 
However I am not managing to make it work.

Do I need to Connect to Tailscale as a relay node (not yet available on the Synology version)?
Does anyone can share a working tutorial?

Thanks

**Comment by DentonGentry** [comment]
If I'm understanding it correctly:
- you have a Synology device which has Tailscale installed, address 100.x.y.z
- you have a DNS server running on the Synology which you want all of your Tailscale devices to use.

If that is the goal, I think you can do this by adding the 100.x.y.z address of your Synology device to https://login.tailscale.com/admin/dns for your Tailnet. Please make sure that "Override local DNS" is selected for this, since you want to use the Synology instead of whatever DNS servers the ISP provided.

I'm going to close this, but if it doesn't work or there are still questions please feel free to reopen.
