### ISSUE TITLE
One-time authkey didn't expire when used on already-authorized node

### ISSUE THREAD

**Issue by tanuck** [tailscale/tailscale#2300]
Hi,

So I've left the title to this fairly vague just because I wasn't sure which part of this is a bug, or if there's no bug and it's all expected behaviour...

So in my network, I have 4 subnet relay nodes, and I wanted to add an ACL tag to each of them. The way I went about this was to perform the same `tailscale up ...` command as I had done previously, adding on the extra tag. I didn't use an `authkey` as I assumed once the node was authenticated, you could freely change its state. This didn't seem to work? The `up` command succeeded, but no new tags were added. So I then generated a one-off key and repeated the `tailscale up` command with said key, this succeeded and the new tag was added to the node. However, the one-off key *did not* revoke itself according to the admin panel.

I'm not sure if there's a bug in either part of this, but the behaviour sure seemed odd to me.

Cheers

**Comment by DentonGentry** [comment]
Changing ACL Tags is supposed to require re-authentication. It looks like we need to make it give a clear error, though.

For the second part, about the one-off key not revoking itself: does that mean you still see the key in https://login.tailscale.com/admin/settings/authkeys ? I think that part is normal, but the key should not be able to authorize a second node and have the second node appear in https://login.tailscale.com/admin/machines

**Comment by tanuck** [comment]
Yes, it still appeared in the list of authkeys at the link you describe. I didn't actually test whether it had become invalid. Given I've been using one-off keys regularly and gotten accustomed to them disappearing from that list as soon as they are used, I assumed it was still valid if present. I can test this though?

**Comment by tanuck** [comment]
Update: yes, I could use the key twice. First to update tags on a already authenticated node, then to authorize a new node.

**Comment by apenwarr** [comment]
I'm guessing the authkey didn't get revoked because it wasn't actually needed in order to change the node's settings (since the node was already authorized). This is confusing and not really desirable (if I use a one-time authkey and `tailscale up` succeeds, that authkey needs to go away, even if the authkey was not needed), so I've retitled the bug to reflect it.

We have a separate (internal) bug https://github.com/tailscale/corp/issues/1331 about the issue where switching ACL tags should require a new auth cycle. If that were fixed, it would have hidden the first problem.

As for your tag change not taking effect on the first call to `tailscale up`, I'm not sure why that would happen. If you can reproduce it (no need to use authkeys for this), please file a separate bug and run `tailscale bugreport` after reproducing (and paste its output into the bug). thanks!

**Comment by tanuck** [comment]
Just noticed this happen again. Added additional subnet routes to a running node, used a one time key but it wasn't revoked in the UI after use. Using version `1.14.3`.

**Comment by nyghtowl** [comment]
We've changed how tagging works and we expect this is no longer a problem. Need to investigate to confirm.

**Comment by DentonGentry** [comment]
This was resolved some time ago, probably in the work to make tags generally available:
https://tailscale.com/blog/acl-tags-ga/

I created two one-time use authkeys carrying two different tags. I used the first authkey on a system which was already authorized:
```
tailscale up --authkey=tskey-auth-abcdefCNTRL-... --force-reauth
```
and noted that the tag on the node changed and the key was properly revoked after its use.

I did it again with the other key, which set a different tag, and noted that the node's tag changed again and the second key was properly revoked after its use.
