### ISSUE TITLE
Unattended registry key will bind to the first person to log in

### ISSUE THREAD

**Issue by havedill** [tailscale/tailscale#2346]
Our use case for tailscale is that of a 1:1 relationship between an employee, and their remote workstation. 

Because they dont have remote access to their workstation without tailscale, we make sure we enforce unattended mode using the HKLM registry key. That way if the machine gets rebooted, the user does not lose access to the machine.

However, because this key is in HKLM, if any OTHER user (an admin, for example) logs into the machine after a reboot (and prior to the end user). Tailscale automatically binds the tailscale session to the admin user - even though they have never launched the GUI and never authenticated.

It would be nice if the unattended key could either be moved, or somehow only bind to the user that **has actually authenticated to tailscale**

**Comment by dblohm7** [comment]
The registry key is a red herring, as that mostly is about how unattended mode is presented in the GUI. It really is more about `tailscaled` not correctly saving the unattended user state when the node is authorized. That was fixed by https://github.com/tailscale/tailscale/pull/6255, so this should not be an issue going forward.
