### ISSUE TITLE
util/deephash: fundamentally kinda broken

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2348]
The whole `deephash` package is a little misguided as a general purpose data structure hasher.

Consider a type like:

```go
type S struct {
     V *Person
}

type Person struct {
      Name string
}
```

Is this true:

```go
Hash(S{new(Person)}) == Hash(S{new(Person)})
```

?

Currently, yes.

But that totally breaks down for sentinel pointers as used by netaddr.IP's `intern.Value` pointers:

```go
// z0, z4, and z6noz are sentinel IP.z values.                                                                                                                                            
// See the IP type's field docs.                                                                                                                                                          
var (
        z0    = (*intern.Value)(nil)
        z4    = new(intern.Value)
        z6noz = new(intern.Value)
)
```

We're saved today by most netaddr types having `AppendTo` methods, but e.g. https://pkg.go.dev/inet.af/netaddr#IPRange doesn't have one. And it does contain an IP value with such sentinel pointers.

So it's currently possible to trick `deephash` into getting the same hash with a v6-mapped-vs-v4 IPRanges.

And in general there's no way for deephash to know what the right thing to do is.

That's a nice thing about the control server's jsonSummer: it's just the SHA-256 of the JSON output, so if JSON works, so does the hashing.

Maybe deephash should require explicit type registration or magic methods (like AppendTo or `DeepHash() [sha256.Size]byte`) on all involved types.

/cc @josharian @crawshaw @sailorfrag

**Comment by crawshaw** [comment]
In Programming Languages equality does not have a right answer.

I have been thinking of deephash as roughly equivalent to cmd/cloner, in that it treats data structures as pointerless. Which means it breaks those sentinel pointers. I don't think there is any way to define `[]byte{'a'} == []byte{'a'}` and support those sentinel values as written.

This notion isn't new to go, as we have `reflect.DeepEqual` which is also an attempt at pointerless equality. So I think it's a sound concept. Presumably netaddr.IPRange is broken under DeepEqual too? If so, can we put an integer into those intern.Values?

How to avoid deephash being used where it shouldn't... I don't know. I think calling it "deep" helps, because it draws the user's mind to reflect.DeepEqual, and hopefully they can see the similar semantics.

**Comment by crawshaw** [comment]
We could also make this clearer by defining a package `deep`, and defining `deep.Equal`, a synonym for reflect.DeepEqual, `deep.Hash`, and `deep.Clone` (a reflect-driven version of cmd/cloner, if we had a use for it).

**Comment by dsnet** [comment]
> Maybe deephash should require explicit type registration or magic methods (like AppendTo or DeepHash() [sha256.Size]byte) on all involved types.

At the very least, I find `deephash`'s introspection of unexported fields to be concerning. 

> We could also make this clearer by defining a package deep, and defining deep.Equal, a synonym for reflect.DeepEqual, deep.Hash, and deep.Clone (a reflect-driven version of cmd/cloner, if we had a use for it).

If `deep.Equal` and `deep.Hash` lived together, I would expect `deep.Equal(x, y) == (deep.Hash(x) == deep.Hash(y))`. However, that would not be case if `deep.Equal` were simply an alias to `reflect.DeepEqual` since it already differs in behavior from `deephash.Hash` as it stands today (which has special handling for the `AppendTo` method).

> That's a nice thing about the control server's jsonSummer: it's just the SHA-256 of the JSON output, so if JSON works, so does the hashing.

😬 There's no guarantee that `json` output is deterministic. At the very least, we should canonicalize it per RFC 8785.

**Comment by bradfitz** [comment]
> 😬 There's no guarantee that json output is deterministic. At the very least, we should canonicalize it per RFC 8785.

But remember the "within the life of a process" constraint. Sure it's not? It sorts maps, etc.

**Comment by dsnet** [comment]
Barring any usages of `MarshalJSON` or `MarshalText` methods, the standard library is deterministic (in practice, but not promised). I've seen non-determinism leak into a `MarshalJSON` implementation through non-deterministic map iteration, but you see all sorts of weird stuff at google3-scale.

**Comment by DentonGentry** [comment]
Quite a few PRs have gone into deephash over the last two years: https://github.com/tailscale/tailscale/pulls?q=is%3Apr+deephash+is%3Aclosed

Is there more to do here?

**Comment by bradfitz** [comment]
I think we've got it reasonably all implemented and defined now.
