### ISSUE TITLE
Windows: add an "about..." menu item

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#235]
Requested in #202, some way to see the version info within the app.

Also mentioned the tailscale-ipn.exe version seems to be hardcoded at 0.0.0.1. Unclear where that's coming from, perhaps something in the NSIS logic?

cc @apenwarr for Windows wisdom.

**Comment by apenwarr** [comment]
0.0.0.1 is just a hardcoded version number in the "file properties" at compile time. I can't remember what happened last time I tried to populate it, but it didn't go as well as I had hoped because that variable is considerably crazier and more filled with backward compatibility than I had hoped.

There is a version number populated in the Uninstall Programs control panel. But yes, there should be an about box.

**Comment by artis3n** [comment]
+1 for an about box. I saw the apt package update for Tailscale on my other machine and have no way of knowing whether my Windows version is up-to-date (except by checking Uninstall Apps as mentioned above, didn't think of that).

**Comment by bradfitz** [comment]
This is now done and will be in a future Windows release.
