### ISSUE TITLE
iOS: running Mullvad can make Tailscale be unable to reauthenticate

### ISSUE THREAD

**Issue by shorthandguy** [tailscale/tailscale#2410]
When using the latest version (1.10.1) of the iOS app on an iPhone (iOS 14) and iPad (iOS 13.6), it's been possible to get the app in a state where it's appeared like the user has needed to reauthenticate in order to continue using it, but it's not been possible to 'fix' this issue within the app. 

This has come about primarily from toggling the connection on and using it, then toggling it off again, switching to a different VPN service and at a later point returning to the app.

The only option available from the dropdown menu has been 'Reauthenticate', with all other options greyed out. Attempting to click on this option results in nothing occurring. Likewise, returning to the home screen and then back to the app does not solve the problem. Attempted to also use the toggle to see if it would have any impact, but this was not the case.

The VPN network being used is configured to use an exit node, but this seems like that would not be of great relevance with this issue. 

The only thing that appeared to 'fix' the issue was rebooting the device and restarting the app, at which point the app seemed to revert to its original logged in state, and it was possible to toggle the connections on and off again.

**Comment by DentonGentry** [comment]
I suspect this is another symptom of https://github.com/tailscale/tailscale/issues/1840

@shorthandguy the next time you see this, could you report (to the minute if possible) the time in your timezone? We'd need a pretty specific timestamp to look at telemetry.

**Comment by sit** [comment]
I've seen this and been able to fix this by going into the iOS VPN settings, activating the Tailscale profile explicitly and turning on the VPN there.

**Comment by baldfox** [comment]
I can also verify that I'm having the same issue. Makes no difference if I toggle the tailscale on or off in the app. It just says reauthenticate but nothing happens when you click it. Will try the solution above, but definitely a glitch.

**Comment by ShredderWalnut** [comment]
I believe I'm experiencing the same symptoms. Besides switching VPN profiles in Settings, another fix is force quitting Tailscale in the App Switcher and relaunching it again.

**Comment by DentonGentry** [comment]
The next time anyone sees this, please include a bugreport generated from the app menu. That will give us an idea of where within the telemetry to look.

**Comment by ericswpark** [comment]
@DentonGentry here are the exact repro steps I used:

1. Launch and enable Tailscale
2. Launch and enable Mullvad VPN
3. Go to settings page and verify that the VPN "provider" has switched from Tailscale to Mullvad
4. Go back to Tailscale app and see the "Needs Authentication" message

This repro procedure works all of the time.

Unfortunately, trying to submit a bug report results in an error showing up. The only way to get it to submit a bug report is to force-close (remove from app switcher) and re-open the app. But by then the bug is gone and the VPN auto-starts. I've captured a bug report right after, but I'm not sure how useful it would be.

BUG-02c01548c20fb919024c07bf63815a3fe829b86b7e6d49c5799c11b1d15ebcfc-20221030134059Z-c7f3d1ced65e2ef7

**Comment by DentonGentry** [comment]
The bugreport adds a marker in telemetry so we know where to look. Unfortunately the telemetry from the time where the problem was happened doesn't appear to have ever uploaded, and was lost when the app had to be force-closed. The first telemetry we get is after it has started back up again, and it all looks normal at that point.

That it happens with Mullvad is a useful repro case. We do want to support better co-existence with Mullvad (https://github.com/tailscale/tailscale/issues/2880), but right now as with all other VPNs Tailscale can end up fighting over routing table, firewall rules, and DNS settings.

**Comment by agottardo** [comment]
Closing because this refers to an outdated version of the app, and we now even have a Mullvad integration.
