### ISSUE TITLE
--advertise-routes option should warn you if control doesn't authorize those routes immediately

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#2426]
Steps:
- `tailscale up --advertise-routes=<something>`
- Returns success
- Try to ping those routes from another node
- Doesn't work because you haven't permitted the routes in the admin panel.

Since the control server knows whether those routes have been permitted (and could even check if there are any users allowed to reach them in the ACL config?), I think we could actually have `tailscale up` report back and print a warning if the routes aren't approved yet.

Filed https://github.com/tailscale/tailscale/issues/2425 about auto-approving subnets, which is another angle for the same issue.

**Comment by apenwarr** [comment]
Customer feedback that led to this issue:

> The part that snagged me is acl/perms check - must go to admin console to make TS allow this routing (that was clear in the docs tho).  The other Linux-isms (IP forwarding on on the relay node?) were known and not a problem (ie Tailscale for Linux network admins).

**Comment by DentonGentry** [comment]
Related, we added a health check for a similar issue:
```
Some peers are advertising routes but --accept-routes is false
```

**Comment by DentonGentry** [comment]
Since this bug was filed, we've added a series of health checks in `tailscale status`. At this point we're more likely to surface unapproved routes as a health report rather than pausing `tailscale up --advertise-routes=...` to wait for confirmation.

https://github.com/tailscale/tailscale/issues/5724 tracks adding a health check for non-approved routes.

At this point I'm going to close this and expect to handle it via https://github.com/tailscale/tailscale/issues/5724 instead.

----

Also since this bug was filed, an autoApprover feature has been added: https://tailscale.com/blog/auto-approvers/
