### ISSUE TITLE
Reenable UPnP port mapping on iOS

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2495]
We're going to ship Tailscale 1.12 with UPnP port mapping enabled on all platforms except iOS due to binary size reasons (which currently impacts our available memory, for perhaps linker reasons)

This is a tracking bug to reenable UPnP on iOS either through lighter code or if we fix the Go linker to decouple binary size from memory size.

**Comment by DentonGentry** [comment]
We have just switched to Go 1.18, which contains all of the linker changes to reduce the size of the binary.

Additionally, Apple has substantially pushed the fleet of iOS devices to iOS 15 which increases the amount of memory available to a Network Extension from 15 Megs to 50 Megs.

**Comment by DentonGentry** [comment]
The current plan is to bump the minimum iOS version to 15 for the 1.26 release. Almost the entire fleet of iOS devices is on 15 already, and remaining devices which cannot update will be able to use 1.24 as long as they need to.

Once that is done, we can depend on having 50 Megs of memory available instead of 15. We can let iOS use portmap then.
