### ISSUE TITLE
provide a way to export machines to CSV

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2537]
The customer asks to add the SORT option to the UI to find out the node has not connected for the longest time and take the necessary option. Also, if there is a way to export the machines to CSV would be helpful too.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3f4lt)

**Comment by bradfitz** [comment]
I think I'd rather this be a CLI command, like `tailscale admin users list --csv` or `tailscale admin users list --sort=connected`.

/cc @rosszurowski

**Comment by rosszurowski** [comment]
We've avoided adding sorting to the admin panel's machines table because (a) it gets tricky to implement and support and (b) it's usually a proxy for what people actually want, which is finding a set of devices. For example…

- "sort by Tailscale version" is usually for finding which devices have an older version
- "sort by device name" is usually for finding a particular device
- "sort by last seen" is usually a proxy for which devices haven't been used in a while

Sorting also doesn't work well with information that isn't in its own column, like "devices that expose subnets" or "devices that have expired keys."

All of these cases are better served by searching and search filters, which we have implemented, but not documented. Here's a little summary I've shared with customers before. You can use these by typing these into the search bar of the admin panel's machines page:

- `is:internal` or `is:external` for querying devices in your network and shared devices you have accepted
- `is:shared` for querying devices from your network shared with other
- `is:expired` for devices whose keys have expired and need reauth
- `is:expiry-disabled` for devices who never need reauth
- `is:unauthorized` for devices needing an admin approval
- `is:exit-node` for devices exposing a default route (Tailscale v1.6 and up)
- `has:subnets` for devices exposing subnets
- `has:update-available`
- `owner:<query>` to find devices owned by a user
- `version:<query>` to find devices running a specific Tailscale version
- `os:<query>` to find devices by operating system
- `tag:<query>` to find devices advertising an ACL tag

So, let's treat "sort machines" in the admin panel as  a "won't fix" item for now.

As for exporting to CSV, that's a fair feature request. We can add that to the admin panel and center this issue around that. 

Adding it to the CLI is also a possibility, but the CLI isn't currently an administration tool — if you have ACLs configured, your CLI won't have a complete picture of the network, which could be confusing. Let's just leave it to the admin panel for now.

**Comment by DentonGentry** [comment]
Adding an encoding to the API would be another way to do this.

**Comment by DentonGentry** [comment]
This was implemented in December 2022:
- https://tailscale.com/changelog/#2022-12-07-service
- https://tailscale.com/kb/1228/export-device-list/
- https://tailscale.com/kb/1229/export-user-list/
