### ISSUE TITLE
symlink for /Applications/Tailscale.app/Contents/MacOS/Tailscale ping <status>  on macOS.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2553]
At the moment, I need to manually run commands like ,

'/Applications/Tailscale.app/Contents/MacOS/Tailscale ping <status>'

It would be convenient if the installer would for example symlink the Tailscale binary in /usr/local/bin, or setup a zsh alias. This way scripts and commands would work in an equal way on Mac and linux…

Workaround:

`alias tailscale=/Applications/Tailscale.app/Contents/MacOS/Tailscale`

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3femp)

**Comment by daankets** [comment]
It's especially needed within organisations that do development ;-)

**Comment by DentonGentry** [comment]
My hesitation is that this is not how I'd really want to MacOS app to be administered, and therefore not something I'd want to encourage by installing a symlink for it. When a feature is ready for use on MacOS, we'd want it to appear in the menubar settings and, if appropriate, as a variable which can be set in a Profile via MDM.

People are free to make aliases in their shell, if they really want to operate the Mac client in this way.

**Comment by bradfitz** [comment]
Well, the bigger issue is that the Mac App Store version doesn't let us do this at all. 

But we can do it for the standalone Mac version when that's ready. It'd be consistent with the other platforms.

**Comment by daankets** [comment]
@DentonGentry I don't disagree with your opinion about how you would like the app to be administered by _most_ end users. But there will always be different usages. For example, we have teams of developers working on macOs devices. And we would like to be able to diagnose their connections (via ssh admin login for example) in case of issues. Being able to run `tailscale status` would allow it, and it would be consistent with the installations on linux.

**Comment by daankets** [comment]
Maybe a menu item that would create a zsh alias would be sufficient. That's how the JetBrains team takes care of it with their dev tools.

**Comment by bradfitz** [comment]
The App Store sandbox doesn't permit that.

**Comment by daankets** [comment]
@bradfitz for the standalone version would suffice I think. We are using that one.

**Comment by bradfitz** [comment]
What's your Tailscale IP?

**Comment by creachadair** [comment]
I found this issue because I was attempting to symlink `/Applications/Tailscale.app/Contents/MacOS/Tailscale` from a location in my `$PATH`, and the resulting command execution (e.g., `tailscale status`) appears to simply hang.

Having found this issue, I will note that the alias does work for me, but I feel like something is still wrong. Is the Tailscale binary doing some path-related shenanigans on `argv[0]` that prevent this from working, or is this maybe some macOS tomfoolery do you think? I don't even get a PID when I run it that way. 

I don't care if Tailscale installs a link for me or anything; I'm happy to maintain that myself. But I would (mildly) prefer to use a symlink rather than an alias unless there's a good reason that can't be done.

**Comment by bradfitz** [comment]
(I deleted a distracting side discussion without a reply)

**Comment by bradfitz** [comment]
@creachadair, the macOS sandbox is a little weird. For the actual logic our binary uses to decide whether to act like the CLI, see:

https://github.com/tailscale/tailscale/blob/v1.12.3/cmd/tailscale/cli/cli.go#L36

For debugging, does it work if you set TAILSCALE_BE_CLI=1 before running your symlink?

**Comment by bradfitz** [comment]
Answering my own question, no, it does not work. It still hangs.

I think this is the macOS sandbox doing something.

**Comment by bradfitz** [comment]
If you don't want a shell alias, you can also put a little wrapper in your $PATH.

Personally I use this:

```
$ cat bin/tailscale.app 
#!/bin/sh
exec $(ps -xo comm | grep MacOS/Tailscale$) "$@"
```

That weirdness is because I alternate between running the App Store version and the binary from Xcode where the path is like:

```
/Users/bradfitz/Library/Developer/Xcode/DerivedData/IPN-xxyzxyzyxx/Build/Products/Debug/Tailscale.app/Contents/MacOS/Tailscale
```

**Comment by creachadair** [comment]
The wrapper script is a good fix, I should have thought of that, thanks.

I think you must be right about it being sandbox-related; I made a little Go program that runs your `ActLikeCLI`, and it reports `true` when run free from the shell. I imagine the answer could be different if it's running inside the sandbox, though.

I tried (briefly) to gin up a `sandbox-exec` profile to see if I could catch it being weird, but I couldn't get it working in the time I allocated myself to fool with it. (Specifically: I was able to get it to run, but it didn't do anything different)

**Comment by errordeveloper** [comment]
My use-case is mostly to be able to run `tailscale status`, `tailscale ip`, and perhaps `tailscale ping`.

I think what would be helpful is a some kind of initial setup step where it's suggested that CLI users can use an alias.

When I installed the CLI with Homebrew, it partially worked, but some commands just bailed due to version drift. In my case the difference was just one patch release...
So, perhaps, making client/server version check tolerate patch release differences would be a reasonable way of resolving this issue? Perhaps it'd would just increasing the chance that CLI installed by Homebrew just works most of the time, unless someone was very unlucky to slip in between minors version being updated in Homebrew, but on in the App Store...

**Comment by DentonGentry** [comment]
I think the wrapper script is the way to go: https://github.com/tailscale/tailscale/issues/2553#issuecomment-912824816 as the App Store sandbox requirement for Network Extensions limits other options.
