### ISSUE TITLE
Auto-sync of google workspace security groups into tailscale ACL config

### ISSUE THREAD

**Issue by daankets** [tailscale/tailscale#2560]
It would be really nice if security groups defined in google workspace would be reusable in the tailscale ACLs. This way, security groups that are already well-maintained via an auditable management dashboard don't need to be duplicated into the tailscale configuration.

**Comment by DentonGentry** [comment]
I'm going to mark this as a duplicate of https://github.com/tailscale/tailscale/issues/979 to implement SCIM for group sync from Okta and Azure, because we have several engineers working on that right now and Google auth is on the list of items to address.

Google is somewhat harder because they stopped accepting SCIM integrations in 2019. There appear to be other APIs from Google that we can use, but using gRPC and Google's usual unique tech stack. I'd expect Azure and Okta to be working first, and go back to address Google after.

Dup of https://github.com/tailscale/tailscale/issues/979
