### ISSUE TITLE
Change owner of Device from Admin Console

### ISSUE THREAD

**Issue by pquerna** [tailscale/tailscale#2569]
I enrolled a couple servers, and want to change the "owner" of the device via the Tailscale console.  It doesn't appear to be possible to do this without de/re registering

**Comment by DentonGentry** [comment]
For most devices, we're likely to ask that the device be re-registered in order to ensure it gets a new NodeID.

For server devices in particular, where access really shouldn't be based on the user who initially registered them, we're likely to handle this using Tags https://tailscale.com/kb/1018/acls/#acl-tags and have the server identity be controlled by the Tag not the User.

**Comment by pquerna** [comment]
Not my specific use case right now, but if the person leaves the company who registered some servers, even with the Tags you are describing, we would have to rebuild them?  That doesn't seem very fun at all.

**Comment by DentonGentry** [comment]
Right now:
The servers are owned by a user, if that user leaves the servers would be removed.
A number of sites use a role account, like servers@example.com, to hold infrastructure nodes like servers and subnet routers.

What I think we're likely to provide:
Devices with Tags would be owned by the tag and no affected when the person who originally set them up leaves the company.

**Comment by DentonGentry** [comment]
Making servers be owned by the Tag is tracked in https://github.com/tailscale/tailscale/issues/2555
Dup of https://github.com/tailscale/tailscale/issues/2555
