### ISSUE TITLE
add native windows/arm64 support

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2606]
Now that Go 1.17 supports windows/arm64, this is a tracking bug for us to build windows/arm64 native binaries for e.g. Microsoft Surface tablets, rather than the 32-bit x86 binaries we use currently on such platforms.

/cc @sailorfrag @apenwarr

**Comment by Erisa** [comment]
From my experience with building my own unofficial builds of tailscale for `windows/arm64` during 1.17 RC, the main issue you'lll run into is https://github.com/go-ole/go-ole/issues/216 (The title has a spelling error, they mean arm64)
Which is partially fixed by https://github.com/go-ole/go-ole/pull/217, and fully fixed with an additional `variant_date_arm64.go` as I noted in my comment on that issue.

After the problems with `go-ole` were resolved locally, I was able to successfully build the publicly available source of Tailscale for `windows/arm64` without issue.

**Comment by DentonGentry** [comment]
We're expecting to release Tailscale 1.14 next week, and at this point though we'll be using Go 1.17 we won't be in a position to produce native ARM64 binaries in time for the release. We'll try again in another month, and we'll watch for go-ole & GetVariantDate (thank you!)

**Comment by Erisa** [comment]
To follow up to my comments, the errors in go-ole are now fixed as of https://github.com/go-ole/go-ole/commit/8b1f7f90f6b1728609c9694f2cff140d34fd91f8, just not tagged to a version yet.

**Comment by bradfitz** [comment]
@Erisa, thanks for the update!

/cc @dblohm7

**Comment by DentonGentry** [comment]
The MSI installer provides native ARM64 support.
https://pkgs.tailscale.com/stable/#windows

**Comment by bradfitz** [comment]
No it doesn't. That's just running 32-bit x86 on ARM64.

We have work remaining to do windows/arm64.

**Comment by kobykahane** [comment]
Is anything currently blocking this?

**Comment by DentonGentry** [comment]
I promise that we will update the bug when work begins in earnest.

**Comment by bradfitz** [comment]
Last we looked into this, the hard part was the GUI. But the GUI's the least important part for performance.

I think we should do this in two stages:

* first make the `tailscaled.exe` service be native `windows/arm64`. That'll help with CPU/performance.
* later care about the low-CPU GUI part.

/cc @dblohm7 @sailorfrag @DentonGentry

**Comment by dblohm7** [comment]
Wasn't the main issue some cgo stuff?

**Comment by bradfitz** [comment]
And there's no cgo in tailscaled.

**Comment by bradfitz** [comment]
`tailscaled` compiles without issue at least:

```
$ GOOS=windows GOARCH=arm64 go install ./cmd/tailscaled/

$ ls -l ~/go/bin/windows_arm64/tailscaled.exe 
-rwxr-xr-x 1 bradfitz bradfitz 19343360 Aug  2 19:27 /home/bradfitz/go/bin/windows_arm64/tailscaled.exe

$ file ~/go/bin/windows_arm64/tailscaled.exe 
/home/bradfitz/go/bin/windows_arm64/tailscaled.exe: PE32+ executable (console) Aarch64 (stripped to external PDB), for MS Windows
```

**Comment by Erisa** [comment]
The `tailscale` and `tailscaled` binaries were compiling without issues for me as far back as Sept 2021 after that last fix to go-ole was merged.
There was a time where I would build my own ARM64 copies with the right version and drop them in as replacements in Tailscale's folder, which worked fine at the time, but I don't use a Windows/ARM64 device anymore so I haven't done that for a while.

**Comment by sailorfrag** [comment]
Shortly after unstable 1.29.164 was built, I changed the build process to include ARM64 binaries in the NSIS installer (MSI will come later). The service (`tailscaled.exe`) and command line tool (`tailscale.exe`) are ARM64; the GUI (`tailscale-ipn.exe`) is still x86 due to some incompatibility in the Windows GUI toolkit we're using. Fortunately, the GUI is not performance sensitive so this shouldn't be much of a problem. I'm not sure in which exact unstable package version this first landed, but I just checked the 1.29.182 installer and it installed as ARM64.

Barring the discovery of problems, this should be in the upcoming 1.30 stable release.

For various technical reasons, we do not have a toolchain to build Windows ARM64 with cgo enabled. This means that a particular obscure Windows certificate based feature is unsupported (this is only currently in use for one customer, who has been notified). I don't believe any other Windows features require cgo.

**Comment by DentonGentry** [comment]
Tailscale 1.30 added a native ARM64 binary as an MSI installer.

**Comment by ranok** [comment]
https://tailscale.com/kb/1189/install-windows-msi/ should be updated to reflect the ARM64 MSI

**Comment by dstaley** [comment]
Just to confirm, `tailscale-ipn.exe` should still be an x86 executable, even after running `tailscale-ipn-setup-1.32.2.exe` on an ARM64 device, correct?

![image](https://user-images.githubusercontent.com/88163/200212661-607939bf-2685-4146-af05-349ae97879c3.png)

**Comment by bradfitz** [comment]
Yes. That's expected. But that's just the UI that uses approximately 0% CPU compared to tailscaled.exe, so the reward for converting it is much lower. (We would've done it if it were trivial, but it ended up not being trivial due to some dependencies that were broken on arm)
