### ISSUE TITLE
P2P Mesh access?

### ISSUE THREAD

**Issue by vysecurity** [tailscale/tailscale#2632]
Hi there,

I'm not sure i'm understanding the concept of Mesh VPN correctly.

I have a servers A and B behind a NAT, and also C on the internet.

When A and B cannot connect with a device D directly, it uses the slow SFO DERP relay (latency). Why does it not automatically assume C is a relay and use it to relay with low latency instead?

Thanks!

**Comment by vysecurity** [comment]
Set up a DERP server on an existing internet facing exit node.

Getting: 
<img width="264" alt="image" src="https://user-images.githubusercontent.com/3596242/128980962-2895efda-c4f2-4fba-8dca-c5799aee7bc0.png">


In tailscale netcheck from the server that is being a NAT.

**Comment by vysecurity** [comment]
![image](https://user-images.githubusercontent.com/3596242/128982604-bb140f30-b79b-4d3a-9c33-f2a98a8e755f.png)

Looks like the DERP server is up, but no clients are able to 'ping' it.

**Comment by vysecurity** [comment]
Seems to have started to work all of a sudden.

**Comment by DentonGentry** [comment]
> Why does it not automatically assume C is a relay and use it to relay with low latency instead?

Maybe someday, but for now the mesh feature means that any two nodes will try to make direct connections not always go through a VPN concentrator. The topology between nodes is a mesh, but a single hop mesh.

The DERPers as relays allow a number of simplifying assumptions:
- they won't move about, their connectivity and available bandwidth and latency characteristics change infrequently
- their IP addresses change so infrequently that they can be [distributed as configuration](https://login.tailscale.com/derpmap/default) not as a dynamic part of the netmap
- they are considered as part of the firmament, not a node in the topology, because the DERPers cannot decrypt the content of messages and cannot be an endpoint. They don't show up in the `tailscale status` list.

**Comment by vysecurity** [comment]
Got it, thanks Denton!

**Comment by uniartisan** [comment]
Hello,I'm curious if anyone else cares about this issue.
According to my understanding, the restriction can only forward encrypted traffic through the drep server, which is undoubtedly a centralized measure and has high requirements on the bandwidth of drep.

I was wondering if it is possible to provide a mesh network similar to wireless routing, where each tailscale node of its own can participate in forwarding, even if my a device and b device cannot get through p2p, but my a device and c device can p2p , device b and device c can be p2p, then my a and b can be transferred through device c

**Comment by bradfitz** [comment]
Old, closed issues aren't a place to start new discussions.
