### ISSUE TITLE
iOS: Unexpectedly high storage usage

### ISSUE THREAD

**Issue by fowl2** [tailscale/tailscale#2639]
I've got Tailscale 1.12.3 on an iPhone 12 running iOS 14.7.1

Settings -> General -> iPhone Storage -> Tailscale shows 671MB of "Documents & Data" (and 18.MB of app).

I think I used Taildrop at  some point, so perhaps a transfer wasn't cleaned up properly?

**Comment by DentonGentry** [comment]
The files are not automatically deleted. When a file is received clicking on the notification will open the Files app, but the files remain until deliberately deleted.

**Comment by fowl2** [comment]
Where in the Files app? There isn't a "Tailscale" under "Locations" or "On my iPhones"

**Comment by DentonGentry** [comment]
It should be in On My iPhone.

<img width="320" alt="2023-02-12%2010 41 04" src="https://user-images.githubusercontent.com/1140756/218330356-404a344b-a3ac-494e-8da1-c6a0e61b65e8.png">

**Comment by DentonGentry** [comment]
I think this is related to not finding the files to delete, please reopen if there is something more.

**Comment by mrnossiom** [comment]
I recently used Taildrop to transfer many 1GB files to my phone. When I click the notification to accept the files, they do appear in the Files app in "On My Phone > Tailscale".

The issue is that when the files are deleted in the Files app, Tailscale storage usage stays the same. I had to reinstall the app to clear 30GB of storage.

I wonder if the iOS app has an internal cache and if there is a way to clear it.
