### ISSUE TITLE
Self define ranges not to be tunneled through Tailscale

### ISSUE THREAD

**Issue by vysecurity** [tailscale/tailscale#2657]
Currently, Tailscale grabs the local LAN and doesn't tunnel it through Tailscale if you set it.

However, what if you don't want other internal network segments, which may not just be your LAN, to not be tunneled through tailscale?

It'll be a good idea to have some configuration item to set a list of subnets not to be tunneled aside from the default LAN.

**Comment by DentonGentry** [comment]
> Currently, Tailscale grabs the local LAN and doesn't tunnel it through Tailscale if you set it.

I don't entirely understand what this means: when using an exit node and "Allow local network access" is set?

**Comment by bradfitz** [comment]
And is this hypothetical or is there a concrete use case? If so, what? And couldn't you just install an OS route?

We avoid extra configuration knobs as much as possible.

**Comment by vysecurity** [comment]
Basically let's say in a large company you have site A, and site B.

Site A has 192.168.0.0/24, 192.168.1.0/24. You're on 192.168.1.0/24

Site B has 192.168.2.0/24, 192.168.3.0/24. The other host is on 192.168.3.0/24

If Site A tries to tunel through an exit node, 192.168.0.0/24 won't be recognised as a local route. If you define using the host and advertise the route, then suddenly Site B can access site A, which you may not want.

With Tailscale in its current configuration, Site A's user cannot access 192.168.0.0/24 for services if the exit node is set to any tailscale device.

**Comment by DentonGentry** [comment]
So site A has a routerA with LAN segments on 192.168.0.0/24 and 192.168.1.0/24, and is the default route for devices at site A. userA on 192.168.1.0/24 at siteA will, if no exit node is active, send 192.168.0.0/24 packets to routerA to be forwarded.

Something, somewhere will have set `tailscale up --advertise-routes=` to offer routes to 192.168.0.0/24, 192.168.1.0/24, 192.168.2.0/24, and 192.168.3.0/24. Maybe routerA and routerB at the two sites.

If userA has an exit node active, they'll use the Tailscale route to send to 192.168.0.0/24. It won't bounce through the exit node, userA will send the traffic directly to whatever node is offering a route to 192.168.0.0/24.

So the feature request is to have a configuration setting to specify 192.168.0.0/24 as a local subnet which should be sent on the LAN to routerA, not sent to the Tailscale route (which might also be routerA).

To be honest: I don't expect to implement this as a configuration setting. It adds complexity for what I think would be a small benefit in a scenario which doesn't seem likely in practice.

We may eventually implement actual routing protocols in the subnet router, to better integrate with corporate environments with complex topologies. I'd expect to implement this kind of feature using iBGP/OSPF/etc integration rather than configuration.

Thank you for the suggestion, but I'm going to close this for now. Feel free to reopen if you have a concrete use-case in the near term. For the longer term, I'd expect to handle this kind of topology in other ways.
