### ISSUE TITLE
Would it be possible for tailscale to not show up in VPN status bar?

### ISSUE THREAD

**Issue by step21** [tailscale/tailscale#2800]
I use the vpn statusbar applet for various specific VPNs, which I only connect to occasionally. Contrary to that, I would like tailscale to be always on, but also be unobtrusive in the background.
As an example where this works, zerotier also connects on startup, but doesn't clutter up my vpn connection status bar. Could this maybe be an optional feature? (I do not care what it uses in the background, but I want less visual clutter, especially as it has its own status bar icon already)

**Comment by DentonGentry** [comment]
Could I ask what OS this would be for, and what the VPN connection status bar is?
It is iOS and the icon at the top of the screen?

**Comment by step21** [comment]
macOS, maybe status bar is the wrong word. Status bar icon?

**Comment by DentonGentry** [comment]
It is possible to run on MacOS without the GUI: https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS

**Comment by step21** [comment]
> It is possible to run on MacOS without the GUI: https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS

Awesome, thanks. Somehow I missed this. If the vpn menubar thing could be an optional thing that would be great too, but likely this would only be possible outside the macapp store as part of the yet unreleased non-macapp store gui, if I am not mistaken.

**Comment by DentonGentry** [comment]
I'm going to close this; as you say, the App Store requires that *something* be visible when a VPN is in use. Though we might investigate alternatives like leaving an app running in the dock, I think the real need in this issue is better met using the CLI version to be as unobtrusive as possible.

**Comment by step21** [comment]
Well, the tailscale status bar icon is there anyway. But fine with closing it.

**Comment by DentonGentry** [comment]
I think that means they are both running. You should be able to quit the one in the UI, and rely on the CLI tailscaled alone.

**Comment by step21** [comment]
To clarify - I mean if I connect using the GUI - then the tailscale status bar icon and the vpn status bar icon will be 'visible', but I am not an expert on app store guidelines and as you say, running it by cli is fine for my purposes.

**Comment by 0bmxa** [comment]
If I understand @step21 correctly, the question is not about the Tailscale icon, but about the system's VPN menu bar item, so this thing here:
![image](https://user-images.githubusercontent.com/15385891/132900482-3cd8bfbe-6843-404f-b5f0-88d97746dd35.png)


This item shows all VPNs that are making use of the system's own VPN modules (e.g. configured via a profile), or have been installed as [Network Extension](https://developer.apple.com/documentation/networkextension). Tailscale uses the Network Extension approach, because that's (afaik) the only way to get a VPN into the AppStore.

The visibility of this menu bar item can be turned off by the user in `System Preferences.app` > `Network` > `Tailscale Tunnel` (or any other VPN) > `Show VPN status in menu bar`, however this will hide the entire menu bar item, so all other VPNs in that menu will also not be visible anymore.

**Comment by step21** [comment]
> If I understand @step21 correctly, the question is not about the Tailscale icon, but about the system's VPN menu bar item, so this thing here:

That's correct. But as specified above (quoted below), it is possible to run the non-Gui version on macos, and that satisfies this need.

> It is possible to run on MacOS without the GUI: https://github.com/tailscale/tailscale/wiki/Tailscaled-on-macOS

But thanks for also reminding me that it is in principle possible to hide this icon.

**Comment by 0bmxa** [comment]
Ah yes, absolutely!
I just wanted to clarify the belonging of this icon for other people wondering about the same! :)
