### ISSUE TITLE
DNS server configuration not working

### ISSUE THREAD

**Issue by aaron-trout** [tailscale/tailscale#281]
**Describe the bug**
DNS servers configured in the admin panel don't seem to be picked up by (MacOS / iOS) clients.

**To Reproduce**
1. Go to DNS in the admin panel
2. Add some internet based server (google / cloudflare etc)
3. Connect a Mac client
4. Try to resolve a DNS record (Goes to network interface provided/defined DNS server)

**Expected behavior**
Query goes to the server defined in Tailscale admin.

**Screenshots**
DNS server definition:

<img width="638" alt="Screenshot 2020-04-10 at 14 33 53" src="https://user-images.githubusercontent.com/2394679/78994959-39206c80-7b39-11ea-919a-8eea3869d859.png">

Wireshark showing DNS queries hitting DNS server provided by DHCP on Wi-Fi interface:

<img width="1047" alt="Screenshot 2020-04-10 at 14 37 05" src="https://user-images.githubusercontent.com/2394679/78995013-56edd180-7b39-11ea-8ef8-46dbc9b2a255.png">

**Version information:**
 - Device: MacBook Pro 15,2
 - OS: MacOS
 - OS version: 10.15.4
 - Tailscale version: 0.97.78

**Additional context**
I have a linux machine at home set up with subnet routes / relay. This works fine in most contexts however when I am using Tailscale via LTE/4G (on EE in the UK) either on my phone or tethered to my Macbook, dns requests to things on my home network (I have public DNS pointing at private IPv4 addresses) get resolved to a 6to4 address (e.g. `64:ff9b::c0a8:c9`) and the request fails.

If I manually set the DNS on my Wi-Fi interface to CloudFlare or Google e.t.c. then everything works as expected (Except for the DNS still going to whatever I've defined locally not what is configured in Tailscale admin).

This should come back with a 192.168.x.x address:

```bash
$ curl -v https://<redacted>/
*   Trying 64:ff9b::c0a8:c9:443...
* Connected to <redacted> (64:ff9b::c0a8:c9) port 443 (#0)
* ALPN, offering http/1.1
* Server aborted the SSL handshake
* Closing connection 0
curl: (35) Server aborted the SSL handshake
```

**Comment by aaron-trout** [comment]
Sounds possibly related to #234? I did try rebooting just in case but that hasn't fixed it 😋

**Comment by bradfitz** [comment]
Yeah, we were tracking this elsewhere but might as well use this bug now. Copying some notes I had from elsewhere:

--

Watching my iOS logs in console with search "provider" and "dns" in search box (`provider <enter>, dns <enter>`), I see it get set on my phone when I hit save on the web UI:

<img width="627" alt="Screen Shot 2020-04-06 at 8 18 23 PM" src="https://user-images.githubusercontent.com/2621/78626492-c4e97e80-7843-11ea-90f3-3247d5686134.png">

And if I change it on the web UI, it changes quickly on the phone:

<img width="635" alt="Screen Shot 2020-04-06 at 8 19 38 PM" src="https://user-images.githubusercontent.com/2621/78626546-f2362c80-7843-11ea-9e4a-c20b43b7c3f7.png">

So that's the good news. It makes it from the adminhttp code to my phone quickly.

But bad news: if I look at the system DNS setting via some Network Utility app, still my home DHCP's announced 10.0.0.1:

![IMG_1181](https://user-images.githubusercontent.com/2621/78626718-696bc080-7844-11ea-802f-29581503c0d5.png)

....

> If you kill everything and turn your wifi off/on, is your DHCP DNS in the NS#1 slot?

Uh, even weirder:

I turn off wifi and turn off "VPN" in Settings (which is the only way I know of to stop IPNExtension) and re-start Tailscale to bradfitz@gmail.com (with the 8.8.4.4 DNS) and I get `NS #1: 10.177.0.34, NS #2: 10.177.0.210`, which I can't ping or resolve a name from (using the network util app) but browsing the web is fine.

**Comment by bradfitz** [comment]
Closing this one as a dup of #101.

**Comment by bradfitz** [comment]
Good news. This is now working. For details, see https://github.com/tailscale/tailscale/issues/101#issuecomment-618794727
