### ISSUE TITLE
Windows 10 client with static ip settings, no internet connectivity

### ISSUE THREAD

**Issue by egala8** [tailscale/tailscale#2872]
I have the following setup.
1. Installed tailscale in few windows 10 clients and the windows 2019 server.
2. Windows 10 clients have dynamic IP address.
3. Advertising the routes using a Linux machine.
4. I can reach the machines and the router through the internal IP addresses.
5. When I change the IP configuration of a client to static the internet connectivity stops. Im using the internal subnet addresses here for the gateway and the static IP.
I am interested to hear the expert thoughts.

**Comment by DentonGentry** [comment]
You change the LAN IP address (the IP address assigned to the Ethernet or Wi-Fi interface) in one of the Windows clients to a static address instead of DHCP? And internet connectivity is lost?

I guess that could be:
- a conflict with multiple stations on the LAN trying to use the same address
- if the static IP is not on the same subnet, it may be that the Linux machine doing the routing doesn't have an address on the new subnet to be able to route it.

I don't really see the presence of Tailscale as being a factor though, at least if I'm understanding the problem correctly.

**Comment by egala8** [comment]
@DentonGentry, the answer to your question is yes. 
I checked the IP address there are no duplicates.
The Linux machine has an IP in the internal subnet.

**Comment by DentonGentry** [comment]
I guess one last set of suggestions: the Windows host gets more than just an IP address from DHCP, it also gets a gateway address, subnet mask, and set of DNS servers. All of those need to be configured manually.

Since there isn't a problem with Tailscale to be addressed here, I'm going to close the bug.

**Comment by egala8** [comment]
I have entered the subnet mask and the gateway address correctly. I could join the windows 10 to the windows domain.
