### ISSUE TITLE
Tailscale keeps asking to restart the windows service

### ISSUE THREAD

**Issue by guylevin** [tailscale/tailscale#2882]
Tailscale keeps asking to restart the windows service

I've restarted the service, and the computer as well serval times.
The service is runnning all the time.

I also uninstalled and installed again.

It keeps asking to restart and won't connect

(Win 11, tailscale 1.14.3)

![163213419257077326503304726704](https://user-images.githubusercontent.com/4077233/133989193-669bc86b-106a-46b6-bacc-836affba8b02.jpg)

**Comment by guylevin** [comment]
Duplicate of #2282 

Fixed by clearing the C:\Users\$user\AppData\Local\Tailscale library

**Comment by DentonGentry** [comment]
Delete %USERPROFILE%\AppData\Local\Tailscale\*

The problem occurs because a different file in c:\Windows got deleted, removing that one will let it recover. It should ask you to log in again within about a minute, or you can logout/login or uninstall/reinstall if it does not.

We know how to fix it at this point, and will be changing how that first file gets stored.

**Comment by guylevin** [comment]
Duplicate of #2282
