### ISSUE TITLE
shared node is unreachable if rebooted from host tailnet.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3033]
### What is the issue?

Recreated test 1, server (user@example.com) can connect to pi (user1@gmail.com) and generated a bug request after the pi rebooted and the server was unable to connect to it. Up/Down on server/laptop and the connection re-establishes

### Steps to reproduce

Share the RasberryPi from x domain to domain and restart the Pi from a node that resides in X domain. It will be unreachable from X tailnet domain but will be reachable from the remote tailnet.

### Are there any recent changes that introduced the issue?

Pi Version: 1.14.3
Laptop/Server Version: 1.14.4

### OS

Linux

### Tailscale version

1.14.3

### Bug report

BUG-989d9972ba632b061e480fbd842ec7e89ffc1a0ac0710e6da9f9071fa60d1914-20211007211030Z-80b8588bc10a0ff8

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3nidt)

**Comment by DentonGentry** [comment]
This resembles the symptoms of an overly aggressive netmap suppression optimization which we fixed about 5 months ago. The symptoms were that connections could not be established in one direction, but would instantly work if the other node first attempted a connection back to the first.

I'm going to close this on the assumption that it was fixed around the end of 2021 by the fix for that issue. We didn't make much progress when this was first filed as we didn't understand what was happening, and at this point we can't get to telemetry from back then to re-analyze.
