### ISSUE TITLE
macOS: Networking errors occur within Chrome when sufficient concurrent network activity exists

### ISSUE THREAD

**Issue by shorthandguy** [tailscale/tailscale#3102]
### What is the issue?

Whenever using TailScale (App version: 1.14.6) on macOS (Big Sur 11.6), when I generate sufficient concurrent network activity within Chrome (issue may not be browser-specific, but the tool that makes it easiest to reproduce this issue is one that works best in Chrome), then on almost every occasion, Chrome will generate a variety of networking-related errors. 

The activity that is primarily happening when the issue occurs is concurrent uploads of media to remote servers (via Chrome). 

I have spent too many hours attempting to perform Root Cause Analysis into this issue, however, nothing that has been tried has been fruitful. This has included:
- Working with the administrator to enable and disable override DNS,
- Working with the administrator to enable and disable MagicDNS
- Using the same DNS servers as what is configured within TailScale
- Using alternative DNS servers 
- Disabling IPv6 on the local network (the ISP generates IPv6 addresses, but these addresses appear to be cycled), but disabling IPv6 on the network and only using IPv4 did not solve the issue
- Upgrading to the latest MacOS client
- Upgrading Chrome to the latest version (v94.0.4606.81)
- Flushing sockets and DNS cache within Chrome and the DNS cache within macOS
- Disabling all extensions within Chrome
- Using Incognito mode in Chrome
- Using a standalone instance of Chrome
- Looked through Net Logs of Chrome and Console logs of macOS
- And various other things..

Our TailScale network is running the latest server software, uses publicly accessible common DNS servers, and uses exit nodes.

Whilst it would be easy to possibly point to either the web application, the tool or the browser itself, the _only_ variable that is consistent is that the error _only_ occurs when connected to TailScale (I can't select to not use 'Use TailScale DNS Server', otherwise my Internet connectivity ceases to work). 

I have tested this issue with TailScale disabled, plus also tested it whilst connected to both NordVPN and VPN Unlimited, and the issue never happens in those cases. 

The primary error that I encounter in Chrome is 'ERR_NETWORK_CHANGED', but the main other error has been 'ERR_NAME_NOT_RESOLVED', 

About the only time these errors _haven't_ occurred has been when i've slowed down the media upload process sufficiently that it didn't end up with as much data in-flight. 

I've been impacted by this issue for some time now, but recently (thanks to performance improvements in the web application I am using), this issue has become so pronounced that it's actually blocking the ability to perform this activity. I can't say for certain that this issue is limited to Chrome, but it _is_ where I have been constantly encountering it.

### Steps to reproduce

Tricky to give an exact set of steps to reproduce (as the steps being taken are specific to the application being used), but in essence, the main activity is uploading a combination of JPEG and PNG images + MP4 Video (via modals within a web application). 

Per 'upload', it's often uploading at least 3 assets when uploading 'video content', and at least 2 assets typically when uploading 'image content' (with some exceptions where it only uploads a single image). In total it's probably uploading >30 assets in the space of around a 3-5 minute period. The web application also returns its own rendered breakpoint versions of the uploaded assets (once these have been processed remotely). 

### OS

macOS

### OS version

Big Sur 11.6

### Tailscale version

1.14.6

**Comment by bradfitz** [comment]
1.24.0 will contain https://github.com/tailscale/tailscale/pull/4411 which lets the control plan direct nodes to go into a mode where there's just one big /10 CGNAT route on the machine, rather than updating the route table as nodes come & go. We'll experiment with that and see how if it makes things happier.

**Comment by jakedgy** [comment]
Will admins be able to toggle this as an experiment on the admin console?

I think this will help MacOS clients on large Tailnets, especially with ephemeral nodes.  My only concern is if users are connected to a network that uses CGNAT/10 or some subnet of it.

**Comment by bradfitz** [comment]
@jakedgy, yeah, we'll probably provide some temporary knob in the ACL/Policy JSON config.

Or we might just do it for all Macs that don't advertise any CGNAT-looking addresses on their other interfaces.

**Comment by DentonGentry** [comment]
You should be able to experiment with this using the following in the ACL JSON:
```
{
  "OneCGNATRoute": "mac-always",
```

**Comment by mdeeks** [comment]
TIL `route monitor`. I ran it for a minute and do see many changes being reported. I'll send the output via support@ rather than posting here though.

**Comment by mihaip** [comment]
From an initial investigation, the two `setRoutesFunc` calls are due to routing configs and DNS configs both calling `SetBoth` (see https://github.com/tailscale/tailscale/blob/d7f452c0a1fc1b131254f72ee3c803e88a49b00f/wgengine/router/callback.go#L38-L52), which eventually ends up calling `setRoutesFunc`. I'm assuming the DNS config is not actually changing most of the time, it seems like we could probably do an early exit somewhere if it does not change.

But that probably won't fix this bug.

**Comment by mihaip** [comment]
@bradfitz I think the reason why `OneCGNATRoute` doesn't help with this is because we still end up calling `setRoutesFunc` with the same config, and generating the same `NEPacketTunnelNetworkSettings`. macOS does not realize that this is a no-op, and removes and adds a bunch of routes, confusing Chrome. Based on http://crbug.com/1076619  (which is about the other network extension type) Chrome says that this is Apple's bug, and there's nothing they can do about it.

I can make the `Set` callback check if `rcfg` is unchanged and in those cases do an early exit, in which case `OneCGNATRoute` would at least help. We can then more aggressively set it for large-ish tailnets.

**Comment by DentonGentry** [comment]
An attempt to lessen the impact of this issue by suppressing no-op network changes will appear in the 1.27.57 release on the unstable track.
- The System Extension version of the Tailscale.app, which one can install outside of the App Store, is available now: https://pkgs.tailscale.com/unstable/#macos
- The App Store 1.27.57 version will appear in TestFlight when Apple completes its review. You can sign up for the macOS Tailscale TestFlight at: https://testflight.apple.com/join/7ExrFq00

**Comment by mihaip** [comment]
A more complete mitigation for this issue is now available via Testflight (version 1.27.57, build 186). See https://github.com/tailscale/tailscale/issues/3102#issuecomment-1170221907 for instructions on how to switch to the unstable/Testflight builds.

**Comment by mihaip** [comment]
Apologies, build 186 does not have the expected change. A build that does will be available in a few hours.

**Comment by mihaip** [comment]
Mac version 1.27.66 (187) was just released to TestFlight, that should actually have the expected fix.

**Comment by DentonGentry** [comment]
Slight update: 1.27.66 is in the review queue, it will go live in Test Flight after approval.

**Comment by imloic** [comment]
Hi, I always have this kind of error with Brave browser `ERR_NETWORK_CHANGED`  MAC OS SONOMA 14
I tried multiple solutions. 

1/ Quit Tailscale and remove the VPN connection (because when you quit Tailscale the VPN is always on ON.
2/ Reboot without starting Tailscale
3/ Disconnect/reconnect ethernet. 

My internet connection is now unstable.

Thanks

**Comment by DentonGentry** [comment]
This issue was closed 1.5 years ago. Please open a new issue, and include a bugreport (hold option while clicking on the Tailscale icon in the menubar, select Debug > bugreport).
