### ISSUE TITLE
Tailscale exe on windows detected as risk by symantec endpoint protection

### ISSUE THREAD

**Issue by akashkj** [tailscale/tailscale#3181]
### What is the issue?

Windows installer is detected as WS.Reputation.1 risk and quarantined by symantec.

![image](https://user-images.githubusercontent.com/14318173/138664721-3839a432-fda4-4823-868b-ffa3f5b3fe8d.png)

### Steps to reproduce

Download installer 1.16.1 with symantec protection running

### OS

Windows

### OS version

Windows 10

### Tailscale version

1.16.1

**Comment by mml** [comment]
(Picking most recent antivirus-labeled bug.)

FWIW, this is happening again with 1.18.2.  I understand what y'all said about your build system, and I believe the virus scanners probably are just using heuristics which are bogus, but running the current one through virustotal gives me three positives.  Two of them simply seem to be detecting tailscale(!), but it would be really nice if users did not have to reason their way through it each time.

It would be nice not 
![virus](https://user-images.githubusercontent.com/3115/146845996-08bad917-12ca-491e-a551-39ee7ddd9ac3.png)

**Comment by DentonGentry** [comment]
We've opened a request with TrendMicro, that does appear to not just be a simple heuristic.

So far as we can see, the ClamAV warning is triggered because Win.Ransomware.Hive-9916034-0 is written in Go and the signature matched something in Tailscale which is also written in Go. I doubt we can proactively prevent these, but signatures creating false positives tend to result in a *lot* of false positives and get adjusted by the AV vendor.
