### ISSUE TITLE
iOS 12 - frequently find Tailscale disconnected

### ISSUE THREAD

**Issue by ghost** [tailscale/tailscale#3187]
### What is the issue?

Go to use Taildrop only to find Tailscale is not connected

*hesitant to declare this is a bug due to age of device and underlying OS. iPhone 6 and iOS12.5 however I frequently go to use Taildrop only to find the the phone isn't currently on my Tailscale network. Simply launching the Tailscale app seem to refresh the connection without the need to tap the connect button.

### Steps to reproduce

Go to use Taildrop

### OS

iOS

### OS version

12.5

### Tailscale version

not sure

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3pfkh)

**Comment by offbyone** [comment]
I have noticed frequent disconnections in iOS 12 as well, including just this morning. I'd be happy to enable any telemetry that might help resolve this.

**Comment by DentonGentry** [comment]
A big difference between iOS 12 and iOS 15 is the amount of memory available to Network Extensions like the Tailscale app. In iOS 12 it is limited to 15 Megs, which includes both the RAM allocated from the heap as well as the space consumed by the application code. We have been in a constant struggle to keep the amount of code+heap within the limit:
- https://tailscale.com/blog/go-linker/
- iOS didn't have UPnP/NAT-PMP/PCP, because the code was too big
- iOS didn't use HTTP2 to talk to the control server, because it used too much memory
- iOS was the only client OS to not have the netstack (user-space TCP/IP stack) available, because it used too much memory. This significantly slowed feature work which might otherwise be able to use the netstack everywhere.

In iOS 15 Apple allows Network Extensions to use 50 Megs of memory. At this point, 8 months after iOS 15 became available, adoption of iOS 15 is nearly complete. There is a single digit percentage of devices still using iOS versions prior to 15.

I'm sorry, but I don't expect to fix this issue for iOS 12. The plan is to increase the minimum system requirement for the 1.26 version of the Tailscale app to be iOS 15, to let us start addressing the issues above due to being able to rely on having more memory available. iOS 12 can continue to download and install the 1.24 version of the app, but will receive no further updates.

I expect Tailscale 1.24 to continue to interoperate with new versions of the Tailscale app, we take backwards compatibility very seriously. The oldest tailscale node still in operation is a Linux system we operate which is running version 0.90. We'll only update it when all other users of the product have updated off of 0.90 (which may never happen).
