### ISSUE TITLE
pkgs: doesn't document apt-transport-https

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#319]
Should the Debian install docs mention:

`sudo apt-get install apt-transport-https`

?

Just hit that myself, and we also had a recent support request about it.

/cc @danderson

**Comment by danderson** [comment]
All recent Debian releases have apt-transport-https installed out of the box. Which release was this on?

We did just add it to the rpi docs, because it's apparently still a thing there, but oldstable through unstable shouldn't need this any more.

(I believe I did this research and removed it after someone complained that it was unnecessary, so I'm feeling like I can't win here :) )

**Comment by bradfitz** [comment]
stretch
