### ISSUE TITLE
KB: Connection error for "Forbidden: CSRF token invalid"

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3225]
The customer is unable to log in and getting Forbidden: CSRF token invalid.

To work around this issue, follow the steps below,

- Token error when trying to authenticate via the app.
- Token error when trying to log in with Safari.
- Able to log into login.tailscale.com with firefox.
- Attempting to login to the app after successful website login still gave token error.
- Restarting iPad and then logging into app worked.
- Revisiting login.tailscale.com on safari after successful app signin shows the admin panel.

**Comment by DentonGentry** [comment]
The solution was to reboot the iPad. I don't think we need a KB article for this.

**Comment by BristolPiggy** [comment]
> The solution was to reboot the iPad. I don't think we need a KB article for this.

I think you do thank you. Try to look at the problem from a beginners perspective. Someone who may for example, be over tired and who haven’t turned their iPad off for months, who were able to set up Zerotier-one in a second but are stumped by this occurrence. 

Sometimes what one person considers the most simplest of actions and solutions, to another is the last thought to consider. 

Plus resetting the iPad has not worked for me. I don’t think it should change anything but I used Brave instead of Firefox.  So currently Tailscale is still outsmarting me (Zerotier-One however is working a charm but can’t be downloaded to a Rpi4 running Dietpi OS, so really need Tailscale up and running…)

**Comment by TBT-SK** [comment]
I just got a report of the same issue on a Mac. Maybe this needs a deeper look that telling people to reboot to fix a website?

**Comment by DentonGentry** [comment]
This issue was closed two years ago, and we've made changes in how the cookies work several times since. If you're experiencing a problem now please file a new issue.
