### ISSUE TITLE
FR: Install script shouldn't unexpectly attempt to escalate privileges 

### ISSUE THREAD

**Issue by Smittyvb** [tailscale/tailscale#3272]
### Tell us about your idea!

The Tailscale install script should not unexpectly attempt to use `sudo`/`doas` to escalate its privileges.

### What are you trying to do?

Install Tailscale on a new machine.

### How should we solve this?

The install script should prompt to verify before attempting to escalate privileges using `sudo` or `doas` if not running as `root`. Since the copy-paste line doesn't have `sudo` in it (`curl -fsSL https://tailscale.com/install.sh | sh`), it gives the incorrect appearance that `root` access is not required to install Tailscale, causing confusion when files that only `root` has access to are used to install Tailscale.

### What is the impact of not solving this?

The Tailscale installer unexpectedly uses more privileges than expected, causing confusion when the installer unexpectedly modifies files in `/usr`. Also, on multiuser systems where the user running the script isn't in the `sudo` group, the system administrator is notified when a user attempts to use `sudo` without permission.

**Comment by DentonGentry** [comment]
I'm having trouble accepting that an install script needing root would be "unexpected."

We do provide the step by step guides https://tailscale.com/kb/1031/install-linux/ which make much more clear what is being done and with what privileges. The point of the install.sh script is to install with minimal hassle for people who don't otherwise want to deal with the details of getting it installed.
