### ISSUE TITLE
Android app is stuck on "starting" with 1.16.0 and later, works with 1.14.6

### ISSUE THREAD

**Issue by mrg0lden** [tailscale/tailscale#3291]
Hi,
Here's a screenshot ![Screenshot_٢٠٢١١١١١-٠٨٢٧١١.jpg](https://user-images.githubusercontent.com/8347078/141242660-32b60686-7696-4558-973f-25d105bbae47.jpg)

The problem is accompanied with another. When I tried to sign out then back in, after I go through the login process it gets stuck on the login page.

When I reverted manually to version 1.14 everything worked normally.

Device: Samsung Galaxy S10+  
SM-G975F/DS  
Android 11
Tailscale version: ‏‪1.16.1-t4f4000fbe-g0e7d23df47d‬‏

If you need any more details I'm up for it.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3tr81)

**Comment by DentonGentry** [comment]
Can you send its Tailscale IP address to support@tailscale.com?

**Comment by mrg0lden** [comment]
The phone's Tailscale IP? It doesn't connect, so I'm not not sure. Is it OK if I rollback to 1.14 and give you that IP address?

**Comment by DentonGentry** [comment]
The IP address could be found on login.tailscale.com in the list of devices, or you could send the email address of the Tailscale account to support@tailscale.com and we can look it up.

**Comment by mrg0lden** [comment]
Sent the details to your provided Email address with this title "Issue 3291 on GitHub"

**Comment by Loose-Moose77** [comment]
I'm having a possibly related issue with the android app as well that started within the last 24 hours. My app has never been updated. Instead of getting stuck on Starting, I will get a quick flash of Active before it goes back to Stopped.

So far in diagnostic, I've attempted to reauthenticate, logoff and back in, force restarting the app, uninstalling, restarting the phone, clear cache and app data. Have attempted on two different wifi networks as well as cell signal. Nothing so far has changed the behavior. Have also checked that both PIA and Zerotier will connect through their own applications.

Reached out to support and after some back and forth they directed me here as possibly related.

**Comment by DentonGentry** [comment]
@Loose-Moose77 your issue is different, I've filed https://github.com/tailscale/tailscale/issues/3294 to cover it. I believe you have a node on your tailnet which is advertising a route to 127.0.0.1/32, which the Android `VpnService.Builder.addRoute()` raises an exception about.

Removing 127.0.0.1 from the advertised routes should make the Android app stop crashing.

**Comment by Loose-Moose77** [comment]
@DentonGentry you're correct, thanks for the follow up!

**Comment by mrg0lden** [comment]
Hey, I updated to the latest version of Tailscale (1.22), and the problem still persists. I can confirm that the problem started exactly with version 1.16. The latest version that works on my phone is 1.14.6. I also updated my phone to Android 12, but that didn't fix anything.

**Comment by DentonGentry** [comment]
After 1.14.6 we updated to Android SDK30, which ran into a problem in the Go net.Interfaces package https://github.com/golang/go/issues/40569. We implemented our own support for getting the Interfaces from the platform, using Android APIs instead of Linux APIs.

I think that is the most likely thing in 1.16 to break a device like this.

**Comment by mrg0lden** [comment]
@DentonGentry Anything I can do to help this issue get resolved? I'm quite familiar with Go, but not that familiar with its internals nor with Go on mobile.

**Comment by DentonGentry** [comment]
- Does your device happen to be set to a locale using Indian-Arabic numerals? 1.16.0 is where we (unintentionally) introduced https://github.com/tailscale/tailscale/issues/4156, which means the app would crash at startup. We fixed it two weeks ago, and expect to deliver the fix in 1.24.x.
- Are you comfortable using Android adb and a USB cable? The app is almost certainly printing a stack trace which would tell us what is wrong.
- Otherwise, there is a reasonable chance the crash backtrace made it into the telemetry if we know where to look. If you could install the current version from the Play Store, watch it crash, then send the Tailscale IP address plus as exact a timestamp as you can (with timezone) to support@tailscale.com, we may be able to find it.

**Comment by mrg0lden** [comment]
Well, I decided to give it a go with the language changed to English (I use Arabic on my phone), and it worked! It seems to be the same bug mentioned on the first point, as it came back when I switched to Arabic again. I'll be waiting for the update, but I'll close this issue. If anything else comes up related to this, I will report here.

Thank you

**Comment by DentonGentry** [comment]
There is an Open Testing release track in the Play Store for the Tailscale app, which gets early release candidates. I built a 1.23.148 APK today which contains the locale fix that will be in 1.24. If you'd like to try it:
- from the Android device: https://play.google.com/store/apps/details?id=com.tailscale.ipn
- from the web (to enable your account to access the Open Testing track): https://play.google.com/apps/testing/com.tailscale.ipn

If you want to go back to the regular production release track later, the Play Store will let you uninstall the Open Testing app. When you go back to install Tailscale again you'll get the choice of whether to use the Production or Open Testing version.

**Comment by mrg0lden** [comment]
I can confirm that it fixes the issue. Thanks everyone!
