### ISSUE TITLE
Subnet adress not working between raspberry pi's

### ISSUE THREAD

**Issue by tkirchm** [tailscale/tailscale#3296]
### What is the issue?

I have connected two sites with rapsberry pi running on each network with subnets active.
With my mobile phone I can connect to all devices on both sites via local IP adress.

But to connect one raspberry to the other I have to use tailescales IP adress and can't use locale one.

### Steps to reproduce

Windows machine/Phone connected to the network can use local IP.

from Windows connected to Tailscale:
ping local IP in Network 1 works
ping local IP in Network 2 works
ping Tailscale IP in Network 1 works
ping Tailscale IP in Network 2 works

from raspberry pi Network 1 connected to Tailscale:
ping local IP in Network 2 doesn't work
ping Tailscale IP in Network 2 works

Other way around is the same between raspberry pi

### Are there any recent changes that introduced the issue?

No

### OS

Linux, Windows, iOS, Android

### OS version

respian buster

### Tailscale version

1.16.2

### Bug report

BUG-28bdcc277258a47e453b354b7f9d9cca636342efd6a9828c291a02fcc903859b-20211112122931Z-be1cf8ebfa335deb

**Comment by DentonGentry** [comment]
Windows, macOS, iOS, and Android accept routes by default. If you have two subnet routers, those subnets will be reachable without having to do anything else.

Because Linux is often used for routing, and because it was the first client developed, Linux does not accept routes by default. It will ignore the routes from the other subnet router unless told to do so.

I believe if you start the two subnet routers with `tailscale up --advertise-routes=... --accept-routes`, it will do what you want.

**Comment by tkirchm** [comment]
Thanks a lot for your fast answer.
Works great.

Love your work. Setting up a site to site network including mobile devices in 5min saves me a lot of time.
