### ISSUE TITLE
Fedora Silverblue changes machine hostname in response to Tailscale network changes

### ISSUE THREAD

**Issue by adrm** [tailscale/tailscale#3329]
### What is the issue?

Tailscale allows to change any client machine name, as described here: https://tailscale.com/kb/1098/machine-names/

But this procedure has different effects depending on the OS of the client. When a Tailscale admin changed the machine name of my clients, the linux one changed its hostname to the assigned machine name, but the MacOS client did not change anything in the client computer, as expected.

I suspect that the linux client treats every host as a server, so it might be helpful in that case for the hostname to be the same as the machine name. But the linux client is not only used in servers, and in that case, a Tailscale admin should not be able to change anything about the configuration of the machine. I believe you think the same, since the MacOS client does not change the hostname when changing the machine name.

### Steps to reproduce

Install linux client, check hostname, follow steps in https://tailscale.com/kb/1098/machine-names/, check hostname again.

The hostname should have changed to what you specified from the Tailscale admin.

### OS

Linux, macOS

### OS version

Fedora Linux 35.20211116.0 (Silverblue)

### Tailscale version

1.16.2

**Comment by adrm** [comment]
For context, now when I run `hostname` I get `<machine name>.<domain>.beta.tailscale.net`, and when I run `dnsdomainname` I get `<domain>.beta.tailscale.net`.

**Comment by bradfitz** [comment]
We don't have code to change the OS hostname on any platform.

**Comment by adrm** [comment]
We weren't able to reproduce in other OSes, even other Linux ones. Maybe there is a bug in Fedora 35 or even just in the Silverblue version that triggers the hostname change over some Tailscale network config change. Any advice about where to report this kind of issue would be appreciated.

**Comment by bradfitz** [comment]
If you can reproduce it on Fedora 35, I'd watch the logs while it's happening and see which process is responsible.

@danderson, @Xe, this ring any bells? Any guesses?

**Comment by DentonGentry** [comment]
I'm not able to produce this behavior with Fedora 35 in a freshly installed DigitalOcean droplet. The local hostname does not change when I change the name from the admin panel.

**Comment by guest42069** [comment]
n.b. that they're using Fedora Silverblue 35 (which is different from Fedora 35, immutable OS with rpm-ostree for package and OS image management, focused on container workloads like in Fedora CoreOS but with a desktop environment).

I use podman, per https://gist.github.com/guest42069/96a4d5361668f45dfa23288fdbecc1d2

Not had any issues other than the known firewalld compatibility stuff for routes (would love a workaround!). You could easily use the --hostname flag to set it as desired (currently it just copies the hosts hostname to the container) and I experience no changes.

**Comment by guest42069** [comment]
silverblue is different from fedora 35, so it may not function the same.
if it was installed via dnf per the fedora docs, it would need to be under toolbox? otherwise how was it installed and I can attempt to reproduce it (i have a silverblue desktop).

my prime suspect, from the description, would be something like NetworkManager (AKA NetworkMangler) using the Reverse DNS of the interface IP to automatically assign a hostname if no valid hostname was set.
See: https://developer-old.gnome.org/NetworkManager/stable/NetworkManager.conf.html and the section on `hostname-mode`.

alternatively, containerise it with podman to avoid it affecting the host system config since silverblue is intended for containerisation. ;)
https://gist.github.com/guest42069/96a4d5361668f45dfa23288fdbecc1d2

**Comment by adrm** [comment]
I installed directly on the host by adding the repo and installing through rpm-ostree, not on containers. Your theory seems sound. With everything that has been said, it seems like some strange bug on Fedora side, and if that is the case I don't really have a clue about where to begin reporting this.

**Comment by guest42069** [comment]
does your system have an explicit hostname set? I.E. did your system have a configured hostname before it was reconfigured to that in the reverse DNS?
if not, use `hostnamectl set-hostname your_predered_hostname` and see if the behaviour stops.
if it did have a hostname set, let me know and I'll try to install via rpm-ostree and let you know how it turned out in my case.
im not sure its a bug, if it is nm then its documented/expected behaviour.

**Comment by adrm** [comment]
I did not configure any specific hostname when I installed my system. It was set to something like "localhost" or something like that.

Since this happened, I set a hostname and tried replicating and it didn't happen again. So it matches with your suspicions, maybe it only happens if you do not set up a custom hostname, and it seems like a Fedora bug. Magic DNS was also enabled, as you said.

**Comment by DentonGentry** [comment]
At this point I think we've concluded that this is setup behavior in Fedora Silverblue, perhaps a function to automatically set the hostname based on the network.
