### ISSUE TITLE
Handle Okta 'user is not assigned' errors more gracefully

### ISSUE THREAD

**Issue by ramyfication** [tailscale/tailscale#3334]
### What is the issue?

When a user exists in an Okta tenant, but is not assigned to the Tailscale app (either directly or via a group), Okta returns an 'access denied' error, with no further information.

We should match this error code and description and direct to a KB article that lists appropriate mitigation steps.

https://login.tailscale.com/a/oauth_response?state=tc-27f9cf592fa81cd8&error=access_denied&error_description=User+is+not+assigned+to+the+client+application

### Are there any recent changes that introduced the issue?

This error occurs for manually created app integrations, as well as the Tailscale app installed from the OIN

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3uxch)

**Comment by danderson** [comment]
See also https://github.com/tailscale/corp/issues/3045 as another case of that.

**Comment by DentonGentry** [comment]
Fixed in January 2023 by [@clairew](https://github.com/clairew) in [tailscale/corp#8617](https://github.com/tailscale/corp/pull/8617) (which most of y'all won't be able to see, sorry).

Fix confirmed in https://github.com/tailscale/tailscale/issues/4861

![okta](https://user-images.githubusercontent.com/1140756/218335636-df9bdcd0-1a59-411a-8fa8-9546cdc9a2dd.png)
