### ISSUE TITLE
Two tailscale network adapters show in list and cause error if delete one of them.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#3383]
### What is the issue?

Tailscale version 1.18
Windows 11 64bit

When  tried to disable the tailscale network adapter. got the following message

![image](https://user-images.githubusercontent.com/75628398/142938417-af7cbae3-75ac-4a3f-8ca4-dbd0d24425a2.png)

Then at some point user got a pop-up, that tailscale needed to reboot the computer.

now he has two tailscale adapters.
![image](https://user-images.githubusercontent.com/75628398/142938516-5799870f-99aa-4860-802a-cc0420117aba.png)

After being updated to v1.18.0

note: just now as a test, he disabled the network adapter.
it has disappeared from the network adapter list. cannot find it, cannot re-enable it.

```
tailscale status
# Health check:
#     - ReceiveDERP is not running
#     - ReceiveIPv4 is not running
#     - ReceiveIPv6 is not running

100.x.x.x   en08                 asdffdsazqqq@ windows -
100.x.r.t   bnas                 asdffdsazqqq@ linux   -
100.g.h.k   server02             asdffdsazqqq@ windows -
100.x.g.r   vserver03            asdffdsazqqq@ windows -
100.g.h.t    wsl01                asdffdsazqqq@ linux   -
```

and now when he try to ping to machines, local on my lan,

```
tailscale ping server02
timeout waiting for ping reply

tailscale ping bnas
timeout waiting for ping reply
```
note: he has to re-start the tailscale service and then the network adapter re-appeared and is working.

again, as a test, he disabled the network adapter and once again, he get

### Steps to reproduce

Windows 11 64bit
tailscale 1.16.2 upgraded top 1.18 tested again.

### Are there any recent changes that introduced the issue?

1.18

### OS

Windows

### OS version

11-64bit

### Tailscale version

1.18

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3vwep)

**Comment by asdffdsazqqq** [comment]
hi, i am asdffdsazqqq.

this is not correct, as the os is windows 11, not windows 10.

```
OS
Windows

OS version
10-64bit
```

**Comment by dblohm7** [comment]
The "Error Disabling Connection" is more or less expected because, as the error message says, the adapter is in use by the system account (via tailscaled). To be able to successfully disable the connection, you need to first stop the Tailscale service.

As for the additional adapters: AFAICT this looks like WinTUN is not recognizing that an adapter already exists (even though it is disabled), and so creates a new one instead.

1.18 includes an updated version of WinTUN whose installation code was overhauled. I am unable to reproduce this issue with 1.18, so presumably that overhaul fixed this issue.

My inclination is to say that since 1.18 is working as expected, we don't need to fix anything.
