### ISSUE TITLE
cmd/tailscale: setting exit node is not immediate

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3447]
I just ran `tailscale up --exit-node=100.68.130.27` and `tailscale status` didn't show me using that exit node for minutes.

Turning it off is instant, both both times I tried to turn it on, it took a long time (waiting for a netmap update?)

at d89c61b8128221d53e5e077634553a3d8cb6f2fa

/cc @danderson @crawshaw

**Comment by bradfitz** [comment]
Confirmed that receiving a netmap diff from control unsticks it and makes "tailscale status" then show the right thing.

**Comment by bradfitz** [comment]
Okay, @danderson and I stared at this together and see the issue.

We never call `b.findExitNodeIDLocked` in the `EditPrefs` path; only on netmap updates.  (We just used to send lots of useless netmap updates that unstuck this regularly, so this bug has been getting worse as the control plane has gotten more efficient.)

**Comment by bradfitz** [comment]
Very related: #3090

**Comment by 0x5c** [comment]
Been hit by that for the last couple days on 1.16 and 1.18
Using the info here I was able to get instant exit node connections by using `up --exit-node` from a down state instead of from an already up state. This seems to be a reliable workaround while waiting until this patch makes it to a release.
