### ISSUE TITLE
FR: IP changing

### ISSUE THREAD

**Issue by DiamondDemon669** [tailscale/tailscale#3483]
### What are you trying to do?

I want to change the IP of tailscale machines

### How should we solve this?

I want to be able to change the last three sections of the tailscale IP

### What is the impact of not solving this?

MagicDNS is good, but I want to change the IP itself

**Comment by bradfitz** [comment]
Why?

To a particular IP, or to something new and random?

**Comment by DiamondDemon669** [comment]
> Why?
> 
> To a particular IP, or to something new and random?

I would prefer to change to a specific IP, but random IP's using DCHP wouldnt be too bad

**Comment by bradfitz** [comment]
But to what end? What's the problem? (see https://xyproblem.info/)

**Comment by DentonGentry** [comment]
To set expectations: I do not expect to implement this feature request. To support node sharing https://tailscale.com/kb/1084/sharing/, Tailscale IPs are allocated from a common pool globally across all tailnets. If individual tailnets could set specific IPs or otherwise constrain the allocation we almost immediately get into cases where the constraints are unsatisfiable.

Barring further input on the use-case for wanting this functionality, I expect to close this issue during the next bug scrub.

**Comment by DentonGentry** [comment]
ETIMEDOUT.
