### ISSUE TITLE
FR: sorting by columns on Machines tab

### ISSUE THREAD

**Issue by secure411dotorg** [tailscale/tailscale#3501]
### What are you trying to do?

Machines view

Sort by any column

### How should we solve this?

Make column labels on machine tab sort up and down

### What is the impact of not solving this?

Hard to see things like machines by last connected, or by operating system

**Comment by rosszurowski** [comment]
Our current plan (which may change) is to _not_ implement sorting, since folks usually want sorting to find certain devices. But finding devices is usually better accomplished by search. (The thinking is documented in #2540).

From what you've described, it sounds like you're looking to find machines by OS and by which devices are connected? You can use search system (building a UI is tracked in #2540) to search for `os:windows` or `os:macos`. We'll need to add filters for connection status to let you filter by last connected.

Is there something I'm missing that sorting by columns on the machines table would help you accomplish?

**Comment by DentonGentry** [comment]
I don't expect to implement this FR, I expect to implement https://github.com/tailscale/tailscale/issues/2540 instead.
Dup of https://github.com/tailscale/tailscale/issues/2540
