### ISSUE TITLE
Resilio sync

### ISSUE THREAD

**Issue by GerasDraugas** [tailscale/tailscale#3523]
### What are you trying to do?

Trying to sync files using Resilio sync via Tailscale. Can't find a solution. Is there a way?

**Comment by DentonGentry** [comment]
Resilio isn't a product we've directly tested, things I'd suggest:
- enabling MagicDNS https://tailscale.com/kb/1081/magicdns/ and setting up Resilio to sync with hostname.example.com.beta.tailscale.net is likely to succeed, at that point it is just a socket connection like any other
- Tailscale is a connectivity VPN, allowing access to your own devices even through firewalls. By default, traffic to the public Internet does not go through Tailscale. So if Resilio is syncing to a cloud storage folder, the connections to the cloud provider will generally not go through Tailscale. Exit nodes https://tailscale.com/kb/1103/exit-nodes/ can help by sending traffic part of the way there, before it will egress from the Tailscale network in order to connect to the cloud provider. If the exit node is running in a VM in that cloud provider's infrastructure like GCP or AWS, its traffic is more likely to stay within the provider's private network infrastructure.

**Comment by DentonGentry** [comment]
If there are further issues in configuring Resilio or if you suspect there is a problem with Tailscale please feel free to reopen the issue later.

**Comment by GerasDraugas** [comment]
I enable MagicDNS but resilio sync doesn't work. Servers / computers cannot see each other.
What else can I do?

**Comment by DentonGentry** [comment]
Can your devices ping each other? You can see all of the devices on your tailnet in https://login.tailscale.com/admin/machines, and see if you can ping the 100.x.y.z IP addresses.

**Comment by GerasDraugas** [comment]
yes, I can ping. I can login to server with remote desktop, but resilio not syncing.

**Comment by DentonGentry** [comment]
I can only offer general suggestions. We are not the support team for Resilio's product.

1. Sometimes services bind to localhost specifically. If Resilio is normally only accessed from the machine running the service, that might be what it is doing. You'd need to have it accept connections from any interface (which is often expressed by having it listen on 0.0.0.0). Since it isn't exposed to the Internet (because remote access is provided via Tailscale), it is usually a reasonable tradeoff to have it listen on all local interfaces.
1. Sometimes services bind to just the interface with the default route, which is probably an Ethernet or Wi-Fi interface in your case. The solution is similar: configure Resilio to bind to 0.0.0.0 instead of a specific subnet route.

**Comment by relink2013** [comment]
Hey I know this issue is closed, but it is the number 1 search result when looking for this so I wanted to provide the answer on how to do this correctly. 

This is actually fairly simple. I will describe my setup and how I did it for context. 

**-My setup:** 

I have my NAS at home that already contains all the files I want to sync to other devices. I want to increase my bandwidth when downloading files over WAN so I also setup Resilio on a computer at my company that keeps a 1:1 sync of my home server. All other devices use "Selective Sync". 

My company has a very restrictive network setup, and I have no desire to modify it just for my own use. So this caused that instance of Resilio to always use a relay server which is very slow. 

**-How I connected through TailScale:**

1. I installed Tailscale on my NAS and my Work PC. 
2. Setup Resilio on both systems, and go ahead and setup the folders you want to sync like you normally would. 
3. On the NAS make sure to note what port Resilio is using for transfers (not the WebUI). This info is found in Resilio under Settings > Advanced > "Listening Port"
4. On the Work PC, I clicked the 3 vertical dots on the folder that Syncs with my NAS and went to Preferences. 
5. In preferences, Check the box that says "Use predefined hosts" and input the Tailscale IP for the NAS along with the port you noted earlier. 

Almost instantly Resilio picked up the NAS, the relay server notification went away, and my speeds jumped from around 250KB/s to 2.5MB/s (2.5MB/s or 25Mb/s is my home internets maximum upload speed, so it definately works)

And thats it! You can do the same on the other end if you need, in my case I didnt need to. Since Resilio works the same on pretty much every device, and Tailscale has a client for pretty much everything, these steps can easily be adapted to pretty much any setup, and you can do this on as many Sync Folders as you need. Now your traffic will go through tailscale at full speed. 

Hope this helps.

**Comment by GerasDraugas** [comment]
How I solved my problem:

1. resilio: I set the port: 20555 ( Preferences -> advanced -> connection: listening port)

2. tailscale: I collected the ip addresses of the devices where resilio is running.

3. resilio: on folder I set other resilio hosts: ip:20555 (options -> preferences -> use predefined hosts

Finished. Everything works fine.
