### ISSUE TITLE
Tailscale > v1.18.0 unable to change /etc/resolv.conf

### ISSUE THREAD

**Issue by denisefrancisco1** [tailscale/tailscale#3531]
### What is the issue?

Hello,

I upgraded my tailscale version from v1.16.1 to v1.18.1 and noticed that some machines whose hostnames were resolved via MagicDNS were unable to resolve after logging into tailscale v1.18.1

What happened: 
```
denise.francisco@denise:~/Downloads/tailscale_1.18.0_amd64$ ssh machinex
ssh: Could not resolve hostname machinex: Temporary failure in name resolution
```

What did I expect to happen? 
To be able to successfully resolve the machinex hostname to a 100.x.x.x virtual IP address

I noticed that my `/etc/resolv.conf` file is not changed anymore after v.1.18.0. Instead of seeing the created tailscale resolv.conf file, I see the ordinary /etc/resolv.conf file. If I change the `search` portion of my original resolv.conf, it works. Do you know why this happens in the v1.18.x versions?

### Steps to reproduce

OS:
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
```

Download tailscale binary for v1.18.0 or above and after running `sudo tailscale up`, try to ssh

### OS

Linux

### OS version

18.04

### Tailscale version

1.18.1

### Bug report

BUG-f1d2220ea259bdd15b26559f09f09a60ac0cd4c24d110723479aa35db4a2cb11-20211208000126Z-0fafeaa143d3078a

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4n8sx)

**Comment by bradfitz** [comment]
Can we get a `tailscale bugreport` which lets us look at logs to see what's happening?

Also: is this in a container?

**Comment by denisefrancisco1** [comment]
Hi Brad, updated the bug report section with the output of the command

**Comment by taylorsmithgg** [comment]
We're experiencing the same issue w/our Ubuntu users:
Bug report: BUG-c4a63aab7de14d43f592d5254eb8f45cfae0b5143a050f1d727c47667534d5dc-20211208205551Z-de88a59f532acf81

**Comment by denisefrancisco1** [comment]
> Can we get a `tailscale bugreport` which lets us look at logs to see what's happening?
> 
> Also: is this in a container?

this is not in a container

**Comment by bradfitz** [comment]
Okay, @danderson says he thinks he knows what's going on here and can look later this week.

**Comment by denisefrancisco1** [comment]
hi @bradfitz any updates on this?

**Comment by denisefrancisco1** [comment]
hi @danderson any updates on this?

**Comment by denisefrancisco1** [comment]
hi @bradfitz @danderson wanted to touch base again to check up on this issue. Any updates?

**Comment by DentonGentry** [comment]
We're relatively thinly staffed during the holiday period. Can you send /etc/resolv.conf from the system which is not being updated to support@tailscale.com? tailscaled may not be figuring out the correct DNS manager to use.

- is systemd-resolved running?
- is /etc/resolv.conf a symlink to a path somewhere in the systemd configuration directories?

**Comment by DentonGentry** [comment]
There were a few changes between 1.16.x and 1.18.x relating to handling of /etc/resolv.conf, which might be involved.

https://github.com/tailscale/tailscale/releases/tag/v1.18.0
- if resolvconf wrote /etc/resolv.conf but pointed it to systemd-resolved, use systemd-resolved for DNS not resolvconf
- if NetworkManager wrote /etc/resolv.conf but pointed it to systemd-resolved, use systemd-resolved for DNS not NetworkManager
- handle /etc/resolv.conf being a bind mount into a container, such that we cannot rename() it.
- work around Ubuntu 18.04 setLinkDomain length limit by omitting reverse lookup information
- make /etc/resolv.conf [parse to the end of the comment section, not use the first match it finds](https://github.com/tailscale/tailscale/commit/139a6c4c9c44593219addaa4df204841a2371e6f)

**Comment by denisefrancisco1** [comment]
Hi @DentonGentry, apologies for the late reply-- but to answer your initial questions:

- systemd-resolved is indeed running
- /etc/resolv.conf is not a symlink to a path. 

I did take a look at the release notes for > 1.16.2 (1.18.x), and the contents of our resolv.conf look like the following (repaced the search domains here):
```
# Generated by NetworkManager
search some.domain.here
nameserver 127.0.0.53
```

Ultimately, we'd like to know what cmdline args or alterations we need to make in order to log in to tailscale with these new changes. Any help would be appreciated !

**Comment by bradfitz** [comment]
@denisefrancisco1, can you try unstable build 1.21.26 and try again and share a `tailscale bugreport`? We added some logging that would help us understand what's happening. Thanks!

**Comment by DentonGentry** [comment]
Notes from a talk with danderson:
This appears to be a race condition, tailscaled chooses a DNS mechanism to use once at startup. We set the systemd unit ordering for tailscaled to start after resolved, but it is still possible for tailscaled to start before the actual DBus portion of resolved has registered itself. If this happens, tailscaled will conclude that resolved isn't actually running and will decide to use the Direct management instead of overwriting /etc/resolv.conf.

The fully general solution would be to make the choice of DNS mechanism dynamic, not just once at startup. We already monitor various DBus notifications, we could watch for a new bus service to appear and respond when it does. We'd do this for a number of services for resolved and NetworkManager. If we see one that impacts the choice of DNS manager we'd tear down DNS and set it back up, giving us a second chance to choose the manager. (Ideally we'd dynamically adjust the DNS config for the new manager, but that opens a vast number of transitions we'd need to test and we'd probably not be able to fully test it)

A more immediate alternative:
systemd units have a way to depend on DBus services. The tailscaled systemd file could delay startup until the resolved dbus channel is actually available. It isn't clear that would be safe to do on all systems (what if they don't use systemd-resolved at all?) but could be done on individual systems which otherwise run into this problem.

An even more immediate alternative:
This is a fairly narrow race condition between when systemd-resolved starts its daemon and when the daemon opens its DBus channel. Adding a one second delay to the tailscaled systemd file would likely avoid the problem.

**Comment by carleeno** [comment]
@bradfitz I'm replying for @denisefrancisco1  (I work with her and she's been ooo).
Here you go: `BUG-509feaceca587b214f048c3bd18ad7cf73344af35d0530496ba015b9cd7c735b-20220124203355Z-9ce99eebbc0c9c57`

**Comment by denisefrancisco1** [comment]
Hi @DentonGentry and @bradfitz ,

We are seeing the same resolv.conf issue on a user's local machine with tailscale version `1.16.2`. This may or may not be related to what's happening for versions 1.18.x+ but here is a follow up bug report: 

`BUG-8dd40100d40864895e225c4183b491310eec00b9411c616b12a5077d111e1fd0-20220128145736Z-26ed85f4526f7fbd`

**Comment by denisefrancisco1** [comment]
Hi @DentonGentry and @bradfitz ,

We are receiving multiple issues regarding using Tailscale 1.18.x+. Can this be prioritized? Are there any additional insights as to what might be going wrong with overwriting /etc/resolv.conf? Users are experiencing this with Tailscale version 1.20.2

**Comment by DentonGentry** [comment]
Detection of systemd-resolved isn't working reliably on these systems, sometimes the system comes up with directManager and sometimes with resolvedManager.

BUG-01b9753e479919406959e2e3fb1d259288e6613430e0c1d9dfd11928aeabf4d4-20220208162952Z-4a325ad9cfea125c
```
2022-02-01 09:46:28.646130537 -0700 -0700: dns: using *dns.resolvedManager
2022-02-02 16:39:26.771148657 -0700 -0700: dns: using *dns.directManager
2022-02-02 16:39:27.783795142 -0700 -0700: dns: using *dns.directManager
2022-02-02 16:52:22.334101364 -0700 -0700: dns: using *dns.directManager
2022-02-02 16:52:23.34563709 -0700 -0700: dns: using *dns.directManager
2022-02-02 17:00:53.153475468 -0700 -0700: dns: using *dns.directManager
2022-02-02 17:00:54.167190044 -0700 -0700: dns: using *dns.directManager
2022-02-02 17:08:00.776196505 -0700 -0700: dns: using *dns.resolvedManager
2022-02-03 10:26:49.93055435 -0700 -0700: dns: using *dns.resolvedManager
2022-02-08 09:29:52.058825867 -0700 -0700: user bugreport: BUG-01b9753e479919406959e2e3fb1d259288e6613430e0c1d9dfd11928aeabf4d4-20220208162952Z-4a325ad9cfea125c
2022-02-08 15:29:26.074339619 -0700 -0700: dns: using *dns.directManager
2022-02-08 15:29:27.089563576 -0700 -0700: dns: using *dns.directManager
2022-02-08 15:41:20.289137056 -0700 -0700: dns: using *dns.directManager
2022-02-08 15:41:21.306644343 -0700 -0700: dns: using *dns.directManager
2022-02-08 15:50:41.48792368 -0700 -0700: dns: using *dns.directManager
2022-02-08 15:50:42.501241254 -0700 -0700: dns: using *dns.directManager
2022-02-08 15:53:56.273777282 -0700 -0700: dns: using *dns.resolvedManager
```

BUG-b17e49dce118755a3fbda1dd743b0b0d4e328b145c1427fdc42ee60ff3d0cb62-20220207224806Z-682bf7b15685dbab
```
2022-02-07 14:24:39.400288672 -0800 PST: dns: using *dns.directManager
2022-02-07 14:24:40.855929894 -0800 PST: dns: using dns.directManager
2022-02-07 14:24:41.2902696 -0800 PST: dns: using dns.directManager
2022-02-07 14:27:23.374551953 -0800 PST: dns: using dns.directManager
2022-02-07 14:27:52.194916945 -0800 PST: dns: using dns.directManager
2022-02-07 14:27:52.627294759 -0800 PST: dns: using dns.directManager
2022-02-07 14:48:06.815673154 -0800 PST: user bugreport: BUG-b17e49dce118755a3fbda1dd743b0b0d4e328b145c1427fdc42ee60ff3d0cb62-20220207224806Z-682bf7b15685dbab
```

We discussed the long term plan at an engineering meeting last week: we need to have tailscaled monitoring for DBus messages and other indications that it needs to change its notion of how to manage the DNS settings on the system continuously at runtime, rather than depend on getting the determination correct on boot. However that will not be a quick development.

The original report says that Tailscale 1.16 worked more reliably on these systems:
> I noticed that my /etc/resolv.conf file is not changed anymore after v.1.18.0. Instead of seeing the created tailscale resolv.conf file, I see the ordinary /etc/resolv.conf file. If I change the search portion of my original resolv.conf, it works. Do you know why this happens in the v1.18.x versions?

In 1.18 several changes were made to more reliably detect when systemd-resolved is in use: https://github.com/tailscale/tailscale/releases/tag/v1.18.0

So it may be that dns.directManager was working better, even though systemd-resolved was running and (technically) should have been used. That would be unexpected, as systemd-resolved has been working well in most contexts. We know of an issue with systemd-resolved in Ubuntu 18.04 where reverse DNS lookups won't work (https://github.com/tailscale/tailscale/issues/3188), but it has otherwise been quite nice.

A couple things which could be done:
- disable use of systemd-resolved to make tailscaled always use dns.directManager, and see if the behavior improves. /etc/resolv.conf is likely a symlink pointing to /run/systemd/resolve/stub-resolv.conf. Removing the symlink and populating a /etc/resolv.conf file with just a "nameserver x.x.x.x" entry will disable use of systemd-resolved, and tailscaled will use dns.directManager to overwrite the file.
- Alternately, to make it more reliably detect systemd-resolved: tailscaled.service already marks itself to run after systemd-resolved: `After=network-pre.target NetworkManager.service systemd-resolved.service` but there is a race of whether systemd-resolved is ready when tailscaled checks. Using `sudo systemctl edit tailscaled.service` to add a "sleep 5" would give systemd-resolved more time to get initialized.

**Comment by ephsiung** [comment]
Thanks for the detailed response.
Fwiw, I added _ExecStartPre=/bin/sleep 5_ to my tailscaled.service and DNS lookups are now working (i.e. /etc/resolv.conf has the expected entries). I've only done 2 reboots so the sample size is small, but we'll roll it out to other users who are seeing this problem and see what happens.

**Comment by DentonGentry** [comment]
Could you try installing from the unstable track https://pkgs.tailscale.com/unstable/ build 1.21.73 or later on one of the systems experiencing this issue most repeatably?

https://github.com/tailscale/tailscale/pull/3905 reorders some of the steps in tailscaled's startup process to try to ensure that systemd-resolved is initialized and ready to respond before tailscaled checks it.

I'm going to reopen the bug for now, we're using this bug to track the support issue.

**Comment by carleeno** [comment]
@DentonGentry I gave 1.21.73 a shot and it has the same behavior (unable to resolve at all):
BUG-509feaceca587b214f048c3bd18ad7cf73344af35d0530496ba015b9cd7c735b-20220212135712Z-7bc5affe56696674

However as mentioned in the email I sent you, it appears I'm dealing with something aside from the race condition, since I can entirely restart tailscaled and it still doesn't resolve.

However once we discovered the difference between our vdesk and local laptops (both running bionic) we discovered a workaround:
- stop and disable `systemd-resolved`
- add these lines to `/etc/NetworkManager/NetworkManager.conf` under `[main]`:
```
dns=default
sudo rm /etc/resolv.conf
sudo systemctl restart NetworkManager
```
This allows tailscale 1.18+ versions to work on our bionic laptops. We're still looking to see if this is something we can/should patch on our end with client device management, but I wanted to share this with you in case it helps you to know why it's failing to resolve for our devices.

And thanks for keeping the issue open for now. Btw the very first post that started this thread (by Denise) is relating to the complete failure to resolve on new versions with our bionic machines, rather than the race condition issue.

**Comment by bradfitz** [comment]
@carleeno, @denisefrancisco1, are one of you available on Monday or Tuesday to debug this on a call together?

I work 8am-4pm Seattle time.

**Comment by carleeno** [comment]
@bradfitz yep I'm available 8-12 (pst) both days. I'll send a message to support@ so you have my contact info.

**Comment by bradfitz** [comment]
Monday 10am. @danderson, sent you the calendar invite too if you can make it.

**Comment by bradfitz** [comment]
During the call we found that the `/etc/resolv.conf` wasn't properly a symlink to systemd's stub conf, perhaps based on how their Ubuntu 18.04 base image was created.

Filed https://github.com/tailscale/tailscale/issues/3937 which would've helped diagnose it earlier.

@taylorsmithgg, please open a new bug with if you're still having problems with Tailscale 1.20.4+ and your symlink is correct.
