### ISSUE TITLE
Quad-100 seems to handle EDNS0 requests incorrectly

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#3639]
### What is the issue?

Noticed that my systemd-resolved reports the following about quad-100:

Dec 29 21:57:54 vega systemd-resolved[1463297]: Using degraded feature set UDP instead of UDP+EDNS0 for DNS server 100.100.100.100.

Not sure what it means, but I'm wondering if we're mishandling DNS requests with EDNS0 extensions in our parsing+routing logic.

### OS

Linux

### OS version

NixOS 21.11

### Tailscale version

1.18.2

**Comment by twitchyliquid64** [comment]
There seems to be four cases where `systemd-resolved` will downgrade from EDNS(0) to UDP:

 - Invalid response packet:
https://github.com/systemd/systemd/blob/2afb2f4a9d6a497dfbe1983fbe1bac297a8dc52b/src/resolve/resolved-dns-server.c#L478
Could be us, could be upstream.

 - Response was missing the EDNS puesdo-section in the additional records section of the response:
https://github.com/systemd/systemd/blob/2afb2f4a9d6a497dfbe1983fbe1bac297a8dc52b/src/resolve/resolved-dns-server.c#L493
Need to investigate if theres cases where we don't set that flag / don't propagate from upstream.

 - Lack of responses (packet loss): https://github.com/systemd/systemd/blob/2afb2f4a9d6a497dfbe1983fbe1bac297a8dc52b/src/resolve/resolved-dns-server.c#L541
I imagine theres a few possibilities here, one of which being that we hit the max pending requests in the resolver and dropped some request packets, or perhaps we didn't get an authorative response from upstream in time.

 - Truncated bit set in responses + TCP connections failed:
https://github.com/systemd/systemd/blob/2afb2f4a9d6a497dfbe1983fbe1bac297a8dc52b/src/resolve/resolved-dns-server.c#L559
Given we don't implement TCP (#1123) this is expected if any upstream server sets the truncated bit. We may want to construct response packets from the forwarder outselves instead of just passing through the response from upstream (with the edns clamp).

Its interesting to note that `systemd-resolved` falls back to TCP as its lowest level (before trying UDP again after a timeout).

**Some next steps**

 - Hopefully gather more instances of this - this will help us determine if this is purely symbolic of graceful degradation, trigged by specific upstream responses, or a bug within our implementation.
 - Consider switching response logic to construct valid response packets rather than forward almost-verbatim from upstream sources.
 - Look at #1123 given it seems to be the low-level fallback and will result in some latency until that times out.

**Comment by DentonGentry** [comment]
We implemented DNS-over-TCP support for all platforms except iOS in 1.26, and for iOS in 1.28.

**Comment by DentonGentry** [comment]
As far as I can tell, this was resolved by adding DNS-over-TCP support in 1.26. I've checked a number of systems using `systemd-resolved` and don't find any log messages about a degraded feature set.
