### ISSUE TITLE
FR: policy routing through multiple exit nodes.

### ISSUE THREAD

**Issue by ryancdotorg** [tailscale/tailscale#3648]
### What are you trying to do?

I have a subnet router running tailscale, and I would like to configure it with multiple exit nodes to be used via policy routing.

For example, I could have exit nodes `Alpha` and `Bravo` and hosts `Kilo`, `Lima` and `Mike` on my LAN.
Then I could configure the subnet router to send IRC traffic from `Kilo` via `Alpha`, all traffic from `Lima` via `Alpha`, and all traffic from `Mike` via `Bravo`.

I'm an American but live in the UK, and I have a few websites I need to interact with (e.g. medical providers) which block UK/EU IP addresses, and I have a Raspberry Pi Zero W in the US which I use for them.

I also have some "home lab" systems for which I route all traffic out of a datacenter.

### How should we solve this?

Broadly, I see two options for how to implement this:

1) Add the default route to a different routing table, have netfilter marks (perhaps with a mask) for each configured exit node, and set up `ip rule` directives to send appropriately marked traffic through the appropriate routing table. Tailscaled would then look at the marks on incoming packets and use them to make routing decisions.

2) When "policy exit" is configured, create a separate tailscaleN interface (e.g. `tailscale1` and `tailscale2`) for each exit node being used, and leave policy routing *entirely* up to the user.

The second option affords greater flexibility and behaves in a pretty "standard" way, but I'm not sure how difficult it would be to implement.

For the first option, forcing tailscaled to care about netfilter marks feels like an egregious layering violation, but it ought to work.

### What is the impact of not solving this?

A potential workaround would be to set up ipip or gretap tunnels on top of the tailnet from the subnet router to each exit node and use those for policy routing. This approximates the second option mentioned above.

I have been using wireguard directly for this, but it's... annoying.

**Comment by DentonGentry** [comment]
The way other users with similar needs are doing this is via subnet routers offering specific routes, rather than an exit node with a (potentially complex) policy layered on top of it.

For example, if Medical Provider A has IP address 1.2.3.4, the Raspberry Pi Zero in the US would use:
`tailscale up --advertise-routes=1.2.3.4/32`

This doesn't work as well when the service provider has a large number of IP addresses.

**Comment by pcl** [comment]
I've got a similar use case -- I'm running Tailscale on a number of Unifi Security Gateways, and I'd like to route all traffic from certain internal subnets out through particular exit nodes. I can run `tailscale up --exit-node=100.... --exit-node-allow-lan-access` and successfully send *all* traffic from site A out through site B, but I'd like to send only `192.168.40.0/24` through site B.

Theoretically I should be able to do this via Unifi configuration, but it'd be a lot nicer to do it all within Tailscale, ideally via a web configurator, but possibly via `--exit-node-subnet=192.168.40.0/24` directives or something. 

I prefer a solution that's entirely within the Tailscale processes, rather than pushing things up to the routers to do their own policy-based routing, since this approach essentially commoditizes the routers themselves. I'd prefer to run networks with heterogeneous routers and just invest the routing smarts in Tailscale configs rather than the appropriate incantations for each different router vendor.

**Comment by DentonGentry** [comment]
@pcl  I believe `tailscale up --advertise-routes= 192.168.40.0/24` on site B would do what you're asking about.

**Comment by DentonGentry** [comment]
To set expectations: I do not expect to implement this feature request.

Exit nodes get used for several things:
1. as an exit node
2. as a way to get a specific public source IP address, to send to an external SaaS provider to add to their allowlist

We're aware of (2) and expect to provide more support for steering specific domains, URLs, or other providers through a specific node. It wouldn't be an exit node.

Policy-based choice of exit node seems like a way to make exit nodes better serve use-case (2). I don't expect to go in this direction. Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by hazcod** [comment]
Hi @DentonGentry , can you al elaborate why this specifically won't be considered?

**Comment by DentonGentry** [comment]
I expect future work to address:
- need for a stable IP address when communicating with external service provides who need an IP to add to their allowlist. This would not be an exit node feature, but enhancement to subnet routing to, for example, allow a URL to be configured as needing to go to a particular node for egress.
- automatically choose amongst available exit nodes based on latency

I don't expect to provide a policy feature to configure other, more complex use of exit nodes. I do not believe that is the right tradeoff of simplicity versus features.

**Comment by ryancdotorg** [comment]
I would still find it useful to be able to have, for example, a VLAN for which all traffic gets routed through a specific exit node, but ultimately, this *is* a thing that can be trivially implemented via additional tunnels. I just wanted to avoid the overhead.

**Comment by ryancdotorg** [comment]
@DentonGentry For what it's worth, the medical provider I need to access runs a login process through several services, which I don't expect to have stable IPs, and may be used for other services. Using dnsmasq to temporarily add IPs for relevant hostnames to an `ipset` would be nice. This is probably at the point, however, where I should configure a proxy for selective use...

**Comment by DentonGentry** [comment]
Policy-based routing of exit nodes will be handled on https://github.com/tailscale/tailscale/issues/3569
