### ISSUE TITLE
FR: enforce exit node in control panel

### ISSUE THREAD

**Issue by hazcod** [tailscale/tailscale#3658]
### What are you trying to do?

For enterprise security, we want to enforce users to go through an exit node to benefit from transport encryption for all connections.

### How should we solve this?

Support enforcing exit nodes centrally and not in the client itself.

### What is the impact of not solving this?

Users being able to override security settings ad forgetting to revert them.

### Anything else?

Comparable, we want to force override DNS servers to be able to benefit from our own malware DNS filtering.

**Comment by dragetd** [comment]
There is a little logical flaw: If the client can access the internet, it could just disable tailscale. If you would enforce/block on your network layer to only allow traffic to the tailscale-node used as an exit node (and to the tailscale management servers), you could block internet access without any changes to tailscale.
So from a security perspective there is nothing to be gained.

This could be tackled from a 'usability' perspective tho. Instead of `sudo tailscale up --exit-node=xxx` there could be an option called `sudo tailscale up --accept-offered-exit-node` or something like this. And *then* the webinterface could allow a feature to 'offer exit-node' to nodes. Such wording would make it clear, that this is not a security but convince feature.

**Comment by mayakacz** [comment]
Going to close this as a dupe of https://github.com/tailscale/tailscale/issues/1745.

> There is a little logical flaw: If the client can access the internet, it could just disable tailscale.

Correct, to strictly 'force' users to do this, this functionality would need to be applied in parallel with say, an MDM solution, that requires Tailscale be installed and logged in on the device.

**Comment by hazcod** [comment]
I don't completely agree, if internal assets are only available via Tailscale the user should have it enabled to access corporate assets. Right now they can still disable the exit node and any additional DNS lookup servers to bypass those security controls.
