### ISSUE TITLE
admin console: show duplicate node keys

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3706]
When two+ nodes are flapping, fighting over a key (e.g. cloned VM/container state), we should highlight that prominently in the web UI.

**Comment by bradfitz** [comment]
We should also push down the unhealthy state to the clients so they can show it themselves in "tailscale status".  The protocol support is there already.

**Comment by irl-segfault** [comment]
What's the fix here from a user perspective?  Tooltip in the web UI says "Multiple cloned devices are trying to share a key.  Reinstall."  Do I need to uninstall the Tailscall mac app and reinstall?

**Comment by DentonGentry** [comment]
You can use Applications > Utilities > Keychain Access to clear the duplicated key.
Use the search box in the upper right to search for "tailscale".

There is a set of selections across the top for "All Items", "Passwords", "Secure Notes", etc. The ones you are looking for are in Passwords.

They are named:
- tailscale-daemon
- tailscale-logdata
- tailscale-machinekey
- tailscale-preferences

Quit the Tailscale app, remove those four items from Keychain Access, and then start the Tailscale app again. It should recover and let you log in again. The new Mac will get its own IP address.

Depending on how the old Mac was configured you may only see three of the items. That is fine, just remove those three.

**Comment by bourbonspecial** [comment]
Whereabouts is that info stored when tailscale is installed on windows? Had a little root around in the registry and in credentials manager but I couldn't see anything with names like

- tailscale-daemon
- tailscale-logdata
- tailscale-machinekey
- tailscale-preferences

**Comment by DentonGentry** [comment]
For Windows you'd remove:
- all files in %LocalAppData%\Tailscale
- all files in C:\ProgramData\Tailscale

**Comment by DentonGentry** [comment]
The admin panel now adds a `Duplicate node key` badge with a tooltip of "Multiple cloned devices are trying to share a key. Reinstall." in these cases.

**Comment by pitosalas** [comment]
I have the same problem (caused likely because of cloning a microsd card between robots.) However I have changed the hostname (platform3) uninstalled tailscale totally, and reinstalled it, and it is still being assigned the same ip as another one (platform2). I thought doing that one one of the two was sufficient?

**Comment by DentonGentry** [comment]
On Linux platforms not using any of the other state storage options like k8s or AWS, the file containing the node key is /var/lib/tailscale/tailscaled.state. You can:
1. sudo systemctl stop tailscaled
1. sudo rm /var/lib/tailscale/tailscaled.state
1. sudo systemctl start tailscaled
1. tailscale up

It will print a URL to authenticate afresh, and will get a new node identity.

**Comment by rudydevolder** [comment]
Easy peasy, this works without reinstalling. Thank you SO MUCH !!!

**Comment by garry-t** [comment]
How to automatically achieve this . I performed two these steps from ansible
1. sudo systemctl stop tailscaled
2. sudo rm /var/lib/tailscale/tailscaled.state
But after restart host or deploy new VM from image I see 
`health("overall"): error: state=NeedsLogin, wantRunning=false`

I guess it because we delete state file :). I cant replicate command to start tailscale again.  What I can see here it is change systemd file somehow

**Comment by ricardodong** [comment]
For those who have the same problem in other platforms, check this [uninstall guide](https://tailscale.com/kb/1069/uninstall?q=uninstall).
