### ISSUE TITLE
FR: service detection for Android

### ISSUE THREAD

**Issue by steren** [tailscale/tailscale#3788]
### What is the issue?

I'm running a web server on my Android phone. It serves successfully on port 8080 on my phone's IP.

When I turn on Tailscale on my Android, I can successfully see the served page when I hit the Tailscale IP followed by :8080, but Tailscale doesn't detect a service running on 8080 for this machine

### Steps to reproduce

- Serve a static index.html from your phone using https://play.google.com/store/apps/details?id=com.phlox.simpleserver
- turn on Tailscale on Android phone
- open Tailscale admin website
- see that no service is detected for this machine

### OS

Android

**Comment by DentonGentry** [comment]
I think we leave service detection out of the mobile clients because... well... because.

To be honest I'm not sure Android would even allow the same kind of access to detect listening ports like we do on regular Linux platforms, as Android often restricts what apps are allowed to see on the device, but we can track this as a feature request.

**Comment by bradfitz** [comment]
In 77cad13c7 I wrote "Android 10+ doesn't allow access to this anymore."

In any case, the whole "services" feature in Tailscale is pretty incomplete. It was never finished. It's just a hint of the sort of things that might be possible later if we build that out. Perhaps later we'll add some mechanism to declare services explicitly if you'd like.

**Comment by DentonGentry** [comment]
Closing as not feasible, it isn't possible to get the listening ports on recent Android releases.
