### ISSUE TITLE
New identity provider: Keycloak

### ISSUE THREAD

**Issue by luketainton** [tailscale/tailscale#379]
**Is your feature request related to a problem? Please describe.**
I run my own Keycloak IAM server that supports OIDC and SAML, but I can't use it with Tailscale.

**Describe the solution you'd like**
Add Keycloak (or Generic OIDC) as a supported identity provider.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2c5ap)

**Comment by bradfitz** [comment]
Not a deal breaker if not but curious: is there a discovery path from email address to Keycloak server, without configuration or client secret registration?

e.g. some DNS record or mechanism ala WebFinger/WebFist?

That is, given just "foo@bar.com", can we discover your Keycloak server and kick off the relying party flow?

**Comment by luketainton** [comment]
I don't think so, no. I do know that Keycloak supports the <URL>/.well-known/openid-configuration that basically lists all of the OIDC endpoints, if that's useful?

***Some example endpoints:***
```json
{
  "issuer": "https://login.example.com/auth/realms/master",
  "authorization_endpoint": "https://login.example.com/auth/realms/master/protocol/openid-connect/auth",
  "token_endpoint": "https://login.example.com/auth/realms/master/protocol/openid-connect/token",
  "token_introspection_endpoint": "https://login.example.com/auth/realms/master/protocol/openid-connect/token/introspect",
  "userinfo_endpoint": "https://login.example.com/auth/realms/master/protocol/openid-connect/userinfo",
  "end_session_endpoint": "https://login.example.com/auth/realms/master/protocol/openid-connect/logout",
}
```

**Comment by padrino121** [comment]
Same issue here, purchased Okta for now given I have no option to use my own as I do with other apps

**Comment by polarathene** [comment]
@padrino121 just :+1: at the top to show your interest (same with anyone else interested, don't just "subscribe" for notifications). It'd help communicate interest to the project devs to raise the value of an identity provider we can self-host. Although afaik OIDC is meant to be able to provide generic data so that it shouldn't need to be just tailored to specific providers like Keycloak.

**Comment by DentonGentry** [comment]
It looks like KeyCloak supports SAML, and SAML support is being worked on as a way to integrate auth providers.

**Comment by polarathene** [comment]
OIDC is more preferable iirc, I don't have my notes on me but SAML had some downsides I think (at least with keycloak).

**Comment by mayakacz** [comment]
**We've just released support for custom OIDC providers with Tailscale, and have tested Keycloak and confirm it works with this flow. Read more in the [blog post](https://tailscale.com/blog/custom-oidc/) and [docs](https://tailscale.com/kb/1240/sso-custom-oidc/).**

Note that when a user logs out of Tailscale, they are not logged out of Keycloak automatically. If users do not log out of Keycloak, then when they reconnect to Tailscale, they will not need to reauthenticate.

To migrate an existing Tailscale account from another identity provider to Keycloak, contact support with an Identity provider change: https://tailscale.com/contact/support/?type=sso. Note that we can only migrate a Tailscale account to a custom OIDC provider that uses a custom domain (for example, @work.com instead of @gmail.com).

**Comment by PovilasID** [comment]
I apricate the "minimal intervention"  ethos but Keycloack does not include Webfinger and I can not/do not want to mess with authorization server adding some webserver to serve this file.
An alternative to this link would be nice. An option to manually input the config (just paste webfinger config) or provide a direct link to  `/.well-known/openid-configuration` . Also building links from email is nice but there should be a _custom_ option to be eable to edit it because taking domain from email will not always work because it is common to put authorization servers on their own subdomains `auth.example.com`, also Keycloack has a prefix `realms/realm_name/`, so building URL as strictly as now will not work too.

**Comment by catzkorn** [comment]
Closing this issue - using Keycloak as an identity provider is now supported via [custom OIDC](https://tailscale.com/kb/1240/sso-custom-oidc/)

**Comment by TheGreyDiamond** [comment]
This is technically implemented yes, however, I was unable to get this working in any way. I was able to get it to redirect me to my Keycloak instance. However, a wide variety of errors were produced. A little more documentation would be very helpful.

**Comment by catzkorn** [comment]
Can you provide information on what errors you experienced?

**Comment by TheGreyDiamond** [comment]
The most recent was this one: 
![2023-09-17_22-23-12-a9c8efe6-6e66-4700-96f1-696f65b77103](https://github.com/tailscale/tailscale/assets/32875212/00840ae0-7be0-43c7-ba3e-3fed44fb0a68)

**Comment by catzkorn** [comment]
Thanks - that error is an OIDC prompt error, we have some information about prompts in our documentation under Identity provider setup. 

https://tailscale.com/kb/1240/sso-custom-oidc/#identity-provider-setup

You need to select 'login' as a prompt when going through the sign up flow.

Prompts are unfortunately specific to how your IdP sets up their service, but can also change dependent on the settings they expose to you as a user. It's not possible to document all the combinations that may occur.

I believe your edit is the 'Callback URL' detailed in our docs.

**Comment by TheGreyDiamond** [comment]
Thank you very much. I do feel very stupid now.

**Comment by catzkorn** [comment]
I will work with our tech writing team to add some information around mapping errors back to clear cut things - like `login_required`. I think that would be a good addition. Some are IdP specific so harder for us to document, but this is a great call out.

Did adding the login prompt allow you to complete sign up?

**Comment by TheGreyDiamond** [comment]
Yes, it indeed fixed the issue! Thank you so very much!

**Comment by cdxker** [comment]
I got around the webfinger issues by making a small webserver, see my gist-blog [here](https://gist.github.com/cdxker/160f5cd730fcd6818dbf32c954b5577c#file-1_tailscale_with_keycloak_auth-md)
