### ISSUE TITLE
FR: add shell completions for the tailscale command

### ISSUE THREAD

**Issue by classabbyamp** [tailscale/tailscale#3793]
### What are you trying to do?

When using the `tailscale` CLI, it would be very helpful to have shell tab completion for things like subcommands, nodes, and more to make it easier to use.

### How should we solve this?

The command line argument parsing library that the CLI currently uses does not support the automatic generation of completion definitions:

> Features like tab completion or colorized output are orthogonal to command tree parsing, and should be easy to provide on top of ffcli.

(from https://pkg.go.dev/github.com/peterbourgon/ff/v3/ffcli)

A proper solution should include completions for the most common shells (for example, bash, zsh, and fish) and be generated at build time (so that distro maintainers can add it to packages easily) and maybe with a flag at runtime (so users can add it to their shell configuration manually if the distro does not provide it). Manually-created completions would also be fine, as long as they are kept up-to-date and available at packaging-time.

### What is the impact of not solving this?

there's no current workaround, aside from having a more painful experience using the `tailscale` CLI

**Comment by cmtsij** [comment]
I tried to write one. please give a try:-)
https://gist.github.com/cmtsij/f0d0be209224a7bdd67592695e1427de

**Comment by classabbyamp** [comment]
(personally) I can't try it because I use zsh, not bash

**Comment by SulimanLab** [comment]
> I tried to write one. please give a try:-) https://gist.github.com/cmtsij/f0d0be209224a7bdd67592695e1427de

This should work with zsh 

https://gist.github.com/SulimanLab/28de6b246144ed722e861f1c7c2a8d33

known issue and limitations:

- The solution uses tailscale --help command to get the subcommands and flags, this might be an issue if the tailscale command changes the format of its help output
- Couldn't parse the description for the suggested completions
- The solution only works with zsh shell, if you need it to work with another shell you have to modify the solution accordingly

**Comment by eliezerlp** [comment]
Beyond auto-completion of the `tailscale` commands themselves I would be most interested in tab completion of hosts for various commands that take a host input. The commands `tailscale ssh` and `tailscale ping` specifically come to mind.

**Comment by cmtsij** [comment]
> Beyond auto-completion of the `tailscale` commands themselves I would be most interested in tab completion of hosts for various commands that take a host input. The commands `tailscale ssh` and `tailscale ping` specifically come to mind.

See my gist for tailscale, it support to auto-complete `tailscale ssh` and `tailscale ping` host or ip already.

**Comment by dioput12** [comment]
Is it possible with ```tailscaled``` too?

**Comment by icio** [comment]
Hey all, we've just merged tab-completion for the `tailscale` CLI into main, so it will be available for the next release. It's a first attempt, so I'm going to re-open this issue as a request for feedback on the initial implementation.

I've not set up autocomplete for all flag-values or arguments, so please make your requests here and I'll start to flesh them :)

**Comment by icio** [comment]
After some tinkering with @soniaappasamy:

* If `tailscale switch --list` shows tailnets with an empty string, the output gets a bit funnt
* `tailscale file get --conflict` descriptions have new lines with breaks when --descs is set

**Comment by icio** [comment]
Have you all tried it? 😸 

Take it for a spin and open some tickets if there's anything that's been overlooked or is obviously missing.

**Comment by bartekpacia** [comment]
Automatic installation of shell completions happens when installing [the `tailscale` Formula](https://github.com/Homebrew/homebrew-core/blob/f4861d055bf1593f5d0b1934b4756cb9ed9e8246/Formula/t/tailscale.rb), but does not happen when installing [the `tailscale` Cask](https://github.com/Homebrew/homebrew-cask/blob/1b29896d0d3d366264a4924b41a57d570c3eb405/Casks/t/tailscale.rb). It'd be great if completions were always installed.

I have the Cask version installed. I ran `tailscale completion zsh > /opt/homebrew/share/zsh/site-functions/_tailscale` and then restarted Zsh (`exec zsh`) and completions work fine. Thanks a ton for all the work:)

**Comment by Sargates** [comment]
For anyone working in WSL with Tailscale installed on the host:

- You can reference the `tailscale.exe` binary directly from your shell inside WSL.
- You can find the path for `tailscale.exe` using the `which` command (i.e. `which tailscale.exe`), but make sure the path returned is valid. On my machine it returned `/mnt/c/Program Files/Tailscale//tailscale.exe` which is an improper path because of the `//`. I don't know why it did this.
1. You can run `tailscale.exe completion ${SHELL:t}` to output the tab-completion script for your current shell. Then, you can redirect that output to a new file `_tailscale` in any directory contained in the `$FPATH` variable.
2. Then make a symlink called `tailscale` anywhere on your `$PATH`, (I chose `/usr/local/bin` but you can choose anything) and link that to the location of `tailscale.exe`.

Full commands look like this:
```zsh
# Make sure the location of `_tailscale` is located on your `$FPATH` variable
tailscale.exe completion zsh > /usr/share/zsh/vendor-completions/_tailscale
sudo ln -s "/mnt/c/Program Files/Tailscale/tailscale.exe" /usr/local/bin/tailscale
```
Then you can use `tailscale up` or `tailscale down` with tab-completion.
![image](https://github.com/user-attachments/assets/f59456fb-5362-4767-8fb7-1d78da7e89fa)
