### ISSUE TITLE
FR: Android - Exclude Application (Android Auto Broken)

### ISSUE THREAD

**Issue by cwilliams5** [tailscale/tailscale#3828]
### What are you trying to do?

Tailscale breaks wireless Android Auto. 

This is common in android VPN apps. 

### How should we solve this?

The common solution for this in most VPN apps (see various commercial VPNs such as Nord, or lots of ad blockers like Blokada or Netguard) is to allow certain android apps to be excluded from the VPN and passed through directly. By setting the "Android Auto" app to this, it begins working. 

Pros: There may be other valid use cases for this, such as bypassing an exit node with heavy video streaming apps. 

Cons: There may be security reasons to not allow your end users to bypass the VPN with certain apps. Perhaps this is a global opt in toggle, or otherwise centrally managed with ACLs or something. 

### What is the impact of not solving this?

I can't get certain users to keep Tailscale on. Having to turn it on and off every time you get in a car is basically a non starter.

**Comment by bradfitz** [comment]
This isn't something you can do at the OS-level, I suppose? Does each VPN typically build its own UIs to configure this?

**Comment by cwilliams5** [comment]
> This isn't something you can do at the OS-level, I suppose? Does each VPN typically build its own UIs to configure this?

Not that I'm aware of, no, that would be too useful. Yes, its built into the application. Most recently I used it in Blokada. You go into the options and it lists all installed apps and you can select ones to bypass. Search by name huge quality of life thing there. So they show two tabs, bypassed apps (so you can remove the bypass), and all others (so you can add a bypass).

If I can provide more details or collect example screenshots or something, let me know.

**Comment by DentonGentry** [comment]
There are various addAllowedApplication and allowBypass APIs on https://developer.android.com/reference/android/net/VpnService.Builder, one can see how such a thing could be constructed.

That may also be the solution for https://github.com/tailscale/tailscale/issues/3460

**Comment by msfjarvis** [comment]
> There are various addAllowedApplication and allowBypass APIs on [developer.android.com/reference/android/net/VpnService.Builder](https://developer.android.com/reference/android/net/VpnService.Builder), one can see how such a thing could be constructed.
> 
> That may also be the solution for #3460

You're looking at the right things, FWIW [this is also how we do it](https://github.com/WireGuard/wireguard-android/blob/7002367e4faf4f794abbe329826f8a03bb85732a/tunnel/src/main/java/com/wireguard/android/backend/GoBackend.java#L265-L269).

The UI we've built in WireGuard supports both blocklist and allowlist -style selections, so you can go from "Allow everything but <foo> through tunnel" to "Exclude everything except <foo> from tunnel". [This is the commit](https://github.com/WireGuard/wireguard-android/commit/7db0fa915ef909ad33b9b29754e1fd1e7ed260a9#diff-ab90ea3d38aa0c7fac4b9d8d2184ff3d04757365f020028b8d0255c529d04b69) where we implemented the support for toggling between each style.

**Comment by ignoramous** [comment]
> allowBypass APIs 

`allowBypass` will break VPN lockdown mode (aka no egress other than via tun-fd): https://github.com/celzero/rethink-app/issues/92 Besides, apps must bind to specific network interfaces to be able to bypass the VPN that lets apps bypass (not many, except the ones trying to negotiate NAT do, according to: https://github.com/Jigsaw-Code/Intra/issues/18).

> Does each VPN typically build its own UIs to configure this?

Pretty much yes, every app has to implement this screen, which isn't as straight-forward as it first seems.

> [This is the commit](https://github.com/WireGuard/wireguard-android/commit/7db0fa915ef909ad33b9b29754e1fd1e7ed260a9#diff-ab90ea3d38aa0c7fac4b9d8d2184ff3d04757365f020028b8d0255c529d04b69) where we implemented the support for toggling between each style. Might be of interest to Tailscale 🤷🏼

It only handles apps with `ACTION_MAIN` + `CATEGORY_LAUNCHER` defined (aka most installed apps). System apps, system components, system `uid`s etc need to be handled if one wants to cover all their bases ([we impl this mostly by trial-and-error](https://github.com/celzero/rethink-app/blob/161674b1cdbdd72fefee5edd953179a637e00f6f/app/src/main/java/com/celzero/bravedns/service/IPTracker.kt#L92) but even it isn't all encompassing).

----

I believe, tailscale already has the concept of network namespaces implemented (even on Android?). If so, depending on [who owns the connection](https://developer.android.google.cn/reference/kotlin/android/net/ConnectivityManager#getconnectionowneruid), tailscale can send it over one network (underlying-network) instead of the other (tailscale)?

**Comment by msfjarvis** [comment]
> This only handles apps with ACTION_MAIN + CATEGORY_LAUNCHER defined in their manifest (ie most installed apps). System apps, system components, system uids etc need to be handled if one wants to cover all their bases (we impl this mostly by trial-and-error but even it isn't all encompassing).

We [replaced that](https://github.com/WireGuard/wireguard-android/commit/4fae2d125577e17a457c26d66398ab6a498733b4#diff-ab90ea3d38aa0c7fac4b9d8d2184ff3d04757365f020028b8d0255c529d04b69) down the line by fetching all apps with the internet permission and that's kept users happy so far.

**Comment by Pepeanuts** [comment]
There is an ETA for this FR?

**Comment by DentonGentry** [comment]
I promise we will comment on the issue when there is status to report. We'll address Android Auto support, but we are not simultaneously working on every feature request ever opened.

**Comment by harrykantas** [comment]
One quick workaround for this could be to expose turning on/off or even toggling tailscale as an [app action](https://developers.google.com/assistant/app/overview) .

That way, one could make use of automation/routine apps like Tasker, Bixby Routines, AutomateIt etc, to setup a rule like "If app X is started, then turn off Tailscale", then revert that action on app X exiting.

Here's an example app action from a VPN app.
![Screenshot_20220526-085744_One UI Home](https://user-images.githubusercontent.com/4271471/170445014-7e982904-272a-4875-b4c5-7e4fd7432458.png)

**Comment by tuxflo** [comment]
This is the way I'm currently dealing with WireGuard and Android Auto. I'm running Automate which detects if my phone is connected to the car via Bluetooth. If the bluetooth MAC matches a "SET_TUNNEL_DOWN" broadcast is sent, otherwise (disconnect) a "SET_TUNNEL_UP" broadcast will take care of the reconnect. Still kind of sad that one has to deal with such hacky ways to get Android Auto working with a VPN, as far as I know should AAuto work flawlessly even with a VPN if split tunneling is done right.

**Comment by comfuture** [comment]
Is there an update?

The Samsung Pay app also does not work when connected to a VPN.
Also, services that restrict GPS geolocation and Geo IP-based location will often refuse to run with a VPN running.
Google One VPN on Android, which is free for Google Storage purchasers, allows you to set certain apps to bypass the VPN.
You can use these apps without interference, even if you keep the VPN on all the time.

I would like to see Tailscale's Android app include a "VPN bypass feature".

**Comment by probablypablito** [comment]
I second this! WireGuard itself lets you exclude applications individually as well.

**Comment by Zocker1999NET** [comment]
as it was not mentioned clearly before, and I just found the other issues myself: #6912 (duplicated by #11208) seems now to be the canonical issue for a user-selectable app exclusion.
