### ISSUE TITLE
FR: Multiple services on a single host using separate IPs, SNI proxy, or other

### ISSUE THREAD

**Issue by stefangrosaru** [tailscale/tailscale#3847]
### What are you trying to do?

I'm trying to access multiple services on the same machine over http. This machine runs traefik as a reverse proxy which exposes multiple web services over HTTP (port 80). 

### How should we solve this?

It would be useful if the MagicDNS entries could extend and cover all subdomains on a machine.

Example, I have a linux host called server, which exposes two services called service1 and service2, a reverse proxy sits in front of these services and forwards HTTP requests based on hostname so that service1.server goes to service1 and service2.server goes to server2.

### What is the impact of not solving this?

The only workaround at the moment is to use different ports for these services and this makes it difficult to work with reverse proxies. Also remembering subdomains is easier than remembering specific port numbers.

**Comment by DentonGentry** [comment]
To set expectations: we're more likely to allow multiple certificates to be issues for a node, and allow different services to be muxed based on SNI.

**Comment by AlexPygin** [comment]
Is this expected to be completed soon? Today, I realized how challenging it is to do basically the same thing called out in the original issue.

I want subdomains so 1Password will suggest a single login per port/subdomain, I can generate a cert so I don't always see "Not Secure", and so I can reverse proxy my http services.

**Comment by DentonGentry** [comment]
I promise that we will update the bug when work begins in earnest. This is not currently at the top of the list to work on.

**Comment by mholt** [comment]
Hi there, we have Caddy users asking for this feature as well: https://caddy.community/t/reverse-proxy-and-https-for-multiple-services-over-tailscale/16287

Basically they're running multiple services on a single host and would like to use subdomains to address them.

I also would like to personally +100 the usecase of 1Password so that it can more easily distinguish which service is being accessed.

I realize from #1196 that you want to reserve the next subdomain label in case it's needed for future features, but in that case could I suggest a single subdomain label for custom subdomains, and then yet another label for the actual subdomains, e.g. `service.svc.host.random.ts.net`?

That's a bit long of course, but at least it's organized. :man_shrugging:  Just an idea.

**Comment by 06kellyjac** [comment]
I've also been running into this with tailscale magicdns + https. It's surprising how many programs/services dont support subpaths e.g. `host.random.ts.net/subpath`

**Comment by riekusr** [comment]
having this issue now as well.

**Comment by Joshuapwilley** [comment]
Also having this issue. Just chiming in so hopefully this issue gets bumped closer to the top of the list.

**Comment by DentonGentry** [comment]
A common solution for this need which is available now is tsnet:
- https://tailscale.com/blog/tsnet-virtual-private-services/
- https://pkg.go.dev/tailscale.com/tsnet

Another common pattern is to use tailscaled --tun=userspace-networking and write the app to use SOCKS5: https://tailscale.com/kb/1112/userspace-networking/

Supporting multiple IP addresses is tracked in https://github.com/tailscale/tailscale/issues/465

**Comment by DentonGentry** [comment]
I think the remaining part of this issue, allowing separate IPs for an interface, is tracked in https://github.com/tailscale/tailscale/issues/465

Dup of https://github.com/tailscale/tailscale/issues/465
