### ISSUE TITLE
FR: Allow creating tags from the modal on https://login.tailscale.com/admin/settings/keys

### ISSUE THREAD

**Issue by voltagex** [tailscale/tailscale#3855]
### What are you trying to do?

![image](https://user-images.githubusercontent.com/83080728/151907157-f019d057-95af-4dfd-9390-d45b49a1c4c4.png)

When I try to create a key, I can't assign any tags to the key because none exist yet.

### How should we solve this?

Add a "new tag" option in the dialog shown above

### What is the impact of not solving this?

Very low impact, I just need to go create some tags first

### Anything else?

It looks like the only way to create tags at all is via JSON? https://tailscale.com/kb/1068/acl-tags/

**Comment by DentonGentry** [comment]
A primary concern with Tags is that a small typo not be the cause of a security incident. The way we tell that a Tag is valid is whether it has a TagOwner defined. Tags without a defined owner will be rejected.

So while it might still be possible to do as is requested here, it would both be:
1) somewhat more complex because an Owner would have to be defined as well, and
2) need to be confident that we're not creating a footgun where you can define a tag on the fly when the actual user intention was to use an existing tag spelled slightly differently.

**Comment by voltagex** [comment]
@DentonGentry ah, I should have added that this is just for a home network where I'm the only user. Wouldn't it work to add the owner as the person creating the tag at first? If it's new, it's not assigned to any machines yet.

**Comment by DentonGentry** [comment]
I do not expect to implement this FR, the main benefit of Tags in dissociating access control and node ownership from the individual who created the node is felt in larger tailnets with multiple users.
