### ISSUE TITLE
"reject" not allowed in ACL but mentioned in "How tailscale works"

### ISSUE THREAD

**Issue by FlorianLoch** [tailscale/tailscale#3879]
### What is the issue?

Tried to set an ACL blocking devices carrying a given tag.

```
  "acls": [
    // Match absolutely everything. Comment out this section if you want
    // to define specific ACL restrictions.
    { "action": "accept", "users": ["*"], "ports": ["*:*"] },
    { "action": "reject", "users": ["tag:server"], "ports": ["*:*"] },
  ],
  "tagOwners": {
    "tag:server": ["<some mail address>"]
  }
```

All I get is `Error: action="reject" is not supported`. But I took that from fig. 8 in https://tailscale.com/blog/how-tailscale-works/.

Reading https://tailscale.com/kb/1018/acls/ it becomes obvious that this action does not exist. I guess, the article should then be adjusted because it gives a wrong impression on how ACLs work with tailscale. At least it confused me.

```
Tailscale access rules are “default deny”, so the only possible action is accept, to allow traffic that would otherwise be denied.
```

### Steps to reproduce

Try to save the given ACL

### Are there any recent changes that introduced the issue?

N.A.

### OS

Other

### OS version

N.A.

### Tailscale version

N.A.

### Bug report

N.A.

**Comment by DentonGentry** [comment]
As you say, there is not a reject action in the ACL syntax. To add an explanation of why: the final compiled ACLs sent to Tailscale nodes for enforcement are combined from several sources:
- the ACL JSON
- whether a [node has set ShieldsUp](https://tailscale.com/kb/1072/incoming-connections/)
- when a [node is shared](https://tailscale.com/kb/1084/sharing/) from another tailnet

Without any notion of "reject" in the ACL syntax, all of these sources can just be combined and compiled into a set of rules. The presence of a "reject" rule in the ACL syntax makes the outcome be order dependent and constrains how more sources could be added in the future. There is no plan to add a reject action to the ACL syntax.

The low level implementation of the compiled ACLs is allowed to have a notion of reject. It also makes it easier to describe behavior at a high level, which is why the blog post uses it.

**Comment by FlorianLoch** [comment]
Thanks for the explanation, makes perfect sense to me! 👍 
Though, wouldn't it be nice to have the blog post mention that this is a simplification for demonstration purposes linking to the ACL article? I guess that would have made me grasp it straight away, not bugging you with an issue on Github ;) 

Additionally, having an "action" field suggest that there is more than one possible value for it and "reject" seemed plausible to me in the first place. :)
