### ISSUE TITLE
DNS stopped working

### ISSUE THREAD

**Issue by frioux** [tailscale/tailscale#3883]
### What is the issue?

I couldn't use MagicDNS for some reason until I restarted tailscale

### OS

Linux

### OS version

Ubuntu 20.04

### Tailscale version

1.20.2

### Bug report

BUG-5286a105daf3d974b6241f786c0fd2ca69341f9da4966d5454cbafc2ff8280c8-20220206200304Z-4ba59fa5930d69c4

**Comment by DentonGentry** [comment]
The main thing I notice is that its node key had expired.
It looks like it just got another one, perhaps by authenticating again.

**Comment by frioux** [comment]
Hmmm. I literally changed this from one tailnet to another yesterday, so I’m surprised that would have already happened?

— 
fREW Schmidt
https://blog.afoolishmanifesto.com

**Comment by DentonGentry** [comment]
The node key having expired is probably due to the logout.
login to the new tailnet would allocate a different node key.

**Comment by drees** [comment]
I had this same issue the other day - my key expired and thus tailscale went down, but because I was using MagicDNS, all DNS requests started failing as well causing issues bigger than just losing connectivity to tailscale

If tailscale goes down because the key expired, or has failed to connect for some reason, it really should revert back to default DNS settings (same as if you had issued a tailscale down command).

Also, there really should be some sort of notification mechanism if a host is trying to connect with an expired key.

**Comment by DentonGentry** [comment]
I don't think there is more to followup on
