### ISSUE TITLE
Why was my issue deleted?

### ISSUE THREAD

**Issue by MatthewCroughan** [tailscale/tailscale#3891]
### What is the issue?

I created a bug report that would have been helpful to share with people. But I have discovered that it was deleted by administrative action in this repo.

### Steps to reproduce

1. Try to access issue number 2712 in this repo
    https://giters.com/tailscale/tailscale/issues/2712
2. Find that it is no longer available, as it has been deleted 
    ```
    user: matthew ~ 
    ❯ curl --silent https://github.com/tailscale/tailscale/issues/2712 | grep deleted
        <h2 data-view-component="true" class="h2 mb-1">      This issue has been deleted.
    ```

### Are there any recent changes that introduced the issue?

N/A

### OS

Linux

### OS version

NixOS

### Tailscale version

N/A

**Comment by DentonGentry** [comment]
We had mistakenly put PII in the comments on the issue. This was a mistake, but I couldn't find a way to delete just the problematic comments. So I deleted the issue, it looked like the main point of the issue had been resolved.

**Comment by MatthewCroughan** [comment]
I don't see any PII in the comments on the issue. Unless you're referring to the fact that Tailscale is able to view my network, IP addresses, device names, etc, purely by knowing nothing more than my username. I found that concerning. Is this supposed to be PII? Is this not publicly acknowledged and accepted by Tailscale? 

All of the information in the issue about my network, I believe is not private information. By PII are you referring to some other information? Or was this purely to protect me?

**Comment by bradfitz** [comment]
It's not a secret that we can look up network details. That's how we do support.

I don't know what PII @DentonGentry is talking about, but yes, I assume it was to protect you and not share any of your information publicly.

**Comment by DentonGentry** [comment]
Since that bug was filed, we've added the ability to generate a bug report from the product. We've added a bug template which encourages adding a bug report string when filing an issue, and using the bug report strings avoids pasting IP addresses into bugs. That prior issue is one of the things which prompted adding the template asking for a bugreport.

The 100.x.y.z addresses from tailscale itself isn't especially problematic, but the product does know the public IP addresses which nodes use to connect and those are problematic to paste. We're trying to rely on the bug report strings in public issues, and not have IP addresses in bugs.
