### ISSUE TITLE
iptables extended match modules cause early termination

### ISSUE THREAD

**Issue by rishid** [tailscale/tailscale#403]
**Describe the bug**
Running tailscale v0.98 on NAS machine that has geoip iptable rule, this is causing tailscaled to exit since it does not recognize the 'geoip' module

`2020/05/25 11:59:25 wgengine.New: listing iptables chains: running [/sbin/iptables -t filter -S --wait]: exit status 1: Can't find library for match `geoip'`

**To Reproduce**
Install an iptable rule with geoip match attribute
`-A INPUT_FIREWALL -m geoip --source-country CN  -j DROP`

**Expected behavior**
Not exit daemon

**Version information:**
 - Device: NAS
 - OS: Linux 3.10
 - Tailscale version: 0.98.0

**Comment by apenwarr** [comment]
I haven't reviewed the code lately but it seems unnecessarily
intrusive to be listing all the rules in the entire table. We should
never, ever be attempting to parse iptables output because it's filled
with gunk.

If we just want to check whether eg. a FORWARD chain exists matching
our tailscale table, something like this should be enough:

    iptables -t filter -C FORWARD -j ts-forward

On Mon, May 25, 2020 at 8:08 AM Rishi Dhupar <notifications@github.com> wrote:
>
> Describe the bug
> Running tailscale v0.98 on NAS machine that has geoip iptable rule, this is causing tailscaled to exit since it does not recognize the 'geoip' module
>
> 2020/05/25 11:59:25 wgengine.New: listing iptables chains: running [/sbin/iptables -t filter -S --wait]: exit status 1: Can't find library for match geoip'`
>
> To Reproduce
> Install an iptable rule with geoip match attribute
> -A INPUT_FIREWALL -m geoip --source-country CN -j DROP
>
> Expected behavior
> Not exit daemon
>
> Version information:
>
> Device: NAS
> OS: Linux 3.10
> Tailscale version: 0.98.0
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Avery Pennarun // CEO @ Tailscale
