### ISSUE TITLE
tailscale/cmd/derper -http-port not works

### ISSUE THREAD

**Issue by Dark-Existed** [tailscale/tailscale#4034]
### What is the issue?

```console
/home/ubuntu/go/bin/derper -http-port -1 -c /home/ubuntu/derper/derper.conf -hostname=hostname.com -verify-clients -certmode manual -certdir /home/ubuntu/derper/cert
```
I use this command to start derper. But I can still access https://hostname.com
if I set `-http-port 81`, it can`t access https://hostname.com:81, but still can access https://hostname.com 

### OS

Linux

### OS version

Ubuntu 20.04

**Comment by DentonGentry** [comment]
`-http-port` is the unencrypted HTTP. Setting `-http-port` to -1 means that http://hostname.com will not work.

https://hostname.com is HTTPS, which uses port 443. https://hostname.com will still work even if `-http-port` is set to -1.

If you set `-http-port` to 81 then http://hostname.com:81 should work.  https://hostname.com:81 will not, because it won't be able to establish an encrypted HTTPS session.

**Comment by Dark-Existed** [comment]
oh, thanks. But is there any way to disable the web.

**Comment by DentonGentry** [comment]
You can disable unencrypted HTTP using `-http-port -1`

If you want to make it use a custom port for HTTPS instead of port 443, you can do so by setting `[DERPNode.DERPPort](https://pkg.go.dev/tailscale.com/tailcfg#DERPNode.DERPPort)`
as described in https://tailscale.com/kb/1118/custom-derp-servers/

If you're asking how to disable encrypted HTTPS altogether: the entire point of derper is to carry Wireguard frames through HTTPS connections.

**Comment by Dark-Existed** [comment]
ok~
