### ISSUE TITLE
FR: Add attribute to disable key expiry on auth key

### ISSUE THREAD

**Issue by danielcompton** [tailscale/tailscale#4109]
### What are you trying to do?

We're running Tailscale in ECS Fargate. We use an ephemeral, reusable key for auth. ECS will boot new containers when we update the image or if the old container fails. If we run our container for more than the key expiry dates then it will expire. 

We can manually disable key expiration in the UI, but we don't want to have to remember to do this every time Fargate boots new containers.

### How should we solve this?

Ideally we'd be able to set an attribute on the key to disable expiry for any devices that use the key.

### What is the impact of not solving this?

We'll need to remember to disable key expiry or to re-deploy the containers before auth expires.

I guess I could also write a Lambda to disable key expiry for the instances with the [API](https://github.com/tailscale/tailscale/blob/main/api.md#post-apiv2devicedeviceidkey---update-device-key), but that is a bit of a pain.

**Comment by DentonGentry** [comment]
[ACL Tags](https://tailscale.com/blog/acl-tags-ga/) are a way to control access to a device based on a Tag instead of based on the User who created it.

If the nodes being created have ACL Tags assigned in the authkey, the default is now to disable key expiry for tagged nodes. https://tailscale.com/blog/tagged-key-expiry/
If you can use tags for the ECS nodes, I think this would accomplish the goal.

**Comment by danielcompton** [comment]
Yep, this works perfectly!
