### ISSUE TITLE
Windows GUI fails to start on login (Shell_NotifyIcon)

### ISSUE THREAD

**Issue by mplough-kobold** [tailscale/tailscale#4133]
### What is the issue?

I'm providing Tailscale support for my team.  One of my team members reported that his system updated last night and when he started work this morning, this message awaited him with Tailscale gone from the system tray.

![image](https://user-images.githubusercontent.com/69480843/157688195-ff3d224a-205b-4056-8b9e-cd4ded01d375.png)

This looks a lot like https://github.com/tailscale/tailscale/issues/3409 and https://github.com/tailscale/tailscale/issues/1073, except he's running Tailscale 1.22.0.

Looks like an upstream fix (as mentioned at https://github.com/tailscale/tailscale/issues/1073#issuecomment-956926199) isn't going to be realistic.  https://github.com/lxn/win/pull/123 has been sitting open since November 2021 and lxn hasn't had a commit since February 2021.  A fork might be necessary.

### Steps to reproduce

Use Windows normally and let it run updates overnight.

### OS

Windows

### OS version

10 Professional

### Tailscale version

1.22.0

**Comment by DentonGentry** [comment]
Was it running 1.20.4 before? 1.22.0 was released 11 days ago, I'm not sure what update would have been applied last night.

**Comment by mplough-kobold** [comment]
As it's not my machine and the user is not a software developer, my answers aren't going to be as solid as they would be if I were troubleshooting my own machine -- sorry about that.  The user installed Tailscale for the first time yesterday so I think 1.22.0 was installed from the start.  I believe it was Windows updates that got installed rather than a Tailscale update.

**Comment by dblohm7** [comment]
I've committed a change that gives us better error information when this happens again.

**Comment by DentonGentry** [comment]
The improved error information when this problem happens is in the 1.28 release.

**Comment by AThilenius** [comment]
I'm running into this as well, on version 1.32.2 It happens somewhere around 1/2 the time.

![image](https://user-images.githubusercontent.com/3269553/199773598-64ca7596-24a0-41ad-8de0-146b1e70db78.png)

![image](https://user-images.githubusercontent.com/3269553/199773502-74cd9d1d-c038-45df-9985-d12d00580f18.png)

**Comment by dblohm7** [comment]
I couldn't understand why my changes were not producing better error codes until I looked more closely at `lxn/win`'s implementation of its `Shell_NotifyIcon` wrapper (having substantially more Go experience than last time also helps me here). I think that entire package is riddled with error-handling bugs. Instead of its syscall wrappers obtaining the Win32 "last error" directly from `syscall`, they do this pattern where `GetLastError` is explicitly called later in the code by `walk`, as if we were writing C code.

Even though this invocation is happening on a goroutine locked to the OS thread, I think there is a pretty good chance that other stuff may go on in the runtime that inadvertently clears the OS thread's last error before `walk` is able to check it.

That entire `win` package needs a sanitization blitz to clean that up, but for the purposes of this issue I'll fix the most important part so that the error handling actually works for the `Shell_NotifyIcon` case.

**Comment by dblohm7** [comment]
In addition to the error handling improvements I landed in `walk`, I suspect that part of this is was due to stuff running on a background goroutine that should have been running on the (locked) main goroutine. A lot of that was fixed in 1.34, so we'll have to wait and see whether this issue remains.

**Comment by gimpf** [comment]
One tiny data-point: I had this issue on two servers, and after the upgrade to 1.34.1 it worked. But I didn't try too hard.

**Comment by DentonGentry** [comment]
At this point I'm going to assume that 1.34 resolved this issue and close it. Reopen if it is still seen, but if any symptoms are different please open a new bug instead.

**Comment by szuro** [comment]
Here we go:

```
> tailscale version
1.60.0
  tailscale commit: b36943c9b3cfc9f917b202025bfde002b076fc87
  other commit: 99e84774ba7d892c022e79a304b5a365a106ff69
  go version: go1.22.0
```

![obraz](https://github.com/tailscale/tailscale/assets/24614981/b8781474-bb8b-4593-a9e3-2498224f2098)

**Comment by szuro** [comment]
Issue still persists
```
> tailscale.exe version
1.62.0
  tailscale commit: df4d4ebd41b6670c8ca371e5e32ea29e00e69708
  other commit: d0454003c8cf8ef88763d53716cb0bb6728222f6
  go version: go1.22.1
```
