### ISSUE TITLE
Support winget release channel officially

### ISSUE THREAD

**Issue by cwilliams5** [tailscale/tailscale#4174]
### What is the issue?

Minor issue...but I use winget for easy management, and we've missed the last 2 tailscale versions. Don't forget us xD

![image](https://user-images.githubusercontent.com/10100743/158312524-54bf40a9-17c7-490b-8b9e-a49109b72ba1.png)

### Steps to reproduce

winget upgrade tailscale
winget list --name tailscale
note package is 3 releases behind

### OS

Windows

### OS version

Win 11

### Tailscale version

irrelevant

**Comment by DentonGentry** [comment]
Tailscale does not distribute a package via winget.

Is this the one? Says 1.18.2. https://winget.run/pkg/tailscale/tailscale
Or this one? Looks like 1.20.4. https://github.com/microsoft/winget-pkgs/tree/afd1f813d3def5f9aca4deb4d32defb92456b1c6/manifests/t/tailscale/tailscale

**Comment by cwilliams5** [comment]
> Tailscale does not distribute a package via winget.

Well, lesson learned for me there then. I had assumed they were doing verification of some sort and packages were official. Go ahead and close this ticket if you want and I'll switch to an official release channel. I suppose perhaps you find value in maintaining this officially so no one else gets tricked and there is an easy package managed version, but hey I get attention must go lots of places. 

> Or this one? Looks like 1.20.4. https://github.com/microsoft/winget-pkgs/tree/afd1f813d3def5f9aca4deb4d32defb92456b1c6/manifests/t/tailscale/tailscale

That's the one I had picked, yes.

**Comment by bradfitz** [comment]
It's at least downloading our official binaries. That's just a metadata repository, like https://chocolatey.org/ is.

We've been meaning to automate our Chocolatey metadata updates (that's #303) and I suppose we should do the same here. They'd probably use very similar mechanisms (send/submit PRs).

/cc @maisem @dblohm7

**Comment by ItzLevvie** [comment]
> @cwilliams5: we've missed the last 2 tailscale versions. Don't forget us xD

One of the main reasons why that package is behind several versions is because the community has made more than 1000+ PRs in a single day which has hit various rate limits and broke Azure Pipelines for the winget-pkgs repository for a few days.

> @cwilliams5: Well, lesson learned for me there then.

It's all good as long as the application is being downloaded from official sources which is what's happening here.

What I mean by "official sources" is the Download URL that comes straight from the publisher despite the WinGet package being community-maintained.

> @bradfitz: It's at least downloading our official binaries.
> @cwilliams5: I suppose perhaps you find value in maintaining this officially so no one else gets tricked

Microsoft is working on the "verified publisher" feature which will allow publishers to takeover their packages; therefore preventing anyone from making any modifications to it.

Despite the package being community-maintained, it doesn't pose as a security risk as WinGet only accepts official URLs from ISVs rather than people uploading malicious installers and tricking people.

> @bradfitz: I suppose we should do the same here. They'd probably use very similar mechanisms (send/submit PRs).
> @cwilliams5: there is an easy package managed version

For the Windows Package Manager (WinGet) you can use https://github.com/microsoft/winget-create as part of your CI/CD Pipelines.

**Comment by gnpaone** [comment]
Well, I can create a PR here so that this repository (ie completely maintained by this repo owners) will submit packages on new release

**Comment by gnpaone** [comment]
> Well, I can create a PR here so that this repository (ie completely maintained by this repo owners) will submit packages on new release

Hey check this out https://github.com/tailscale/tailscale/pull/4350

**Comment by dblohm7** [comment]
Closing as dup in favour of https://github.com/tailscale/tailscale/issues/2257
