### ISSUE TITLE
SSO Login button colors

### ISSUE THREAD

**Issue by JayDoubleu** [tailscale/tailscale#419]
**Is your feature request related to a problem? Please describe.**

SSO login page is driving me crazy.
I noticed it straight away some time ago however it only become aggravating when having to run multiple logons for testing purposes.

The problem is that Google sign in is blue and Microsoft Login page is red !
When I am trying to log in with google I am intuitively clicking on red button.
If I want to log in with Microsoft I am intuitively trying to click the blue button.

Google to me has always been associated with red colour and Microsoft with blue.

**Describe the solution you'd like**

Just please swap the colours.
![SSO](https://www.okta.com/sites/default/files/styles/product_content_image_large/public/Okta_Customer-Identity_Authentication_Social.png)

**Comment by rosszurowski** [comment]
Huh! As primarily a Google user, I've always associated Google with blue and Microsoft with the reddish-orange we use (perhaps [because of Office365](https://www.office.com/)?). And I thought that was the case more widely too — so I appreciate you breaking me out of my bubble :)

I've surveyed a number of sites, and while it's a bit of a mixed bag for colors. Out of ~30 sites surveyed:

* Google as predominantly blue: 3
* Google as predominantly orange: 3
* Microsoft as predominantly blue: 1
* Microsoft as predominantly orange: 0

The most common pattern across the board is white buttons with logos, like Medium's implementation:

<img src="https://user-images.githubusercontent.com/303731/83180073-e141c300-a0f0-11ea-82ae-17180ab09095.png" width="400" />

I'm not a fan of the increased cognitive effort to read the text / logos. But in the interest of avoiding frustrations like this, I'll update our login page to follow this white-with-logos style.

**Comment by JayDoubleu** [comment]
Beautiful. Looking forward to it :)

**Comment by rosszurowski** [comment]
@JayDoubleu just made the update: https://login.tailscale.com

Thanks for reporting!

**Comment by JayDoubleu** [comment]
Perfect ! Thank you sir.
