### ISSUE TITLE
Application-defined capabilities

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#4217]
Currently, the Tailscale ACL system lets you grant access to IP protocols (TCP, UDP, etc) and ports (80, 443, 22, etc).

Those can be viewed as as a capability grant: the admin grants the capability for a node X to do "tcp/443" on node Y.

But that's only a network-level capability. We can say that you have TCP/3306 access, but there's no support for saying, "You have read-only access to the database" vs "You have read/write access to the database."

In Tailscale 1.6 or so started adding support for the "WhoIs" handler and the localapi for application to ask, "Who is the remote node connecting to me?"

That lets you write Tailscale authentication proxies that speak Tailscale in the front (Tailscale crypto, Tailscale authentication) and then map it to another system on the backend, filling in the authentication as desired. But if that backend system requires some lazy user provisioning or access control (authz, not authn), there's no way from the Tailscale ACL config to grant certain users/groups access to higher-level application capabilities ("mysql.com/rw", "mysql.com/ro"), etc.

@maisem and I propose extending the Tailscale ACL syntax to permit arbitrary capabilities where we currently accept ports.

That is "80", "udp/443", and "tcp/8000-8999" are capabilities today. But they're capabilities for the network.

We propose that you be able to write:

```
{
    "src": ["group:all"],
    "dst": ["mon:tcp/80,443"],
},
{
    "src": ["group:eng"],
    "dst": ["mon:cap/grafana.com/rw"],
}
```

A capability is an arbitrary string (`"grafana.com/rw"`) that is granted between a pair of nodes, identified by IPs.  (or in this case, `"mon"` being a Host alias to a Tailscale IP)

Then, the `WhoIs` lookup response is extended to include the capabilities that the remote user has:

```patch
diff --git a/client/tailscale/apitype/apitype.go b/client/tailscale/apitype/apitype.go
index cae573a4..c5d10dff 100644
--- a/client/tailscale/apitype/apitype.go
+++ b/client/tailscale/apitype/apitype.go
@@ -11,6 +11,9 @@
 type WhoIsResponse struct {
        Node        *tailcfg.Node
        UserProfile *tailcfg.UserProfile
+
+       // Caps are extra capabilities that the remote Node has to this node.
+       Caps []string `json:",omitempty"`
 }
```

Implementation linked below, which might answer further questions.

/cc @maisem @nickoneill @crawshaw @mayakacz @Xe

**Comment by danderson** [comment]
+1 on the general principle, being able to stop worrying about both authentication and authorization would simplify a variety of headaches, for us and others.

I'm not a fan of the proposed syntax, it's adding more grammatical noise to an already pretty noisy statement (where do I use `:`? `/`? In which order?).

We should also define a convention for namespacing of capabilities now, ahead of time. Otherwise, we'll find ourselves in a position where neither we nor other vendors can ever ship capability-using software, because there's no way to be sure that the capability names we picked didn't get used for other purposes already. This can be something as simple as a convention like "use vendorname/capname when shipping software, and capabilities with no / in them are reserved for private use by tailnet owners". So for your own internal software you can use short names like "flarb-rw", whereas we'd use e.g. "tailscale/taildrop", "tailscale/ssh", ...

**Comment by danderson** [comment]
More syntax complaints: how do I grant a capability only when accessing a specific service, rather than machine-wide? If I have two different database proxies on a single machine (as we do), I need to be able to grant different rights per-port, or per-abstract-service somehow.

In my mind's eye, the UX for this on the developer side was that WhoIs takes in an application-id, and ACLs are expressed in terms of that, rather than destination machine. e.g.

```
{
    "src": ["group:eng"],
    "dst": ["app:my-thing:rw"],
}
```

Then if you `WhoIs(srcIP, "my-thing")`, you get back a `Caps=["rw"]`, rather than have to sort through a bajillion caps that aren't relevant to you.

I guess stepping back, my request is to slow down slightly and figure out what the right set of semantics are. I'm certain what you proposed initially won't work for some of our needs, and I'm pretty sure my counteroffer also sucks, and I don't want to be locked into either of them because we thought through those things after shipping.

**Comment by bradfitz** [comment]
The syntax is meant to actually simplify things, as we're going to subsume the `ACLRow.Proto` thing that's awkward right now. Right now a port "80" means "UDP 80 or TCP port 80" and you have to go in and specify which protocol you meant over on the side, but we should've done it next to the port ("tcp/80", "udp/443").

The docs are currently:

```
// The "ip" part of each "ip:port" can be of the form:
//   * a literal IP (1.2.3.4)
//   * a literal IP + CIDR (1.2.0.0/16)
//   * a hostname alias ("host1")
//   * a hostname/CIDR ("host1/16")
//   * "tag:foo" (for any node running as that tag)
//   * "autogroup:internet" to access "the internet" (see func theInternet)
//   * "autogroup:self" to access nodes owned by the same user
//   * "autogroup:members" to access nodes owned by users
// The "port" part of each "ip:port" can be:
//   * a single port (22)
//   * comma-separated ports (22,80,443)
//   * a port range (8000-8099)
//   * or "*" for all                                                                                                                    
```

So looking at just the port part,

```
// The "port" part of each "ip:port" can be:
//   * a single port (22)
//   * comma-separated ports (22,80,443)
//   * a port range (8000-8099)
//   * or "*" for all
```

That would be extended to:

```
// The "port" part of each "ip:port" can be:
//   * a single port (22)
//   * comma-separated ports (22,80,443)
//   * a port range (8000-8099)
//   * or "*" for all ports
//   * "proto-or-"cap"/....
//       - tcp/80
//       - tcp/22,80,443
//       - udp/3000-3999
//       - cap/<name> like cap/example.com/database-rw
```

The only rule is that the port can't have a colon in it, for parsing ambiguity, so neither can the cap.

We can use `cap/DOMAIN-NAME/foo`, like `cap/tailscale.com/taildrop`, etc.

I really think capabilities should be between nodes, like port capabilities are, and not be tied to a port. For one, not all environments even let you know which port connected to you. And sometimes you want to know the capabilities of a peer _before_ you connect to it. (e.g. can I send a Taildrop file to a node that's not me?)

**Comment by bradfitz** [comment]
Oh, and I forgot the earlier hack idea that led to this.

The workaround is for any given capability you want to use, you roll the dice and make up a random IPv6 address with some ULA prefix. Then advertise a route to it, then give people with that "capability" ACLs to that "IP", and then in the client checking the capabilities, you instead check the client's allowed packet filter and whether it can reach that capability's dummy IPv6.

That seemed so hacky, though, even if it was something we could do today without server help.

**Comment by danderson** [comment]
Noting some topics I'd like to talk about in our design meeting, so I don't forget about them:

 - The capabilities as expressed do not let you grant different capabilities to different services on a machine. Case in point, we run two Postgres proxies on a single machine, and I could see wanting to grant read-only to the production one and read-write to the QA one. In this model, I cannot do that. Does it matter? Are 3p vendors going to want to do this and find themselves hamstrung?
 - Not all capabilities are tied to the network in the first place, so attaching them strongly to our current src/dst feels weird. One example of that we discussed today was using capabilities to express permissions on the Tailscale admin API, which exists outside of tailnets.
 - What does the programming interface look like on-node? If I'm developing an application, I don't care to know the 200 capabilities that an entire machine has, I care about the few capabilities that have meaning to me. Checking "does user have cap X" and "what caps that I care about does user X have?" should be easy.
 - Lumping all this into a single string makes the grammar complex enough that I'm starting to want a formal EBNF definition for it. Where do I put `:`, `,`, `-`, `/` ? Why? The examples listed above make me feel like I'll always need the ACL reference docs open to write correct definitions. I wonder if we're conflating a bunch of things that could/should be separate fields in the ACL proto.

**Comment by bradfitz** [comment]
> The capabilities as expressed do not let you grant different capabilities to different services on a machine. Case in point, we run two Postgres proxies on a single machine, and I could see wanting to grant read-only to the production one and read-write to the QA one. In this model, I cannot do that. Does it matter? Are 3p vendors going to want to do this and find themselves hamstrung? If we don't care initially, how do we keep the door open for that retrofit later?

For something like our `ompg` which uses tsnet, the answer is to run multiple. But we could also extend this to do port-specific capabilities too by extending the string. e.g. `cap/example.com/database-rw/on-port-123`. But I feel strongly that we need node (IP)-specific capabilities as the base for things like the Taildrop example above.

> Not all capabilities are tied to the network in the first place, so attaching them strongly to our current src/dst feels weird. One example of that we discussed today was using capabilities to express permissions on the Tailscale admin API, which exists outside of tailnets.

We already have MapResponse.Node.Capabilities for those. We already put `https://tailscale.com/cap/is-admin` in there, for instance.

> What does the programming interface look like on-node? If I'm developing an application, I don't care to know the 200 capabilities that an entire machine has, I care about the few capabilities that have meaning to me. Checking "does user have cap X" and "what caps that I care about does user X have?" should be easy.

Well, I doubt it'll be 200, but we can make the localapi WhoIs query let you filter by the ones you care about.

> Lumping all this into a single string makes the grammar complex enough that I'm starting to want a formal EBNF definition for it. Where do I put :, ,, -, / ? Why? The examples listed above make me feel like I'll always need the ACL reference docs open to write correct definitions. I wonder if we're conflating a bunch of things that could/should be separate fields in the ACL proto.

@maisem and I worked through several possibilities and didn't come up with anything better, especially as separate fields. It introduced various ambiguities.

An EBNF for the capability syntax (which includes the existing port number capabilities) is easy enough, though.

**Comment by bradfitz** [comment]
An EBNF:

```
# dst describes an ACLRow.Dst value. If no dst-type is provided, it's
# equivalent to three rules, with dst-type values "tcp", "udp", and
# "icmp". The cap-spec is only allowed when dst-type is "cap"; otherwise
# the part after the slash must be a prot-spec.
dst = [ dst-type , "/" ] , ( cap-spec | port-spec)

dst-type = ip-proto | "cap"

cap-spec = "cap/" , no-slash+

no-slash = any digit excluding "/"

ip-proto = ip-proto-name | ip-proto-number

ip-proto-name = "tcp" | "udp" | "sctp" | ...

ip-proto-number = "proto" , digit+

port-spec = port-range [ "," port-range ]+

port-range = "*" | port-number | ( port-number , "-" , port-number )
```

The other possibility is extending `ACLRow.Action` (which currently can only be `"accept"`) to also permit the value `"grant"` to grant capabilities.

In that case, the mean of the `"dst"` value would change to not permit port numbers, and you could write:

```
{
    "action": "grant",
    "src": ["group:eng", "group:sysadmin" ],
    "dst": [ "mon", "backup-mon", "100.105.104.103" ],
    "cap": ["grafana.com/rw", "example.com/other-cap" ],
}
```

... to mean that everybody in those two groups gets those two capabilities on all three of those destinations.

If we wanted to permit port-specific capabilities in the future, we could make a new `"action"` type, like `"grant-port"`. I remain a little skeptical that'll be useful, but maybe. We could even start with `"action": "grant-host"` for now, so neither gets the bare name `"grant"`.

**Comment by mayakacz** [comment]
From discussion today with @crawshaw @bradfitz @maisem @danderson @nickoneill 

Initial discussion:
* capabilities should grant access to services, not nodes
* want tailscaled to have multiple IP addresses per node
* need a way to represent an IPv4 & IPv6 address ("tailNIC")
  + AWS calls these "network interfaces" or "endpoints"
* want to be able to have services run across machines, want virtual IPs and name-based virtual hosting
* how are capabilities different for services vs. SSH
  + self-hosted apps might be read, read-write; but services like Grafana that have a concept of roles, e.g., admin, might be able to plug in and consume. Could allow any string
  + SSH is about a user, not a capability. SSH is special
  + would like to be able to support multiple sets of permissions for the same app, e.g., escalating capabilities

So we could have a world where:
* A service runs on a specific Tailscale IP
  + A service can be referred to by a tailNIC, including an IPv4 address, an IPv6 address, and a (host) name
* A user could restrict access and capabilities for a specific service
* A node in Tailscale can run multiple services on multiple IPs
* Virtual NIC/ IPs allow for load-balancing a service between multiple nodes
  + This may be hard to get right in WireGuard

What we could start with, with capabilities:
* Have capabilities work with existing Tailscale IPs, assuming it refers to a single service. This allows us to add more services to a node in the future and this will still express capabilities for only that service 
* Can have multiple capabilities. You connect with all capabilities you've been granted
* In ACLs, would need two ACLs to access a given application on 
  + one ACL to access over Tailscale (`accept`)
  + one ACL to grant capabilities to the capability in Tailscale (`grant`)
* Haven't decided on ACL format - either grants are referred to like a port, or (likely?) a separate grant part of an ACL
  + all the other fields are matches (e.g., port). Capabilities are grants, a different concept
  + destination be optional (`*:*`) for a whole tailnet, so grant capabilities for a whole tailnet

**Comment by danderson** [comment]
Some examples of the different syntaxes, based on some hypothetical capability-supporting software in a company tailnet:
 - Grafana dashboard with `grafana.com/read` and `grafana.com/write` capabilities
 - A company "superuser dashboard" that grants scoped access to customer accounts, with capabilities `mycorp/view/basic-info`, `mycorp/view/network-debugging`, `mycorp/modify/password-reset`, `mycorp/modify/change-settings`, `mycorp/modify/assume-identity`.

I implement the following rules, which feel like a plausible "advanced" example:
 - All employees can view (but not modify) Grafana dashboards.
 - Production-engineering can modify Grafana dashboards.
 - Engineering and support can view basic customer info
 - Engineering can view network debugging info
 - Support can reset passwords and change settings
 - Escalation support can log in as customers.

## Option 1: ports and capabilities inlined together

```
"ACLs": [
  // Grafana permissions
  {
    "action": "accept",
    "src": ["autogroup:members"],
    "dst": ["tag:dashboards:80", "tag:dashboards:cap/grafana.com/read"],
  },
  {
    "action": "accept",
    "src": ["group:prod-engineering"],
    "dst": ["tag:dashboards:cap/grafana.com/write"],
  },
  // Superdash permissions
  {
    "action": "accept",
    "src": ["group:support"],
    "dst": [
      "superdash:80",
      "superdash:cap/mycorp/view/basic-info",
      "superdash:cap/mycorp/modify/password-reset",
      "superdash:cap/mycorp/modify/change-settings",
    ],
  },
  {
    "action": "accept",
    "src": ["group:engineering"],
    "dst": [
      "superdash:80",
      "superdash:cap/mycorp/view/basic-info",
      "superdash:cap/mycorp/view/network-debugging",
    ],
  },
  {
    "action": "accept",
    "src": ["group:support-escalations"],
    "dst": [
      "superdash:80",
      "superdash:cap/mycorp/modify/assume-identity",
    ],
  }
],
```

## Option 2: capabilities are a separate "grant" action

```
"ACLs": [
  // Grafana permissions
  {
    "action": "accept",
    "src": ["autogroup:members"],
    "dst": ["tag:dashboards:80"],
  },
  {
    "action": "grant",
    "src": ["autogroup:members"],
    "dst": ["tag:dashboards"],
    "cap": ["grafana.com/read"],
  },
  {
    "action": "grant",
    "src": ["group:prod-engineering"],
    "dst": ["tag:dashboards"],
    "cap": ["grafana.com/write"],
  },
  // Superdash permissions
  {
    "action": "accept",
    "src": ["group:support", "group:engineering", "group:support-escalations"],
    "dst": ["superdash:80"],
  },
  {
    "action": "grant",
    "src": ["group:support"],
    "dst": ["superdash"],
    "cap": [
      "mycorp/view/basic-info",
      "mycorp/modify/password-reset",
      "mycorp/modify/change-settings",
    ],
  },
  {
    "action": "grant",
    "src": ["group:engineering"],
    "dst": ["superdash"],
    "cap": ["mycorp/view/basic-info", "mycorp/view/network-debugging"],
  },
  {
    "action": "grant",
    "src": ["group:support-escalations"],
    "dst": ["superdash"],
    "cap": ["mycorp/modify/assume-identity"],
  }
]
```

## Option 3: same as 2, but grants are in a separate section of the network policy file

```
"ACLs": [
  // Grafana permissions
  {
    "action": "accept",
    "src": ["autogroup:members"],
    "dst": ["tag:dashboards:80"],
  },
  // Superdash permissions
  {
    "action": "accept",
    "src": ["group:support", "group:engineering", "group:support-escalations"],
    "dst": ["superdash:80"],
  },
],
"Capabilities": [
  // Grafana permissions
  {
    "action": "grant",
    "src": ["autogroup:members"],
    "dst": ["tag:dashboards"],
    "cap": ["grafana.com/read"],
  },
  {
    "action": "grant",
    "src": ["group:prod-engineering"],
    "dst": ["tag:dashboards"],
    "cap": ["grafana.com/write"],
  },
  // Superdash permissions
  {
    "action": "grant",
    "src": ["group:support"],
    "dst": ["superdash"],
    "cap": [
      "mycorp/view/basic-info",
      "mycorp/modify/password-reset",
      "mycorp/modify/change-settings",
    ],
  },
  {
    "action": "grant",
    "src": ["group:engineering"],
    "dst": ["superdash"],
    "cap": ["mycorp/view/basic-info", "mycorp/view/network-debugging"],
  },
  {
    "action": "grant",
    "src": ["group:support-escalations"],
    "dst": ["superdash"],
    "cap": ["mycorp/modify/assume-identity"],
  }
]
```

**Comment by danderson** [comment]
Talking to a user earlier today, they suggested a way that we could reduce the operational annoyance of having to specify both network and capability permissions to get stuff to work: could we allow specifying capabilities as the source of a network ACL?

Simple example: anyone who has any L7 capabilities granted for Grafana, is allowed to access Grafana:

```json
{
  "action": "accept",
  "src": ["cap:grafana.com/*"],
  "dst": ["tag:dashboards:80"],
},
```

This reduces the maintenance burden, because as the network admin, you have to write out the network-level permission exactly once, and then for all future changes, you can reason entirely about the L7 permissions, and be assured that L4 permissions will update in lockstep, without having to specify the sources twice.

It also gives a plausible use for wildcards in capabilities, which is something we were struggling to find a need for earlier :P

cc @bradfitz @maisem @mayakacz @crawshaw @nickoneill thoughts? (disconnected from the syntax bikeshedding in prior comment)

**Comment by danderson** [comment]
Now that I've impartially laid down some stuff above, my opinions: I like Option 2 the best, in terms of how readable the L7 capability grants are. I find it much easier to see at a glance "okay this is what this rule is granting". Doubly so if we also allow capabilities as the src for network ACLs, because then the network ACLs are write-once.

**Comment by mayakacz** [comment]
I think you asked two questions,
* Can capabilities be a src in an ACL?
* Which option makes the most sense?

---

> could we allow specifying capabilities as the source of a network ACL?

> anyone who has any L7 capabilities granted for Grafana, is allowed to access Grafana

I think transitive capabilities as src confusing.
Right now, you can only make srcs things like groups, or tags, which make sense to me in that they are meant to be properties of the node, and they infrequently change. So I am member of group Engineering, or this is a server. But, my access rights change as what I'm auth'd as changes, not when what *else* I can access changes.
I'm assuming we'd have to limit src=capability to dst=where you have a service running, then, but we don't necessarily know where that is.

I understand what you're trying to do, to simplify the ACLs for L4 vs L7 differences. You're basically saying, capabilities/ L7 is the default way of granting access.
I wonder if this might just be 'too soon' - right now, the default permissions are about L4 access. If I only have capabilities for some things, this will create a mishmash of L4 & L7 permissions in my ACLs, which I think are potentially more confusing short term, not less confusing. But, if capabilities / L7 are the default way to grant access, then making L4 permissions in lockstep with L7 makes sense.

---

What you're saying about L4 vs L7 is the main question here. Do we expect a user to specify *both* an ACL *and* a capability?
* If they only specify an ACL, then the devices can still connect. The application may or may not handle capabilities and interpret these, and so the user may or may not actually be able to access a given application.
* If they only specify a capability, then... should it work?

I'm realizing that
* I think capabilities are about restricting access to a service/ application only, not a node. We assume these are 1:1, but this leads to weird models where you grant access to a node a service is running on separately from granting access to the service.
* If you've specified a capability, we don't know if your service/ application is even using it. If you specify that a user gets read access to an application, but the application isn't configured to do anything with that information, that's confusing and potentially harmful.

I prefer option 2, but I wonder if option 3 is better for current reality. I'm wondering if:
* Capabilities are specified separately from node ACLs, but end up being a property of a service (for now == node), in their own section of ACLs. That would be option 3. That would also be the closest to SSH.
* For a capabilities ACL to be valid, you must do _something_ on the node to opt it in/ otherwise confirm you've configured capabilities as intended. That would also be the closest to SSH.

**Comment by sagarrakshe** [comment]
Hello, 

As I see, this feature will take some time to be GA. Does anyone have a workaround for this?

**Comment by DentonGentry** [comment]
Could I ask what you expect to work around? This tracks a feature request to allow ACLs to control access to things other than IP addresses+ports. It would be implemented at the same time as the Tailscale product provides a new feature which can access things that are not IP addresses + ports.

I don't see what you'd need to work around.

**Comment by sagarrakshe** [comment]
@DentonGentry I should have been more specific in the ask. The use-case I am looking for is grouping read-only users and read-write users of database. I solved the networking part (IP address+port) with Tailscale, but not the database access control. 
So I was asking for any workaround or any solution on top of Tailscale for this use-case.

**Comment by DentonGentry** [comment]
I don't think there is currently a way to do exactly that. Some things which exist and seem related:
- [nginx-auth](https://tailscale.com/blog/tailscale-auth-nginx/) uses Tailscale to identify the User connecting, passing the identity through to nginx to decide what access that user should have.
- [pgproxy](https://tailscale.com/blog/introducing-pgproxy/) a proxy allowing a postgres DB, even a software-as-a-service Postgres DB, to be placed on the tailnet. This proxy does interpose on the postgres protocol but doesn't currently intercept users and access control.

A pgproxy-like system might implement more of the postgres protocol to understand what access should be allowed.

**Comment by madjam002** [comment]
Just to hopefully add something to this discussion, I've been using this feature for a few months now (thanks to Headscale, I wrote a patch to parse the ACLs as proposed here) combined with the cmd/nginx-auth tool to allow for ACL rules to define what users can access different services behind a reverse proxy (see my PR #5507 for this).

It's then possible to write ACLs like so:

```
{
  "action": "grant",
  "src": ["group:allowed_grafana"],
  "dst": ["tag:ingress_controller"],
  "cap": ["nginx.ingress.kubernetes.io/allow/grafana.mycorp.internal"]
}
```

And e.g in Kubernetes annotate an ingress resource like so:

```
nginx.ingress.kubernetes.io/auth-url: "http://unix:/var/run/tailscale/tailscale.nginx-auth.sock"
nginx.ingress.kubernetes.io/auth-snippet: |
  proxy_set_header Remote-Addr $remote_addr;
  proxy_set_header Remote-Port $remote_port;
  proxy_set_header Expected-Cap "nginx.ingress.kubernetes.io/allow/grafana.mycorp.internal";
```

I'm not polling for an update or anything here, just wanted to share my use case and how much I love this WIP feature, it's rock solid :) I think it would be a great addition one day to the official Tailscale offering.

**Comment by nogweii** [comment]
Has this been addressed already? I see that in the [Kubernetes operator documentation](https://tailscale.com/kb/1236/kubernetes-operator#impersonating-kubernetes-groups-with-acl-grants) there is a syntax that works:

```json
  {
    "grants": [{
      "src": ["group:k8s-readers"],
      "dst": ["tag:k8s-operator"],
      "app": {
        "tailscale.com/cap/kubernetes": [{
          "impersonate": {
            "groups": ["tailnet-readers"],
          },
        }],
      },
    }]
  }
```

**Comment by bradfitz** [comment]
Sufficiently done to close this issue. It launched: https://tailscale.com/blog/acl-grants
