### ISSUE TITLE
Move pkgs.tailscale.com to a CDN?

### ISSUE THREAD

**Issue by aofei** [tailscale/tailscale#4247]
Today I happened to have a failed install of Tailscale on a machine that blocked [AS14061](https://bgp.he.net/AS14061) (aka DigitalOcean). And learned that [pkgs.tailscale.com](https://pkgs.tailscale.com) hasn't been CDNed yet. It feels odd to me that a modern product's package distribution service hasn't been CDNed. Since [tailscale.com](https://tailscale.com) is already on Cloudflare, maybe [pkgs.tailscale.com](https://pkgs.tailscale.com) should be there too. And honestly that would be a good thing for people outside of North America as well.

<details><summary><code>tailscale.com</code>'s geolocation</summary><br><pre>
$ curl -fsS "https://api.ip.sb/geoip/$(dig +short tailscale.com | head -1)" | jq
{
  "organization": "Cloudflare",
  "isp": "Cloudflare",
  "asn": 13335,
  "asn_organization": "CLOUDFLARENET",
  "ip": "104.16.243.78"
}
</pre></details>

<details><summary><code>pkgs.tailscale.com</code>'s geolocation</summary><br><pre>
$ curl -fsS "https://api.ip.sb/geoip/$(dig +short pkgs.tailscale.com | head -1)" | jq
{
  "organization": "Digital Ocean",
  "longitude": -121.9753,
  "city": "Santa Clara",
  "timezone": "America/Los_Angeles",
  "isp": "Digital Ocean",
  "offset": -28800,
  "region": "California",
  "asn": 14061,
  "asn_organization": "DIGITALOCEAN-ASN",
  "country": "United States",
  "ip": "167.172.11.40",
  "latitude": 37.3417,
  "postal_code": "95051",
  "continent_code": "NA",
  "country_code": "US",
  "region_code": "CA"
}
</pre></details>

**Comment by bradfitz** [comment]
Yes, this has been a low priority background project.

(Tailscale folk: some work started in https://github.com/tailscale/corp/pull/3602)

**Comment by vysecurity** [comment]
I put pkgs.tailscale.com and other items under my own domain and just front their domain. This way you can have faster speeds yourself without waiting.

**Comment by DentonGentry** [comment]
Work on this is being carried out in a private repository, I don't think the public bug really helps.

**Comment by marcoslater** [comment]
@DentonGentry I don't want to intrude on a closed issue, however it's worth mentioning that with the way that the [tailscale maintained github action](https://github.com/tailscale/github-action) works, it would speed up downloads for these significantly and improve build times, specially for those who run builds on self-hosted runners in Europe. 

Would love to see this implemented. Given the versioning on the package names, I don't suppose it's as easy as hitting the orange cloud on Cloudflare and setting a basic cache rule?

**Comment by marcoslater** [comment]
![image](https://user-images.githubusercontent.com/4334625/203132677-84711bb1-5288-4c2e-a56b-d4a76339d33a.png)

It also appears that the lack of a CDN is significantly hurting download speeds now that there's a lot of people downloading the new version due to the recently released CVE's, putting releases on CDN's is an industry standard and this could be avoided. It's dissapointing to see Tailscale has not implemented it yet. (@bradfitz )

**Comment by marcoslater** [comment]
@bradfitz Any updates on this? It's still super slow to get tailscale packages from Europe.

**Comment by stevetrease** [comment]
Download speeds are fine here in the UK :-)

**Comment by vysecurity** [comment]
Well yeah, he said Europe.

**Comment by marcoslater** [comment]
They may be fine from time to time but not always, additionally download heavy workflows like their own github actions tooling checks/fetches the new versions each run, making a high latency round trip fairly detrimental to the usage of it if you're not in the US where their single download server is. 

These days the implementation of a CDN towards a single instance is a fairly trivial task, so it is a little bizarre how it's been running with out with internal notes to add one for so long. Perhaps it has not yet reached the right team as a request?

**Comment by bradfitz** [comment]
We deployed a CDN today.

We're still ramping it up and tuning some things, but it's almost entirely on for most things now.

**Comment by aofei** [comment]
Not sure about this, it doesn't look like it's on a CDN just from pinging.

https://ping.pe/pkgs.tailscale.com

![img_kJCMbMeq](https://github.com/tailscale/tailscale/assets/5037285/3a6e4802-97f1-411f-b2ba-e573e51452d3)

**Comment by martafolf** [comment]
Just to pitch in, @aofei is correct. It is not on a CDN. However, the latency has improved since the beginning of this issue, as they moved the location, it serves the data from a (DigitalOcean) server on the US West Coast to a server on the US East coast with NetActuate. 

If you view their screenshot, there's a gradually ascending latency the further away you get from the US East coast side, however it can be difficult to read in the way that table is formatted. 

To help visualise what they posted, here's a 500 probe world-wide measurement from the Ripe Atlas network: https://atlas.ripe.net/measurements/59693147/#map

If you see the map on the link above, the latency is great on the East Coast, however as the circle widens, it drops off, being very high in far reaches like Asia and Australia. 

I've made another 500 probe test against tailscale.com itself, which does use a CDN: https://atlas.ripe.net/measurements/59693277/#map 

As you can see the latency is low throughout a large portion of the globe, as there's locations spread near each of the probes. 

I hope this helps understand the way a CDN looks and can help deliver packages closer to the end user. 😄

**Comment by DentonGentry** [comment]
> Not sure about this, it doesn't look like it's on a CDN just from pinging.

```
$ wget https://pkgs.tailscale.com/stable/tailscale-setup-1.48.1.exe
--2023-09-06 04:59:59--  https://pkgs.tailscale.com/stable/tailscale-setup-1.48.1.exe
Resolving pkgs.tailscale.com (pkgs.tailscale.com)... 199.38.181.239, 2607:f740:f::d19
Connecting to pkgs.tailscale.com (pkgs.tailscale.com)|199.38.181.239|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dl.tailscale.com/stable/tailscale-setup-1.48.1.exe [following]
--2023-09-06 04:59:59--  https://dl.tailscale.com/stable/tailscale-setup-1.48.1.exe
Resolving dl.tailscale.com (dl.tailscale.com)... 109.105.218.17, 2a09:8280:1::a:1a71
Connecting to dl.tailscale.com (dl.tailscale.com)|109.105.218.17|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 52860056 (50M) [application/x-ms-dos-executable]
Saving to: ‘tailscale-setup-1.48.1.exe’
```

**Comment by bradfitz** [comment]
Some of the HTML and index pages aren't on a CDN yet. Most the downloads are, however. We'll move more over in time.
