### ISSUE TITLE
FR: support login from Okta Mobile app and dashboard

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#4287]
### What are you trying to do?

Access OKta from Okta Dashboard ;
Okta users' workflows are often initiated from the Okta Mobile app or dashboard (at https://your-company-name.okta.com/)

After installing the Tailscale app from the OIN, Okta admins can configure it to be shown in these locations:
![image](https://user-images.githubusercontent.com/75628398/160165295-8ee9c649-aaf8-498d-b09d-afd7b9e322a8.png)

When users click on the Tailscale tile, they get a 403 error, as in this [ticket](https://app.frontapp.com/open/msg_10p1j8y9).

To support this feature, we'll need to launch the Tailscale app after successful auth from Okta.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_66scx)

**Comment by darshinimashar** [comment]
Users might also want something like this: https://developer.okta.com/docs/guides/custom-url-domain/main/

**Comment by DentonGentry** [comment]
To set expectations: I do not think this is feasible, because the product is a VPN app not a web service. After authenticating from the Okta mobile app we'd need to wake up the Tailscale VPN, tell it to authenticate, and pass it some kind of credential. I don't know what kind of credential we can provide, a bearer token like one would pass to a web service is not sufficient.

**Comment by DentonGentry** [comment]
Closing as not feasible, we need an OAuth flow to authenticate the user.
