### ISSUE TITLE
Offline exit nodes are shown as available on the Windows client

### ISSUE THREAD

**Issue by GOATS2K** [tailscale/tailscale#4521]
### What is the issue?

I attempted to connect to an exit node on my tailnet and Tailscale showed as connected - however I did not have internet access.
The machine turned out to not be connected to the tailnet.

I wish the machine didn't show up in the exit node list if it was offline.

### Steps to reproduce

Connect to the seemingly available exit node.

### OS

Linux, Windows

### OS version

Windows 10, Ubuntu 20.04

### Tailscale version

1.24.0

### Bug report

BUG-ad05fa0b039867dbafe733d26bb42a2d738b4d0621d93aecb115fec609bd31f3-20220425231459Z-d3fb3780873c2f6f

**Comment by DentonGentry** [comment]
That exit nodes remain in the list is a deliberate choice: blocking ability to reach the exit node doesn't deselect or make the exit node unselectable. Instead, blocking ability to reach the exit node results in breaking connectivity: failing closed, instead of failing open and using the public network.
