### ISSUE TITLE
hello.ipn.dev enabled by default

### ISSUE THREAD

**Issue by the-woocash** [tailscale/tailscale#457]
**Describe the bug**
hello.ipn.dev server present in authorised devices on a new account, giving it full access to lan created inside tailscale. There is no mention about this during onboarding. The user has to read through FAQ to find that it's an IRC server. No information about any ACLs that would exist to prevent server's access to user's devices. On the other hand that server is shared between all users, potentially being a vulnerability.

**To Reproduce**
1. Join tailscale
2. Authorise any device(s). 
3. In the admin panel notice there's an unknown pre-authorised device having access to all Your devices - hello.ipn.dev. No information about the reason up to this point during registration and onboarding process.

**Expected behavior**
No preexisting authorised non-user-created devices should have access to the virtual lan.

**Version information:**
All version

**Comment by evelynmitchell** [comment]
I agree that this should be explicitly enabled as part of the onboarding testing, and that it should be indicated what this does and that you want to remove it after your testing is done.

**Comment by apenwarr** [comment]
This came up in a reddit discussion today (https://www.reddit.com/r/Tailscale/comments/h79gmr/helloipndev_security/fumdx2f/). I'll paste my response from there below. Since the docs and onboarding UX for this definitely need improvement, I'll leave this issue open until then.

Actually the reason for the auto-added server on new network is to prevent a chicken-and-egg problem: after you install just one node, how do you know it's workng? If you install two nodes and they can't talk to each other, how do you know which one (or both) is broken?

hello.ipn.dev helps with those questions, even if it's just a pingable server. But ping is hard to do on iOS or Android, and even on other OSes it requires people to drop to the command line, which can be tough, so we added an https server you can visit from a browser. And then we had to make the https server respond with something, so we added a (go-based) irc server kind of as a joke. (You can also connect using a regular irc client, which is another important test: most BeyondCorp-style products cannot proxy non-http traffic like irc.) More on testing with hello.ipn.dev here: https://tailscale.com/kb/1030/next-steps

The irc server seems to have gotten misconstrued as a tech support mechanism lately, which isn't ideal (since we're a small team and can't monitor it full time), so we'll probably aim to shut it down and redirect people to freenode. But on the other hand, some users like it so we're hesitant to shut it down.

Anyway, other commenters are correct that it's ACLed to not allow outgoing connections; it makes a good demo of a "one way" node. Nevertheless, users who are concerned about keeping their network private should remove the test node from their network, as described here: https://tailscale.com/kb/1073/hello-ipn-dev

**Comment by DentonGentry** [comment]
hello.ipn.dev can be removed in the admin panel.
<img width="749" alt="Screen Shot 2021-05-20 at 4 20 10 PM" src="https://user-images.githubusercontent.com/1140756/119060632-733c7e80-b987-11eb-9949-c70688623cb0.png">

It serves a useful function in onboarding: that there will always be a second device, one which will at least respond to ping.

At this point I'm going to close the issue. We understand the idea, and have provided ways to remediate the concern by removing the node.
