### ISSUE TITLE
Windows Split DNS is overridden by GPO configured by AD domains

### ISSUE THREAD

**Issue by sailorfrag** [tailscale/tailscale#4607]
### What is the issue?

When a Tailnet has split DNS configured, the Tailscale client configures Windows 8 and newer using NRPT to selectively send DNS queries for particular DNS suffixes to the Tailscale client. The Tailscale client then forwards the requests along to the appropriate DNS server.

Unfortunately, a couple of customers have reported that this does not work at all for them. Evidence indicates that the NRPT rules are simply being ignored. In both cases, they have configured a GPO to set various DNS settings (such as search domains).

### Steps to reproduce

1. Install Tailscale on a Windows 10 Enterprise computer that is part of an AD domain
2. Configure a GPO that sets DNS search domains
3. Configure split DNS on the Tailnet
4. Using `ping`, Wireshark and/or the other tool of your choice (not `nslookup` because it is not aware of fancy DNS lookup rules) check some hostnames that only resolve correctly if split DNS rules are being followed.

### Are there any recent changes that introduced the issue?

No, this appears to have been a problem since the last major Windows DNS implementation change.

### OS

Windows

### OS version

Confirmed on Windows 10, probably affects 8 and newer

### Tailscale version

1.24.0

**Comment by sailorfrag** [comment]
I'm still actively investigating this issue and will provide updates when available.

**Comment by sailorfrag** [comment]
In terms of workarounds for now, I think the best I can suggest is to configure "override local DNS" and configure the global resolvers to one of the public DNS services that use anycast (in particular, Google at 8.8.8.8, Cloudflare at 1.1.1.1, Quad9 at 9.9.9.9 will all automatically be recognized by Tailscale and automatically upgrade to using DoH); those should provide reasonably good localized DNS results regardless of location. The full list of public DNS services that our client recognizes is at https://github.com/tailscale/tailscale/blob/main/net/dns/publicdns/publicdns.go -- services not in that list should still work, but won't use DoH.

**Comment by sailorfrag** [comment]
Easier reproduction step: in the key `HKLM\Software\Policies\Microsoft\Windows NT\DNSClient` (create it if needed), create a new string value SearchList and put something in there (it's a comma separated list of domain names). Split DNS immediately stops working.

The `[MS-GPNRPT]` document from Microsoft indicates that if settings in both `HKLM\Software\Policies\Microsoft\Windows NT\DNSClient ` and `HKLM\System\CurrentControlSet\services\Dnscache\Parameter` exist then the latter is ignored. We configure our NRPT entries in the latter.

**Comment by sailorfrag** [comment]
I [found a web version](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-gpnrpt/8cc31cb9-20cb-4140-9e85-3e08703b4745) of the `[MS-GPNRPT]` document. It appears to be the same version as the PDF I found elsewhere.

Today's testing reveals that creating keys of the form `HKLM\Software\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig\{GUID}` appear to have no effect. The PowerShell `Add-DnsClientNrptRule` command and the Local Group Policy Editor both create entries in `HKLM\System\CurrentControlSet\services\Dnscache\Parameter\DnsPolicyConfig\{GUID}` and those rules also stop working when any value is created in `HKLM\Software\Policies\Microsoft\Windows NT\DNSClient` (I created a value with a made-up name and it still broke NRPT). After making changes, sometimes it takes a full reboot to see the final effect.

So I'm somewhat confused by how inaccurate the `[MS-GPNRPT]` document is -- either there is no second path for creating these rules or it has a different name. The document also only describes Version 1 whereas PowerShell and the policy editor create Version 2 rules (I don't see any difference other than the addition of a comment and display name). Searching for references to any of these things only produces a handful of search results, mostly people who have noticed funny behavior when DNSClient settings interact with NRPT, usually with a description of how to delete one or the other to solve those problems. I'm attempting to document this reasonably well so that hopefully the next person to encounter this doesn't have to discover it all from scratch again.

Notably, PowerShell `Get-DnsClientNrptRule` shows the rules that are configured under `...\Dnscache\Parameters\DnsPolicyConfig\{GUID}` but not those that are configured under `...\DNSClient\DnsPolicyConfig\{GUID}`. If any values appear in `...\DNSClient` then `Get-DnsClientNrptPolicy` and `Get-DnsClientNrptPolicy -Effective` are blank even though `Get-DnsClientNrptRule` shows rules.

As far as I can tell, the best path forward from here is to fall back to our pre-NRPT code path if values are detected in the `DNSClient` key. I have been unable to find any newer or more helpful documents than the one I've been referring to so far.

**Comment by KevinCathcart** [comment]
I looked into this on a Windows Server 2022 Domain controller. The following is all based upon experiments performed on there. It is possible that older win 10 boxes may not perform the same (have not tested yet), but I betting they do.

Domain Group Policy (as opposed to the local group policy editor, which actually bypasses the whole GPO infrastructure for these settings!) does indeed use the `HKLM\Software\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig\{GUID}` path, and it does work. I've even verified this by creating a GPO with just a split dns server listed, and the whole GPO just has the version metadata, and a registry.pol file, the latter of which only touches the above listed registry key.

However there is a caveat. Unlike the `HKLM\System\CurrentControlSet\services\Dnscache\Parameter\DnsPolicyConfig\` path, or even the the values in the `DNSClient` parent key, the dns client service will not notice changes to those paths. It appears to check them only at startup, or if notified that a group policy has been applied. There may well be other things that could trigger this reload, but the obvious candidates like the PowerShell cmdlets don't seem to do it.

I don't think there is a way to artificially trigger the group policy was applied notification, but there is something that can be done to force it to happen, namely run `gpupdate /force /Target:Computer`. `gpupdate` is a command to make a computer immediately apply applicable any GPOs, rather than waiting for it to happen in the background. However, by default, it will only apply GPOs that indicate that they have changed since the last time they were applied, and for the notification, we need to have at least one actually applied.The `/force` option causes it to reapply the GPOs even if it thinks they are unchanged. As all computers have at least one GPO available (the local machine GPO), this will always result in a GPO being applied, and thus the DNS Client service will be notified and will reread the Policy registry keys. The `/Target:Computer` option means only apply machine-wide (Computer) policies, as opposed to also including User policies. We don't care about the user portion, and this should make the command run faster.

I'm not convinced that this would be ideal for tailscaled to do, but it might be better than falling back to the pre-NRPT codepath. It does have an important caveat regarding staggered timing if something could potentially trigger changes on many devices within an organization, as outlined below.
  
So, the basic algorithm for applying split DNS would be:
 
 1. Apply the `HKLM\System\CurrentControlSet\...` key. No reason to not always do this.
 2. Check if the `HKLM\Software\Policies\Microsoft\Windows NT\DNSClient` key exists, if it does not exist we are done.
 3. Check if the `HKLM\Software\Policies\Microsoft\Windows NT\DNSClient` key contains any values, or any subkeys (recurive), other than the one Tailscale will create. 
 4. If non-tailscale keys or values exist, then check if the Tailscale DnsPolicyConfig key is fully up to date, and if not, apply needed changes.
 5. If the Tailscale Policy config key is the only contents (including values) in the `HKLM\Software\Policies\Microsoft\Windows NT\DNSClient`, then remove that whole key.
 6. If you may any changes to the Policy keys, then wait for a random time between 0 and 10 minutes, and finally run `gpupdate /force /Target:Computer`.
 
The waiting is important to avoid potentially having hundreds of devices in a single organization all hitting the domain controller at once (possibly overwhelming it, but more realistically bottle-necking the network) with requests for GPO data if something changes control side to make all the nodes want to update their split DNS configuration. Obviously, if the update is triggered by something already staggered in such a manner, this could be skipped. 10 minutes is the time frame that the Group Policy GUI tool uses when large numbers of devices are targeted be force refreshed. (It normally uses a 30 minute stagger in the background refreshes, but that in an ancient number from the pre Windows XP days based upon what really old servers and networks could handle, kept unchanged for mostly for compatibility.)

If an alternate trigger for triggering NRPT policy reloading from the `HKLM\Software\Policies\...` keys was found that does not require `gpupdate`, then the staggering could be removed, and step 6 would be changed to perform the alternative trigger.

**Comment by sailorfrag** [comment]
Interesting. Thank you for that in depth research. I did eventually resort to rebooting after I made each change but perhaps there were some approaches I thought I ruled out before rebooting. Or perhaps a reboot doesn't reset things quite as much as `gpupdate /force`. Do you think I can reproduce this without a domain controller? I can arrange for a domain controller but it's much less work to use a standalone Windows installation.

**Comment by KevinCathcart** [comment]
Sorry about the delayed reply, the notification failed to show up in GMail.

A few thoughts:

1. The main reason i spun up a domain controller was simply because I wanted to see what it does if you create a domain level GPO, rather than a local GPO, because the editor for a machine level GPO cannot cheat and update registry directly. Instead it needs to put is changes in registry.pol, or it can't work) and to see what happens when you apply the policy to a client. But I did not want to bother spinning up a second machine as a client so I only applied the GPO to itself.

I'd be quite suprised if everything I tested except for creating the GPO itself/ applying it as adomain GPO would not work on a normal workstate domain connected or not. I just simply have not bothered to spin up a VM for testing, and would prefer to not break magicdns on my main workstation for testing purposes. I'm not invested enough to bother, since I looked into this mostly as an excuse of learning more about how GPOs and Windows DNS works.

But everything I'm seeing suggests that just setting the values in `HKLM\Software\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig\{GUID}`, and running `gpupdate /force` should work fine even on a home edition (which don't support being connected to a domain). 

2. I'm really surprised to hear that rebooting was not enough. It should work, although obviously rebooting is not something that users would tolerate tailscaled doing on its own initiative!! Indeed even rebooting is overkill. My testing suggested that even restarting the DnsCache service that is enough. However Microsoft has denied all users the right to stop that service, so to "restart" it, you need to find the ProcessID of the service from task manager, then go to the process tab, and kill it (the service manager will think it crashed, and auto restart it). Once again that would be a totally unacceptable thing for tailscaled to do. but is a much faster option for manual testing than a full reboot.

The service only monitors the non-policy registry keys directly. For the policy registry keys it relies on RegisterGPNotificationInternalWorker, which is obviously an internal variant of version of the [RegisterGPNotification](https://docs.microsoft.com/en-us/windows/win32/api/userenv/nf-userenv-registergpnotification) API. The API triggers an event handle on group policy changes, which the service monitors for, and resets the event, and then reloads the relevant keys from the registry.

It looks to the be only scenario in which the dnscache service it reads the policy keys, except at startup. (Hard to be certain from a quick and dirty reverse engineering session. And sadly I don't have a copy Win 10 or Win 11 source code. 😄). Which is why I think the only way to make it work is to actually make windows apply a GPO. "gpupdate /force" is the main supported api for doing this. There is a COM based API for editing local group policy (`IGroupPolicyObject`) which will also apply it when closed, but you really don't want to try to touch that API directly from a golang program. .NET has better COM interop, and even there I wouldn't bother.

Hope this helps.

**Comment by trentcainbp** [comment]
@sailorfrag @KevinCathcart @dblohm7 I've been in contact with Tailscale Support who advised me of this issue (Thanks Keli!). We are having a similar issue where Split DNS is not working on our domain joined Windows 10 machines. The difference for us is that we are **not** configuring NRPT via Group Policy.

What seems to be happening for us is that when Group Policy is applied and/or refreshed, it creates a empty DnsClient and DnsPolicyConfig key (HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig). When this empty DnsPolicyConfig key exists, Split DNS does not resolve correctly and Get-DnsClientNrptPolicy returns no results. 

The workaround for us at the moment is to manually delete the empty DnsPolicyConfig key and reconnect to Tailscale. Upon reconnecting, DNS resolves correctly and Get-DnsClientNrptPolicy returns the NRPT policy that Tailscale has created. Another temporary workaround we are considering is to configure NRPT via Group Policy with the same settings that Tailscale is adding.

I just wanted to mention this as I wasn't sure if this scenario would be covered under this issue or not.

**Comment by trentcain** [comment]
@sailorfrag @KevinCathcart @dblohm7 I've been in contact with Tailscale Support who advised me of this issue (Thanks Keli!). We are having a similar issue where Split DNS is not working on our domain joined Windows 10 machines. The difference for us is that we are not configuring NRPT via Group Policy.

What seems to be happening for us is that when Group Policy is applied and/or refreshed, it creates a empty DnsClient and DnsPolicyConfig key (HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig). When this empty DnsPolicyConfig key exists, Split DNS does not resolve correctly and Get-DnsClientNrptPolicy returns no results.

The workaround for us at the moment is to manually delete the empty DnsPolicyConfig key and reconnect to Tailscale. Upon reconnecting, DNS resolves correctly and Get-DnsClientNrptPolicy returns the NRPT policy that Tailscale has created. Another temporary workaround we are considering is to configure NRPT via Group Policy with the same settings that Tailscale is adding.

I just wanted to mention this as I wasn't sure if this scenario would be covered under this issue or not.

**Comment by KevinCathcart** [comment]
> I've been in contact with Tailscale Support who advised me of this issue (Thanks Keli!). We are having a similar issue where Split DNS is not working on our domain joined Windows 10 machines. The difference for us is that we are **not** configuring NRPT via Group Policy.

This issue might also occur if you are setting any dns client settings via group policy (the documenting is unclear, and I did not investigate that myself), but it also sounds like you are not doing that, given that the DnsClient key is empty, except for the DnsPolicyConfig subkey.

> What seems to be happening for us is that when Group Policy is applied and/or refreshed, it creates a empty DnsClient and DnsPolicyConfig key (HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig). When this empty DnsPolicyConfig key exists, Split DNS does not resolve correctly and Get-DnsClientNrptPolicy returns no results.

Right even the empty DnsPolicyConfig key can be problematic. It is however a bit odd that group policy is creating the empty key. The normal group policy registry mechanism tends to delete empty keys. The format does support requesting to create a key without specifying a value, and presumably that would prevent deleting the key for being empty. But it is not entirely clear why/how things would end up in such a state. The UI would not normally do that. It might be possible that trying to remove registry values from the gpo via powershell might do something like that? Not entirely sure.

I would suggest checking the registry.pol files for the various group policy objects applicable to the computers that get the key created, to see if any of them mention the key in question. These files are a mixture of text and binary data. They can be viewed (inconviently) with a text editor or hex editor. Because it is Windows, the text portions are encoded in UTF-16. If you can find a GPO that references the DnsPolicyConfig key, then I would suggest having your group policy admins recreate the group policy object, such that it no longer has the key. (Alternatively, it is probably possible to use powershell to get rid of the entry.)

If it is not that, then remaining possibilities are some form of group policy linked startup files creating the key, but I can't imagine why that would happen. Or that a group policy extension is creating it. This one might be possible, but does not feel especially likely.

Lastly, if you are creating workstations from a base image, it is theoretically possible that it is the system group policy registry.pol file, but that would be really weird, as the ui does not use those keys for local group policy, and there is to much knowledge no cli for setting specific keys in the system GPO.

> The workaround for us at the moment is to manually delete the empty DnsPolicyConfig key and reconnect to Tailscale. Upon reconnecting, DNS resolves correctly and Get-DnsClientNrptPolicy returns the NRPT policy that Tailscale has created. Another temporary workaround we are considering is to configure NRPT via Group Policy with the same settings that Tailscale is adding.
> 
> I just wanted to mention this as I wasn't sure if this scenario would be covered under this issue or not.

The problem here is that tailscaled really needs to know if the keys are configured via group policy. We would only want it to specify NRPT keys on the group policy path if group policy is creating the dnsclient keys, as otherwise it would be preventing other dns configuration settings from getting read.

The algorithm I suggested above would not handle your case properly, since it relies on there being at least one registry value set other than the nrpt sub-key that tailscale would set, as an indication that group policy is creating the dnsclient key, since if group policy stops creating the key, tailscaled should also only be using the other path for NRPT settings. Of course, worst case, you could set some other dns client configuration policy to specify some default value, and then the algorithm I suggested should work.

I suppose tailscaled could use an alternative algorithm where merely checks for the dnsclient group policy key, and if present, creates its NRPT keys, with no cleanup mechanism, but that seems less desirable.

Hope this helps.

**Comment by trentcain** [comment]
@KevinCathcart thank you for the detailed reply. You are correct, it looks like one of our registry.pol files does contain a single entry for the DnsPolicyConfig key.

The .pol files are definitely a pain to work with. However, I came across a Windows PowerShell cmdlet ([GPRegistryPolicyParser](https://www.powershellgallery.com/packages/GPRegistryPolicyParser/1.0.0)) that can parse them. I was able to parse them and output the details to JSON using the following command:

```powershell
Get-ChildItem "C:\Windows\System32\GroupPolicy\*.pol" -Recurse | ForEach { @{File=$_.FullName;Values=(Parse-PolFile -Path $_.FullName)} } | ConvertTo-Json -Depth 10
```

In the JSON output I was able to find the below entry:

```json
{
   "KeyName":  "SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient\\DnsPolicyConfig",
   "ValueName":  "\u0000",
   "ValueType":  0,
   "ValueLength":  "0",
   "ValueData":  null
}
```

I'll reach out to our Group Policy Admins and see if they can remove this.

Thanks again for your help.

**Comment by dlowry-fl** [comment]
@trentcain we ran into a similar problem. Turns out the key was getting set in our "Domain Policy" and we were able to remove it with these commands:

```
Set-GPRegistryValue -Name "Domain Policy" -Key "HKLM\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig" -Type String -Value ""
Remove-GPRegistryValue -Name "Domain Policy" -Key "HKLM\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig"
```

HT: https://github.com/MicrosoftDocs/windowsserverdocs/issues/1527#issuecomment-509374326 (also provides an explanation why you need both commands)

**Comment by alduboishc** [comment]
Sorry to necro an old thread, but your suggestions did the trick. In my case, there were 2 offending GPO.
I wanted to share a guide on how to properly find and fix the issue for anyone stumbling on this thread.

Here's how I did it :

## Problem Description
We discovered that Tailscale's split DNS functionality wasn't working due to empty DNS policy settings in two Group Policy Objects (GPOs):
- Default Domain Policy
- Defender - Exclusions policy

## Resolution Steps

### 1. Identify Affected Policies
Run this PowerShell command to export all GPO settings:
```powershell
Get-ChildItem "C:\Windows\System32\GroupPolicy\*.pol" -Recurse | ForEach { @{File=$_.FullName;Values=(Parse-PolFile -Path $_.FullName)} } | ConvertTo-Json -Depth 10 | Out-File -FilePath "C:\gpo_export.json" -Encoding UTF8
```

In the exported JSON file, search for entries matching this pattern:
```json
{
    "KeyName": "Software\\Policies\\Microsoft\\Windows NT\\DNSClient\\DnsPolicyConfig",
    "ValueName": "\u0000",
    "ValueType": 0,
    "ValueLength": "0",
    "ValueData": null
}
```

### 2. Locate Policy GUIDs
Look for the full policy paths to find the GUIDs:
```
"File": "C:\\Windows\\System32\\GroupPolicy\\DataStore\\0\\SysVol\\domain.local\\Policies\\{POLICY-GUID}\\Machine\\Registry.pol"
```

### 3. Optional: Verify Policy Names
You can verify the policy names using:
```powershell
Get-GPO -Guid "POLICY-GUID"
```

### 4. Fix the Policies
Run these commands to clean up the empty DNS policies:
```powershell
# Fix Default Domain Policy
Set-GPRegistryValue -Name "Default Domain Policy" -Key "HKLM\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig" -Type String -Value ""
Remove-GPRegistryValue -Name "Default Domain Policy" -Key "HKLM\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig"

# Fix the custom policy
$CustomPolicyName = (Get-GPO -Guid "YOUR-POLICY-GUID").DisplayName
Set-GPRegistryValue -Name $CustomPolicyName -Key "HKLM\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig" -Type String -Value ""
Remove-GPRegistryValue -Name $CustomPolicyName -Key "HKLM\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig"
```

The issue occurs because empty DNSClient policy configurations block Tailscale's NRPT rules from functioning properly

**Comment by nickkhyl** [comment]
Re-opening due to the issue described in the comment above.

We can also use this to track further improvements to how we create NRPT rules when they're also managed via GP/MDM. A potential improvement is to write them to the LGPO instead of directly to the registry and/or avoid calling [`RefreshPolicyEx`](https://learn.microsoft.com/en-us/windows/win32/api/userenv/nf-userenv-refreshpolicyex).
