### ISSUE TITLE
ssh/tailssh: motd support

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#4627]
We don't do pam_motd. (https://linux.die.net/man/8/pam_motd)

OpenSSH Ubuntu default is:

```
UsePAM yes
```

Ubuntu has `/etc/pam.d/login` with:

```
# (Replaces the `MOTD_FILE' option in login.defs)
# This includes a dynamically generated part from /run/motd.dynamic
# and a static (admin-editable) part from /etc/motd.
session    optional   pam_motd.so motd=/run/motd.dynamic
session    optional   pam_motd.so noupdate
```

Its motd is updated by http://manpages.ubuntu.com/manpages/trusty/man5/update-motd.5.html

Maybe we should just best effort parse `/etc/pam.d/login` etc and try to act alike.

Worst case no MOTD (like today) and not the end of the world.

/cc @maisem @danderson @raggi @Xe

**Comment by maisem** [comment]
We can also try `cat /run/motd.dynamic` which works on ubuntu at least

**Comment by danderson** [comment]
If we do that we'd want to run through some well known locations (at least add /etc/motd to the list). But the format of pam_motd.so lines seems easy enough to grab the filename out of, and that'll work for every distro using PAM (all of them these days, I guess?)

**Comment by raggi** [comment]
It's tricky to say what the right answer is. There is also the `PrintMotd` and `PrintLastLog` options in sshd, and associated user-hints `~/.hushlogin`. There are additional steps to be covered if we start on the path I think, from the manpage:


1.   If the login is on a tty, and no command has been specified, prints last login time and /etc/motd (unless prevented in the configuration file or by ~/.hushlogin; see the FILES section).
2.   If the login is on a tty, records login time.
3.   Checks /etc/nologin; if it exists, prints contents and quits (unless root).
4.   Changes to run with normal user privileges.
5.   Sets up basic environment.
6.   Reads the file ~/.ssh/environment, if it exists, and users are allowed to change their environment.  See the PermitUserEnvironment option in sshd_config(5).
7.   Changes to user's home directory.
8.   If ~/.ssh/rc exists and the sshd_config(5) PermitUserRC option is set, runs it; else if /etc/ssh/sshrc exists, runs it; otherwise runs xauth.  The “rc” files are given the X11 authentication protocol and cookie in standard input.  See SSHRC, below.
9.   Runs user's shell or command.  All commands are run under the user's login shell as specified in the system password database.

**Comment by danderson** [comment]
So far the only request we've had is for motd printing. I'm personally okay to wait on those other things until anyone actually wants them, they all seem very niche to me (and I could argue, are super-specific to openssh, so we're welcome to deviate from what it does)

**Comment by crawshaw** [comment]
I did a little bit of googling because I didn't know the state of things. It looks like there's been no attempt to standardize the replacement of /etc/motd and we'd need to search for several possibilities. We can, but it's surprising.

**Comment by raggi** [comment]
I mean, on ubuntu if we wanted to have motd printed, it might be better just to run `login -f $USER` instead, in that case, as that'll go through all the pam modules, not just motd.

**Comment by maisem** [comment]
oh!! TIL `login`. I wonder how much of `incubator.go` it could replace?

**Comment by raggi** [comment]
It doesn't accept arguments to pass on to the shell, so you still need the other stuff for non-interactive invocations.
