### ISSUE TITLE
In-band signalling on Tailscale tunnels

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#464]
We have a couple of features in the pipeline:
 - Advertising routes from multiple nodes, with automatic failure detection & failover (requires peer healthchecking/BFD)
 - Smarter NAT traversal that relies on active communication between peers

For both of these, we need some way for the Tailscale daemons on either end to talk to each other securely. For obvious reasons, we'd prefer to not have to invent our own security stack for that purpose, since we already have a very good WireGuard doing heavy lifting. The channel doesn't need to be particularly high bandwidth, nor does it need to be lossless (at least for the above use cases).

Two obvious ways to go about this:
 - New DERP message types. We want the traffic to be private and secure end to end, so I _think_ this still involves inventing a new crypto stack, since right now the only e2e messages we carry are WireGuard ciphertext payloads - where the e2e aspect is handled by WireGuard itself.
 - Exchange packets through the WireGuard tunnels. With DERP we have guaranteed connectivity between the peers, so using the tunnel itself for our own purpose should be fine. We could park an old unused IP protocol (I'm partial to 0x10, "CHAOS") for the purpose, and inject/remove those packets within tstun for processing inside tailscaled.

cc @bradfitz thoughts?

**Comment by apenwarr** [comment]
I'd much prefer to avoid any direct coordination between peers whenever possible.

1. Advertising routes and failover: we can use wireguard to determine whether we have a valid connection to that node or not. If the node can't provide access to a particular subnet, it should tell the coordination server it can't handle those subnets anymore and rely on that to distribute status. Otherwise we have two sources of truth and have to choose between them.

2. For smarter NAT traversal, I think it makes sense to write out the specific type of communication we need between the two nodes and see what's the best way to exchange those messages (if messages are really needed).

Separately: we talked about removing endpoint information from the tailcontrol protocol and instead exchanging endpoint info only through DERP. This might improve privacy and also minimize useless tailcontrol updates. We might want to think about that at the same time.

**Comment by bradfitz** [comment]
I'd rather not rely on Wireguard working when part of the purpose of the signaling is to help Wireguard work. I know in theory it should and that we're really helping magicsock work, but it still makes me uncomfortable.

I'd prefer DERP messages. We can have a separate node keys that are only use for DERP nacl boxes and not wireguard.

**Comment by bradfitz** [comment]
> Exchange packets through the WireGuard tunnels. With DERP we have guaranteed connectivity between the peers, so using the tunnel itself for our own purpose should be fine. We could park an old unused IP protocol (I'm partial to 0x10, "CHAOS") for the purpose, and inject/remove those packets within tstun for processing inside tailscaled.

Update 6 months later: we now have TSMP using IP protocol 99.

**Comment by bradfitz** [comment]
Between Disco messages and TSMP, we have this at two different layers now, so closing.
