### ISSUE TITLE
Nameservers order

### ISSUE THREAD

**Issue by github0013** [tailscale/tailscale#4693]
### What is the issue?

![Tailscale](https://user-images.githubusercontent.com/809378/168709014-77d05d84-665c-4256-b5a5-87a72d528b83.png)

```
$ uname -a
Linux ubuntu 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ tailscale --version
1.24.2
  tailscale commit: 9d6867fb0ab30a33cbdfc8e583f5d39169dbb2e6
  other commit: 2d0f7ddc35aa4149e67e27d11ea317669cccdd94
  go version: go1.18.1-ts710a0d8610

$ cat /etc/resolv.conf
# resolv.conf(5) file generated by tailscale
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.120.120.94
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 2001:4860:4860::8888
nameserver 2001:4860:4860::8844
```

On Ubuntu, the order is as shown on the tailscale "DNS Nameservers" page.  100.120.120.94 comes first (my local DNS).
What my local DNS is doing is that I have multiple docker containers running and I am giving local specific hostnames to them. (e.g. mywebsite.test)

```
$ uname -a
Darwin m1a.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 arm64

$ /Applications/Tailscale.app/Contents/MacOS/Tailscale --version
1.24.2
  tailscale commit: 9d6867fb0ab30a33cbdfc8e583f5d39169dbb2e6
  other commit: 2d0f7ddc35aa4149e67e27d11ea317669cccdd94-dirty
  go version: go1.18.1-ts710a0d8610

$ cat /etc/resolv.conf
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
nameserver 2001:4860:4860::8888
nameserver 2001:4860:4860::8844
nameserver 100.120.120.94
nameserver 8.8.8.8
nameserver 8.8.4.4
```

Whereas on OSX, it seems IPv6s come first on top of the first entry `100.120.120.94` on that page.

This is crucial because if 100.120.120.94 doesn't come at the top, my local DNS can't correctly resolve the IP addresses for my local specific hostnames.

### Steps to reproduce

1. install tailscale
2. setup a local DNS server
3. set the IP address on the "DNS Nameservers" page (https://login.tailscale.com/admin/dns)
4. add 8.8.8.8 nameserver
5. check on "override local DNS"
6. `cat /etc/resolv.conf`

You will see nameservers are placed in different orders.

### OS

macOS

### OS version

11.6 (20G165)

### Tailscale version

1.24.2

**Comment by DentonGentry** [comment]
If it matters which nameserver is used to resolve a domain, you need to use Split DNS for that domain and only put the one DNS server in its list.

We have tried repeatedly to handle cases where there are multiple nameservers but only one of them will return the correct answer. That way leads to madness.
- Some operating systems send queries to all nameservers in parallel and use the first one which responds. Some operating systems round robin as a form of load balancing.
- No matter what the OS does in terms of ordering, DNS response from that first nameserver can be lost and result in sporadic and reproducible errors because one of the subsequent DNS servers gets used.
