### ISSUE TITLE
Admin panel overhaul: configure who's the admin, add logout button, etc.

### ISSUE THREAD

**Issue by Serrvosky** [tailscale/tailscale#47]
At this moment, it's not possible to do the following basic action:

- Promote another user to admin (at this moment, only the first user to login in a domain is the admin)
- Logout
- ...

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171687447992101) by [Unito](https://www.unito.io/learn-more)

**Comment by danderson** [comment]
Yup, we're aware the admin UI needs a bunch of work. In the meantime, if you need things like promoting new admins, please email support@tailscale.com and we can help you out.

**Comment by rosszurowski** [comment]
Closing this out since we launch a big rev of the admin panel a while back. It's now possible to manage which users are admins, view more detailed information about machines, logout (ha), and more.

Of course, we still have lots of work to do, but we can file and track those feature requests separately.
