### ISSUE TITLE
iOS encrypted dns not working with Tailscale active

### ISSUE THREAD

**Issue by dragon2611** [tailscale/tailscale#4741]
### What is the issue?

It seems on iOS having the tailscale vpn profile active bypasses encrypted dns settings.

Note: I tried both the dns profile set by the nextdns app and uninstalling their app and using a apple config profile.

### Steps to reproduce

Use an encrypted dns provider (nextdns in this case) on Cellular data

Enable tailscale (even if dns is not setup on tailnet)

Discover iPhone is using the cellular carriers dns server. 

Switching to another vpn config in iOS settings restores encrypted dns.

### OS

iOS

### OS version

15.5

**Comment by DentonGentry** [comment]
This might be https://help.nextdns.io/t/35hlk1r/known-issues-with-iosmacos-system-encrypted-dns-doh-support

**Comment by dragon2611** [comment]
It seems not to reset when you turn tailscale off via the app either.

I might try setting dns options on the tailnet and leaving tailscale on.

**Comment by andriej** [comment]
I agree, came here to report that disconnecting (making Tailscale inactive) on latest iOS does not turn on encrypted DNS - which was not happening with other VPN clients. 
That's the only issue I have with iOS app.

**Comment by DentonGentry** [comment]
In Tailscale 1.32 [one can configure NextDNS](https://tailscale.com/blog/nextdns/) in https://login.tailscale.com/admin/dns, and the iOS device will use DNS-over-HTTPS to reach it.

**Comment by andriej** [comment]
Issue was after de-activating tailscale - iOS with active nextDNS had it removed.
Does this news mean it's fixed?

**Comment by agottardo** [comment]
> Issue was after de-activating tailscale - iOS with active nextDNS had it removed.
> Does this news mean it's fixed?

@andriej Are you still experiencing this? If you have a DoH profile installed by an app like NextDNS, turning off the Tailscale VPN tunnel should automatically restore NextDNS. That's the behaviour I see on my iPhone. Do you not see that happening on your device?

**Comment by SRugina** [comment]
@DentonGentry I believe this problem is solvable for iOS, at least if the iOS app functions similarly to the official wireguard client ~~(if only the tailscale client were open source, then we'd know)~~.

Tailscale needs to set the `DNS` servers of the wireguard profile that it sets up to `0.0.0.0/32, ::/128` and one can use https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/ to calculate the `AllowedIPs` excluding `0.0.0.0/32, ::/128` and including whatever the partial tunnel tailscale uses is (can't remember off the top of my head). This essentially excludes iOS's internal DNS from the VPN profile, hence allowing a DoH DNS profile like the one from https://apple.nextdns.io/ to function even with tailscale active.

The above should only work when override local dns is off / mullvad exit nodes are not used which is good as we don't want dns to leak in those scenarios, since I assume tailscale is using a full tunnel when those options are used (i.e. `AllowedIPs` is `0.0.0.0/0, ::/0` which does prevent iOS from using any of its own dns profiles).

This is based on [a guide to using nextdns with mullvad vpn](https://www.reddit.com/r/mullvadvpn/comments/x6b3dq/guide_nextdns_mullvad_wireguard_doh3_on_ios/) under the `Mullvad (WireGuard) steps:` heading, which I've successfully modified to use ProtonVPN for personal use to demonstrate that the steps work with any wireguard profile in the wireguard client.

Hopefully tailscale can easily modify the wireguard profile used internally to fix this issue :) even if the internals are quite different, given that the official wireguard app can do it, it must be possible for tailscale to do the same, it'll be [somewhere in their code](https://git.zx2c4.com/wireguard-apple/tree/)

**Comment by agottardo** [comment]
The latest version of the iOS app now available on TestFlight includes a **DNS Settings** view. It provides a switch to toggle **Use Tailscale DNS Settings**. When the switch is set to Off, it is now possible to use an encrypted DNS profile while Tailscale is running. 

We expect this change to roll out to all customers in Tailscale 1.56 for iOS. Closing this.
