### ISSUE TITLE
Too many connections causes local client issues

### ISSUE THREAD

**Issue by jhawk28** [tailscale/tailscale#4810]
### What is the issue?

We have 500+ machines connected to Tailscale. I want to run scripts using ansible. If I connect to too many at a time, the tunnels seem to die and I get errors like this:

UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 100.x.x.x port 22: Operation timed out", "unreachable": true}

### OS

macOS

### Tailscale version

1.24.1

### Bug report

BUG-e788f1602941ac0db46f906c1e1c5510557d072a075d15a7be50bc0e3606fbd1-20220607153713Z-ff45dec4bc9cec6a

**Comment by bradfitz** [comment]
How is Tailscale involved in this bug report?

Can your Ansible client SSH to 500+ non-Tailscale machines without similarly failing?

**Comment by jhawk28** [comment]
Yes. Tailscale tunnels stop working until I quit and restart Tailscale.

**Comment by DentonGentry** [comment]
The Tailscale app in the App Store is written using an Apple technology called a Network Extension. The extension for the Tailscale app is named IPNExtension.

The Network Extension APIs do not provide a way to modify the routing table which the IPNExtension previously set. Instead when there is a meaningful change in the tailnet, like addition or removal of a node, the IPNExtension has to clear the routing table and program a new one with /32 routing entries for each Tailscale IP address. The /32 route entries are used in order to co-exist with other potential users of the CGNAT space like various ISPs.

In an active tailnet with a number of nodes, there are frequent netmap changes requiring the routing table to be reprogrammed. If Chrome is trying to operate during the time the IPNExtension is doing this, it will result in the ERR_NETWORK_CHANGED error. I believe this is also likely involved in the SSH difficulty.

The 1.28 release for macOS changed the strategy for routing table programming:
- if no other interface in the system uses the CGNAT range, then program a single 100.64.0.0/10 route and never change it again
- if there are other interfaces using CGNAT, continue the current strategy of individual /32s which have to be cleared and re-added on any change

That said, there are relatively few cases where macOS will actually have a CGNAT IP address even if the ISP does use the range. A residential gateway or Wi-FI router will typically implement NAT and the macOS device will instead see a private IP address like 192.168.x.x. Mobile phones are far more likely to directly see a CGNAT address. So we expect in almost all cases that the IPNExtension on macOS will program 100.64.0.0/10, while iOS is more likely to fall back to individual /32 entries.

--------

All of which is a way of saying that I think this was fixed in 1.28.

**Comment by jhawk28** [comment]
I think this has improved, but it still happens.
