### ISSUE TITLE
Windows DNS Server serving tailscale ip addresses to non-tailscale nodes.

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#4829]
### What is the issue?

It appears that Windows Server which is running tailscale pulls the tailscale DNS information in to the Windows DNS server. 
Gathering more information, and will update here when I do. 

Internal reference: HS-2703

### OS

Windows

**Comment by dblohm7** [comment]
I've been reading [this document](https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-dns-dynamic-updates-windows-server-2003) and it looks like this feature is part of the Windows DHCP client and is configured when setting up the TCP/IP connection.

I think what's needed here is for us to figure out how to programmatically disable this feature for the Tailscale connection so that the machine's DHCP client isn't firing off requests to the domain controller to add DNS records.

**Comment by raggi** [comment]
There is also: https://docs.microsoft.com/en-us/powershell/module/nettcpip/new-netipaddress?view=windowsserver2022-ps

```
-SkipAsSource
Indicates whether an address is a primary IP address. This parameter identifies the primary IP address for outgoing traffic in a multiple IP address scenario. If this parameter is set to True, the addresses are not used for outgoing traffic and are not registered in DNS.
```

**Comment by raggi** [comment]
Some more detail: https://devblogs.microsoft.com/scripting/use-powershell-to-change-ip-behavior-with-skipassource/#do-ip-addresses-skip-when-no-one-is-looking

**Comment by JayWStapleton** [comment]
+HS 2225
These errors appeared to be associated with linkchange events for those logs.

**Comment by Rychveldir** [comment]
I installed tailscale on a domain joined Windows 11 client and this issue appears again. I made sure the flag in the nic properties was off (it was already off before) and i set the registry value, both had no effect, tailscale ip still gets added to domain dns as round robin.

**Comment by Rychveldir** [comment]
What is weird is that you can't easily check the flag in settings, because to access the DNS tab under advanced TCP/IP settings, Windows will throw an error "The adapter requires at least one IP address. Please enter one." For some reason the tailscale nic doesnt have an IP set.

**Comment by gr84fun** [comment]
I am having the same problem, this has been an ongoing issue. The Tail scale Nic is registering to the AD DNS even after the dynamic updates is turned off. In my particular case its a secondary app server that keeps registering the tailscale ip. Then my app stops working cause the client tries to access the database via DNS and is served the tail scale ip locally.

**Comment by gr84fun** [comment]
So i found there are two setting to check, i believe one has to do with if the machine with tailscale is a Client DNS vs if it has DNS installed on the machine itsself. Also after you make the changes you need to restart the machine for the changes to take effect, I am waiting till after hours to restart to test this theory.

**Comment by KlausHuber** [comment]
We also still see the same behavior. One of the servers (not a DC nor a DNS server) has Tailscale installed. The DNS client on this server announces itself on the DNS server (our DC) with the local IP as well as the Tailnet IP address (which is wrong imho). This makes the server unreachable for non-tailscale devices if they pick up the wrong A-record from the DNS server.

- Tailscale is latest version 1.66.4
- The DisableDynamicUpdate Registry key is set on the Tailscale interface (probably set by Tailscale agent)
- How should the -SkipAsSource parameter be implemented on the Tailscale interface? (which apparently doesn't have an IP address properly https://github.com/tailscale/tailscale/issues/4829#issuecomment-1670451272 )

For us, this issue is definitely *not* closed.
Any suggestions?

**Comment by Codelica** [comment]
From what we've seen (as of Tailscale 1.82.5) the registry entry made for this issue works for normal AD client hosts.  

However, it isn't enough to stop a Tailscale connected AD server running DNS service from adding it's Tailscale IP to its own host entry.  We also tried setting "RegisterThisConnectionsAddress" to false via Powershell which didn't work either. 

The only way we've found to stop a Tailscale connected AD server running DNS to not add it's Tailscale IP is to disable DNS service on the Tailscale interface.

**Comment by chiastail** [comment]
This does not work:
_"_The only way we've found to stop a Tailscale connected AD server running DNS from adding it's Tailscale IP is to disable DNS service on the Tailscale interface."_
because you can't disable this setting without a provided IP Adress in the GUI

**Comment by chiastail** [comment]
Tailscale continues to register the Tailscale IP address on domain controllers.
The registry setting to avoid this behaviour works with other servers and nodes.


As a result, services that access the DC via the DNS name sometimes receive the wrong IP address and then do not work randomly.
Very annoying.

You have to manualy edit the DNS Zone after each reboot.

**Comment by Codelica** [comment]
Disabling DNS service on the Tailscale interface worked for us, but wasn't a good solution as the interface seemed to get recreated (and activated) presumably via updates.  The final solution, which is working for us, was to add a registry entry as follows specifying the IP to use and then rebooting:

```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\DNS\Parameters\PublishAddresses
Data type: REG_SZ (string value)
Value: IP address [IP address]
```

Not ideal, but still working for us after about 3 months now.  It's discussed a bit here as Method 1: https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/a-record-registered-host-dns
