### ISSUE TITLE
control/controlclient: noiseClient dial doesn't use DNS bootstrap (dnsfallback) dialer

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#4845]
When we added the Noise dialer in 1.24.0 we lost the DNS bootstrap (dnsfallback) dialer support.  (found via debugging ticket http://go/hs/2307; details in https://github.com/tailscale/corp/issues/5702)

The Noise client now dow does:

```go
   conn, err := controlhttp.Dial(ctx, nc.serverHost, nc.privKey, nc.serverPubKey, uint16(tailcfg.CurrentCapabilityVersion), nc.dialer.SystemDial)
```

Where `nc.dialer.SystemDial` doesn't have any of the DNS fallback.

That means when somebody has a broken DNS config on their machine we can hit https://controlplane.tailscale.com/key?v=32 over TLS to get the key(s) but then the Noise dial to the same hostname fails, unable to find its IP address(es).

/cc @maisem @danderson

**Comment by mihaip** [comment]
As far as I can tell, this is already happening. The `nc.dialer.SystemDial` dialer is wrapped with a `dnscache.Resolver` that uses `dnsfallback.Lookup`:

https://github.com/tailscale/tailscale/blob/d6b8a18b09d2c24111777d51f79fd63680023438/control/controlhttp/client.go#L196-L206

Empirically it also appears to work (at least if I mess with Mac's DNS settings, the client is still able to connect).

Perhaps the issue that the user was facing was a slow DNS server, and we need to tweak the timeouts? Or we should reuse the `dnscache.Resolver` across calls, so that even if the initial call fails, the next call doesn't have to start from scratch in terms of looking up fallbacks?

**Comment by DentonGentry** [comment]
Barring further comment as it appears this is already implemented, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment]
Believed fixed by https://github.com/tailscale/tailscale/commit/42fd96409023f2d2d8ec0111c18e6be0c4791bad
