### ISSUE TITLE
net/dns: forward to systemd-resolved rather than returning an error?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#5120]
Linux running `systemd-resolved`.

`dig @100.100.100.100 google.com` hangs.

tailscaled says:

```
dns udp query: upstream nameservers not set
dns udp query: upstream nameservers not set
dns udp query: upstream nameservers not set
```

But `tailscaled` knows that `systemd-resolved` is running. Rather than that "upstream nameservers not set" error, should we just forward to 127.0.0.53?

Obviously we don't _have_ to make 100.100.100.100 always work for all names, but it'd be kinda nice for consistency to support than when easy.

Thoughts, @danderson, @twitchyliquid64, @maisem, @Xe?

**Comment by crawshaw** [comment]
Recalling a discussion from a while ago, I was confused because on Windows I believe 100.100.100.100 _does_ forward. I would like us to be consistent across OSes, which I believe we are not today.

**Comment by bradfitz** [comment]
The other thing it could do is forward to the fallback global DNS servers as configured in the admin console. (I think maybe we do that on macOS already?)

**Comment by danderson** [comment]
If systemd-resolved owns /etc/resolv.conf, then forwarding is safe to do. If it's not, then it's unsafe, because resolved switches to "forward to whatever's in resolv.conf" in that case, which will likely be us, and result in an infinite routing loop that pegs CPU at 100% (because no IP TTLs to save us).

In general, we cannot implement "forward to whatever would have handled this if tailscale weren't there", which is what "forward to the OS" means. Indeed, Apple OSes explicitly do _not_ want us to do that, and don't provide APIs beyond "hand the query to the OS and hope there's not a routing loop".

If we want to be consistent, the only behaviors we can implement are to not forward on any platform (which will break the WSL2 hack on windows), or forward to fallback DNS resolvers (and introduce one more reason why we can never remove that confusing concept from the admin panel). Or we can be inconsistent and only forward when the OS enables it, and we can prove that it's safe from routing loops.

**Comment by ryankask** [comment]
Should users affected by this change their configuration to make this work? 

It seems like DNS works for applications but running nslookup or dig I see “Status: SERVFAIL”.

**Comment by DentonGentry** [comment]
> Should users affected by this change their configuration to make this work? I’m using Arch.

On Linux, systemd-resolved works best: https://tailscale.com/blog/sisyphean-dns-client-linux/

**Comment by DentonGentry** [comment]
Based on https://github.com/tailscale/tailscale/issues/5120#issuecomment-1192204105 and the likelihood of introducing a DNS lookup loop, I don't think we can implement this as described.
