### ISSUE TITLE
Peer to peer connection isn't used

### ISSUE THREAD

**Issue by jrmuizel** [tailscale/tailscale#5127]
### What is the issue?

```
$ tailscale status
100.101.6.89    hawkman              jrmuizel@    linux   -
100.66.43.110   macbook-pro-4        jrmuizel@    macOS   active; relay "ord"; offline, tx 264376 rx 227224
```

```
hawkman$ tailscale netcheck

Report:
	* UDP: true
	* IPv4: yes, 63.245.212.198:36677
	* IPv6: yes, [2620:101:80f2:224:70a7:b6da:6754:9af5]:38121
	* MappingVariesByDestIP: true
	* HairPinning: false
	* PortMapping:
	* Nearest DERP: New York City
	* DERP latency:
		- nyc: 12.6ms  (New York City)
		- ord: 13.2ms  (Chicago)
		- dfw: 35ms    (Dallas)
		- sfo: 60.8ms  (San Francisco)
		- sea: 61.6ms  (Seattle)
		- lhr: 86.6ms  (London)
		- fra: 97.1ms  (Frankfurt)
		- sao: 128.3ms (São Paulo)
		- tok: 147.5ms (Tokyo)
		- syd: 205.2ms (Sydney)
		- sin: 215.1ms (Singapore)
		- blr: 231.7ms (Bangalore)
```

```
macbook-pro-4$ /Applications/Tailscale.app/Contents/MacOS/Tailscale netcheck
2022/07/22 15:11:06 portmap: [v1] UPnP reply {Location:http://192.168.0.1:1900/igd.xml Server:ipos/7.0 UPnP/1.0 Archer C7/2.0 USN:uuid:060b7353-fca6-4070-85f4-1fbfb9add62c::urn:schemas-upnp-org:device:InternetGatewayDevice:1}, "HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=100\r\nDATE: Fri, 22 Jul 2022 14:11:06 GMT\r\nEXT:\r\nLOCATION: http://192.168.0.1:1900/igd.xml\r\nSERVER: ipos/7.0 UPnP/1.0 Archer C7/2.0\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nUSN: uuid:060b7353-fca6-4070-85f4-1fbfb9add62c::urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\n\r\n"
2022/07/22 15:11:06 portmap: UPnP meta changed: {Location:http://192.168.0.1:1900/igd.xml Server:ipos/7.0 UPnP/1.0 Archer C7/2.0 USN:uuid:060b7353-fca6-4070-85f4-1fbfb9add62c::urn:schemas-upnp-org:device:InternetGatewayDevice:1}

Report:
	* UDP: true
	* IPv4: yes, 24.52.241.132:54154
	* IPv6: no
	* MappingVariesByDestIP: false
	* HairPinning: false
	* PortMapping: UPnP
	* Nearest DERP: Chicago
	* DERP latency:
		- ord: 60.7ms  (Chicago)
		- nyc: 60.8ms  (New York City)
		- dfw: 60.8ms  (Dallas)
		- sea: 73.2ms  (Seattle)
		- sfo: 76.6ms  (San Francisco)
		- lhr: 108ms   (London)
		- fra: 121.2ms (Frankfurt)
		- sao: 165.4ms (São Paulo)
		- tok: 188.2ms (Tokyo)
		- blr: 238.1ms (Bangalore)
		- sin: 247.1ms (Singapore)
		- syd:         (Sydney)
```

The reporting of UPnP is very intermittent and sometimes I get:
```
macbook-pro-4$ /Applications/Tailscale.app/Contents/MacOS/Tailscale netcheck

Report:
	* UDP: true
	* IPv4: yes, 24.52.241.132:59151
	* IPv6: no
	* MappingVariesByDestIP: false
	* HairPinning: false
	* PortMapping:
	* Nearest DERP: Chicago
	* DERP latency:
		- ord: 579.1ms (Chicago)
		- nyc: 579.5ms (New York City)
		- dfw: 602.1ms (Dallas)
		- sfo: 615.4ms (San Francisco)
		- sea: 622.8ms (Seattle)
		- lhr: 647.3ms (London)
		- fra: 672.7ms (Frankfurt)
		- sao: 702.2ms (São Paulo)
		- tok: 734.5ms (Tokyo)
		- blr: 836.2ms (Bangalore)
		- sin: 836.5ms (Singapore)
		- syd: 867.3ms (Sydney)
```

### OS

Linux, macOS

### OS version

Ubuntu 20.04.4, macOS 10.15

### Tailscale version

1.28.0

### Bug report

BUG-1c009264c5ab293a423ad3562054c257bdb9cc658742903cccffbf56ac60e457-20220722191446Z-91e1dd9ec1c656db

**Comment by DentonGentry** [comment]
At first glance, this appears to be hard nat at both ends and a portmapping implementation in one router which doesn't reliably work.

Is the issue that you want it to find a direct connection and it doesn't?

**Comment by jrmuizel** [comment]
Yeah, I want it to find a direct connection. Is there a way to get more debugging information out about why it's failing?

**Comment by DentonGentry** [comment]
One side is hard NAT, the inner source UDP port to outer source UDP port changes for every destination:
```
	* MappingVariesByDestIP: true
```
This means it can send to whatever destination port it wants, but cannot control its source port.

The other side is easy NAT, the inner:outer UDP source port map is the same for all destinations.
```
	* MappingVariesByDestIP: false
```
This means it can send to whatever destination port it wants, and we can predict what its source port will be. If the other end could control its source port, then this would be enough. They could get packets flowing through this NAT, they'd be able to control a 5-tuple to match what the NAT expects. But the other end is hard NAT and cannot control its source port.

With one end being hard NAT, the other end needs to be trivial NAT: allow any packet from any source port to reach the given destination port. Portmapping would accomplish this, and the machine with easy NAT does think it has portmapping available:
```
	* PortMapping: UPnP
```

However as you say, it appears to not actually work.

To go further we'd need details of the router and what we might be able to do. However we do not want that kind of personal information in public bug reports. Please send to support@tailscale.com, referencing this bug report, and include:
- a `tailscale bugreport` from the machine with easy NAT and portmapping
- some detail of what the router that intermittently reports portmapping. Also please look whether it has NAT-PMP or PCP available, two other portmapping protocols which may work more reliably.

I'm going to close this because the level of detail is no longer appropriate for a public bug report.

**Comment by kokroo** [comment]
> With one end being hard NAT, the other end needs to be trivial NAT: allow any packet from any source port to reach the given destination port.

I believe I am stuck in the same situation as the OP here.
The only thing I am unsure about is if my "easy side" allows a packet from any source port to reach the given destination port.
Can we add a field in the "netcheck" command to see if this behavior is true?
MappingVariesByDestIP only indicates if the port is predictable, it does not indicate if the port accepts incoming connections from any port on the other side.
