### ISSUE TITLE
`tailscale up` breaks networking (invalid DNS servers)

### ISSUE THREAD

**Issue by gouku** [tailscale/tailscale#5287]
### What is the issue?

When Tailscale is up Docker cannot pull images.

### Steps to reproduce

- install tailscaled in Debian with official install script
- sign in with the command prompted after installation
- run `docker compose pull`
- See the error

```
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 100.100.100.100:53: read udp 100.97.241.42:14169->100.100.100.100:53: i/o timeout
```

### OS

Linux

### OS version

Debian 11

### Tailscale version

1.28.0

### Bug report

BUG-6049b8b334f96ad86dc38d67b7575ef97037d24394f55de3df0dde48e4a374c9-20220803194426Z-716d607e4d53785f

**Comment by gouku** [comment]
It seems not only docker compose is not working. The whole networks are down after enable tailscale. 😣

**Comment by DentonGentry** [comment]
From telemetry:
`2022-08-03 19:40:32.635477299 +0000 UTC: dns: Resolvercfg: {Routes:{.:[100.100.2.136 100.100.2.138]} Hosts:7 LocalDomains:[beta.tailscale.net. example.com.beta.tailscale.net. ts.net.]+65arpa}`

100.100.2.136 and 100.100.2.138 are not nodes on this tailnet, these DNS servers are not reachable.

**Comment by gouku** [comment]
Anything I can do to resolve this problem?

**Comment by DentonGentry** [comment]
In https://login.tailscale.com/admin/dns, I believ you entered global DNS servers of 100.100.2.136 and 100.100.2.138. Those appear to be the DNS servers supplied by Alibaba Cloud, is that correct?

Unfortunately because Alibaba Cloud also uses the CGNAT range, the same range which Tailscale uses, those IP addresses can'd be used for DNS at the same time as Tailscale is trying to use it. You'd need to enter different DNS servers, like for example 223.5.5.5 and 223.6.6.6.

**Comment by DentonGentry** [comment]
Closing as an issue in network topology. Using the public IP addresses of Alibaba's DNS servers 223.5.5.5 and 223.6.6.6 should work.
