### ISSUE TITLE
4via6 routes - MagicDNS names don't include tailnet name

### ISSUE THREAD

**Issue by JayWStapleton** [tailscale/tailscale#5324]
### What is the issue?

Setting up a 4via6 subnet route, and `192.168.250.70.via-1` will resolve properly but `192.168.250.70.via-1.possum-mudpuppy.ts.net` will not. 

Ideally, both of these should work.

**Comment by bradfitz** [comment]
Even if we made 100.100.100.100 serve an AAAA record for `192.168.250.70.via-1.foo-bar.ts.net`, that doesn't mean `ping 192.168.250.70.via-1` would use it because that contains too many dots in it for the search suffix to be used. (See [`man 5 resolv.conf` and `options ndots`](https://man7.org/linux/man-pages/man5/resolv.conf.5.html))

We might have to switch to using hyphens, like `192-168-250-70-via-1` if we want our MagicDNS suffix(es) to catch it.

But now we have a potential namespace collisions.

We might want to start blocking MagicDNS from allowing names of that form.

/cc @danderson @maisem @mayakacz @DentonGentry

**Comment by bradfitz** [comment]
Hyphens was done in 66b4a363bdae217b0ad41924e13e12e67eccea02, released in 1.34.0: https://github.com/tailscale/tailscale/releases/tag/v1.34.0

/cc @maisem
