### ISSUE TITLE
tailscale cert doesn't work in docker image

### ISSUE THREAD

**Issue by yidongw** [tailscale/tailscale#5334]
### What is the issue?

The same issue has been mentioned in https://github.com/tailscale/tailscale/issues/5072 but it has not been fixed.

I'm opening a new issue trying to get some attention.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/commit/c6648db3336bfe10b40e7cf75d3a94ad1326fcc7 fixed the identified problem in https://github.com/tailscale/tailscale/issues/5072. I don't doubt there may still be a problem: what does it do? What does it print when it fails? And please include a "tailscale bugreport" from the system where it fails.

**Comment by yidongw** [comment]
exactly the same bug that is described in https://github.com/tailscale/tailscale/issues/5072. The author of that issue also commented the problem still exists

**Comment by telometto** [comment]
I'm experiencing the exact same issue. For me, the issue is that I'm using TrueNAS, so it creates containers by itself. Passing the command mentioned in https://github.com/tailscale/tailscale/issues/5072#issuecomment-1214334796 inside the running container yields and error. After which, it seems to create the cert, successfully, but the cert doesn't work.

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/5072
