### ISSUE TITLE
userspace-networking as exit-node without IPv6 connectivity breaks Chrome 104+

### ISSUE THREAD

**Issue by KayLEvans** [tailscale/tailscale#5425]
### What is the issue?

Unable to browse websites through exit node on google chrome. Chrome returns a ERR_CONNECTION_RESET error. Firefox and Safari works fine. I ran a wireshark capture on the tailscale vpn tunnel and it appears that chrome is trying to access the ipv6 address of the website however the exit node's ISP does not have any ipv6 capability, which I think is the cause of this error. If chrome has previously cached the ipv4 address of that website then it will work fine, but if you try to use incognito mode or guest mode in chrome then the connection reset error appears.

### Steps to reproduce

1. Advertise exit node on opnsense router.
2. Enable exit node in admin panel.
3. Activate exit node on tailscale client.
4. Attempt to browse websites using exit node. Chrome returns ERR_CONNECTION_RESET error. When exit node is disabled, browsing returns to normal as expected.
5. Use a different web browser and browsing works fine.

### OS

macOS

### OS version

MacOS Monterey 12.5

### Tailscale version

1.28.0

### Bug report

BUG-ada8048276570b184149432e6f7106aa37c0a258779dd63085611b52d9f593f8-20220813134359Z-2b4b0289c9e2c92b

**Comment by mclarence** [comment]
> Thanks for letting us know! Would you happen to know the ISP?

The ISP is TPG Australia.

I would like to add that I have replicated it on a windows machine as well. I have also used a different device (synology NAS) as an exit node and the same issue still persists.

**Comment by DentonGentry** [comment]
Interesting. We know of cases where the opposite happens, that the IPv6 ULA that Tailscale uses discourages Chrome from using IPv6: https://github.com/tailscale/tailscale/issues/2299

**Comment by ookees** [comment]
This is similar to what is happening to me as of Chrome 104. It happens on all chromium based browsers as of 104. Anything before 104 works. Safari works fine, Firefox also works but only if I turn off DNS over HTTPS. Turning off secure DNS in chrome doesn't fix it. This happens on both Mac and Android 13.

My exit node is a Mac running Monterey.

**Comment by willnorris** [comment]
For folks seeing this issue, can you confirm whether you have IPv6 connectivity on your network (specifically from your exit node)?  I'm guessing that you don't.  You can test at https://test-ipv6.com/

**Comment by ookees** [comment]
Tailscale's response to my support email:

We've got this tracked down to a change in how Chromium is choosing IPv6 routes over IPv4, regardless of the actual availability of that route. It's being advertised whether or not it works, and Chrome changed the priority of how it makes those attempts.

Our team is working on a fix, but it won't be immediately available. Because exit nodes are such a fundamental part of how Tailscale works, it's too late to make it into the next 1.30 release, because we'll need to some time to test and verify the changes. So, keep an eye out for 1.30.1 most likely.

In the meantime, if you can get IPv6 working, that's certainly an option. Failing that, you'll want to either use a non-Chromium browser, or a different exit node. What's happening is limited to certain types of exit nodes (like Synology, but not Raspberry Pi, for example), so changing either of those things should get things working for you until our fix makes its way out.

Many thanks for bringing this to our attention, and for working with us to get to the bottom of things! You can definitely follow along at https://github.com/tailscale/tailscale/issues/5425 for updates too.

**Comment by ookees** [comment]
> For folks seeing this issue, can you confirm whether you have outbound IPv6 connectivity on your network (specifically from your exit node)? I'm guessing that you don't. You can test at https://test-ipv6.com/

Yes, thats dependent on my ISP. Which from my understanding they don't support IPv6 yet in my area. From what I am reading it may be coming soon. But it may only be business customers at first. 

Chromium made a recent change that caused this. Thats why all my chromium based browsers before which believe was version 104 were working fine.

**Comment by willnorris** [comment]
Just to add a little more context to the response from our support team that @ookies posted above... 

The recent change in Chromium to how it handles ipv6 and ipv4 connections when DNS queries return both types of address is [discussed here](https://bugs.chromium.org/p/chromium/issues/detail?id=1351204#c15).  The problem arises when using a Tailscale exit node on a platform that uses [userspace networking mode](https://tailscale.com/kb/1112/userspace-networking/) (basically everything other than Linux) AND when an outbound IPv6 connection is not available.

In these cases, Tailscale will accept Chrome 104's IPv6 connection (which it attempts first, per the recent change above), but will then fail to make an outbound IPv6 connection.  From Chrome's perspective, the initial connection to the exit node succeeded, so it never fails over to IPv4.  But because the exit node has no outbound IPv6 connectivity, it goes nowhere.  This has always been the behavior in Tailscale, but because Chrome used to attempt IPv4 first, it was never noticed.

We have a working patch that fixes the issue by not establishing the client connection until we've verified that we also have an outbound connection.  As noted above, we won't get this into 1.30, but shortly thereafter.

In the meantime, the only workarounds we've identified are:

1. use a difference browser, something not based on Chromium 104
2. use a different exit node, one that doesn't use userspace networking (like a recent-ish linux box)
3. establish outbound ipv6 connectivity for your exit node

**Comment by patbranchaud** [comment]
Hello @willnorris, when should we expect an update on apple store? Thank you

**Comment by willnorris** [comment]
I feel like "never as soon as we would like" is the correct response from developers everywhere? 😖 

@DentonGentry would likely know what versions have been submitted to Apple for review.

In the meantime, you may already be aware, but there are [several ways to run Tailscale on macOS](https://tailscale.com/kb/1065/macos-variants/) which don't all rely on App Store approval.

**Comment by DentonGentry** [comment]
The 1.31.1 was submitted to the Apple review process yesterday. That is usually days not weeks, but we have no control nor even visibility into it. It is done when Apple says it is done.

**Comment by patbranchaud** [comment]
> I feel like "never as soon as we would like" is the correct response from developers everywhere? 😖
> 
> @DentonGentry would likely know what versions have been submitted to Apple for review.
> 
> In the meantime, you may already be aware, but there are [several ways to run Tailscale on macOS](https://tailscale.com/kb/1065/macos-variants/) which don't all rely on App Store approval.

Perfect thank you very much, I'll look into it

**Comment by edwardmp** [comment]
Still seeing this issue with Tailscale 1.34 on both exit node and client. Safari works fine, Chrome gives connection reset errors.

Are you aware of this? I do note that my exit node has IPV6 configured in ifconfig, but IPV6 doesn't actually seem to work.

**Comment by DentonGentry** [comment]
@edwardmp Please file a new issue, and make sure to include a `tailscale bugreport` while the problem is happening. It is likely not the same as this issue.
