### ISSUE TITLE
wgengine/magicsock: connectivity failure with BPF disco when SO_MARK in use

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#5607]
Machine 1: Linux, HEAD, two VLANs: 10.0.0.0/16 (the default route interface) and 10.2.0.0/16
Machine 2: Linux, HEAD, one VLAN: 10.2.0.0/16

If Machine 1 is run with `TS_FORCE_LINUX_BIND_TO_DEVICE=1` (to disable use of SO_MARK and force the net/netns SO_BINDTODEVICE mode), then `tailscale ping -tsmp` between the machines fails. But `tailscale ping` works regardless.

If I set `TS_FORCE_LINUX_BIND_TO_DEVICE=0` or set `TS_DEBUG_DISABLE_RAW_DISCO=1`, then `tailscale ping -tsmp` (and regular ping, etc) work.

/cc @danderson @andrew-d @raggi

**Comment by danderson** [comment]
Summary of debugging: this is an extreme edge case condition, but real. For this to happen, you need:

- A system `A` running linux, with magicsock binding to device instead of using SO_MARK (so either userspace mode or SO_MARK disabled by debug flag), and with the new BPF disco receive codepath enabled.
- A system `B` running linux with the normal SO_MARK mode.
- `B` lives on a single vlan `V1`, with router `R`.
- `A` lives on two vlans, `V1` and `V2`. It gets internet on `V2`, also via `R`.
- `R` allows traffic to flow between `V2` and `V1`.

![Drawing of cursed setup](https://user-images.githubusercontent.com/1918/189765164-5d01d001-8f4e-4afb-a825-44c50ddcc876.jpg)

In this setup, `A` can only send packets on `V2`, because that's the network that carries its default route. However, BPF can receive disco packets from both `V1` and `V2`, since it's a raw socket listening everywhere.

When `A` and `B` try to communicate, `B` sends a disco packet to `A` over `V1`. This packet arrives just fine since `A` and `B` are both on that network, and the BPF receive path receives and processes that disco packet on `A`.

`A` sends a disco pong in response, which gets sent on `V2` because `A` can only send on `V2`. The pong follows the default route and arrives at `R`, which cheerfully forwards the packet to `B` on `V1`.

`B` receives a disco pong, and goes "ah! this is a viable datapath for p2p traffic", and switches from DERP to p2p sending over `V1`. WireGuard packets arrive at `A`, and promptly get dropped because magicsock can only receive non-disco traffic on `V2`. Yet `B` is convinced that this datapath works, because every disco ping it sends gets an answer. Oops.

This is an exceedingly unlikely configuration to find yourself in: you'd have to have this unusual network topology, and additionally `A` would have to somehow have enough permission to install BPF programs, but not enough to use SO_MARK. Realistically, this only happens in troubleshooting situations where Tailscale folks force behaviors on/off by hand.

Nonetheless, #5608 fixes this by explicitly disabling the BPF receive path when SO_MARK sockets aren't in use, so that the "receive disco on any interface" behavior only takes effect when magicsock can also send on any interface.
