### ISSUE TITLE
FR: Tailscale Android app working with Samsung Secure Folder apps

### ISSUE THREAD

**Issue by masterpae** [tailscale/tailscale#5672]
### What are you trying to do?

I want tailscale to work for Secure Folder apps on Samsung phones

### What is the impact of not solving this?

No Secure Folder apps can access tailscale network at all.

**Comment by DentonGentry** [comment]
What happens when you try to use the Secure Folder app? It doesn't connect? It doesn't start?

**Comment by DentonGentry** [comment]
We'd need more information to go on. Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by DentonGentry** [comment]
return -ETIMEDOUT

**Comment by Sudlon** [comment]
I know this is closed but I think I may know what @masterpae ran into and and after quite some test work and debugging, I fixed it. Since I couldn't find anything on this and this thread is basically the only hit you get when searching for "tailscale secure folder" I think it might be useful to share my solution for anyone else running into this situation.

So, to make an app in the Samsung Secure folder work over Tailscale, you need to "install" and setup the Tailscale app in the Samsung secure folder as well (so not just in the "open" part of your phone). Apparently the traffic is not routed via Tailscale that is installed in the "open" part and any app in the Secure folder part just times out because it can't find the address it's looking for.
