### ISSUE TITLE
Mac userspace subnet router binding to wrong interface

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#5719]
On macOS, subnet routers forwarding connections on with netstack can bind to the wrong device when the machine has multiple NICs.

Situation from debug call:

* macOS (one of the GUI builds)
* three network devices (wired ethernet (primary), wifi, USB ethernet dongle with a /30 to a raspberry pi)
* `tailscale up --advertise-routes=192.168.1.0/30`

The netstack forwarding code gets the packet and does an outbound TCP dial but netns binds the socket to the primary wired ethernet's NIC instead of the USB ethernet dongle.

We should look at the routing table and pick the right device.

/cc @andrew-d @danderson @crawshaw @maisem @quinnypig

**Comment by andrew-d** [comment]
I'm pretty sure this is because this code here picks the default route (i.e. "to the internet") to bind to, rather than the route for a specific destination:
https://github.com/tailscale/tailscale/blob/0607832397046fd0acb73daf8e00ef17b171a5c6/net/netns/netns_darwin_tailscaled.go#L35

**Comment by andrew-d** [comment]
@bradfitz - Any chance you can get an (appropriately-redacted, if necessary) dump of `netstat -nr` from the system in question?

**Comment by bradfitz** [comment]
The line you link to is for tailscaled, not the GUI version. But similar.

I don't have the routing table output but it was as described above: a /30 on a separate link that wasn't the default route's.

**Comment by QuinnyPig** [comment]
I do; it's my system in question. Here's a partial dump just because it's wordy as hell, particularly on the ipv6 section; en0 is wired, en1 is wireless (same network), en8 is the other interface with a small network attached, utun5 is Tailscale. 
```
Internet:
Destination        Gateway            Flags           Netif Expire
default            192.168.1.1        UGScg             en0       
default            192.168.1.1        UGScIg            en1       
default            link#34            UCSIg           utun5       
10.98.32/28        link#22            UCS               en8      !
10.98.32.11/32     link#22            UCS               en8      !
10.98.32.15        ff:ff:ff:ff:ff:ff  UHLWbI            en8      !
100.64/10          link#34            UCS             utun5       
100.93.10.83       link#34            UHWIi           utun5       
100.99.181.129     link#34            UHWIi           utun5       
100.100.100.100/32 link#34            UCS             utun5       
100.100.100.100    link#34            UHWIi           utun5       
100.126.71.95      100.126.71.95      UH              utun5       
127                127.0.0.1          UCS               lo0       
127.0.0.1          127.0.0.1          UH                lo0       
```

**Comment by QuinnyPig** [comment]
Now that I'm not remote I can troubleshoot more accurately; what can I do to help?

**Comment by DentonGentry** [comment]
This may have been fixed by https://github.com/tailscale/tailscale/pull/5940, which went into Tailscale release 1.32.2 for macOS.

App Store releases go through a gradual rollout process which starts with 1% of the fleet on the first day and gradually increases, your Mac may not have been prompted to update yet. Visiting the App Store page for Tailscale should show the update as available even if it hasn't prompted an update yet.

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/tailscale/pull/5940

**Comment by fylie** [comment]
**Reopening since we have another report of this issue.**


The report was on version: TestFlight 1.35.99, commit ID a45c9f982ae2b10f790f37abd8c8e6cfe495cbe5


Some details from investigating with @mihaip and @andrew-d : 
Based on logs, we can see that `en0` is consistently chosen as the default route, which results in dropped packets meant to go to other interfaces. The [routing code](https://github.com/tailscale/tailscale/blob/11ce5b7e57bbf67ed89f404e9e5b3a8ac14c7723/net/netns/netns_darwin.go#L32-L44) for macOS just selects the default route, while Linux does [something a little different](https://github.com/tailscale/tailscale/blob/11ce5b7e57bbf67ed89f404e9e5b3a8ac14c7723/net/netns/netns_linux.go#L105-L109) that results in setting the bypass mark and not explicitly binding to an interface.

To fix this, Mihai thinks that we’d need to loop over all interfaces and if any have explicitly set `InterfaceIPs` that matches the target address, prefer that over the default.

**Comment by DentonGentry** [comment]
I believe https://github.com/tailscale/tailscale/pull/7065 is available in the current macOS TestFlight.

**Comment by DentonGentry** [comment]
Believed fixed by https://github.com/tailscale/tailscale/pull/7065
