### ISSUE TITLE
systemd-resolved is not detected, tailscaled overwrites /etc/resolv.conf

### ISSUE THREAD

**Issue by Subbeh** [tailscale/tailscale#5811]
### What are you trying to do?

Tailscale updates `/etc/resolv.conf` automatically and adds tailscales domains before any local domain.

This causes dns lookups to always use tailscale over any local name resolution and there is no option that I know of to change this.

To illustrate this, these are the contents of my resolv.conf file:
```
nameserver 100.100.100.100
search tailnet-xxxx.ts.net myemail.gmail.com.beta.tailscale.net mydomain
```

In order to make this work for my local network, I need to move my own domain forward manually to have precedence over the tailscale domains:
```
search mydomain tailnet-xxxx.ts.net myemail.gmail.com.beta.tailscale.net
```

### How should we solve this?

Add an option to choose the precedence of domain names to search

### What is the impact of not solving this?

I am unable to access local domains

**Comment by DentonGentry** [comment]
I know this was filed as a request for the specific feature, but if you'd include the output of `tailscale bugreport` we could help get the system to do what you want in other ways.

That a 100.100.100.100 nameserver is added implies that `tailscaled` has gone into its Direct mode where it overwrites /etc/resolv.conf and tries to handle all of the DNS lookup internally.

On Linux, if `tailscaled` can detect that `systemd-resolved` is running it will not write 100.100.100.100 and will add its configuration to `systemd-resolved` instead. In almost every way, if you want more control over what happens with DNS lookups then we should figure out how to get `systemd-resolved` to be in control and you can make adjustments to its configuration. It has a lot.

--------

We've tried various forms of ordering within the DNS settings, between the order in which nameservers appear or in which search domains appear.

- Some operating systems send queries to all nameservers in parallel and use the first one which responds. Some operating systems round robin as a form of load balancing.
- No matter what the OS does in terms of ordering, a DNS response from that first nameserver can be lost and result in sporadic and nonreproducible errors because one of the subsequent DNS servers gets used.

We can't make such features work correctly across the whole tailnet. Instead we aim to work better with the platform DNS, and if you only need the one platform to do something then working with the platform DNS can accomplish it. For Linux, that means getting `systemd-resolved` to take over handling DNS.

**Comment by Subbeh** [comment]
@DentonGentry thanks for the quick reply.

I had previously disabled `systemd-resolved` but enabled it again as per your suggestion, but it doesn't seem to have the desired effect:
```
$ systemctl status systemd-resolved
● systemd-resolved.service - Network Name Resolution
     Loaded: loaded (/usr/lib/systemd/system/systemd-resolved.service; enabled; preset: enabled)
     Active: active (running) since Mon 2022-10-03 09:49:02 AEDT; 2min 49s ago
       Docs: man:systemd-resolved.service(8)
             man:org.freedesktop.resolve1(5)
             https://www.freedesktop.org/wiki/Software/systemd/writing-network-configuration-managers
             https://www.freedesktop.org/wiki/Software/systemd/writing-resolver-clients
   Main PID: 29097 (systemd-resolve)
     Status: "Processing requests..."
      Tasks: 1 (limit: 18808)
     Memory: 2.5M
        CPU: 78ms
     CGroup: /system.slice/systemd-resolved.service
             └─29097 /usr/lib/systemd/systemd-resolved

$ cat /etc/resolv.conf
nameserver 10.10.10.10
search mydomain tailnet-xxxx.ts.net myemail.gmail.com.beta.tailscale.net

$ systemctl restart tailscaled

$ cat /etc/resolv.conf
# resolv.conf(5) file generated by tailscale
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.100.100.100
search tailnet-xxxx.ts.net myemail.gmail.com.beta.tailscale.net mydomain
```

How does tailscaled determine if systemd-resolved is running? 

The output of `tailscale bugreport` is `BUG-1777032ac075c073d8af1777fb68ed51ad3681c3349a756a05351c04a14fcf57-20221002225717Z-e362d71a6f3ea46d`

**Comment by DentonGentry** [comment]
Please reopen the bug if `tailscaled` is still not able to determine that `systemd-resolved` controls the DNS settings.
