### ISSUE TITLE
Tailscale not detecting Docker Port Forwarding to Host 

### ISSUE THREAD

**Issue by byteshiva** [tailscale/tailscale#5813]
### What is the issue?

I'm forwarding a port eg 3000 from docker to host envionment. I have tailscale daemon  running on host. 

I'm able to do `curl http://localhost:3000/` on host environment but the same is not detectable in tailscale. Am I missing something here. 

### Steps to reproduce

1. Install `tailscale` on local linux environment.
2. `docker pull ubuntu` 
3. `docker run -i --expose=3000 <containe ip> bash`
4. `mkdir web && touch index.html && python -m http.server`

### OS

Other

### OS version

Linux  5.15.61-v8+ aarch64 GNU/Linux

### Tailscale version

1.30.2

**Comment by DentonGentry** [comment]
To be reachable over Tailscale the port would need to be bount to INADDR_ANY or to the Tailscale IP. Ports bound to localhost do not automatically become reachable over the tailnet.

--------

`tailscaled --tun=userspace-networking` actually does make localhost-bound ports reachable over the tailnet. Without a /dev/net/tun, that is the only way it can allow incoming connections.

I'd suggest adjusting the docker parameters to make the port be available to 0.0.0.0 though, instead of switching to userspace-networking

**Comment by byteshiva** [comment]
By settings IP address to 0.0.0.0:port (eg 0.0.0.0:8000) inside docker made it work.


Example:
```
touch index.html && echo "sample" > index.html
python -m http.server --bind 0.0.0.0 3000
```

**Comment by DentonGentry** [comment]
Seems to be resolved.

**Comment by metaskills** [comment]
Hope this helps someone else, I was having an issue getting this working with my Dev Container since I use `dockerComposeFile` and wanted to share the fix:

- https://github.com/devcontainers/spec/issues/245
