### ISSUE TITLE
tailscale android can't sign in 

### ISSUE THREAD

**Issue by ericmigi** [tailscale/tailscale#5916]
### What is the issue?

This happens every time I try to sign in, tried clearing cache, deleting/reinstalling etc

https://user-images.githubusercontent.com/1048265/195504147-d668f352-d279-4a34-bb67-c1d0c09201f1.mp4

![image](https://user-images.githubusercontent.com/1048265/195504131-e668b151-4202-48b7-b411-c8a5f686e3a3.png)

### OS

Android

### OS version

Android 12

### Tailscale version

1.31.167

**Comment by DentonGentry** [comment]
Sign in with Google uses a local, Android-specific authenticator which uses local Google account credentials (the accounts shown in Android Settings) to log in. I'm not sure what is going wrong, but since it happens before the device can join a tailnet it means we don't even get telemetry to see what it is doing.

Sign in with Other will open a browser window to log in, and one of the choices there will also be Google. That one uses any credentials stored for browser login, not accounts in the Android Settings, but as it takes a completely different path it might work even if the first one is failing.

**Comment by bradfitz** [comment]
Are you reporting a regression from a previous version of Tailscale for Android, or is this the first time you're trying to use Tailscale on Android?

Also: what phone? (or is this an emulator?)

**Comment by ericmigi** [comment]
first time I'm using Tailscale on this device. Asus zenfone 9. 

Happy to test anything else you suggest. Kinda amazed with how quickly yall respond, you are making me feel bad about my current linear backlog

**Comment by DentonGentry** [comment]
> Happy to test anything else you suggest

Mainly, please try "Sign in with Other" and then use the Google signin button on the web page it opens. This uses a very different OAuth flow than the Google button on the first interstitial page, and has a chance of working even when the first one does not.

**Comment by DentonGentry** [comment]
If "Sign in with Other" using the browser login flow doesn't work, please reopen the bug.

**Comment by GrahamboJangles** [comment]
It's still a bug, just because there is a "workaround" that sometimes works, it doesn't fix the bug
