### ISSUE TITLE
TestRouterStates fails without fwmask support, breaks Alpine builder

### ISSUE THREAD

**Issue by robertgzr** [tailscale/tailscale#5928]
### What is the issue?

https://gitlab.alpinelinux.org/robertgzr/aports/-/jobs/871792

```
--- FAIL: TestRouterStates (0.02s)
    router_linux.go:197: failed to determine ip command fwmask support: exit status 1
```

### Are there any recent changes that introduced the issue?

https://github.com/tailscale/tailscale/commit/f6da2220d30943181def1b48c97e95cbd1ddc01e

### OS

Linux

### OS version

Alpine Linux Edge

### Tailscale version

1.32.0

**Comment by twitchyliquid64** [comment]
Im out starting tomorrow till Monday but I'll make the test more robust then.

The root cause is that the `TestRouterStates` test does not adjust its expectations for a system with an old busybox `ip` binary (though the main code does).

A workaround in the meantime might be to use a more recent busybox install or to install the full ip utility.

**Comment by DentonGentry** [comment]
I don't think we'll have a fix until next week, I'd suggest that you disable that test in your fork for now.
