### ISSUE TITLE
FR: Control split DNS via API

### ISSUE THREAD

**Issue by DAlperin** [tailscale/tailscale#5932]
### What are you trying to do?

Control split DNS via the API.

### How should we solve this?

Extend the funtionality of `POST /api/v2/tailnet/:tailnet/dns/preferences`

### What is the impact of not solving this?

Cannot work on project

**Comment by willnorris** [comment]
self assigning to investigate how much work this will require.

**Comment by DAlperin** [comment]
Thank you!

**Comment by DentonGentry** [comment]
The public API is https://github.com/tailscale/tailscale/blob/main/api.md#tailnet-dns-nameservers-post

When we added SplitDNS, we added a private API which the admin panel uses. The private API added:
- SplitDNS
- Fallback Resolvers

The Fallback Resolvers have been the sticking point about documenting that API. We didn't really want to widely disseminate the requirement of having Fallback Resolvers in software which we don't control.

Fallback Resolvers are where the admin panel would require that you enter a global resolver even if "Override local DNS" was turned off. With "Override local DNS" turned off, in theory we shouldn't need to have a global DNS server: we're telling the client to use whatever DNS it got from DHCP.

Fallback Resolvers cover cases in a couple of the clients, notably macOS/iOS and Android, where they could not retrieve the list of DNS resolvers from the underlying platform. They could not implement having "Override local DNS" off in all cases because they couldn't figure out the local DNS servers the platform had.

The 1.20 client release at the beginning of 2022 removed the last remaining client requirements for Fallback Resolvers. Clients of 1.20 or later should no longer need to have a Fallback Resolver. However the control server still needed to handle the long tail of older clients in the field.

In late August 2022 we stopped requiring Fallback Resolvers to be entered. You can now set a DNS config where you enable MagicDNS and add a SplitDNS domain, you leave "Override local DNS" unchecked, and you are no longer prompted to enter a Global resolver.

--------

So, to have a public API which allows SplitDNS configured, we likely want to:
- copy the private API, but remove all fields concerning FallbackResolvers
- decide whether the Admin panel continues to use its private API or switches to the new public one
- decide whether we retain the saved config of any Fallback Resolvers we already have. There are still clients out there older than 1.20 which the coordination server would include Fallback Resolvers in.
