### ISSUE TITLE
Mac OS DNS not working with Little Snitch causing everything to stall

### ISSUE THREAD

**Issue by charlieporth1** [tailscale/tailscale#6049]
### What is the issue?

Tailscale on MacOS along with Little Snitch causes Tailscale 100.100.100.100 to cause a DNS failure . This also causes tailscale login to fail and stall

### Steps to reproduce

Little Snitch with Tailscale DNS

### OS

macOS

### OS version

12.6.1

### Tailscale version

1.32.1

### Bug report

BUG-35893509828d08d18c2a03e9b683b67d7b0f779d377205bf93994ec12f09344f-20221025002139Z-0f7dbb1d3baf5008

**Comment by bradfitz** [comment]
macOS forced Little Snitch to also become a Network Extension as of a few macOS releases ago. And macOS has/had problems with multiple Network Extensions existing at the same time.

Just to set expectations: there is very likely nothing we can do here. You can report this bug to Apple but you're about as likely to hear back from Apple as we are.

That said, are you sure it's not some Little Snitch setting you have enabled? Because we've heard of other people using Little Snitch + Tailscale together successfully.

**Comment by knyar** [comment]
Latest version is now 1.32.2, and unfortunately App Store does not allow installing old versions, but I installed 1.32.2 from the App Store and it seems to be working fine with Little Snitch (version 5.5, running in "alert mode"). I could log in successfully, and DNS resolving through 100.100.100.100 seems to work well:

```
$ dig spoon.tail12345.ts.net @100.100.100.100 +short
100.65.102.66
```

If you are still seeing this issue, could you please share a bit more details on how to reproduce it?

**Comment by charlieporth1** [comment]
Works
