### ISSUE TITLE
FR: "Clone" an auth key

### ISSUE THREAD

**Issue by iliana** [tailscale/tailscale#6098]
### What are you trying to do?

I have a few tasks that use GitHub Actions and auth keys to do things around my tailnet. These expire every 90 days, so every now and then I need to go make new keys with the same settings ("resusable", "ephemeral", set the tags). I'd like a less error-prone way to do this.

### How should we solve this?

I'd like a little "Clone..." link in the list of auth keys (both valid and recently invalidated), which would just prefill the "Generate auth key" form with however that one was set up.

### What is the impact of not solving this?

I'm at least able to view the configuration of older keys to see what I'm supposed to click, so I use that and create the replacement auth keys manually.

**Comment by DentonGentry** [comment]
A development effort which is very close to deliver is described in https://github.com/tailscale/tailscale/issues/3243#issuecomment-1253946534

The application would have a long-lived API credential, which would allow it to programmatically create authkeys. Because the issuance of the authkey would then be in code, I suspect it would no longer be an issue to repeatedly create new authkeys.

**Comment by iliana** [comment]
Hmm, although I quite possibly will keep using auth keys directly as secrets in GitHub Actions because then I don’t have to think about OAuth :) I agree the general usefulness (to others, not to specifically me) of this FR might diminish with that being implemented.

**Comment by DentonGentry** [comment]
Duplicate of https://github.com/tailscale/tailscale/issues/4904
