### ISSUE TITLE
FR: Report Tailscale SSH events for auditing

### ISSUE THREAD

**Issue by Starttoaster** [tailscale/tailscale#6107]
### What are you trying to do?

I would like to have visibility on who logs into any connected server using Tailscale SSH. Basically I would like to log created SSH sessions using Tailscale SSH.

### How should we solve this?

Send created SSH session events using Tailscale SSH to the new audit logs list in the web admin pane.

### What is the impact of not solving this?

Organizations that use Tailscale for SSH-ing into their servers will either have to create and manage their own solutions for logging SSH sessions, or will continue to have no visibility on what users authenticated to what systems.

**Comment by DentonGentry** [comment]
To set expectations: the config audit log feature recently launched includes events known to the coordination server, such as devices being removed or users being added.

Most SSH activity on the tailnet takes place without the coordination server being aware or involved, with the sole exception of check mode where it knows there is an authentication. It isn't practical for all SSH activity to appear in the configuration log.

There are 1-2 features coming which might prove suitable, however.

**Comment by eugene1g** [comment]
One use-case would be to know of _failed_ SSH connection attempts. Recently I updated ACL rules which broke connectivity for one of my developers, and they thought something was wrong on their side after an upgrade. They wasted 1-2 hours before escalating the issue to me. I should've known better, and since then I added new `tests` into our config. But it would be great to have a live log of `dropped` connections (SSH or otherwise).

Another use case is for infosec compliance - devops must demonstrate how they log all remote access attempts (successful or otherwise), and if we're routing all connectivity through Tailnet it would be awesome to have that log easily accessible for SSH (even if we need to get an extract every 90 days).

**Comment by Starttoaster** [comment]
> To set expectations: the config audit log feature recently launched includes events known to the coordination server, such as devices being removed or users being added.
> 
> Most SSH activity on the tailnet takes place without the coordination server being aware or involved, with the sole exception of check mode where it knows there is an authentication. It isn't practical for all SSH activity to appear in the configuration log.
> 
> There are 1-2 features coming which might prove suitable, however.

Seems reasonable to me that at least `check` mode could create a log in the Audit Logs then. I'm not too terribly sad if anything that's meant to bypass that check doesn't get retained in logs, because that's likely automation infrastructure rather than a human operator anyway. But all SSH events would be a nice-to-have.

Anyway, I appreciate the response and expectation setting :)

**Comment by DentonGentry** [comment]
I believe this is addressed by https://tailscale.com/kb/1246/tailscale-ssh-session-recording/
