### ISSUE TITLE
Question: How does DERP relay WebRTC over UDP?

### ISSUE THREAD

**Issue by stephenhibbert** [tailscale/tailscale#6195]
I have a use-case to send WebRTC over Tailscale - this is because I'd like to keep the benefits of low-latency, adaptive bitrate and UDP transport that come with the WebRTC protocol - but I would like to leverage the Tailscale overlay network for NAT traversal, signalling and DERP relay when required. 

Functionally, this works in my setup. My question is on performance - specifically... _does the DERP relay limit my transport options when using WebRTC?_

Natively with WebRTC, I understand that the protocol will try direct, then TURN/UDP, then TURN/TCP and finally TURN/TLS.

If I am in a situation when a relay is required, does the DERP implementation provide all of these options or only some? And finally, would you expect any other performance differences over native WebRTC?

**Comment by bradfitz** [comment]
DERP relays encrypted wireguard IP packets. They can be any IP blob of data. In fact DERP doesn't even know if they're wireguard or IP. They're just opaque bytes addressed to a public key. If there's webRTC down in there, that works as well as anything.

If your browser is doing webRTC over UDP to a Tailscale IP and that Tailscale IP doesn't have a direct path, that UDP packet will go over DERP (only TCP currently). The WebRTC peers may or may not decide that's their best option. They, like Tailscale, try a bunch of options and see what works best.

**Comment by DentonGentry** [comment]
(I see that Brad responded but I'd typed most of this so I'm just gonna post it)

Tailscle creates Wireguard tunnels on demand between nodes. If it can find a direct path between nodes it will send Wireguard in UDP frames. If there are too many intervening NAT devices or other reasons why the two nodes cannot get direct packets through, they will both make HTTPS connections to a DERP server and will send their Wireguard packets through HTTPS for the DERP to relay to each other.

In this environment, if you are using WebRTC between devices which are connected via Tailscale they would be packets flowing through the Wireguard tunnel. WebRTC would still be attempting its direct/TURN/etc path discovery, but `direct` would always work because the Wireguard tunnels between nodes will appear be a single hop with no NAT inside the Tailscale connection.

If you are using Tailscale to connect to your own devices and you use WebRTC to connect to a public IP, then Tailscale doesn't get involved. Tailscale is a split VPN by default, it only provides connectivity between your own nodes and allows public Internet use to go to your regular Internet connection. There is an [exit node](https://tailscale.com/kb/1103/exit-nodes/) feature which will route all traffic, but you have to choose to turn it on.

**Comment by stephenhibbert** [comment]
Thanks both for the quick and detailed response.

So I can confirm I see the behaviour you describe WebRTC path discovery working directly over the Tailscale IP when inspecting with the about:webrtc page in Firefox.

I can also see by running tailscale status on the WebRTC server that I am going via DERP - this is possibly because I am on an LTE network with several NATs and IPv6 -> IPv4.

So, to check my understanding… with the current implementation, DERP always uses HTTPS so it’s possible that we could see a latency/performance impact compared to a TURN/UDP relay because of the reliable delivery through the DERP server?

A feature request to mitigate this could be to implement DERP/UDP. And a potential workaround is to exit node - but in this setup (IoT device over LTE) that would need to be in the ISP network.

**Comment by bradfitz** [comment]
DERP over UDP has been discussed enough elsewhere (it'd be nice but not critical and isn't trivial) so I'm going to close this bug.
