### ISSUE TITLE
tailscaled: process management

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#627]
PR https://github.com/tailscale/tailscale/pull/626 reenables the systemd circuit breaker for tailscaled. This is not ideal (see @danderson's description on the PR of precisely what was happening before and after this change, we want neither). Ideally the service would restart an infinite number of times and use a backoff timer for restarting.

Is there any reasonable compromise we find acceptable using just systemd? If not, do we need our own process manager? The big downside is this gets us further into the process management business. The upside is it would do what we want, and be consistent behavior across various Unix environments (and non-systemd linux systems).

We already do process management in the Windows client. The core implementation of it is in [ipnserver.BabysitProc](https://github.com/tailscale/tailscale/blob/main/ipn/ipnserver/server.go#L277). If we do go this way ideally we would share that code.

**Comment by bradfitz** [comment]
I really don't want to do our own process manager on Linux. I want systemd-style `Type=simple` behavior with a single process.

I'd prefer to do our own sleep at start-up. If the filesystem where we store our failure history state is unwritable or otherwise unavailable, we assume the worst and do a big sleep with a big banner printed telling the user why we're starting slowly.

We can also do the magic logcatcher HTTP response header to have the client slow down.

And we make the logtail client, on HTTP failure to the logcatcher, also assume the worst and start a backoff sleep (keeping the failure count history on disk to be used as a sleep on subsequent restarts, again with the huge sleep fallback if history file is unavailable).

Both are important because not everybody will be in systemd (e.g. container crash looping). So in the container crash looping case, we want the logtail client to do its sleeps and not let the process exit until the sleep is done.

**Comment by DentonGentry** [comment]
Barring further discussion, I'm planning to close this in the next bug scrub.

**Comment by DentonGentry** [comment]
Going to close this as, almost a year later, I don't think we're considering using something other than systemd.
