### ISSUE TITLE
DNS stops working after sleeping

### ISSUE THREAD

**Issue by georgyo** [tailscale/tailscale#6298]
### What is the issue?

When my  Archlinux laptop sleeps over night, in the morning DNS resolutions do not work till I down/up tailscale (don't need to restart the actual process), turning off tailscale also solves the DNS problem.

The failing DNS happens even after tens of minutes of resuming from sleep, first few times made we wonder if my internet was having trouble. This is with configured with nextdns.

The tailscale logs give some hints, when these messages were sent I was able to do `dig google.com @8.8.8.8` without issue. 

```
Nov 12 08:00:05 glap tailscaled[771]: wgengine: Reconfig: configuring DNS
Nov 12 08:00:05 glap tailscaled[771]: dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
Nov 12 08:00:05 glap tailscaled[771]: dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
Nov 12 08:00:05 glap tailscaled[771]: dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[] Hosts:[]}
Nov 12 08:00:05 glap tailscaled[771]: magicsock: ReSTUN("link-change-minor") ignored; stopped, no private key
Nov 12 08:00:05 glap tailscaled[771]: magicsock: ReSTUN("link-change-minor") ignored; stopped, no private key
Nov 12 08:00:13 glap tailscaled[771]: [RATELIMIT] format("dns udp query: %v") (15 dropped)
Nov 12 08:00:13 glap tailscaled[771]: dns udp query: context deadline exceeded
Nov 12 08:00:15 glap tailscaled[771]: dns udp query: context deadline exceeded
Nov 12 08:00:15 glap tailscaled[771]: [RATELIMIT] format("dns udp query: %v")
```

 I can send the full log to someone but it has mild secrets, mostly around nextdns.

### Steps to reproduce

Configure tailscale to use nextdns for magic dns

`tailscale up`

put laptop to sleep over night

wake up and not have DNS resolutions working

### Are there any recent changes that introduced the issue?

None

### OS

Linux

### OS version

Arch Linux (Rolling) 

### Tailscale version

1.32.2

### Bug report

BUG-bf0a9d4ebf130dc3c12bfb3372cc32f665a098d82518f942bff4d8f40c92a50e-20221112133151Z-4faad35670cc0ddd

**Comment by DentonGentry** [comment]
From telemetry:
```
2022-11-12 01:59:59.591127776 +0000 UTC: dns: resolvedIsActuallyResolver error: resolv.conf has no nameservers
2022-11-12 01:59:59.591168836 +0000 UTC: dns: [rc=nm resolved=not-in-use ret=direct]
2022-11-12 01:59:59.591226686 +0000 UTC: dns: using *dns.directManager
```

`tailscaled` decided that it should write to /etc/resolv.conf, and is fighting for DNS supremacy with some other process which is also trying to write to /etc/resolv.conf — most likely the DHCP client, since the issue is noted when resuming from sleep.

The best way to avoid DNS issues like this is to get `systemd-resolved` working. If `tailscaled` determines that `systemd-resolved` is in charge of the DNS configuration then it won't try to write to `/etc/resolv.conf` and will send its DNS config via DBus to `systemd-resolved` instead.

The `resolvedIsActuallyResolver` message above means that `tailscaled` found a comment in `/etc/resolv.conf` that `systemd-resolved` was in use but there was no `nameserver 127.0.0.53` line, which means the DNS config appeared to be broken.

Generally the way to resolve this is to make `/etc/resolv.conf` be a softlink to `/run/systemd/resolve/resolv.conf`

**Comment by georgyo** [comment]
I attempted what you suggested, but the problem happened again after a sleep of only an hour

```
# ls -lhva /etc/resolv.conf
lrwxrwxrwx 1 root root 39 Nov 12 18:59 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf
```
Since the tailscale DNS server is failing after the sleep, systemd-resolved is now has log messages to that affect.

```
Nov 12 21:51:56 glap systemd-resolved[380]: Using degraded feature set UDP instead of UDP+EDNS0 for DNS server 100.100.100.100.
Nov 12 21:52:01 glap systemd-resolved[380]: Using degraded feature set TCP instead of UDP for DNS server 100.100.100.100.
Nov 12 21:52:12 glap systemd-resolved[380]: Using degraded feature set UDP instead of TCP for DNS server 100.100.100.100.
Nov 12 21:52:22 glap systemd-resolved[380]: Using degraded feature set TCP instead of UDP for DNS server 100.100.100.100.
Nov 12 21:52:32 glap systemd-resolved[380]: Using degraded feature set UDP instead of TCP for DNS server 100.100.100.100.
Nov 12 21:53:51 glap systemd-resolved[380]: Failed to send hostname reply: Transport endpoint is not connected
```

**Comment by ceiphr** [comment]
Hello!

Same issue. Fedora 37.

Here's systemd-resolved's status:
![Screenshot from 2022-12-05 11-10-40](https://user-images.githubusercontent.com/21004034/205685692-79156517-6036-4534-af9f-08a8546ab329.png)

I believe Fedora has systemd-resolved correctly configured. `nameserver 127.0.0.53` can be found in `/etc/resolv.conf` and the logs in the screenshot seem to hint that tailscale is talking to `systemd-resolved` since `100.100.100.100` is used.

Please let me know if you need any more details.

**Comment by ceiphr** [comment]
Friendly ping. Is there a simple workaround for this? I love Tailscale and NextDNS. I'd really love to use both this way.

**Comment by DentonGentry** [comment]
@ceiphr it is not clear to me that you are seeing the same issue, please file a different bug.

----

```
Nov 12 21:52:01 glap systemd-resolved[380]: Using degraded feature set TCP instead of UDP for DNS server 100.100.100.100.
```

This actually does represent progress, in that they are not fighting for DNS supremacy any more. However we wanted `systemd-resolved` to win, but instead `tailscaled` won.

I think the most straightforward way to resolve this would be:
1. `systemctl stop tailscaled`
2. restore the default `systemd-resolved` resolv.conf file, by soft linking to ../run/systemd/resolve/stub-resolv.conf again
3. Make sure that /etc/resolv.conf now shows 127.0.0.53 as the nameserver
4. `systemctl start tailscaled`

**Comment by DentonGentry** [comment]
I'm going to assume that the root cause is fighting for DNS supremacy with a DHCP client, and that getting `systemd-resolved` to own the DNS setting will resolve it.
