### ISSUE TITLE
cmd/containerboot: `invalid proxy destination IP: ParseAddr(""): unable to parse IP`

### ISSUE THREAD

**Issue by stavros-k** [tailscale/tailscale#6300]
### What is the issue?

Installed with:

```shell
TS_ACCEPT_DNS: "false"
TS_AUTH_ONCE: "true"
TS_KUBE_SECRET: ts-tailscale-tailscale-secret
TS_ROUTES: 10.10.10.0/24
TS_SOCKET: /var/run/tailscale/tailscaled.sock
TS_USERSPACE: "false"
```

Got:

```shell
boot: 2022/11/12 16:56:23 Failed to enable IP forwarding: invalid proxy destination IP: ParseAddr(""): unable to parse IP 
boot: 2022/11/12 16:56:23 To run tailscale as a proxy or router container, IP forwarding must be enabled.
boot: 2022/11/12 16:56:23 You can either set the sysctls as a privileged initContainer, or run the tailscale container with privileged=true. 
```

To be honest, tried reading through the containerboot code, but I can't figure out why it executes that code path.

`TS_DEST_IP` is not even defined, and it defaults to `""`.

It should only enter that block when proxyTo(`TS_DEST_IP`) is not `""`...

### OS version

TrueNAS Scale / k3s

### Tailscale version

1.33.158

**Comment by danderson** [comment]
I think this was fixed by the PR you looked at, can you check with the tag `unstable-v1.33.177` ?

We started tagging the 1.33 builds as explicitly `unstable-...` to clarify that they're dev builds rather than stable. If you can still test with the latest unstable to make sure I fixed the bug, I'd appreciate it. For production/packaging use, the latest stable build is tagged with `stable`, currently that's `v1.32.2`. The version tags are going to be a bit messy until we release the next stable (1.34), because we didn't want to delete the previous confusing unstable tags and break people.

**Comment by stavros-k** [comment]
> I think this was fixed by the PR you looked at, can you check with the tag `unstable-v1.33.177` ?
> 
> We started tagging the 1.33 builds as explicitly `unstable-...` to clarify that they're dev builds rather than stable. If you can still test with the latest unstable to make sure I fixed the bug, I'd appreciate it. For production/packaging use, the latest stable build is tagged with `stable`, currently that's `v1.32.2`. The version tags are going to be a bit messy until we release the next stable (1.34), because we didn't want to delete the previous confusing unstable tags and break people.

Ah, couldn't figure out in which version this fix was added...
Will check and report!
Thanks

**Comment by danderson** [comment]
Yeah, our versioning scheme is fairly confusing, because the different numbering constraints of all the platforms we ship on force our hand a bit. I just checked, and `unstable-v1.33.177` was built 3 commits after the latest containerboot PR, so it should have the fix for DEST_IP as well, and the regression tests for it.

**Comment by stavros-k** [comment]
It works! Thanks!
