### ISSUE TITLE
DERP: avoid serving derps behind high level load balancers

### ISSUE THREAD

**Issue by raggi** [tailscale/tailscale#6478]
### What are you trying to do?

Serving a custom DERP on AWS.
DERP behind ELB fails due to the HTTP upgrade being incorrectly handled.

### How should we solve this?

We can provide additional diagnostic tools:

- [x] A run-once feature for derpprobe that makes it easier to perform a one-off validation of a derp instance.
- [x] Documentation that recommends against putting DERP behind proxies/load balancers.

### What is the impact of not solving this?

Running custom DERPs is troublesome, requiring internal knowledge of DERP requirements and behaviors.

**Comment by DentonGentry** [comment]
Additionally for those finding this issue: having multiple `derper` backends behind a load balancer does not work. That results in a split brain scenario where connectivity is broken to a different subset of the tailnet based on which backend as client happens to connect to.

**Comment by kylecarbs** [comment]
@DentonGentry if all the `derp` backends use `mesh` I believe it would work.

We're doing this and are currently unable to use [cloud load balancers](https://cloud.google.com/load-balancing/docs/https#illegal_request_and_response_handling).

Could derp us a WebSocket upgrade instead?

**Comment by DentonGentry** [comment]
> @DentonGentry if all the derp backends use mesh I believe it would work.

I understand. We do not document the mesh mode because it was too hard for us to support third party use of. People who do more than that are welcome to do so, but without support. I did not describe the mesh mode in this issue for that reason: we support one derp per region.

> Could derp us a WebSocket upgrade instead?

As of https://github.com/tailscale/tailscale/pull/3165 derper is supposed to support WebSocket. It was needed for the [Tailscale SSH Console](https://tailscale.com/blog/ssh-console/) which, running as WASM in the browser, needed WebSockets to the derp. Does WebSocket not work in your environment?

The non-WASM `tailscaled` never uses WebSocket, only the WASM client does.

**Comment by raggi** [comment]
The tasks documented in this change, and an additional derp check tool are done.
