### ISSUE TITLE
Official support for scoop package manager

### ISSUE THREAD

**Issue by dblohm7** [tailscale/tailscale#6497]
Shayne volunteered for this one.

**Comment by shayne** [comment]
Submitted https://github.com/ScoopInstaller/Extras/pull/9802

- [ ] Create issue to update hostinfo to detect packaging

**Comment by shayne** [comment]
We've landed in Scoop! As part of this, I updated the pkgs server to support serving checksums for all file URLs (just add `.sha256` to the end of the URL). This is important because it means we're fully compatible with their auto-update bot that will monitor for new releases and automatically update the spec with the new URL and checksum.

https://github.com/ScoopInstaller/Extras/blob/master/bucket/tailscale.json

**Comment by shayne** [comment]
Closing. Filed #6988 for hostinfo changes.
