### ISSUE TITLE
Google Cloud IAP tunnel uses service account of tailscale router

### ISSUE THREAD

**Issue by arnecls** [tailscale/tailscale#6504]
### What is the issue?

I have a tailscale router running inside a GCP VPC.
When connecting to another GCP instance via [os-login](https://cloud.google.com/compute/docs/oslogin) and [IAP](https://cloud.google.com/iap/docs/tcp-forwarding-overview), the service account of the tailscale router machine is used instead of the account of the user triggering the command.

It does not matter if I try to access the internal or external IP of that VM, which confuses me a bit.
If I disconnect from tailscale, everything works as expected.

My router configuration looks like this:

- A DNS route for `internal` to `169.254.169.254` (instance [metadata](https://cloud.google.com/compute/docs/internal-dns#access_by_internal_DNS))
- `169.254.169.254/32` is routed to the tailscale router
- The Google Cloud VPC subnet is also routed to the tailscale router

### Steps to reproduce

```bash
# Create a ${gcp_project} and deploy a tailscale router on a VM (config as described above)
# Add a firewall rule to allow IAP tunneling, see https://cloud.google.com/iap/docs/using-tcp-forwarding
# Enable os-login is on the ${gcp_project}
# Give user foo@bar.com os-login user or admin rights on the project (project owners have this by default)
# Create a new instance ${instance_name} on the project in zone ${instance_zone}
# Log in via gcloud auth as foo@bar.com 
# Connect tailscale

gcloud compute ssh ${instance_name} --project=${gcp_project} --zone=${instance_zone} --tunnel-through-iap

# Leads to
Error: googleapi: Error 403: End user credentials must match the user specified in the request. Request for user [ tailscale-router@${gcp_project}.iam.gserviceaccount.com] does not match the credential for [foo@bar.com]
```

### OS

macOS

### OS version

12.6

### Tailscale version

1.32.2-t54e8fa172

### Bug report

BUG-786c1345f4bc60363d358a9b143eb5a1e25f667ac8dd82cfbf7679d4828b61f5-20221125090946Z-9f84a098c2ffaf60

**Comment by arnecls** [comment]
I just realised that this also happens with using an IAP-tunnel.
So it seems like os-login is confused by the tailscale router for some reason.

**Comment by knyar** [comment]
I could not replicate this, but, if I understood you correctly, you have a GCP VM acting as a subnet router on your Tailscale network that exposes its local metadata server (169.254.169.254) to other users on the tailnet. This means that any device on the tailnet can now fetch [service account credentials](https://cloud.google.com/docs/authentication/application-default-credentials#attached-sa) associated with that GCP VM. I suspect `gcloud compute ssh` is trying to do that, and this is why you are seeing a 403 error that mentions the VM service account.

When you disable Tailscale, the metadata server endpoint (169.254.169.254) is no longer reachable via the subnet router, and gcloud is using some other auth method.

In general I would advise against exposing the metadata server to other users on your tailnet, since it is designed to only be reachable from within the VM. If you are doing this purely to get `.internal` DNS names resolved, I would probably suggest to run a simple DNS resolver on the VM that would proxy requests for `.internal` to 169.254.169.254.

**Comment by arnecls** [comment]
> In general I would advise against exposing the metadata server to other users on your tailnet, since it is designed to only be reachable from within the VM. If you are doing this purely to get .internal DNS names resolved, I would probably suggest to run a simple DNS resolver on the VM that would proxy requests for .internal to 169.254.169.254.

That makes a lot of sense. I guess by doing this, gcloud (and other tools) think my Laptop _is_ the VM, as they can reach the metadata server. I'll try to use dnsmasq to expose a DNS endpoint instead (unless I find a DNS endpoint in GCP I can talk to)

**Comment by arnecls** [comment]
Turned out the easiest way to do this is to create a DNS policy in GCP like this

```bash
gcloud dns --project=YOUR_VPC_PROJECT policies create inbound-dns --description="expose dns endpoints per subnet" --networks="YOUR_VPC" --enable-inbound-forwarding
```

Then do the following

```bash
gcloud compute addresses list --project=YOUR_VPC_PROJECT --filter='purpose="DNS_RESOLVER"' --format='csv(address, region, subnetwork)' | grep YOUR_TAILNET_ROUTER_SUBNET
```

The returned IP has to be added as a route and as a DNS resolver in tailscale.
Works like a charm.
