### ISSUE TITLE
running `tailscale up` causes network connection interrupt on Windows 

### ISSUE THREAD

**Issue by stevenbrix** [tailscale/tailscale#6763]
### What is the issue?

when trying to configure tailscale on our Windows machines, we want to run the `tailscale up` command over SSH. however, this command causes the network connection to drop so SSH just hangs (RDP will disconnect). we do this currently on all our Mac machines without problem.

### Steps to reproduce

1. connect to windows machine over ssh (RDP is also fine)
2. run `tailscale up`

### Are there any recent changes that introduced the issue?

No

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.32.3

### Bug report

BUG-12d8eaa086a1acc17112322c79459170833427b84335c7bfb20f4cdbb77f159c-20221216181346Z-f355d65f80191d59

**Comment by bradfitz** [comment]
More concretely, I think:

You were in "Unattended mode" on Windows (aka "server mode") and weren't running the GUI. Then `tailscale up` (without the `--unattended` flag) reconfigured `tailscaled` to bring it out out of server mode. Because the CLI's exit then transitioned the number of connected clients from 1 to 0, and you weren't then in server mode, it stopped the service.

The bug here is likely that a bare "tailscale up" is supposed to be a no-op if you're already running and not modify settings. Windows is a special case with its client-mode-by-default and "Unattended mode" to make it go into server mode, so that was likely overlooked somewhere.

cc @maisem @dblohm7

**Comment by bradfitz** [comment]
But I can't reproduce with Tailscale 1.34.1 now. We did a bunch of work in this area recently for Fast User Switching so I think we might've fixed this in the process.

@stevenbrix, can you upgrade and see if it's still a problem? If so, let us know how.

**Comment by stevenbrix** [comment]
ok i updated and it is indeed no longer happening, thanks!
