### ISSUE TITLE
Localapi no longer working on local port 41112

### ISSUE THREAD

**Issue by legowerewolf** [tailscale/tailscale#6777]
### What is the issue?

Before 1.34.1, I was able to connect to the localapi over `http://localhost:41112`. After upgrading, this endpoint no longer seems to be responding. Is this behavior intended, and if so, is there a new endpoint to use?

### Steps to reproduce

```powershell
PS> Invoke-WebRequest http://localhost:41112/localapi/v0/status
Invoke-WebRequest: No connection could be made because the target machine actively refused it.
```

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.34.1

### Bug report

BUG-ffb460934ee244f27913f9d01935a213031b6fb6e4bd2ea3110996016d22cf09-20221217203832Z-b285f812e79d47d4

**Comment by bradfitz** [comment]
Yes, that's intentional. We moved it to a named pipe on Windows as a defense in depth measure.

"tailscale debug local-creds" will run a localhost TCP HTTP proxy that you can use to hit it, but it doesn't use a predictable port number.

"tailscale status --json" will print out the JSON from your above example command.

Or you can speak HTTP to the named pipe. Or modify the "debug local-creds" to use a fixed port number. (maybe we should add a flag, @maisem?)

**Comment by legowerewolf** [comment]
Ok, thanks, good to know. Is there any documentation about the various localapi endpoints anywhere? The one I'm most concerned with right now is `whois`, but having an actual list somewhere would be helpful. Same with the peerapi.

**Comment by bradfitz** [comment]
Neither are really considered public, stable interfaces. The peerapi stuff we necessarily have to evolve a bit slower but we can still remove things once two nodes are past a certain point in time. The localapi can change from release to release if needed. But looking at the source code for the LocalClient methods in https://pkg.go.dev/tailscale.com/client/tailscale#LocalClient is probably the best best.
