### ISSUE TITLE
Web I/F Device hostname on hover event css is darker than it should be 

### ISSUE THREAD

**Issue by charlieporth1** [tailscale/tailscale#6793]
### What is the issue?

Device hostname on hover event css is darker than it should be.
This could be due to force dark mode being enabled on my chrome browser via "chrome://flags" however it just happened within the last 2 hours 
![image](https://user-images.githubusercontent.com/13573364/208530674-d5867cec-3542-452a-bc0d-16ad153c1947.png)

### OS

Other

### OS version

Web

### Tailscale version

Web

**Comment by bradfitz** [comment]
cc @rosszurowski

**Comment by rosszurowski** [comment]
Interesting, I didn't know Chrome had this "force dark mode" flagged feature.

From [what I've read of this feature](https://developer.chrome.com/blog/auto-dark-theme/), the recommended approach to fix rendering issues is to just use dark mode styles to correct bad colours. This isn't ideal: we don't want most users to see dark mode styling for a few elements while the rest of the page is still in light mode.

It seems like there is also a [JS-based auto dark mode detection](https://developer.chrome.com/blog/auto-dark-theme/#detecting-auto-dark-theme), but since this auto-dark-mode feature is hidden behind a flag, and the hover contrast issue only affects readability during hover, I'm inclined to hold off on fixing this until we implement dark mode generally — which we're working on at the moment (tracked in https://github.com/tailscale/tailscale/issues/2634).

If you come across any points in the UI where large blocks of text aren't readable or it's difficult to work with, please let me know and we can make a one-off fix.
