### ISSUE TITLE
timeout waiting for Tailscale service to enter a Running state

### ISSUE THREAD

**Issue by eochoa260** [tailscale/tailscale#6832]
### What is the issue?

We cycle EC2 nodes nightly that run `tailscale up` on startup and lately we've been getting intermittent alerts and have nodes that fail to register.  Tailscale output in our logs shows:

```
Complete!
Created symlink from /etc/systemd/system/multi-user.target.wants/tailscaled.service to /usr/lib/systemd/system/tailscaled.service.
timeout waiting for Tailscale service to enter a Running state; check health with "tailscale status"
```

### Steps to reproduce

The tailscale up command that we're running right after enabling the systemctl service:
```
tailscale up --hostname=${tailscale_hostname} --authkey=${tailscale_auth_key} --advertise-routes=${subnets_to_advertise} --advertise-tags=tag:ssh,tag:${vpn_tag} --ssh --advertise-exit-node --timeout=1m
```

### Are there any recent changes that introduced the issue?

We recently added the nightly cycling to all 5 of our ASGs but we were only cycling one ASG before.  Version was auto-updated to 1.34.0 and now 1.34.1 too.  

### OS

Linux

### OS version

Amazon Linux 2

### Tailscale version

1.34.1

### Bug report

BUG-dff9ca38c0cb8ec01cdb1913f7bcf58624df25dc665409eb7f87c7e5822deae5-20221223040551Z-528045b87bb0feba

**Comment by DentonGentry** [comment]
From what I can see around the time of the BUG line, the tailscale interface did come up and join the tailnet. Does that match your experience, that even if the `tailscale up` timed out that it nonetheless succeeded?

```
2022-12-23 03:54:25.650776527 +0000 UTC: Program starting: v1.34.1-t328b49c4d-g921b59a2e, Go 1.19.2-ts3fd24dee31: []string{"/usr/sbin/tailscaled", "--cleanup"}
...
2022-12-23 03:54:25.761865478 +0000 UTC: Program starting: v1.34.1-t328b49c4d-g921b59a2e, Go 1.19.2-ts3fd24dee31: []string{"/usr/sbin/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--socket=/run/tailscale/tailscaled.sock", "--port=41641"}
...
2022-12-23 03:54:26.278298418 +0000 UTC: Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
...
2022-12-23 03:55:26.804925459 +0000 UTC: control: direct.TryLogin(token=false, flags=2)
2022-12-23 03:55:26.804954967 +0000 UTC: control: LoginInteractive -> regen=true
```

The ASGs are just rebooting, or they are actually being destroyed and re-created? If just rebooted, it is possible that tailscale comes up because the saved config says to bring it up and `tailscale up` may not be doing anything successfully.

**Comment by rocktavious** [comment]
Prior to all of this we didn't have the `--timeout=1m` flag on and so the instance would just hang forever and never register and would prevent our bootstrap script from progressing to the next thing.

We've added the timeout flag and then wrapped `tailscale up` in a for loop and it does seems like the 2nd or 3rd try it finally works and enters a running and our bootstrap script move onto the next thing.

So this is what you are likely seeing - but about a week or two ago when we didn't have the for loop it would just hang indefinitely and never register to the control plane.

We don't reboot the instances nightly we just use AWS ASG scheduled action scaling to scale up and then back down (with a termination policy of OldestInstance) so that we effectively get a daily cycle of 1 or 2 nodes.

**Comment by rocktavious** [comment]
FWIW we also get this output

```
Failed with Exit Code: 1, retry attempt #1. <-- this is our for loop logging this
Some peers are advertising routes but --accept-routes is false
```

**Comment by DentonGentry** [comment]
`Some peers are advertising routes but --accept-routes is false`

That message was added in https://github.com/tailscale/tailscale/pull/6291/ and will be printed if `tailscale up` has already decided to exit for other reasons. It wouldn't cause `tailscale up` to hang or timeout on its own.

**Comment by eochoa260** [comment]
That's the message that I usually see once it connects.  This is the message I'm seeing right after the timeout before the retry:

```
timeout waiting for Tailscale service to enter a Running state; check health with "tailscale status"
```

I've checked the status before when it was hanging on the tailscale up command and it returned "Needs login" or something to that effect.

**Comment by DentonGentry** [comment]
I doubt this will be figured out now, glad it is working.
