### ISSUE TITLE
FR: 100.100.100.100 equivalent for ipv6

### ISSUE THREAD

**Issue by yangboyd** [tailscale/tailscale#6855]
### What are you trying to do?

Currently there is ipv4 100.100.100 in overwrittern /etc/resolv.conf
cat /etc/resolv.conf 
resolv.conf(5) file generated by tailscale
 DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.100.100.100

Is it possible to add ipv6 one for ipv6 network?

### How should we solve this?

Add ipv6 address to /etc/resolv.conf

### What is the impact of not solving this?

not work in ipv6 network

**Comment by bradfitz** [comment]
When you've set `disableIPv4` to `true` in your policy file (https://tailscale.com/kb/1018/acls/), we already do set `nameserver fd7a:115c:a1e0::53` in resolv.conf.

But if you want to use the Tailscale 100.x.y.z addresses in general but only one node in your tailnet is IPv6-only, well... it still seems to work.

There's no way to disable IPv4 on Linux, so even if you have a Linux device that's IPv6-only, hitting 100.100.100.100 for DNS still works (note that 100.100.100.100 doesn't leave the machine).

So I guess I don't understand the problem here.

While, we _could_ add both `100.100.100.100` and `fd7a:115c:a1e0::53` to the resolv.conf, I don't see what it solves.

@yangboyd, @wasabipesto, @justinia, can one of you elaborate?

/cc @danderson

**Comment by yangboyd** [comment]
In ipv4/v6 dual stack machine, some program use ipv4, some program use ipv6,  if both 100.100.100.100 and fd7a:115c:a1e0::53  in it, so all programs work fine?

**Comment by DentonGentry** [comment]
Even if not populated in /etc/resolv.conf, fd7a:115c:a1e0::53 will answer queries sent directly to it.

```
$ dig @fd7a:115c:a1e0::53  ubuntu.example.com.beta.tailscale.net

; <<>> DiG 9.18.1-1ubuntu1.3-Ubuntu <<>> @fd7a:115c:a1e0::53 ubuntu.example.com.beta.tailscale.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53064
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ubuntu.example.com.beta.tailscale.net.        IN A

;; ANSWER SECTION:
ubuntu.example.com.beta.tailscale.net. 600 IN A 100.102.2.100

;; Query time: 0 msec
;; SERVER: fd7a:115c:a1e0::53#53(fd7a:115c:a1e0::53) (UDP)
;; WHEN: Sat Feb 18 18:39:57 PST 2023
;; MSG SIZE  rcvd: 110
```
