### ISSUE TITLE
FR: Split tunneling on Android

### ISSUE THREAD

**Issue by Victor239** [tailscale/tailscale#6912]
### What are you trying to do?

Currently I use Mullvad VPN and it allows me to use the split tunneling feature to exclude multiple apps from being routed via the VPN. When I instead use Tailscale + the exit node feature to replicate Mullvad functionality I don't see any way I can exclude specific apps from being routed via the VPN. 

### How should we solve this?

Implement split tunneling like Mullvad.

### What is the impact of not solving this?

Still using Mullvad VPN instead.

**Comment by Rihcus** [comment]
I don't think this will work directly since both ios and android allow only one vpn to be active at a time. There are only two ways I can think of for this to be done.

1. Add an option in tail scale to split tunnel with an openvpn or wireguard config (to avoid the two apps and only one vpn interface can be active at the same time issue).
2.  (Android Only) You can download an app like shelter which makes a work profile on your phone. You can for instance keep apps that need tailscale in the work profile while keeping apps that need mulvad in your standard profile (or vice versa.

**Comment by Victor239** [comment]
I'm not asking for supporting running two VPNs at once. I'm saying there's a feature that Mullvad VPN on Android has that should be added to Tailscale VPN also.

**Comment by danderson** [comment]
Yeah, that would make sense as a feature, I think. Thanks for the suggestion!

**Comment by Platun0v** [comment]
One guy started working on this feature, but no updates since the end of summer https://github.com/tailscale/tailscale-android/pull/56

**Comment by Ged-fi** [comment]
The lack of this feature breaks Android Auto. I.e. if I have Tailscale enabled, Android Auto won't be able to connect to the network until I disable VPN.  "Most other" VPN clients have support for split tunneling on Android precisely for this reason.

**Comment by Myned** [comment]
I ran into this while crafting an Automate flow to trigger Wake-on-LAN. The packet fails to send with:
```
android.system.ErrnoException: Binding socket to network 100 failed: EPERM (Operation not permitted)
```

I am able to split-tunnel the Automate app through e.g. Mullvad and it sends the packet properly, but the only mechanism for Tailscale is currently hardcoded (like Android Auto), which isn't necessarily a viable method for tasking apps like Automate or Tasker because one may want tasks to go through the VPN depending on workflow.

It's worth noting that the above occurs even without an active exit node.

This is also relevant for apps such as Netflix that explicitly block data center IPs, though this is only applicable for an exit node with a blocked IP.

I can take a look at that PR to see what needs to be done to make that process interactive, but any direction would be greatly appreciated.

Also @Ged-fi, the issue with Android Auto should have been solved with v1.30.0. https://github.com/tailscale/tailscale/issues/3828 may need to be reopened if that's not the case.

**Comment by Ged-fi** [comment]
@Myned I am on 1.36.1, experiencing issues with Android Auto just in the last week.  I will try to reproduce the issue.  It may be a local device problem, as often with Android - but perhaps worth checking that there isn't a feature regression somewhere?

**Comment by Myned** [comment]
I wasn't able to reproduce the problem with Android Auto using the latest master (v1.37.0-dev20230306) and the Android Studio desktop head unit. Internet access functions correctly on the device.

**Comment by Ged-fi** [comment]
@Myned I can confirm that this works under most conditions, but seems to occasionally break when networks change.  I have not been able to reliably reproduce what might be triggering the error condition, and it may also be device-specific.  My initial hunch is that the device switching between WIFI, 3G and LTE seems to sometimes cause DNS resolution to not work as expected.  However, troubleshooting this with only a standard handset is challenging at best.  I will update the ticket if I somehow manage to identify a way to reliably reproduce what I am seeing.

**Comment by Myned** [comment]
I could see what you're experiencing being related to https://github.com/tailscale/tailscale/issues/915, in that case.
Main workaround is to disable MagicDNS or Private DNS, if you have both enabled.

Regardless, this is perhaps a bit off-topic for this issue with split tunneling.

**Comment by TJuberg** [comment]
I keep running into the same problem. If I have tailscale enabled on my Android phone I currently need to turn this off whenever I am in my car for apps that want to communicate with the car over the built in Wifi (Android auto itself works fine finally) and when using payment app in stores (no.coop.members).

We really need to be able to specify apps that are excluded instead of having to create bug reports to get them added to the hardcoded exclude list like Android Auto.

**Comment by expoli** [comment]
How is the development progress of this feature? I feel that this feature is very necessary. Why has there been no corresponding progress for such a long time? Have there been any issues encountered?

**Comment by JeffsGitHubAccount** [comment]
Yeah hopefully we can see this feature get added at some point.

**Comment by agottardo** [comment]
Looking into this.

**Comment by amwalters** [comment]
I have installed the git version of the app and much appreciate this work.  I would like to additionally request the option to reverse the logic around app selection to support "included apps" as opposed to excluded apps.  For my use case I would like to select a few banking apps to route over the VPN, but allow all other apps to use the standard network.

**Comment by agottardo** [comment]
Shipped in v1.70! 🎉 

Details and instructions at https://tailscale.com/kb/1444/android-app-split-tunneling

**Comment by KyleFN** [comment]
Great to have this, would also love to see this on [Linux too](https://github.com/tailscale/tailscale/issues/7766).

**Comment by guidopetri** [comment]
@agottardo this still isn't working for me. On connection to Android Auto, I still get the same "please disconnect from VPN" message. I've confirmed that split tunneling is enabled and Android Auto is on the exclude list. Tailscale version 1.70.0-td601f16e1-g6deb61a20e5

**Comment by agottardo** [comment]
> @agottardo this still isn't working for me. On connection to Android Auto, I still get the same "please disconnect from VPN" message. I've confirmed that split tunneling is enabled and Android Auto is on the exclude list. Tailscale version 1.70.0-td601f16e1-g6deb61a20e5

Please open a new issue detailing which application is failing to work. This issue has been closed and should not be used anymore.
