### ISSUE TITLE
/etc/resolv.conf is overwritten causing DNS resolution issues

### ISSUE THREAD

**Issue by ecksun** [tailscale/tailscale#6925]
### What is the issue?

When starting tailscaled it overwrites /etc/resolv.conf with its own settings. I would like it to leave the file in place and manage those settings myself.

_EDIT: removed text about override.conf, that is not the example anyone seeing a similar problem should follow._

### Steps to reproduce

Basically as soon as tailscaled is started it overwrites the config, so the following reproduces the issue:

```bash
sudo systemctl start tailscaled
```

I'm running NetworkManager but not systemd-resolved.

### Are there any recent changes that introduced the issue?

I have only just started using tailscale and as such have only been using 1.34.2

### OS

Linux

### OS version

Debian bookworm

### Tailscale version

1.34.2

### Bug report

BUG-NO-LOGS-NO-SUPPORT-this-node-has-had-its-logging-disabled

**Comment by DentonGentry** [comment]
If at all possible we'd recommend using systemd-resolved instead of NetworkManager for DNS, we're much more able to send DNS configuration to it: https://tailscale.com/blog/sisyphean-dns-client-linux/

If you don't want the Tailscale DNS settings, you can:
- disable MagicDNS and all configuration in https://login.tailscale.com/admin/dns
- Use `tailscale up --accept-dns=false` on the specific node. For example --accept-dns=false on this NetworkManager node would prevent it from writing to /etc/resolv.conf.
- Modifying the systemd configuration is definitely not the way we'd recommend to do this.

> BUG-NO-LOGS-NO-SUPPORT-this-node-has-had-its-logging-disabled

This means we won't be able to do further diagnosis. no-logs-no-support means agreeing that there will be no support because all of the telemetry has been disabled.

**Comment by ecksun** [comment]
> If at all possible we'd recommend using systemd-resolved instead of NetworkManager for DNS, we're much more able to send DNS configuration to it: https://tailscale.com/blog/sisyphean-dns-client-linux/

Yeah, I just don't want DNS configured at all. Anyway, that is a very informative post, thank you

> Use tailscale up --accept-dns=false on the specific node. For example --accept-dns=false on this NetworkManager node would prevent it from writing to /etc/resolv.conf.

Ah, that explains it, I expected settings to be arguments to `tailscaled` so I was trying to find a config by reading `tailscaled --help`.

> Modifying the systemd configuration is definitely not the way we'd recommend to do this.

No, I can understand that, but since I found no other way and my DNS configuration was broken this was the easiest way forward, I also thought it would be a good way of being clear of the result I was after

Thanks for the help, `tailscale up --accept-dns=false` did just what I wanted
