### ISSUE TITLE
MagicDNS issues on MacOS Ventura 13.1 (22C65)

### ISSUE THREAD

**Issue by barnabasbusa** [tailscale/tailscale#6944]
### What is the issue?

I have MagicDNS issues on MacOS Ventura 13.1. 

Magic DNS doesn't translate any domain names anymore. As soon as I enable tailscale on my mac, DNS resolution stops working completely. Internet connectivity remains, however all (internal to tailnet and external public facing) DNS requests time out. 

Tailnet still works. I'm able to look up dns names from other devices using their magic DNS name. Issue also seem to have just appeared. It was working with an earlier version. (Issue started approx 2 weeks ago). Can't exactly recall which version. 

Checking my /etc/resolv.conf file I have the following:
```sh
search <foo-bar>.ts.net <my-email>.beta.tailscale.net
nameserver 100.66.157.1
```
I have not changed the nameserver IP address. 

When I check for tailscale DNS nameservers for my linux boxes, its all showing 100.100.100.100 in /etc/resolv.conf. 

Some additional info: 
```
Tailscale version used: 1.34.2 (App Store)
tailscale version (CLI)
1.34.2
  tailscale commit: c5ef9103d92b9b0a2932f869db56fbd7344ad417
  go version: go1.19.4
```
Tailscale CLI also returns a warning such: 
```
"Warning: client version "1.34.2-tc5ef9103d" != tailscaled server version "1.34.2-t1f0817693-g56304b539"
```

### Steps to reproduce

* Use the latest MacOs version
* Download tailscale from the appstore. 
* Download tailscale command line tool with brew
* Enable MagicDNS
* Enable tailscale 
* Try to ping any public/private domain name. 

### Are there any recent changes that introduced the issue?

No recent changes from my side.

### OS

macOS

### OS version

MacOS Ventura 13.1

### Tailscale version

1.34.2

### Bug report

BUG-aa2b466f2990010725ba4d6e96f9d7f3ae5e760bc86b27ab073aa5e79b3f7b5f-20230112185250Z-18ed1587870ec766

**Comment by DentonGentry** [comment]
`nameserver 100.66.157.1`

I'm going to guess that you have TunnelBear installed.

I say this because Tunnelbear, even if not active, even if disabled, runs a daemon which watches for up events on tun devices.

Not just its own tun devices. Any tun device. Including Tailscale's tun device.

When the Tunnelbear device sees a tun device transition to the up state, it configures DNS the way TunnelBear would want it: take the IP address of the interface, treat it as a /24, and append a .1 to it.

It therefore deliberately breaks DNS for Tailscale.

https://github.com/tailscale/tailscale/issues/2000

----

> Download tailscale from the appstore.
> Download tailscale command line tool with brew

By the way, these two don't work together. You can run the AppStore app as a CLI using `/Applications/Tailscale.app/Contents/MacOS/Tailscale status` or similar.

**Comment by barnabasbusa** [comment]
This was it indeed. Thanks for the assistance!
