### ISSUE TITLE
cmd/tailscale: add "update" command

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#6995]
We'd like to have a portable CLI command to do upgrades, downgrades, track switches, etc across a bunch of platforms. At least Windows, common Linux distros (Debian, Ubuntu) on the host (not containers), Synology, tailscaled-on-macOS, maybe the macOS GUI builds too (after figuring out some Sparkle stuff).

Earlier commit starting to add some of this was d9144c73a8ed520c8b59b604323acca7d879a568.

**Comment by bradfitz** [comment]
Related, but distinct: #755 (windows auto-update). This bug isn't about auto-updating necessarily, except in that people could set this to run as a scheduled task. But there will be real Windows auto-update support later. This bug's about the CLI.

**Comment by Foxboron** [comment]
Code like this should not exist on rolling release distros like Arch. Running `tailscale update` on Arch *is* going to break peoples systems sooner or later.

I need a way to disable this in the Arch package.

**Comment by Foxboron** [comment]
Void Linux has patched it out; https://github.com/void-linux/void-packages/commit/60610c8b1081d300e1358a0626a94d13931021dc

**Comment by classabbyamp** [comment]
This should only be enabled in versions of tailscale that come from and are built by tailscale directly, IMO. When tailscale (or any package) comes from a central source like a linux distro's package manager, that should be the only method of doing updates, and users know this. There is no need to add a "special" method of updating tailscale, even if it's just invoking `apt` or `apk` or `pacman` behind the scenes.

I suggest putting this behind a [build tag](https://pkg.go.dev/go/build#hdr-Build_Constraints), like `go build -tags selfupdate ...`, so that it is disabled by default.

**Comment by awly** [comment]
@Foxboron removed Arch support from `tailscale update` in https://github.com/tailscale/tailscale/pull/9081
The command is still there, but it always returns an error on Arch now.

**Comment by Foxboron** [comment]
@awly thanks!
