### ISSUE TITLE
Get "Untitled Goose Game" 🦢 LAN multiplayer working over Tailscale

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#702]
Untitled Goose Game is getting a multiplayer LAN mode: https://twitter.com/house_house_/status/1295758889837686785

This might work already with Tailscale! If not, it probably doesn't because of some missing multicast/mdns discovery mechanism. Let's see if we can figure out how to make it work.

This means the Tailscale team will have to play Untitled Goose Game for work, which will hopefully become our primary 1:1 meeting software.

**Comment by bradfitz** [comment]
Closing this for now. We can open a new multicast bug later.

**Comment by 2m** [comment]
> The other consoles and Steam are options though! Steam uses a simple custom multicast protocol to discover other steams, once we figure out a story for multicast over Tailscale we could relay that traffic easily.

This would be awesome!

Steam Remote Play allows direct connections but only PC to PC (because it needs an IP addressed entered explicitly to the Steam Client Console).

If tailscale would support this, then it would enable direct connections from Android or from Steam Link HW device to gaming PC over the internet, which would be great!
