### ISSUE TITLE
Pure userspace relay node option (for Mac, Windows, Cloud Run, Synology, etc)

### ISSUE THREAD

**Issue by patrickbeam** [tailscale/tailscale#707]
It would be very useful if we had the ability to relay to a remote network from a macOS system.  I have a very common use case in which I would like to relay some routes through a mac for several devices in remote locations that are very low powered.  Is it on the roadmap to add this feature to the mac client?

**Comment by bradfitz** [comment]
Yes, I'm planning on adding a pure userspace relay option which would permit use cases like running on Mac, Windows, Synology (Linux with missing kernel modules), Google Cloud Run, root-less Linux, etc.

**Comment by patrickbeam** [comment]
Thanks for the response @bradfitz.  That's fantastic news, really loving the product so far great job.  I'll be on the lookout for that enhancement to drop.

**Comment by bradfitz** [comment]
Update: I've got this somewhat working in a proof-of-concept phase at least. It's not super polished yet. I'll be focusing on Synology use cases first.

**Comment by DentonGentry** [comment]
Jotting some notes about userspace tailscaled on Cloud Run:

I have a Google Cloud Run system able to join the Tailnet using the userspace tailscaled + socks5 proxy. A couple things are hacked around which would need proper fixes for this to really work:
- wgengine/monitor/monitor_linux.go and wireguard-go/device/sticky_linux.go expect to create RTNETLINK sockets, which fails in a Cloud Run container. I made them return nil.
- net/netns/netns_linux.go:control() will call bindToDevice if it cannot run ip route. This prevented tailscaled from ever reaching control or log upload until I commented it out.

This allows tailscaled to contact Control and join the Tailnet using an authkey I generated. However it cannot contact any 100.x.x.x address of nodes within the Tailnet, presumably because it cannot install routes to reach them because I commented out the RTNETLINK sockets.

----

Looking more at bindToDevice(): it cannot figure out which interface has the default route so it takes its fallback of binding to "lo" (which it knows isn't going to work but does for safety to prevent routing loops).

This is the interface list on the Cloud Run container:
```
2: eth0: <UP,LOWER_UP> mtu 65000
   link/[65534] 00:00:00:00:00:00 brd 00:00:00:00:00:00
   inet 169.254.8.130/32 scope global dynamic
3: eth1: <UP,LOWER_UP> mtu 1280
   link/[65534] 00:00:00:00:00:00 brd 00:00:00:00:00:00
   inet 169.254.8.1/32 scope global dynamic
   inet6 fddf:3978:feb1:d745::c001/128 scope global dynamic
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536
   link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
   inet6 ::1/128 scope global dynamic
   inet 127.0.0.1/8 scope global dynamic
```
 
This is /proc/net/route:
```
Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT
eth0 8008FEA9 00000000 0001 0 0 0 01FFFFFF 0 0 0
eth1 00000000 00000000 0001 0 0 0 00000000 0 0 0
```

However when tailscaled tries to process /proc/net/route it finds it empty (debug printfs added). I have to assume this is something about the network namespace.

```
2021-03-24 22:04:03.277 PDT defaultRouteInterfaceProcNet processing: Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT
2021-03-24 22:04:03.277 PDT
2021-03-24 22:04:03.277 PDT defaultRouteInterfaceProcNet: no zeroRouteBytes
2021-03-24 22:04:03.277 PDT defaultRouteInterfaceProcNet processing:
2021-03-24 22:04:03.277 PDT defaultRouteInterfaceProcNet returning empty no default
```

Therefore bindToDevice() gets an empty interface string and falls back to its default "lo".

**Comment by DentonGentry** [comment]
userspace support debuted in 1.6 for local containers.

In 1.8 the support was broadened to include Heroku and Google Cloud Run:
- https://tailscale.com/kb/1107/heroku/
- https://tailscale.com/kb/1108/cloudrun/

MacOS in 1.8 pulls in the userspace stack to use for subnet routing, though we have not yet hooked up such a setting in the UI to enable it.

**Comment by apenwarr** [comment]
This works now. I suggest opening a separate bug for future features.
