### ISSUE TITLE
 freebsd: "interface wg0 already exists"

### ISSUE THREAD

**Issue by wardn** [tailscale/tailscale#72]
**Is your feature request related to a problem? Please describe.**

NewUserspaceEngine in wgengine/userspace.go issues a call to CreateTUN, which creates the wg0 interface on first run, but results in an "interface wg0 already exists" on subsequent runs.

**Describe the solution you'd like**

Mostly just looking for some context on whether this scenario exists on other platforms and how you'd like it to be handled.  Perhaps a way to handle CreateTUN in which if it already exists, it gets reused.

**Describe alternatives you've considered**

Looking at the wireguard-go implementation, it looks like they're setting an environment variable after creating the tun, and referencing the file descriptor in the environment variable on subsequent runs. I can issue an "ifconfig wg0 destroy" to clean up the interface on close but that seems a little brute-forcish, and handling it higher up will likely impact all the platforms. I've checked the linux/darwin/windows implementations for an example of how this is handled but it's not immediately apparent from the code.

**Additional context**

logtail...
Starting userspace wireguard engine.
external packet routing via --tun=wg0 enabled
CreateTUN: interface wg0 already exists
Error starting wireguard engine: interface wg0 already exists

**Comment by danderson** [comment]
On linux, the device's lifetime is tied to the file descriptor that created it, so when the process dies it all gets cleaned up automatically. This is the default behavior for the linux tuntap driver, you have to make extra efforts to make the device persistent.

So, that's why you're not seeing this logic already there. I'm assuming freebsd's tuntap behavior is different, but I don't know how to correct it. I'll dig through the code a bit and see if I find anything obvious.
