### ISSUE TITLE
Android app crashes when typing in Change server

### ISSUE THREAD

**Issue by glongzh** [tailscale/tailscale#7336]
### What is the issue?

when i start typing url in Change server, the app exits with nothing.

### Steps to reproduce

tap 3-dots menu 3 times to show the "Change server", and input url

### OS

Android

### OS version

MIUI 14/Android 13

### Tailscale version

1.36.1

**Comment by DentonGentry** [comment]
This is https://github.com/tailscale/tailscale/issues/7255, which is fixed in a development release in the Open Testing track. It will also be fixed in a 1.36.2 we're planning to build this week.

Anyone can join the Open Testing track and installthe 1.37 release:
- From the Android device: https://play.google.com/store/apps/details?id=com.tailscale.ipn
- From the web: https://play.google.com/apps/testing/com.tailscale.ipn

Duplicate of This is https://github.com/tailscale/tailscale/issues/7255
