### ISSUE TITLE
IP address mask /32 causes issues with dnsmasq

### ISSUE THREAD

**Issue by eSoares** [tailscale/tailscale#7340]
### What is the issue?

I'm currently using tailscale client in a Raspberry Pi 4 (Linux Raspbian bullseye) with a custom tailscale server (headscale).
The client when connected, attributes an address in the address space 100.64.0.0/10, but each client ends up with an IP address with mask /32 by default.

This behavior looks like is caused by this [line](https://github.com/tailscale/tailscale/blob/d38abe90be0738f097ba79abed0a50af226b16f7/wgengine/router/router_linux.go#L587) in particular, where no mask is put.

A /32 mask causes issues with dnsmasq, where it will ignore the interface and not answer correctly dynamic-host queries, since it indicates that address range is a single device instead of a network range of devices.
This issue was pointed https://github.com/pi-hole/FTL/issues/1531#issuecomment-1430342537.

Such behavior makes running a DNS server harder and per tailscale documentation it should be possible.

I propose that at least a /8 mask should be set, but better would be the server sending the mask to be used.

### OS

Linux

### OS version

Tested under Linux Raspbian bullseye

### Tailscale version

1.34.1

### Other software

Pi-hole [v5.13](https://github.com/pi-hole/pi-hole/releases/v5.13)
Headscale [0.20.0](https://github.com/juanfont/headscale)

**Comment by bradfitz** [comment]
This doesn't seem like a problem with Tailscale.

**Comment by eSoares** [comment]
Just tried to use with a fresh installation of tailscale, and the IP address that I got had a mask of /32.

I don't think dnsmasq is wrong where, if there is a subnet of devices behind that interface, the mask shouldn't be /32.

**Comment by danderson** [comment]
Tailscale is a layer 3 VPN. In layer 3 networks, it's common and normal to assign singleton IP addresses to interfaces, and then use explicit routing table entries to steer traffic, rather than rely on the implicit routes created by using wider netmasks on interface addresses.

So, dnsmasq is indeed wrong here. It seems to be assuming that all interfaces behave like Ethernet as configured by ifupdown(1), which is a good enough approximation for simple home LAN setups, but doesn't translate correctly to layer 3 routed interfaces. I expect it would have the same problem if faced with a BGP-routed network, which similarly decouples the concepts of address netmasks and network reachability. I don't know what dnsmasq is trying to decide based on address netmask, but it should not expect that heuristic to work universally.

Either way, practically we cannot set a wide netmask on our interface address. Doing so implicitly populates routing table entries that break connectivity for some OSes and network topologies. We need to preserve the ability to deaggregate our routes and leave the overall /10 uncaptured, and the way to do that is to set up the interface the way we have.

**Comment by eSoares** [comment]
Thanks for the explanation. 

While I agree that is a possible to use a singleton IP address and then define routing entries, the idea that interfaces belonging in a network should have a mask that reflect it still makes sense as a expected behaviour.

> Either way, practically we cannot set a wide netmask on our interface address. Doing so implicitly populates routing table entries that break connectivity for some OSes and network topologies. We need to preserve the ability to deaggregate our routes and leave the overall /10 uncaptured, and the way to do that is to set up the interface the way we have.

That's why I was suggesting for the server to send the mask, the smallest possible to all the connected devices in the tunnel. 
The routes created by tailscale will break connectivity to those IPs either way.

A good alternative solution would be the option to execute a script after connection (issue #6367 ) and in my case would place a network mask manually in the interface.

**Comment by bradfitz** [comment]
> That's why I was suggesting for the server to send the mask, the smallest possible to all the connected devices in the tunnel. The routes created by tailscale will break connectivity to those IPs either way.

We add a bunch of /32 routes to the Tailscale IPs of peers as needed.

Then we can even co-exist for the most part with other people using the same CGNAT space too.

The peers for whom we install /32 routes aren't neatly packed into one little CIDR we can advertise. They're randomly sprayed over the whole 4 billion address space. 

If you want to write a program to subscribe to netlink events (or run `ip monitor | head -1` in a loop), you can. But that feels like fixing the wrong problem. You should work on getting dnsmasq fixed instead.

**Comment by eSoares** [comment]
I understand that **this** is not a tailscale problem, is a **my** problem. 😅 

And I agree that the best strategy to use IP addresses is pick them randomly in the network space and then manually adding routes.
From the point of view of tailscale, the current solution is the **best** solution. And all my proposals makes it worse.

> That's why I was suggesting for the server to send the mask, the smallest possible to all the connected devices in the tunnel.

This proposal was a bit to find the middle ground, where tailscale would still send /32 mask, but users with custom servers (i.e. headscale) could define a new mask.
Even tailscale could add the option to have continuous addressing for those that don't use CGNAT.

I understand that such a solution brings nothing to tailscale, and solves a niche problem, as such the interest in adding such option are close to none.
I will close the issue, and thank you for the time and discussion. I have learn somethings today! :smile:

> You should work on getting dnsmasq fixed instead.

I'm trying!
