### ISSUE TITLE
Windows: [WSL2] Address MTU issue when running tailscaled under WSL2

### ISSUE THREAD

**Issue by shayne** [tailscale/tailscale#7346]
> **Note**: A meta issue to track efforts to improve the user experience of running `tailscaled` under WSL2.

Packet sizes and the MTU in WSL2 are still causing persistent issues that, ideally, are resolved, and at minimum, we address them with an in-process workaround.

As of late 2022, the state of MTU in WSL2 is: `eth0: ... mtu 1280 ...`. Please look over #4833 for full context.

The user experience is pretty bad and could be better as everything appears to work, and Tailscale can connect. Sending pings to nodes receive replies, but larger-packet-leaning protocols will hang, like SSH and TLS.

At a minimum, we should add a warning and suggestion to increase MTU (to what?) to the `$ tailscale status` output. I also have tailscale/tailscale-www#2443 open to add WSL2 install instructions and known issues to our docs.

At best, we should devise a workaround that makes it "just work," and we continue to track the progress of WSL2 and changes to the network stack.

cc/ @raggi @dblohm7

**Comment by DentonGentry** [comment]
@s-aia as I think PMTU discovery is one of the potential ways to make this more smooth.

**Comment by raggi** [comment]
The broader/general recommendation would be to run Tailscale on the Windows side by preference. WSL is changing in undocumented ways at a pace that means we'll always have trouble making sure it's ok. Users also don't really have control over what version of WSL they're running.

Reading up on various related bugs in the WSL bug tracker, it's become a real wild west. It seems that some other VPN software now reaches around and changes the (windows side) MTU of the interfaces too in order to (mistakenly) attempt to fix the problem. This causes more issues because there's no synchronization between the host side interface MTU and the guest side interface MTU - the current defaults (at time of writing) are 1500 host side and 1280 guest side.

I think the most safe thing we can probably do, but it still might break users arbitrarily is to have a check in tailscaled for:

- $WSL_INTEROP is set
- eth0 is the default interface
- eth0 has an MTU of exactly 1280

If all of the above conditions are met, then we raise eth0 MTU to 1360. This is a conservative strategy that will work in most cases, even if the user has secondary VPN software on the Windows host side that can not transport nearer ethernet frame sized packets, while providing exactly enough space for tailscaled to function correctly when the user sends 1280 byte packets on tailscale0.

The alternative would be to drop the MTU of tailscale0 to less than 1280, but that would be a violation of the IPv6 specification, which is likely to lead to more problems. It would also really start leading to even more poor performance.

**Comment by shayne** [comment]
The workaround in #7441 was released Mar 14t 2023, in [v1.38.1](https://github.com/tailscale/tailscale/releases/tag/v1.38.1)

**Comment by shayne** [comment]
Assuming we have pulled the most practical available lever, perhaps we close this out soon.

Barring further comment, we'll expect to close this during the next regular bug scrub.

**Comment by raggi** [comment]
Agreed, we can close out for now. The situation will continue to evolve as WSL2 makes further changes - I strongly suspect the current 1280 default will not be the final form, if for no other reason than it's quite slow for the most common use cases. We can reopen this bug or open a new one when new dimensions arise.
