### ISSUE TITLE
Synology shows as `1.36.2-dev20230222` in admin panel

### ISSUE THREAD

**Issue by avidrissman** [tailscale/tailscale#7349]
### What is the issue?

Two things to note.

First is that on the panel, while a Synology running 1.36.1 showed up as “1.36.1”, a Synology running 1.36.2 shows up at running “1.36.2-dev20230222”. Dunno if that’s intentional.

Second, I updated my Virtual DSM, and while the Tailscale version eventually showed up as changed, the installation process seemed to hang. On my real DSM, the installation claimed to error out, although it does seem like it installed fully, as the panel shows that long version.

I don’t know if any of this is intentional or actionable, but thought you should know.

### OS

Synology

**Comment by DentonGentry** [comment]
DSM6 or DSM7?

> Second, I updated my Virtual DSM, and while the Tailscale version eventually showed up as changed, the installation process seemed to hang. On my real DSM, the installation claimed to error out, although it does seem like it installed fully, as the panel shows that long version.

We do get reports of error messages but successful install in cases where the upgrade is triggered while using Tailscale to reach the admin page. We haven't yet figured out what the root cause is; presumably we're returning an error to something during the upgrade process.

> while a Synology running 1.36.1 showed up as “1.36.1”, a Synology running 1.36.2 shows up at running “1.36.2-dev20230222”.

This is what I see, you see a `dev20230222` string?
<img width="520" alt="Screenshot 2023-02-22 at 7 46 47 PM" src="https://user-images.githubusercontent.com/1140756/220817215-25a5c22c-73f7-4fb6-98b5-ca64a34c399d.png">

**Comment by avidrissman** [comment]
Sorry, DSM 7.1.1-42962 Update 2.

As for the version string, I mean on https://login.tailscale.com/admin/machines:

<img width="1050" alt="SCR-20230222-vxu" src="https://user-images.githubusercontent.com/3914435/220818673-21cfb0a8-61ca-4c54-ae75-dcb1b67883b9.png">

**Comment by DentonGentry** [comment]
Huh. I see `1.36.2-dev20230222` in the admin panel as well.

I think this happened because https://github.com/tailscale/tailscale-synology/pull/111 matches a code change made in `main` of https://github.com/tailscale/tailscale, but today's build happened from `release-branch/1.36` which does not contain the matching code change.

**Comment by avidrissman** [comment]
If the glitchiness of the install is a known thing, then I’ll leave the fate of this bug to you. If you want to track the version number issue, go ahead, otherwise feel free to close it.

**Comment by DentonGentry** [comment]
I've withdrawn the 1.36.2 SPKs, pkgs.tailscale.com is back to offering 1.36.1 for Synology.

It is fine to leave it installed on your devices. So far as I can tell, the code in tailscale-synology expects `version.longStamp` but the `release-branch/1.36` uses `version.Long`, so tailscale-synology decides that it must be a developer build. This should be harmless, I'd just rather fix and release a 1.36.2 (or 1.36.3) which gets the version number correct before many more people install it.

**Comment by avidrissman** [comment]
This is now working as expected with the new release.
