### ISSUE TITLE
Unable to download iOS app through Brave browser (page hangs)

### ISSUE THREAD

**Issue by christine-tailscale** [tailscale/tailscale#7433]
### What is the issue?

- I expected that clicking the "Download iOS" button on the Downloads page would redirect me to the iOS App Store.
- However, clicking on the "Download iOS" button launched a new browser tab and hung for 3 minutes before I decided to close the tab.
- See recording:

https://user-images.githubusercontent.com/123998549/222574253-b1e77a62-9c17-4758-aac0-acab8cc125da.mp4

FWIW, everything works as expected on Safari, so this may be unique to Brave.

### Steps to reproduce

1. Open Brave browser (v.1.48.1) on iPhone 13 (iOS v.16.3.1)
2. Go to https://tailscale.com/download
3. Click on the "Download iOS" button

### OS

iOS

### OS version

iOS v.16.3.1

### Tailscale version

n/a

**Comment by mihaip** [comment]
All the "Download iOS" button does is open https://apps.apple.com/us/app/tailscale/id1470499037?ls=1 in a new tab. I'm guessing something in Brave is blocking that URL -- even if I navigate to it manually it doesn't load.

Though the App Store link on other pages like https://tapbots.com/ivory/ does work -- I wonder if it's because we use a `target=_blank` option for it. @rosszurowski do you think we could try to skip that attribute for the iOS one only? It should not be necessary if it's going to open the App Store anyway.
