### ISSUE TITLE
Error: no node found in netmap with IP 

### ISSUE THREAD

**Issue by guitardoc** [tailscale/tailscale#7513]
### What is the issue?

I’m trying to set up an exit node on my Raspberry Pi with Debian Bullseye using the guide on the tailscale website ([Exit Nodes (route all traffic) · Tailscale](https://tailscale.com/kb/1103/exit-nodes/)). I got as far as

sudo tailscale up --exit-node=myIP

myIP being the IP of the Raspberry Pi as shown in machines (100.x.y.z).

Even though having painstakingly followed the guide I get the following error:

‘no node found in netmap with IP myip’

How can I proceed to make it work?

Thank you.

### OS

Linux

### OS version

Debian Bullseye

### Tailscale version

1.36.2

### Bug report

BUG-bc79c61f8fa41328552194444474be75a22628179530fa29a364e4a6bd68423a-20230309085735Z-732795f4b36f1855

**Comment by DentonGentry** [comment]
The bugreport appears to have been captured on the exit node. What device was trying to use the exit node and said `no node found in netmap with IP myip`

**Comment by DentonGentry** [comment]
Please generate a `tailscale bugreport` from the node trying to use the exit node immediately after you see "no node found in netmap with IP"

**Comment by guitardoc** [comment]
Here comes the bug report from immediately after the error message:

BUG-bc79c61f8fa41328552194444474be75a22628179530fa29a364e4a6bd68423a-20230309144052Z-9bc83a457141f04a

**Comment by guitardoc** [comment]
Did the bug report help finding the issue?

**Comment by RunarGull** [comment]
I´m having the same issue as well

**Comment by DentonGentry** [comment]
Unfortunately I don't see anything especially suspicious in telemetry around the time of the BUG line.

The error message comes from: https://github.com/tailscale/tailscale/blob/731688e5cc63eaf9d0750ea2f426263c34de9c3a/ipn/prefs.go#L582
when looking up the exit node in the netmap, the exit node is not found.

**Comment by guitardoc** [comment]
I just updated the system to tailscale 1.38.2 over 1.38.1.
Unfortunately, the issue persists. The error message is still the same. What can I do to make it work?

**Comment by rockbrigade** [comment]
It turns out that Tailscale is not the right thing for me, but I want to report that I got the same error following the same instructions on the Tailscale website about setting an exit node.

Raspberry Pi 3B+, running Dietpi. 

Basic information, hope it helps:
```
command: sudo tailscale up --exit-node=<raspberry pi Tailscale IP>
response: no node found in netmap with IP <raspberry pi Tailscale IP>

```
bug report after receiving that response:
BUG-cf6f85e3e236dac2a137e421037b07d89afc0f798dcb46bbae5348a57f62cf2e-20230324213125Z-e7163feb2ea9c8d4

**Comment by Taubin** [comment]
I'll add in my bug report for this as well:

BUG-8953b099a9b0749b587c685c71e2fb5ddfbbbe61d0bcb6ae476664f867edc3e1-20230327003841Z-875be9c603b024b1

This is on unraid not a pi.

**Comment by masterct88** [comment]
Hi, i have the same problem, and for my connection the only vpn i can run is Tailscale.
my bug report:
BUG-66c534c335dbcafb64e3b44288dddc632037d3f5974ceb508b28052985690385-20230408233445Z-e9da6b9e2fe2697a
Any update or info you can share?

**Comment by talkleasy** [comment]
I have the same issue. Is this being actively investigated? Thanks.

**Comment by guitardoc** [comment]
Looks like it has been put on the back burner with the current labels "nuisance" and "very few".

**Comment by DentonGentry** [comment]
@Taubin Around the time of the bugreport there is nothing in the telemetry regarding "no node found in netmap with IP". I believe the issue that system is encountering is different.

Similarly @masterct88, around the time of the bugreport there is no mention of "no node found in netmap with IP".

I don't doubt there is a problem being experienced, but I do not believe it is THIS problem. If you want to file new issues please do.

**Comment by masterct88** [comment]
Hi everyone, the problem is found on Linux only, docker o directly installed.
I use UNRAID and my Work Around is to install Tailscale on windows:
Linux setup as exitnode;
Windows setup for share internal network.
Works but it'snt ideal.
I think the bug is only in Linux, If you need more info please ask.
Thanks, Alessandro.

**Comment by DentonGentry** [comment]
@guitardoc There is one raspberrypi on your tailnet. You've been blanking out its IP address so I'll refer to it as 100.99.98.97. All of the bugreports appear to have been generated from this Raspberry Pi.

On the Raspberry Pi with IP 100.99.98.97, are you running:
`rpi# tailscale up --exit-node=100.99.98.97`
?

I ask because that is the only way I'm able to produce that error message, tell a Linux system to use itself as an exit node:

```
root@dgentry-tor1:~# ip addr show tailscale0
11: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none
    inet 100.127.188.88/32 scope global tailscale0
       valid_lft forever preferred_lft forever
root@dgentry-tor1:~# tailscale up --exit-node=100.127.188.88
no node found in netmap with IP 100.127.188.88
```

--------

The intent with an exit node is to tell other devices on the tailnet to use the exit node, to teleport themselves to the location of the exit node and have all of their public Internet traffic egress from that exit node. On a Linux system you'd use `tailscale up --exit-node=` but put the IP address or hostname of some other system on the tailnet which has been configured to be an exit node.

For macOS, iOS, and Windows this is in an "Exit node" menu of the UI.

**Comment by guitardoc** [comment]
@DentonGentry Yes, I am running 
`pi@raspberrypi:~ $ tailscale up --exit-node=100.99.98.87` on the raspberry pi

I was under the impression that the raspberry's IP as shown on the tailscale admin webpage has to be configured as the exit node? It said so on the help page, at least that is what I understood (English is not my first language):

<img width="384" alt="image" src="https://user-images.githubusercontent.com/77169595/232202556-c305db23-3037-477a-a8de-3c3e03983b77.png">

...and then running the above command (tailscale up). Is this not correct? Which other device has to be used instead? I have my home network which the raspberry is an integral part of running using a Fritzbox router which is connected by glass fibre to the internet.

**Comment by DentonGentry** [comment]
At this point as far as I can see, the Raspberry Pi has been configured as an exit node and is ready to be used.

You can now set _other_ devices on your tailnet to use the exit node.
- on a Linux machine, use `tailscale up --exit-node=100.99.98.87` to enable the exit node and `tailscale up --exit-node=` to disable it
- on Windows, right click the Tailscale icon in the taskbar and select Exit node > raspberrypi
- on macOS, click the Tailscale icon in the menubar and select Exit node > raspberrypi
- on iOS and Android, tap the three dot menu and select Exit node > raspberrypi

Does the exit node work?

**Comment by guitardoc** [comment]
After I finally understood the mechanism it works like a charm! Thank you very much for your help!!!

**Comment by kuduacz** [comment]
So Can you tell me how to make it work?
