### ISSUE TITLE
Admin console is empty

### ISSUE THREAD

**Issue by tombajzek** [tailscale/tailscale#7515]
### What is the issue?

Admin console has no content, and therefore I can't do anything depending on that. This is a Mac-Mini running High Sierra (10.13.6). This is a server I use making SMB and VNC connections frequently, and with no issues. 

Also, the admin consoles of my **other** Tailscale devices show dozens of open ports on this system in the 49000 range when I view **Services**. I went to its admin console to see if I could find a clue as to why this is happening and noticed the blank admin console. I don't know if it has always been this way because I don't recall needing to use its admin console previously, as I can always connect to this system and use it without issues. It's just annoying to have 7 screens of useless ports displayed for this system when I use the **Services** screen on other systems.

I just updated to the Tailscale 1.36.2 from the App Store, but that had no effect.

Please advise.

Thanks,
Tom Bajzek

### Steps to reproduce

I selected the **Admin Console** in the Tailscale menu.

### Are there any recent changes that introduced the issue?

Not that I can recall, since I don't know when this started. I just observed it today.

### OS

macOS

### OS version

macOS High Sierra 10.13.6

### Tailscale version

1.36.2, but it was happening on 1.30

### Other software

No special networking or security software runs on this host. Right now, only Finder, Safari, and Activity Monitor are running.

**Comment by DentonGentry** [comment]
There is not a way to make progress on this without knowing the account information, which is not something we want to put on public bugs. Please file this as a support request https://tailscale.com/contact/support/ instead of a bug.

**Comment by mihaip** [comment]
This is likely due to an old version of Safari being used (the latest that macOS 10.13.6 runs is Safari 13.1.2, the current version is 16.3).

It looks like it's broken enough that our JavaScript doesn't load at all:

![image](https://user-images.githubusercontent.com/513813/224119597-f9a51494-241f-4659-944e-12865aac1aee.png)

We officially support only the current and previous version of browsers (so Safari 16 and 15).Note that you can access the admin console from a different browser (e.g. Chrome, a more recent version of which may be be available for macOS 10.13) or a different machine entirely (which can run a more recent version of Safari).

**Comment by tombajzek** [comment]
Thanks for the response. I'll just use another browser in that case.
