### ISSUE TITLE
tsnet does not compile

### ISSUE THREAD

**Issue by pitust** [tailscale/tailscale#7596]
### What is the issue?

I am attempting to compile the tshello example from [tsnet/example/tshello/tshello.go](https://github.com/tailscale/tailscale/blob/v1.36.2/tsnet/example/tshello/tshello.go), however it does not seem to compile...

I execute `go get -u tailscale.com/tsnet` to add the dependency, however when attempting to compile i get this really confusing go error:
```
../../go/pkg/mod/tailscale.com@v1.38.1/wgengine/netstack/netstack.go:26:2: found packages refs (refcounter.go) and refs_template (refs_template.go) in /Users/pitust/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230317235517-acf460d0d735/pkg/refs
```

### Steps to reproduce

1. `git clone https://git.sr.ht/~pitust/tailscale-bug-repro`
2. `cd tailscale-bug-repro`
3. `go get`
4. `go run test.go`

### OS

Linux, macOS

### OS version

Debian sid, macOS 12.1 21C52

### Tailscale version

1.38.1

### Other software

 - go version go1.20.2 darwin/arm64
 - go version go1.19.5 linux/arm64

### Bug report

BUG-17affcea25dd9e0a4d359258d8471abeabf9cad6d29c55c4dec9052dab76c9c4-20230318125102Z-e4b29c020f689b2f

**Comment by DentonGentry** [comment]
> Tailscale version 1.28.0

Could you try from current `HEAD` ?
Even if something is broken, we wouldn't go back to fix 1.28 at this point.

**Comment by pitust** [comment]
Hi! This issue is not related to the tailscale version installed -- the code fails to build with the go compiler. I filled out the form incorrectly - it's broken on `v1.38.1`.

**Comment by bradfitz** [comment]
You need to use Go 1.20. Go 1.19 won't work.

**Comment by bradfitz** [comment]
Tailscale is using `gvisor.dev/gvisor v0.0.0-20221203005347-703fd9b7fbc0`

Your error is from `gvisor@v0.0.0-20230317235517-acf460d0d735`

Your go.mod is apparently pulling in a newer gvisor. We haven't built or tested with that yet, so you'll have to debug. And it looks like maybe you're on the Bazel file tree branch rather than the "go" gvisor branch.

I suggest downgrading your gvisor dep to match what Tailscale's using.
