### ISSUE TITLE
FR: add Exherbo Linux in install.sh

### ISSUE THREAD

**Issue by kelivel** [tailscale/tailscale#7652]
### What are you trying to do?

Add Exherbo Linux support to install.sh

### How should we solve this?

OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux hygiea 5.18.8 #3 SMP PREEMPT_DYNAMIC Thu Dec 1 11:44:41 EST 2022 x86_64 GNU/Linux

NAME="Exherbo"
PRETTY_NAME="Exherbo Linux"
ID=exherbo
ANSI_COLOR="0;32"
HOME_URL="https://www.exherbo.org/"
SUPPORT_URL="irc://[irc.libera.chat/#exherbo](http://irc.libera.chat/#exherbo)"
BUG_REPORT_URL="https://gitlab.exherbo.org/"

**Comment by DentonGentry** [comment]
https://www.exherbo.org/ doesn't respond.

Descriptions elsewhere state that it is a source-based distribution like Gentoo with a "... fast and flexible package manager called Paludis"

Needing a new packaging tool to be supported makes this much more difficult to implement, especially because https://paludis.exherbo.org/overview/features.html doesn't respond either.

**Comment by DentonGentry** [comment]
https://www.exherbo.org/ is still down a week later.

I don't see us making progress on this distribution.
