### ISSUE TITLE
FR: Distribute Android app in the Amazon Appstore

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#7774]
My new car has FireTV tablets in the headrests for kids to watch cartoons and stuff.

They've removed the developer options, so no ADB over the network, which means I can't side-load our F-Droid APK.

The only way to get an Android app onto them is via the "Amazon Appstore": https://en.wikipedia.org/wiki/Amazon_Appstore

My car says there are about 100 VPN apps available on the FireTV Stick Tablet Amazon Appstore for Android (I can't figure out all the layers of branding) but no Tailscale.

We should get in that app store too.

**Comment by alexdelprete** [comment]
@bradfitz Is there an official procedure to install Tailscale on a FiresTV stick? I saw some hacky procedures, but wanted to know if there was an official working package and install procedure.

**Comment by DentonGentry** [comment]
Amazon Fire devices lack the Google Play Services, so one would need to use a version of the Tailscale app which doesn't need Play Services like https://f-droid.org/en/packages/com.tailscale.ipn/

**Comment by cablespaghetti** [comment]
I’ve got the same issue with my kids Amazon tablets. I can install the app on my adult profile from f-droid which wasn’t too difficult but because it’s not from the Amazon App Store it’s impossible to make it available on my kids restricted profiles. 

It would be nice if the version of the app which is on fdroid could be added to the Amazon store. Thanks!

**Comment by tmm1** [comment]
In the mean time, it would be helpful if the docs and website had a little more guidance on how Amazon device users can use Tailscale. Even if its just a "sideload this apk" and a link to where they can find it would be helpful.

The content at the moment is all very Play Store specific:

https://tailscale.com/kb/1079/install-android/
https://tailscale.com/download/android

**Comment by tomcook** [comment]
I have another use case for Tailscale on Fire Tablets that's not related to kids: I have a couple cheap tablets around the house used as Home Assistant control panels. My Home Assistant install is linked to Tailscale and I usually access it via my ts.net URL, but for these tablets I have to use their local IP addresses. 

My preference is to route all traffic over Tailscale but right now it's not possible since they can't join the tsnet. This is super low priority since my setup works fine and linking them to Tailscale would just be a small improvement, but would still be much appreciated!

**Comment by agottardo** [comment]
This is currently being worked on.

**Comment by agottardo** [comment]
The app is now available on the Amazon Appstore for Fire TVs and tablets: https://tailscale.com/kb/1394/install-amazon-fire
