### ISSUE TITLE
Docker image build for 1.38.2 not available

### ISSUE THREAD

**Issue by hollie** [tailscale/tailscale#7809]
### What is the issue?

Hello,

I see the docker image on [docker hub is still reporting 1.38.3](https://hub.docker.com/r/tailscale/tailscale/tags) to be the latest version.

Could it be that the automatic build process for the 1.38.4 image has failed? Could somebody please take a look so that we can update our containers to the latest Tailscale version? I'd like to get rid of the CVEs that are fixed in the latest release.

Thanks,
Lieven

**Comment by hollie** [comment]
I can't seem to open a normal ticket, I hope it is OK to use the bug report form for this question.

**Comment by DentonGentry** [comment]
As with your previous https://github.com/tailscale/tailscale/issues/7680: we are still building the release.

**Comment by hollie** [comment]
@DentonGentry 

OK, from #7680 I understood there was an issue with the build environment and I wanted to ensure that you were aware 1.38.4 was also not automatically built yet.

Thanks for confirming that the release is in the process of being built, I will close this ticket.

Have a nice day,
 Lieven

**Comment by DentonGentry** [comment]
We test releases internally, but are mindful that we cannot possibly test everything that all users run. We ramp the rate that platforms go out in order to watch for signs of any new problem that we missed in testing.

Platforms which deploy to users most aggressively go out later in the process in order to give time to watch for signs of regressions in the platforms which go out earlier in the process.
- Apple's App Store and Google's Play Store, which actively push releases to users
- container releases, where it is common to script and immediately deploy new versions which appear

That containers are published later than some other platforms is normal, and working as intended.

Additionally if we have an issue with one of the earlier platforms, we work on it first: catching a regression early is the point of doing this.

> OK, from https://github.com/tailscale/tailscale/issues/7680 I understood there was an issue with the build environment and I wanted to ensure that you were aware 1.38.4 was also not automatically built yet.

That was not the conclusion of https://github.com/tailscale/tailscale/issues/7680.

**Comment by hollie** [comment]
@DentonGentry thanks for the clarification. With this info I now understand what you meant with #7680, I misinterpreted it previously.

Keep up the good work, tailscale is awesome ❤️
