### ISSUE TITLE
Magic DNS: beta.tailscale.net should be auto-added to your search paths

### ISSUE THREAD

**Issue by rosszurowski** [tailscale/tailscale#781]
Someone shared in the user Slack that they couldn't get Magic DNS working. Turns out they didn't add `beta.tailscale.net` to their search paths and were trying to access a domain without that suffix.

I can't think of why we shouldn't auto-add it to the search path. As long as teams can opt-out, it's far less confusing for us to do it on their behalf.

**Comment by danderson** [comment]
When we introduce sharing, having beta.tailscale.net in the search path opens people up to hijacking attacks. Suddenly "www.google.com" might be "www.google.com.beta.tailscale.net", for instance. I'd be wary of automatically adding anything other than their fully qualified tailscale.net domain to the search path (which is entirely under their control).

**Comment by rosszurowski** [comment]
@danderson I suppose that risk depends on how we assign domain names when we introduce sharing.

I'd be surprised if we allowed external machines to share the same domain name used to access it within their local network. For example, if I invited a google.com machine to my network, it should probably be qualified in some way e.g. "google.com.external-name.beta.tailscale.net" no?

But perhaps it'd be a better experience to add the full <domain>.beta.tailscale.net in there automatically…

**Comment by apenwarr** [comment]
Hmm, I think there's some misconception here. For example, on an @example.com employee's domain, example.com.beta.tailscale.net *is* auto-added to the DNS search path, as it should be, so that if I try to go to 'mybox' it expands to 'mybox.example.com.beta.tailscale.net' which is correct.

We don't just add beta.tailscale.net, because that would be confusing. If I try to go to mybox.example.com, that doesn't mean I want to go to mybox.example.com.beta.tailscale.net.

If the user was reporting an issue, we might need to dig a bit deeper to see if there's a problem with their DNS search path, or something else.

**Comment by rosszurowski** [comment]
Oh. Perhaps I wasn't on the right version when I verified this bug, but this is working for me right now on my iOS device on the @tailscale.com network. The [user who reported this](https://tailscale-users.slack.com/archives/C019ZEXDFEH/p1600854938001700) never got back to us with more details. Pinged again, but I'll close this out since it doesn't seem like we can replicate.
