### ISSUE TITLE
FR: allow hostnames in DNS servers

### ISSUE THREAD

**Issue by dmitrybelyakov** [tailscale/tailscale#7872]
### What are you trying to do?

Add my DNS server as a hostname

### How should we solve this?

Allow hostnames for DNS servers, not just IPs

### What is the impact of not solving this?

Unable to add DNS server who's IP dynamically changes because of ISP restrictions

**Comment by DentonGentry** [comment]
Let's say we do that, and allow `dns.example.com` to be added as a global DNS server in https://login.tailscale.com/admin/dns

Every OS Tailscale works with — Linux, Windows, macOS, iOS, Android, etc — requires an IP address. So something, somewhere has to turn dns.example.com into an IP address. Since the client may not have any DNS servers (expecting to get them from the Tailscale config) we'd presumably have the coordination server do so and send down an IP.

The hard part is: how does one determine that dns.example.com has moved to a new IP address, and communicate the new IP address?

**Comment by uhthomas** [comment]
Per the [documentation on DNS](https://tailscale.com/kb/1054/dns/), it should be possible to use Tailscale IPs for DNS. Tailscale IPs should be static and avoid the problem of a dynamic IP address. Does this help in your situation @dmitrybelyakov?

Depending on your use-case, [arbitrary DNS records](https://tailscale.com/kb/1054/dns/#can-i-add-arbitrary-dns-records-to-magicdns) could help too (#1543).

**Comment by dmitrybelyakov** [comment]
Thank you for your replies and looking into this.

@uhthomas that is actually a very good solution and is what i ended up doing in combination with "override local dns" feature. And I agree, having arbitrary DNS records in tailscale would be amazing - I'll go upvote it.

I think this can be closed now.
