### ISSUE TITLE
p2p Direct connection is not established for RDP

### ISSUE THREAD

**Issue by josedev-union** [tailscale/tailscale#7973]
### What is the issue?

I have been facing some connection lagging issues for RDP from my device(win10) to the corporate device(win2012 server). Those are in the different region(continent)s. When i check `tailscale status` and `tailscale ping`, it is showing that the connection is relying on `mia` DERP server.
To fix this connection issue, I want to establish p2p between those devices and opened UDP 41641 port of the corporate device by following the tailscale document.
But the connection keeps relying on DERP server.

### OS

Windows

### OS version

win10 on my device and win2012 server on the corporate device

### Tailscale version

1.36.0 on my device and 1.34.1 on corporate device

**Comment by DentonGentry** [comment]
If direct connections are not working there are a few things one can do:
1. Open ingress of UDP port 41641, as you note. https://tailscale.com/kb/1082/firewall-ports/
1. In cases where that doesn't work it is often because the firewall has a limited number of connection tracking slots and can't handle the number of clients all trying to use port 41641. Setting `RandomizeClientPort` is generally the next step.
1. One can enable NAT-PMP, PCP, or UPnP in the residential router.

However: it is very hard for us to support an individual account like this in a public bug report. We sometimes need to correspond about IP addresses and router settings, and things which should not be public. I'd ask that you instead submit this as a support ticket at https://tailscale.com/contact/support/ so we can look up details of the tailnet and correspond in private email.
