### ISSUE TITLE
Login stuck until registry cleaned

### ISSUE THREAD

**Issue by zouxingyuks** [tailscale/tailscale#8153]
### What is the issue?

最近安装tailscale 后出现有两台电脑卡在 login 界面，排除 vpn 网络连通性等问题后仍然无法登录。
后经过 清理注册表成功解决此问题，特此分享。

### OS

Windows

### OS version

win 10

**Comment by DentonGentry** [comment]
最近安装tailscale 后出现有两台电脑卡在 login 界面，排除 vpn 网络连通性等问题后仍然无法登录。
After installing tailscale recently, two computers were stuck on the login interface. After troubleshooting problems such as VPN network connectivity, I still could not log in.

后经过 清理注册表成功解决此问题，特此分享。
After cleaning the registry, this problem was successfully solved, and I would like to share it here.

**Comment by DentonGentry** [comment]
return -ETIMEDOUT

**Comment by zouxingyuks** [comment]
同意确实是注册表的问题，包括但不限于网络设备管理器失效等一系列问题均可以通过注册表清理来修复。

**Comment by DentonGentry** [comment]
同意确实是注册表的问题，包括但不限于网络设备管理器失效等一系列问题均可以通过注册表清理来修复。
I agree that it is indeed a problem with the registry, including but not limited to a series of problems such as the failure of the network device manager, which can be repaired by cleaning the registry.

**Comment by PureWhiteWu** [comment]
你好，想问一下是怎么清理注册表的呀？

**Comment by zouxingyuks** [comment]
> 同意确实是注册表的问题，包括但不限于网络设备管理器失效等一系列问题均可以通过注册表清理来修复。 I agree that it is indeed a problem with the registry, including but not limited to a series of problems such as the failure of the network device manager, which can be repaired by cleaning the registry.

使用ccleaner 清理注册表即可
