### ISSUE TITLE
iOS app disconnects periodically

### ISSUE THREAD

**Issue by jbschooley** [tailscale/tailscale#8183]
### What is the issue?

Seems to be once a day for me. I’ll grab my iPhone when I wake up and try to connect to something on my Tailscale network and it won’t connect. Or I’ll see an ad, which means Tailscale isn’t sending DNS traffic to my PiHole. Opening the app resets the connection and fixes it. 

### Steps to reproduce

Turn on Tailscale on iOS. Use it throughout the day. Go to sleep. Wake up, pick up device, try to connect to a device on tailnet. Hit or miss whether it’ll work. 

### OS

iOS

### OS version

16.4.1a

### Tailscale version

1.40.0

**Comment by DentonGentry** [comment]
This is likely memory growth until the app reaches the 50 MByte limit for Network Extensions in iOS and is killed. Tailscale 1.42 on iOS will set the memory GC to be more aggressive at 42 MBytes footprint, trying to prevent it growing further.

**Comment by jbschooley** [comment]
Oh cool, I really hope that's the reason and I'm looking forward to that update!

**Comment by alex-reilly-pronto** [comment]
A few folks at my company have also been experiencing this issue for the past month or so. We aren't logging when it happens, but it isn't happening to everyone and for those it is happening to, the impression is that it's getting more frequent.

Similar symptoms. The tailscale app shows that the connection is live, but we can't reach services we should be able to reach through tailscale. Turning the connection off and back on again in the tailscale app resolves the issue.

**Comment by captainfodder** [comment]
This same issue only started for me with the UI overhaul version 1.46.0, and since then I am having the same issues.

At a bare minimum a notification of the VPN being disconnected would be nice so I can know when I'm offline and can re-open the app for it to reconnect. Having the constant uptime restored would be ideal though.

iPhone 12 Pro (A2341)
iOS 16.5.1 (20F75)
TailScale app 1.46.1
Carrier: Verizon

**Comment by purple-emily** [comment]
I am encountering this issue. I cannot ping any device on the tailnet.

**Comment by agottardo** [comment]
We will be rolling out a fix for this issue in the next app update. The version currently available on TestFlight already includes it.

**Comment by niklasb** [comment]
I'm experiencing this still, where the DNS server (which is routed through Tailscale) is not reachable after phone wakeup. @agottardo what version and fix were you referring to, I cannot see anything in the ChangeLog since 1.56.1 which seems related?

If needed, I can create some bug reports after wakeups where this was observed.

**Comment by HotRainRider** [comment]
Why you are closing topics that aren't fixed? iOS still dropping VPN without warning even on latest beta and macOS after 4 years still is not reconnecting after sleep mode and breaking internet altogether.

**Comment by HotRainRider** [comment]
> I'm also still experiencing this. Loose internet on a fairly regular basis (at least once a day) on my iPhone and occasionally on my iPad. Only fix is to switch off Tailscale and switch it on again. 

Yes the Talescale thing is unusable. Either it drops internet completely when BPN crashes or worse it reverts to normal DNS and you think you are secure; also the widget shows still connected when it's nor... sometimes when you just try to reconnect after a drop it doesn't and kills internet then and you need to restart the phone. 

On macOS also buggy as hell, when you go to sleep mode with Talescale VPN connected it drops internet after coming out of sleep although showing as connected with VPN; then when disconnect is clicked it disconnects and connects again right away by itself still not working. After some back and forth it maybe gets working again.

So the whole thing is just not working at all and by the looks of it since iOS problem here is over 4 years old I guess they will never fix it.

**Comment by mrkspflr** [comment]
interestingly I've never had an issue with tailscale on iOS up to ~version=1.76 since 1.76 disconnects are happening so often per day that I started to create a shortcut which reconnects the vpn under some conditions eg wifi change etc. but this is also not working as it should (error while executing shortcut automatically etc) could it be related to bluetooth + wifi routing order or changes within iOS 🤔🧐🤨
