### ISSUE TITLE
SetHostinfo now logs too seldom, leaving out important metadata

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#830]
Sometime around the v1.0 release, we changed how often SetHostinfo logs its structure, which includes important information about OS version and tailscale version. On iOS, it doesn't seem to log at all. This seems to have been an accidental result of an optimization. For proper statistics, we need to bring this back.

**Comment by bradfitz** [comment]
What does "too seldom" mean?

If it logs at start-up and on any changes, is that sufficient?

It seems like "every N minutes" is counter to our goals of minimizing network/bandwidth/battery.

Or is our policy "every N minutes, if we're already writing it to the network"? If so, what if we're just really good at making minimal network requests, as we plan to be with control protocol changes we've been discussing. Then we'd be back to rarely logging it, so is the at-start-up-and-on-changes plan sufficient?

The only point of every-N-minutes is for ease of logs analysis. But we want to have good logs analysis infrastructure anyway that can keep state over multi-day/week sessions.

I'd like to figure out the general policy here because we our current logging is a mix of styles and it's not clear there's an overall design.

/cc @crawshaw @danderson

**Comment by bradfitz** [comment]
Also, what log format should we use? The old one was an accidental Go fmt %v dump of the fields.

What about JSON, like:

```
2020/10/19 08:28:53.263237 control: HostInfo: {"IPNVersion":"date.20200921","BackendLogID":"d9f138f3e96aae117701600a23c51dd0c38b0524c548f99a6d134b7d30ef0096","OS":"linux","OSVersion":"Debian 10.6 (buster); kernel=4.9.0-6-amd64","Hostname":"tsdev","GoArch":"amd64","Services":[{"Proto":"tcp","Port":22},{"Proto":"tcp","Port":139},{"Proto":"tcp","Port":445}]}
```

?

**Comment by bradfitz** [comment]
Per meeting:
* on start & on change only is fine
* JSON is fine
