### ISSUE TITLE
MacOS 13.4 update: Tailscale exit node functionality stops working

### ISSUE THREAD

**Issue by sspreitzer** [tailscale/tailscale#8314]
### What is the issue?

After upgrading to MacOS 13.4 the exit node functionality in the MacOS tailscale client does no longer work.

Setting the network device order with `networksetup -ordernetworkservices "Tailscale Tunnel" […]` does temporarily fix the issue.

### Steps to reproduce

Using MacOS 13.4.

### Are there any recent changes that introduced the issue?

Upgrading to MacOS 13.4.

### OS

macOS

### OS version

13.4

### Tailscale version

1.42.0 (App Store)

### Bug report

BUG-2b22a8c433ae0d2c6bd83772b9a13e70a537e0fb09cd8a252b51396cf5b63f50-20230609054605Z-20906c709dc3688b

**Comment by kelivel** [comment]
@sspreitzer What are you trying to reach when the exit node fails? Your bugreport shows an ACL error when you try connecting to nodes using their local IP, and I see a DNS error. If you can share a few details about what your steps are after connecting to the exit node, I'll work on reproducing this.

**Comment by kelivel** [comment]
Closing this one for now due to inactivity. If this is still occurring, try [fully uninstall Tailscale](https://tailscale.com/kb/1069/uninstall/?tab=macos) and reinstall using the latest client version. If the behavior is still present after, reach out to our support team at http://www.tailscale.com/support and we can take a closer look and reopen this issue if a bug is identified. Feel free to mention me by name (Keli) so the request is routed to me and include a link to this issue in your message.
