### ISSUE TITLE
Support subnet routing ("relay node") functionality on Windows.

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#835]
Now that Windows supports "server mode" in the latest 1.1.x builds, the next feature users will want is Windows to be able to be a relay node, like Linux. (We've actually heard this request several times already)

This is a tracking bug for that.

Various options exist:

* Proxy TCP connections with gvisor's netstack (#707). Portable. Limits proxying to TCP and UDP (but other IP protocols aren't often used). Adds extra memory/buffering.
* Still userspace, but use TCP/IP Raw Sockets (https://docs.microsoft.com/en-us/windows/win32/winsock/tcp-ip-raw-sockets-2) and do the NAT ourselves. Maybe not terrible, but also not terribly fun.
* Figure out how to get the Windows kernel to do it for us (like we do on Linux). It does seem possible (https://www.experiencingit.net/windows/windows-server/windows-server-2016-nat-router/), but it also might require Windows Server. Maybe that's okay.

(Any others?)

I intentionally didn't compare the performance of the three options above because the use of TUN makes it non-obvious. It might even be faster to stay in userspace and make fewer system calls.

/cc @apenwarr @danderson 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2fc9d)

**Comment by apenwarr** [comment]
I started off pretty nervous about netstack but I'm starting to come around. I think it might do most things that most people want from an in-office relay. (I assume this mostly comes down to printers, SMB, and airplay.) It would work on macOS too. The netstack option would be a lot like sshuttle, but without the several disadvantages of the Linux transproxy system (most importantly: we don't have to ACK a TCP SYN until we have established the proxied connection, which is pretty cool).


All but the last option doesn't allow connections initiated *from* the Windows-hosted network *into* the tailscale network. Luckily I don't think that's a common request; there's too much value in having every Windows user log into their own machine for security purposes anyway. Relaying is almost always used to transport requests *from* Tailscale into the relayed network.

--- original message ---
On October 19, 2020, 2:05 PM EDT notifications@github.com wrote:



Now that Windows supports "server mode" in the latest 1.1.x builds, the next feature users will want is Windows to be able to be a relay node, like Linux. (We've actually heard this request several times already)

This is a tracking bug for that.

Various options exist:

Proxy TCP connections with gvisor's netstack (#707). Portable. Limits proxying to TCP and UDP (but other IP protocols aren't often used). Adds extra memory/buffering.

Still userspace, but use TCP/IP Raw Sockets (https://docs.microsoft.com/en-us/windows/win32/winsock/tcp-ip-raw-sockets-2) and do the NAT ourselves. Maybe not terrible, but also not terribly fun.

Figure out how to get the Windows kernel to do it for us (like we do on Linux). It does seem possible (https://www.experiencingit.net/windows/windows-server/windows-server-2016-nat-router/), but it also might require Windows Server. Maybe that's okay.


(Any others?)

I intentionally didn't compare the performance of the three options above because the use of TUN makes it non-obvious. It might even be faster to stay in userspace and make fewer system calls.

/cc @apenwarr @danderson

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by bradfitz** [comment]
I forgot to reference this bug, but d488678fdc928def9caa6fb261093066bdaa8980 adds hybrid netstack mode and enables it for Windows. It will be in Tailscale 1.8.0.

**Comment by kokos76** [comment]
Hey! I'm really looking forward to the opportunity to use my "Windows 10" home computer as an "Exit node"!

**Comment by DentonGentry** [comment]
If you'd like to try it, the functionality is present in the 1.8 pre-release at https://pkgs.tailscale.com/unstable/#windows
Version 1.7.403 contains the hybrid netstack mode.

**Comment by kokos76** [comment]
@DentonGentry , please tell me how to complete step 1 from this tutorial https://tailscale.com/kb/1103/exit-nodes/ on Windows? I tried and get the error: 

> PS C:\Program Files (x86)\Tailscale IPN> tailscale --advertise-exit-node
> flag provided but not defined: -advertise-exit-node

**Comment by DentonGentry** [comment]
First, you'll need to install the new version of Tailscale from https://pkgs.tailscale.com/unstable/#windows

Open cmd.exe, and use: `tailscale up --advertise-exit-node --reset`
The --reset is to work around https://github.com/tailscale/tailscale/issues/1833, noticed while trying this locally.

At https://login.tailscale.com/admin/machines you should see the Windows system has a new "Exit Node (!)" label. The exclamation point is because an admin must approve it before it can be used as an exit node. In the menu on the far right of the Windows machine's entry (with three dots), select "Review Route Settings..." and approve it.

The Windows system should now be available as an exit node for your other Tailscale devices to choose.

**Comment by DentonGentry** [comment]
Subnet relay support for Windows is in the 1.8 release.

**Comment by HunterDG** [comment]
For anyone else reading this - I just wasted a couple days spinning up a Tailscale docker container (and [failing](https://4x5mg.net/2021/06/27/how-to-install-tailscale-relay-on-docker/#comment-5754549487) for a strange reason that might need it's own issue) because the [docs](https://tailscale.com/kb/1019/subnets/) say subnet routing is only supported on Linux.  

in fact, the `--advertise-routes` flag _works just fine on Windows_ - it's just not in the GUI.  

This thread conflates subnet routing with exit node functionality (which _is_ in the GUI).

**Comment by Xe** [comment]
Subnet routing and exit nodes are basically the same thing from how they are implemented in the code. Exit nodes just aren't used by default and have extra implications on how the client uses them.
