### ISSUE TITLE
Fix Documentation about Palo Alto Networks NAT workaround

### ISSUE THREAD

**Issue by shubb30** [tailscale/tailscale#8356]
### What is the issue?

The [documentation](https://tailscale.com/kb/1181/firewalls/#palo-alto-networks) for the Palo Alto Networks firewall workaround is not really a viable workaround for most companies.  The Static IP NAT, only works in a [1:1](https://live.paloaltonetworks.com/t5/general-topics/mismatch-of-static-ip-source-translation-address-range-between/td-p/33381) mapping.  You cannot set the source, to be `any` and have it work for all devices behind the firewall.  It will throw the error in the KB forum post.

### Are there any recent changes that introduced the issue?

The documentation used to be correct, that there is no workaround for Palo Alto Network firewalls.

**Comment by DentonGentry** [comment]
It may not be universally applicable, but we added this to the KB article after confirmation from sites using it to successfully get direct connections and not use relays.

**Comment by shubb30** [comment]
Were those sites able to use it to allow all hosts to get direct access, or a single host?  I was able to get one host to have direct access using a different NAT rule type, but only one host. The screenshot does not show the source IP configuration, so it is not clear that this will only work with a 1:1 mapping.

**Comment by DentonGentry** [comment]
Are you able to use Persistent Dynamic IP and Port in the NAT Policy? I believe the option was added in PAN-OS 10.1.7.
[Persistent NAT for DIPP](https://docs.paloaltonetworks.com/pan-os/10-1/pan-os-new-features/networking-features/persistent-nat-for-dipp)

In testing here it is resulting in multiple devices able to maintain direct connections, because the Palo Alto NAT is now `MappingVariesByDestIP:false` in `tailscale netcheck`.

<img width="803" alt="Screenshot 2023-12-28 at 8 15 09 PM" src="https://github.com/tailscale/tailscale/assets/1140756/6688d734-d60a-4d9d-b39a-0953b988044f">
