### ISSUE TITLE
FR: Allow for passcode or fingerprint to access the mobile app

### ISSUE THREAD

**Issue by jkwek** [tailscale/tailscale#8486]
### What are you trying to do?

It would be nice to have the option to secure the mobile app further by setting a passcode and allowing fingerprint (Touch ID on iOS) to unlock the passcode.  I allow access to my home network via subnet router in my tailnet and would like to have this additional layer of security for:

1. Shared devices
2. If the device falls into the wrong hands while unlocked
3. Parental controls (kids can't change settings)

I use my Google account for Tailscale authentication and no passwords are ever required to bring the node up, even if I previously logged out.

### How should we solve this?

Other apps like Evernote and Dropbox implement this additional layer of security on both Android and iOS.  They have an option in their settings to create a passcode and optionally use fingerprint to unlock it.  

### What is the impact of not solving this?

I can work around this somewhat by using an app locker in Android.  It is not the most secure method but it works.  iOS I am not aware of a way to do this and therefore only install Tailscale when I need it.  I have tried logging out after I'm done using Tailscale, but my Google account is associated with my device and therefore does not require a password to reauthenticate.  With something like OpenVPN, I can require a password to connect (not save it).

### Anything else?

https://help.evernote.com/hc/en-us/articles/208314318-Set-a-passcode-to-lock-your-app
https://help.dropbox.com/installs/ios-touch-id (they have this on Android too)

**Comment by ellnic** [comment]
Could I also just add to this that the option for either Face ID/Touch ID **_OR_** a password/pin that is app specific would be ideal. 

Why?

Let's say I use tailscale on my daughters iPad. She can unlock her iPad with Face ID/Touch ID, request apps, use passwords etc. But I don't want her getting access to the tailscale app. In this case unlocking the tailscale app with Apple's authentication would be a problem. 

The only workaround I can think of is the option for both apple's authentication and an app specific authentication.

**Comment by agottardo** [comment]
Maybe a workaround: on iOS, you can use the Screen Time feature to restrict access to specific apps using a PIN (which is different from the PIN used to unlock the device).

**Comment by ellnic** [comment]
Thanks for the suggestion.

However, unless I am mistaken, you can only restrict certain things like messaging on a permanent basis and still make use of the screen time feature.  For apps to be blocked using the screen time pin, the screen time schedule must be in effect. So to restrict an app such as Tailscale permanently, the only way I can see of doing it you would have to enable downtime permanently then add all other apps to exceptions. If you’re taking about the app limits section, you unfortunately need to set at least 1 minute per day.

There doesn’t appear to be a way to just axe an app of your choice. If I’m just being daft here I am very welcome to be corrected! :-)

**Comment by agottardo** [comment]
> There doesn’t appear to be a way to just axe an app of your choice. If I’m just being daft here, I welcome being corrected! :-)

Yeah :( I tried playing around with it and sadly looks like you're correct, no way to do this properly with Screen Time.

**Comment by jkwek** [comment]
> Could I also just add to this that the option for either Face ID/Touch ID **_OR_** a password/pin that is app specific would be ideal.

This is exactly how the other apps I mentioned (Evernote/Dropbox) work.  You can set a passcode for the app that is specific to it.  There is then a separate toggle to allow to unlock the app using Face ID/Touch ID.  To me this would be ideal to implement the same way in the Tailscale app.

**Comment by agottardo** [comment]
This is a cool feature, and protecting the app UI with a PIN or Face ID can definitely be useful to some users. 

However, this is not an easy feature to implement. The first thing that comes to my mind is that since Tailscale provides a VPN extension, it can be enabled/disabled from the VPN settings of your iPhone, bypassing the app entirely.

To prevent a user from starting the VPN without authenticating, we would need to intercept any attempt to start the tunnel from outside the app and prompt the user to launch the app, authenticate them, and only then start the tunnel. This will break automations like Shortcuts, or features like VPN On-Demand.

A major painful point here is also that preventing a user from disconnecting without authenticating first is currently impossible with the APIs that Apple provides. Anybody can just toggle the switch in Settings and the Tailscale process will be killed by iOS, not allowing us to execute an authentication flow first.

MDM configurations on managed devices can be used to enforce a VPN and prevent its disablement, but this is not something easily configurable by a user and requires the device to be supervised by a MDM server.

We will do some research to determine whether implementing this feature is feasible.

**Comment by ellnic** [comment]
FWIW, yes the VPN can be disabled/enabled but the reason I wanted the feature was more to hide the IPs and stop the tailscale config being messed with accidentally. It’s not because I want a completely bullet proof way to stop the VPN being enabled/disabled. 

Having said that, yes of course it would be nice. However, this would have to come from Apple. As much as I love my iDevices, Apple continue to perplex me. Why have all the screen time control when I can’t lock out the setting app, or at least certain elements of it!

**Comment by jkwek** [comment]
> However, this is not an easy feature to implement. The first thing that comes to my mind is that since Tailscale provides a VPN extension, it can be enabled/disabled from the VPN settings of your iPhone, bypassing the app entirely.

Hmm, that is a tricky situation that I didn't consider.  It sounds like a PIN/Face ID/Touch ID configuration would work for ellnic's case of not wanting kids to change settings within the app, but not for my use case of preventing access to my tailnet if someone else has my phone unlocked.   Perhaps if there's another auth method I can use and require a password every time to connect I can work around it.  If I go into the VPN area in the Settings App, my OpenVPN connections do not connect because I did not save the password, while the Tailscale connects right up.  If it could require a password or PIN before allowing the connection, that would be ideal.

> We will do some research to determine whether implementing this feature is feasible.

Thank you!

**Comment by ellnic** [comment]
@jkwek it may not do much, but we could always drop an message here: https://www.apple.com/feedback/

Apple could so easily solve this and improve the situation by:

1. (In your case) having an option to request the device pin for VPN / WiFi changes (like macOS)
2. (In my case) allow a device managed by screen time to: 
 a) screen time pin restrict the settings app
 b) and / or only allow certain sections of it (like WiFi)

As I said above, Apple continue to perplex me. 

There’s a slim chance, but if as many people as possible drop a FR message in feedback, it _could_ happen.

**Comment by Baven1227** [comment]
Good shit

**Comment by angorn23** [comment]
I’m curious if there has been any more thought put to this, I would also really like the option to require a PIN to open the Tailscale app. 

Tailscale alongside Adguard Home have done wonders to help protect my kids even when away from home, until they learn that Tailscale is the app they need to turn off the VPN from… then it’s useless…

I will also submit a request to Apple, it’s absolutely absurd that you can’t set a screen time limit of 0. 1 minute, then a free minute is plenty of time to turn off Tailscale or whatever…

Thanks guys, and fantastic product!!

**Comment by agottardo** [comment]
The only way to do this at the moment is by supervising the iOS device, installing the Tailscale VPN configuration with a configuration profile and on-demand rules set to Always. You would need to [do this](https://tailscale.com/kb/1380/ios-mdm#install-the-tailscale-vpn-configuration) via Apple Configurator or a MDM solution. Applying the [ForceEnabled](https://tailscale.com/kb/1315/mdm-keys#force-tailscale-to-always-be-running) policy might also be useful.

**Comment by angorn23** [comment]
Thanks for the quick reply, I am looking into this now, thank you for pointing me in the right direction.
