### ISSUE TITLE
ip ssl cert problem

### ISSUE THREAD

**Issue by ZhiShengYuan** [tailscale/tailscale#8516]
### What is the issue?

it's seems that tailscal doesnt support the ip ssl,if you use this, `tailscale netcheck` will report `tlsdial: warning: server cert for "DELETED" is not a Let's Encrypt cert`

### Steps to reproduce

1:install tailscale
2:setup a derp server (but listen 127.0.0.1,HTTP only)
3:setup an nginx as the web server,reverse proxy `/bootstrap-dns` and `/derp` to the derp
4:add this node to acl, and test it

 

### Are there any recent changes that introduced the issue?

please notice that if the domain is used, it works well
the ip SSL cert is free , and get from Zerossl 

### OS

Linux

### OS version

Debian 12

### Tailscale version

1.14.4

**Comment by DentonGentry** [comment]
The error message comes from:
https://github.com/tailscale/tailscale/blob/ffaa6be8a4d84f3c5595328a44f3df2a8cf92e7f/net/tlsdial/tlsdial.go#L101-L116

It is trying to be helpful in the error message, as all of Tailscale's own infrastructure uses Let's Encrypt. However, it only printed that message because the certificate validation failed. Provides other than Let's Encrypt do work if the certificate validates.

The most common reason for validation to fail when using other CAs is lack of a complete certificate chain: a CA's root certificate signing an intermediate certificate which signs the derper's certificate. If the intermediate certificate is omitted from the bundle, `tailscaled` will likely fail to validate the cert.

A browser may still be able to work even when `tailscaled` says there is a problem: browsers are commonly bundled with the current intermediate certificates for a large number of CAs.

**Comment by DentonGentry** [comment]
The problem is that the certificate is not valid, not something Tailscale can help with.

**Comment by ZhiShengYuan** [comment]
> The problem is that the certificate is not valid, not something Tailscale can help with.

Thank you for your help, even though I have confirmed that the certificate is valid (it is accepted by Chrome, Firefox, and Linux), I believe this warning is only because it is not issued by Let's Encrypt. Since I no longer use IP certificates, I cannot reproduce this issue. Thanks again for your assistance.
