### ISSUE TITLE
FR: exit node support in tsnet

### ISSUE THREAD

**Issue by peterkeen** [tailscale/tailscale#8553]
### What are you trying to do?

When using tsnet it would likely be useful for some applications to be able to use an exit node on the tailnet for egress traffic, specifically when using `HTTPClient`.

### How should we solve this?

Add a `ExitNodeIP` setting to `tsnet.Server` that sets up the exit node on `Start`.

### What is the impact of not solving this?

Currently not using, it just seems like something that's missing.

**Comment by DentonGentry** [comment]
Could I ask what having an exit node function in tsnet would accomplish that could not be accomplished by running `tailscaled`?

I ask because the packet forwarding paths are very different:
1. `tailscaled` on Linux with a `/dev/net/tun` device can push packets down to the kernel to forward out to the Internet.
1. tsnet runs a TCP/IP stack entirely in userspace. This works but has various drawbacks, for example it has to terminate TCP connections on one side and re-initiate a new outgoing TCP connection on the other. This doesn't perform as well and doesn't provide end-to-end flow control.

**Comment by peterkeen** [comment]
@DentonGentry yeah honestly now that I've had some time to think about it, the request doesn't make a ton of sense.

**Comment by bmteller** [comment]
this feature would be useful for us but we already have our own workaround in place. we kind of make use of the tsnet package in order to run an exit node on a device where we can't run tailscaled. I took some of the tsnet code and rewrote it so it would run an exit node. its about ~500 lines of code. the imports look like:

```
        "tailscale.com/control/controlclient"
        "tailscale.com/ipn"
        "tailscale.com/ipn/ipnlocal"
        "tailscale.com/ipn/store"
        "tailscale.com/net/dns"
        "tailscale.com/net/interfaces"
        "tailscale.com/net/netaddr"
        "tailscale.com/net/netmon"
        "tailscale.com/net/tsdial"
        "tailscale.com/smallzstd"
        "tailscale.com/tsd"
        "tailscale.com/types/logger"
        "tailscale.com/types/logid"
        "tailscale.com/types/nettype"
        "tailscale.com/util/must"
        "tailscale.com/wgengine"
        "tailscale.com/wgengine/netstack"
```

the downside for us is a lot of these interfaces our tailscale internal interfaces and if we ever want to update the tailscale code it breaks our client.

**Comment by cedws** [comment]
I was looking for this to be able to use Tailscale as a sort of VPN SDK. I have specific requests I want to route via a Tailscale exit node, without wanting the complexity of also running tailscaled in my container.

**Comment by korfuri** [comment]
One use-case I have been considering: I'd like to advertise exit nodes on my tailnet that send the traffic through other VPNs. For instance, I have a commercial VPN provider that offers me multiple egress points, and I can connect to any of those via a dedicated Wireguard configuration they provide. I have N client devices on my tailnet who may want to use some of these points of egress sometimes, but I don't want to manage N devices * M outgoing connections.

I can achieve this by creating various network namespaces on an always-on node, and getting creative with routing, but it could be error-prone. Instead, I was toying with the idea of a simple Go binary that glues together tsnet (setup as an exit node) and a userspace wireguard connection. It would then pass the bytes back and forth between the two connections. This would give me as many virtual nodes on my tailnet as I need, and I could just pick an exit node among the list in tailscale, without having to manage multiple VPNs concurrently.
