### ISSUE TITLE
FR: generate TLS certificates for k8s-operator exposed services

### ISSUE THREAD

**Issue by dhess** [tailscale/tailscale#8638]
### What are you trying to do?

I've exposed several services in my Kubernetes cluster to my Tailnet using `k8s-operator`, but besides the `kube-apiserver`, which appears to be handled as a special case, it's not obvious how one would create TLS certificates for the exposed services.

For example, I've exposed my Argo CD service, and its machine name on the Tailnet is `argocd`, but I can only access it via HTTP. Creating TLS certificates for real machines requires [running `tailscale cert`](https://tailscale.com/kb/1153/enabling-https/#provision-tls-certificates-for-your-devices) on that machine, but it's not clear how one would do that for an exposed Kubernetes service.

### How should we solve this?

Setting an annotation on the service to create a TLS certificate for its Tailnet "machine" would be a really nice way to solve this.

### What is the impact of not solving this?

No known workaround.

**Comment by michaelbeaumont** [comment]
At the moment the k8s-operator just uses iptables to directly forward traffic to the `LoadBalancer` `Service`, and there's no room for TLS handling with this mechanism. But it's also not clear whether `Service` is the right abstraction here since we would then no longer be directly load balancing all `Service.spec.ports`. 

I started a little experiment exposing the `tailscale serve tls-terminated-tcp` functionality, which handles TLS certs. But it uses [Gateway API](https://gateway-api.sigs.k8s.io/), i.e. the next interation of `Ingress`, instead: [michaelbeaumont/tailway](https://github.com/michaelbeaumont/tailway).

One other way I think might work is to act a little like `cert-manager` where, while keeping the direct iptables forwarding, the `k8s-operator` also manages getting and renewing the TLS certs but instead of keeping them in the tailscale state `Secret`, it exposes them in a TLS `Secret` for use with any arbitrary in-cluster `Ingress` or Gateway API implementation.

**Comment by maisem** [comment]
The operator now has support for Kubernetes Ingress resources which allow generating TLS certs.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ts-ingress
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - hostname
  defaultBackend:
    service:
      name: nginx
      port:
        number: 80
```
