### ISSUE TITLE
Tailscale pod restart causes duplicate node key

### ISSUE THREAD

**Issue by joeypiccola** [tailscale/tailscale#8679]
### What is the issue?

Using a similar deployment shown [here](https://github.com/joeypiccola/k8s_home/blob/main/kubernetes/applications/networking/tailscale/app/deployment.yaml), when tailscale pod is terminated and a new one starts the warning "duplicate node key" appears in the console for the machine. 

My understanding with state is that it is written to the Kubernetes `tailscale-auth` secret. I create this secret in advance with only an `AUTH_KEY`, following the tailscale pod startup I see `_current-profile`, `_machinekey`, `_profiles`, and `profile-xxx` created in the secret. This info remains unchanged when a pod is terminated and a new one starts. 

### Steps to reproduce

Create a kubernetes secret named `tailscale-auth` with your `AUTH_KEY`. Deploy tailscale similar to deployment linked in "What is the issue". Once confirmed the deployment and tailscale are functioning, delete the pod. In my case the new pod comes up but in the web console for the machine it shows "duplicate node key". 

### Are there any recent changes that introduced the issue?

A node was lost in a kubernetes cluster causing the pod to come up on a differnt node. Upon coming up "duplicate node key" was noticed for the machine in the web console. 

### OS

Other

### OS version

Kubernetes v1.26.0

### Tailscale version

v1.44.0

**Comment by irbekrm** [comment]
> when tailscale pod is terminated and a new one starts the warning "duplicate node key" appears in the console for the machine

I think this happened because there was a period of time when the old pod was not yet terminated and the new pod was starting up and tailscale was running in both and calling the control server with the same node key retrieved from the state in the `Secret`.

The possibility of ending up in this state should have been reduced by the change in https://github.com/tailscale/tailscale/pull/6087/commits/a2ca72393352606e75ed73121551a4a8575a3303 and I can see that with this change recreating a pod does not result in duplicate node issue as the old pod is terminated almost immediately. If you are using the `v1.44` image that already includes this change, but you are overriding it with the deprecated `run.sh` script.

Would you be able to try to update your manifest to not run the script and see whether that fixes the issue? You might need to change a couple env var keys, see https://github.com/tailscale/tailscale/blob/main/docs/k8s/subnet.yaml.

**Comment by joeypiccola** [comment]
All fixed! Thank you. 100% my fault, blindly copying things around. Thanks again!
