### ISSUE TITLE
No container image tagged 1.46.0?

### ISSUE THREAD

**Issue by evandeaubl** [tailscale/tailscale#8687]
### What is the issue?

It's been a few days since the 1.46.0 release, but I haven't seen a container image show up either on docker.io or ghcr.io, either with a 1.46.0 tag, or even an update to the latest tag. My tailscale pod feels left out. :smile:

### OS

Linux

**Comment by DentonGentry** [comment]
Because so many sites automate deployment of container images the instant they appear, we routinely wait at least a day after release to look for anything unexpected that didn't turn up in testing.

There was something unexpected after 1.46.0, a regression in ARM platforms using a non-4k page size: https://github.com/tailscale/tailscale/issues/8658. Our ARM testing was all on 4k page size platforms. We have withdrawn the Linux ARM packages for 1.46.0. As x86-64 is unaffected those packages remains up.

We expect to release 1.46.1 next week. A day or so after that release, if nothing untoward is noted, we'd publish container images.

**Comment by evandeaubl** [comment]
Gotcha, was wondering if it was something like that. Thanks for the quick response!
