### ISSUE TITLE
Tailscale API List tailnet devices  - OAuth client based query does not report 'shared in' devices

### ISSUE THREAD

**Issue by jwtb** [tailscale/tailscale#8707]
### What is the issue?

- API access token request get list of all devices (isExternal = **false|true**)
- request with OAuth generated token does not show 'shared in' devices (isExternal = **true**)

I understand API response depends on the access token used in some cases (https://github.com/tailscale/tailscale/blob/main/api.md#list-tailnet-keys).  What about device list, I expected to see all devices with OAuth client based query.

Tested with **org.github** and **@gmail.com** free plans.

### Steps to reproduce

- tailnet with single 'shared in' machine 
- `curl -s -u "tskey-api-API-access-token:"  'https://api.tailscale.com/api/v2/tailnet/-/devices' ` (token from admin console) - all machines listed
- `curl -s -u "tskey-api-OAuth-access-token:" 'https://api.tailscale.com/api/v2/tailnet/-/devices'` (token created with OAuth client) - 'shared in' node missing in response

**Comment by knyar** [comment]
Note that [node sharing](https://tailscale.com/kb/1084/sharing/) involves sharing a node with an individual user, not the whole tailnet. Since an OAuth client is not associated with a specific user, it does not display devices shared with users in its tailnet. As you pointed out, using a personal API token will make nodes shared with the user included in the response.
