### ISSUE TITLE
ESET can't recognize Tailscale's style of Windows firewall rules

### ISSUE THREAD

**Issue by foriequal0** [tailscale/tailscale#8781]
### What is the issue?

This is not actually a bugfix request.
Obviously it's ESET's problem. I'll report this to them too.
This is just a note for whoever suffers from the issue.

Tailscale effectively runs these commands to create defender firewall rules:
```cmd
netsh advfirewall firewall add rule name=Tailscale-In dir=in action=allow localip=<CIDR> profile=private enable=yes
```
https://github.com/tailscale/tailscale/blob/301e59f398c955f22c481ca1cb92eb32694f3c8b/wgengine/router/router_windows.go#L283

But ESET Endpoint Security seems doesn't recognize that form.
ESET only seems to recognize when rule is given with `protocol=<TCP/UDP/...>` but without `localip=<CIDR>`.
If we give `localip=` or, omit `protocol=` (or give `protocol=any`), neither of them will work.

Workaround might be:
```
netsh advfirewall firewall add rule name=Tailscale-In-TCP dir=in action=allow remoteip=100.64.0.0/10,fd7a:115c:a1e0:ab12::/64 protocol=tcp profile=private enable=yes
netsh advfirewall firewall add rule name=Tailscale-In-UDP dir=in action=allow remoteip=100.64.0.0/10,fd7a:115c:a1e0:ab12::/64 protocol=udp profile=private enable=yes
```

### Steps to reproduce

Install Tailscale.
Install ESET Endpoint Security.
Enable ESET Firewall.

You can't access to the node from other nodes in the tailnet.

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.46.1

### Other software

ESET Endpoint Security 9.0.2046.0

### Bug report

BUG-dc7ca7caa9f5e0ea3c8c9028c9242ff2db5b26d63601bb5cff5472cce280a35c-20230803094156Z-0f97b37a5461c9a8

**Comment by DentonGentry** [comment]
Thank you for describing the issue.

I think this will still be discoverable by anyone else encountering the issue whether it is open or closed, so I'm going to close the issue.

**Comment by mato** [comment]
I came across this while searching for "Tailscale ESET firewall" or similar, so am going to add my own experience here before I forget, in the hope that it will be useful to others.

Scenario: Windows 10 client, ESET Endpoint Security 10.1.2058.0. ESET's firewall is configured with the recommended defaults that their policy gave me, i.e. "Automatic" mode.

In order to get Tailscale to work, starting from _Settings_ -> _Advanced settings_ (gear icon at bottom right) in the ESET UI:

1. Go into _Protection_ -> _Network protection_ -> _Firewall_  and turn _Evaluate also rules from Windows Firewall_ **ON**.
2. Go into _Protection_ -> _Network protection_ -> _Firewall_ -> (Rules) _Edit_ and add the following firewall rule:
    a. Name: Allow all to/from Tailscale IPs.
    b. Action: Allow.
    c. Application: Any or no signature.
    d. Direction: Both.
    e. IP Protocol: Any.
    f. Local host: Any.
    g. Local port: Any.
    h. Remote host: 100.64.0.0/10
    i. Remote port: Any.
    j. Profile: Any.

Note that I only have ESET in a non-English locale installed here, so the above may not match exactly what you see, but you get the idea.
