### ISSUE TITLE
Tailscale app is outdated in Synology Package Center

### ISSUE THREAD

**Issue by pawisoon** [tailscale/tailscale#8914]
### What is the issue?

Latest available app is 1.38.4-700038004, and Version 1.48.0 is available(for linux). 
Can we please get this updated in Synology Package Center and automate release for future so we always have up to date and secure version available for Synology? 

### OS version

DSM 7.2

**Comment by DentonGentry** [comment]
I understand the frustration and the belief that surely automation is the answer.

- The process to submit updated packages to Synology is a manual one.
- We release [updated Tailscale versions every 4 weeks](https://tailscale.com/kb/1168/versions/). Under no circumstances will the Package Center accept updates at that rate.

We pick and choose which releases to submit, sending those which have something especially meaningful for Synology specifically. Otherwise, we risk being unable to deliver a release which contains something of especial interest to Synology users solely because we submitted a build too recently. 

At this point, if you want features from recent development it is best to manually load the package from https://pkgs.tailscale.com/stable/ or, if you want to really live on the edge, from https://pkgs.tailscale.com/unstable/

**Comment by pawisoon** [comment]
Thanks for explaining @DentonGentry. Now I understand it. Would it be possible for Tailscale project to host a package source recognisable by Synolgy? e.g. 
<img width="936" alt="Screenshot 2023-08-17 at 23 51 09" src="https://github.com/tailscale/tailscale/assets/6951295/9295ba2d-7571-408c-ab39-708c6a49ac39">

**Comment by DentonGentry** [comment]
We're working in a different direction: Tailscale 1.48.0 adds support for `tailscale update` on Synology platforms, which will download and install an updated version. This is expected to be the basis for an autoupdate system.

https://tailscale.com/changelog/#2023-08-16-service

**Comment by DentonGentry** [comment]
Closing as not having an immediate solution, but we'll proceed with work on `tailscale update`

**Comment by dimaguy** [comment]
This issue needs to be reopened as tailscale is already in 1.56.1 while synology is lagging behind in 1.38.4. Is there any issue blocking this @DentonGentry?
Plus, I'm not too sure it is a good idea to get software to autoupdate outside of the Package Center umbrella (because it means that people will be first downloading an outdated version that might have security issues down the line), so if you're going that path maybe create a minimal net installer-only version that synology package center distributes.
Or just host a synology 3rd party repo, I believe that's already done on debian-based distros so it's nothing new

**Comment by DentonGentry** [comment]
We wanted the [updated web interface](https://tailscale.com/kb/1325/device-web-interface) to be in the next release submitted to the Package Center. The updated web interface is in 1.56.0.

When we prepare to submit an update to the Package Center we wait a few weeks after the general release on other platforms and [Synology users using our builds](https://pkgs.tailscale.com/stable/#spks) to watch for signs of unexpected trouble or regression. That will be in January. We do not have a way to issue a quick-fix nor rollback, if a release makes it out with a regression then it will remain in the Package Center with that problem for an extended period of time.

Once submitted for testing, it takes about a month for the new release to appear in the Package Center. So we'd expect an update in probably Q1 of 2024.

**Comment by dimaguy** [comment]
The updated web interface idea sounds cool yeah!
What about having a 3rd party repo for a more "bleeding edge" update channel and the main Package Center repo for stable "battle-tested" versions? As far as I can tell the delay on the main repo comes from it requiring a manual test by synology, something that wouldn't apply on the 3rd party one

**Comment by rjakobsson** [comment]
Tailscale is currently not working on the Synology platform, because of the login-button malfunctioning. Would appreciate an update / a fix.

**Comment by dimaguy** [comment]
> Tailscale is currently not working on the Synology platform, because of the login-button malfunctioning. Would appreciate an update / a fix.

I'd recommend opening a new issue for that, raises more attention

**Comment by MoritzWeber0** [comment]
> Once submitted for testing, it takes about a month for the new release to appear in the Package Center. So we'd expect an update in probably Q1 of 2024.

Is there any news? The latest version of Tailscale is still 1.38.4 in the Synology Package Center.
