### ISSUE TITLE
"cannot determine CPU architecture for Synology model "DS213v10-j" (Go arch "arm")"

### ISSUE THREAD

**Issue by Smultie** [tailscale/tailscale#8927]
### What is the issue?

Decided to try out the new 'tailscale update' feature on my Synology NAS. 
Not sure if it's supposed to work on the device, either

### Steps to reproduce

Log into Synology with SSH.
'tailscale update'

### OS

Synology

### OS version

Synology DSM 6.2.4

### Tailscale version

1.48.0

**Comment by snachx** [comment]
same problem here DS216play-j

**Comment by awly** [comment]
Those device models need a [CPU-specific SPK package](https://pkgs.tailscale.com/stable/#spks). Without knowing the exact CPU architecture, `tailscale update` can't figure out which SPK to download.
Some of the Synology CPU architectures (anything other than i686, x86_64 and armv8) are armv5 or armv7 from Go's perspective, but they won't accept a generic armv5/v7 SPK. So we currently map certain device models to CPU architectures they have per Synology docs.  

We detect the device model in `tailscale update` by reading `/proc/sys/kernel/syno_hw_version`, which may or may not be the right place. DSM doesn't seem to ship any other tools to detect this programmatically.

@Smultie @snachx do you know which exact model your devices are, according to the list at https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures or https://kb.synology.com/en-us/DSM/tutorial/What_kind_of_CPU_does_my_NAS_have?

Is `DS213v10-j` is `DS213` or `DS213j`?
Is `DS216play-j` the same as `DS216play` or `DS216j`?

One other useful piece of data is `/etc/synoinfo.conf`. Could you paste the output of `grep platform_name /etc/synoinfo.conf`?
Perhaps we can detect CPU platforms that way, instead of by device model name.

**Comment by Smultie** [comment]
grep platform_name /etc/synoinfo.conf showed no information 

However, when scrolling through /etc/synoinfo.conf I noticed the following field:
unique="synology_88f6282_213"

Not sure what that reads for other devices (@snachx ??), but I'm pretty sure the '88f6282' portion refers to the CPU.

**Comment by snachx** [comment]
@awly @Smultie 

My device model is DS216play, the package arch is monaco, DS216play and DS216j are different devices with different package arch.

the output of grep platform_name /etc/synoinfo.conf is empty.
grep unique /etc/synoinfo.conf shows:
unique="synology_monaco_ds216play"

the second part is the same as the package arch.

**Comment by awly** [comment]
Thanks for all the info!
I made a fix and it will be available in 1.48.1. Keeping this issue open until we confirm.

**Comment by Smultie** [comment]
You're welcome and thank **you**
Updating the *.spk manually everytime is quite a hassle, so being able to update over SSH is a great QOL improvement!

Having the Synology package center just do it all automatically for us would be even better, but I guess that's outside what Tailscale can influence...?

**Comment by bradfitz** [comment]
The SPK generation is all automated on our side. We can't push arbitrary updates to Synology Package Center whenever we want, though. They accept updates occasionally (and manually) and it's not a super quick process.

**Comment by awly** [comment]
1.48.1 is published with the fix for CPU detection.
