### ISSUE TITLE
iOS app drains battery at higher rate than expected

### ISSUE THREAD

**Issue by ellnic** [tailscale/tailscale#8957]
### What is the issue?

@agottardo This was mentioned @doodlemania2 in the issue that tracked the new VPN on demand feature but I don’t see an open issue for it (unless I’ve had a brain fart). 

I too get this, I know you mentioned you were looking into this but I’ll open this just so we can troubleshoot. 

For me, when VPN is enabled, battery drain seems to be approx 5% per ~10 mins. iPhone 12 Pro Max, 89% battery health. 

### Steps to reproduce

1. Enable  VPN
2. Use phone monitoring battery percentage
3. Disable VPN - notice decline in drain

### Are there any recent changes that introduced the issue?

I don’t know. I’ve only just started using Tailscale for  iOS. 

### OS

iOS

### OS version

16.1

### Tailscale version

1.48.0

### Other software

None - test device.

**Comment by bradfitz** [comment]
Dup of #3363

**Comment by ellnic** [comment]
Wow ok. I did do a search but didn’t go as far back as 2021!! Sorry for the dupe.

**Comment by agottardo** [comment]
@ellnic if you want to provide extra details in that issue, please make sure to attach a Bug Report ID. We need to look at diagnostics to determine what is causing abnormal power consumption.

Updating to a newer iOS version is also likely to improve battery life on your device quite a bit. This is not something Tailscale-specific, however you're definitely missing out on the many performance/power improvements that Apple has released since October 2022.

**Comment by ellnic** [comment]
@agottardo thanks - I don’t always jump on bleeding edge Apple updates due to certain apps that haven’t been updated to include support yet. I will, however, update on my test device and monitor. I’ll report back with bug report IDs if the issue persists. 👍
