### ISSUE TITLE
Tailscale on Windows 7 is completely broken

### ISSUE THREAD

**Issue by ithakaa** [tailscale/tailscale#8962]
**After dedicating significant time and conducting thorough testing, I've come to the conclusion that the intended functionality doesn't work on Windows 7, regardless of Tailscale's claims.**

My Ubuntu Server 22.0.4 is successfully running Headscale without any issues for both my Linux and Windows 10 nodes.

After investing a substantial amount of effort, I've successfully established a connection between Windows 7 (SP1, 64-bit) and Headscale by disabling the Tailscale service and manually running tailscaled with the "-tun userspace-networking" flag through an administrator command prompt.

Nevertheless, I've identified two critical issues with Windows 7:

1. The Tailscale IP (100.64.111.4), as reported by my Headscale server, doesn't appear in the results of "ipconfig /all" or "route print."

2. While I can ping the Ubuntu server with IP 100.64.100.2, I'm unable to ping Windows 7 at 100.64.111.4 from the Ubuntu Server at 100.64.111.2, even with the Windows firewall disabled.

### Steps to reproduce

Clean installation of Windows 7 SP1 (64)
Install Tailscale 1.32.0 **(all other versions are completely broken)** 

### OS

Windows

### OS version

Windows 7 SP1 - 64

### Tailscale version

1.32.0, all other versions are broken

**Comment by bradfitz** [comment]
When you say `-tun userspace-networking` you get what it says on the tin: userspace networking. That means it doesn't tell the Windows kernel about anything. So you don't get an IP address that Windows knows about, routes that Windows knows about, etc. Instead, it's all terminated and relayed from the tailscaled.exe process.

See https://tailscale.com/kb/1112/userspace-networking/

That page says it's about "Containers" but it's really about all use of `-tun userspace-networking`.

So that part is working as intended.

We're dropping support for Windows 7 because Microsoft, WireGuard, and Go are all dropping support for Windows 7, making supporting that platform increasingly impossible.

But we had been testing Windows 7 in prior releases and it did work in normal kernel mode, at least for some versions of Windows 7 that are fully updated with all the various service packs and hot fixes (e.g. https://github.com/tailscale/tailscale/wiki/Win7).

We won't be debugging Windows 7 issues going forward, though.

**Comment by DentonGentry** [comment]
I'll post the draft I was working on, but leave the bug closed.

> The Tailscale IP (100.64.111.4), as reported by my Headscale server, doesn't appear in the results of "ipconfig /all" or "route print."

Tailscale's normal mode of operation is a TUN device. On Linux this is `/dev/net/tun`, on Windows this is the WinTUN drive. TUN is a way for userspace processes to send IP packets to the kernel for processing. When you see a `tailscale0` interface in `ipconfig /all`, it is the TUN device you are seeing.

`-tun userspace-networking` means not to use TUN, use a userspace TCP/IP stack instead. You won't see the interface in `ipconfig /all` for that reason: it isn't a network interface at all, it is an application.

We don't test and never supported `-tun userspace-networking` on Windows. It undoubtedly does work to some extent, but isn't something we'd debug further.

> While I can ping the Ubuntu server with IP 100.64.100.2, I'm unable to ping Windows 7 at 100.64.111.4 from the Ubuntu Server at 100.64.111.2, even with the Windows firewall disabled.

Given a Tailscale IP address we could consult telemetry to look into why this is. It is not related to the `ipconfig /all` symptom. As you're using Headscale there isn't really more to do here.

> 1.32.0, all other versions are broken

You are welcome to use 1.32.0. Tailscale releases maintain backwards compatibility for a long, long time. The oldest node still in active use runs release 0.100. It is a node we run in order to test interoperability.

**Comment by ithakaa** [comment]
> We won't be debugging Windows 7 issues going forward, though.

I kindly suggest that any mention of Windows 7 support be reconsidered and removed from the official Tailscale documentation. This will help prevent potential confusion and frustration for users who may attempt to use Tailscale on Windows 7 based on the documentation's information.

In my case, it took a few days to come to this realisation
