### ISSUE TITLE
[android] App pretended to work, but actually didn't, when another VPN was already running

### ISSUE THREAD

**Issue by njsmith** [tailscale/tailscale#904]
**Describe the bug**

I installed the Android app on a phone that already had a VPN connected using the [Wireguard app](https://play.google.com/store/apps/details?id=com.wireguard.android&hl=en_US&gl=US). The Tailscale app authenticated fine, my phone showed up in the Tailscale website admin console, the app said it was active, etc., but in fact the app wasn't working at all, and never even popped up the Android system dialog to request permission to work as a VPN. In order to get it to work, I had to manually go into the phone's network settings and disconnect my Wireguard VPN, and then toggle the active/inactive button in the Tailscale app, and *then* I got the permission dialog and was able to actually use Tailscale.

I get that you're working with the system VPN frameworks here and they might have limitations. But at the least it would be good if the Tailscale app could detect this case and tell you that it's not working and you need to go disable your current VPN or whatever.

**Version information:**
 - Device: Pixel 3a
 - OS: Android
 - OS version: Android 11
 - Tailscale version: 1.2.2-t76c298d8-g39dfd8495

**Comment by eliasnaur** [comment]
I couldn't reproduce not getting the system VPN dialog on Android 11. I installed Wireguard, added a tunnel, started it, and then signed in to Tailscale and started its VPN. System dialog popped up every time for me, and on "OK" Tailscale's VPN replaced Wireguard's, as expected. The other way round worked as well: starting Wireguard again automatically stopped Tailscale.

However, I did notice that if you cancel the system dialog, or exit Tailscale while the dialog is shown, the Tailscale VPN is not automatically stopped. That will be fixed in the next release.
