### ISSUE TITLE
Updated Umbrel App, No longer starting

### ISSUE THREAD

**Issue by 0ceanSlim** [tailscale/tailscale#9054]
### What is the issue?

I updated my umbrel node tailscale install yesterday and since then my tale scale is not starting on umbrel. Just stuck in the starting. 

### OS

Linux

### OS version

umbrel on Ubuntu LTS

### Tailscale version

v1.46.1

**Comment by DentonGentry** [comment]
The template asks for a bugreport because without it, we're not going to be able to debug anything.

If you can't obtain a bugreport, I'd recommend to contact https://tailscale.com/contact/support/ instead. That will give them enough information to find the tailnet, and from there locate telemetry from the device.
