### ISSUE TITLE
 v1.48.2 not containerized?

### ISSUE THREAD

**Issue by NLZ** [tailscale/tailscale#9426]
### What is the issue?

If I see it correctly then v1.48.2 has not been pushed to Docker Hub or GitHub Packages, v1.48.1 is the latest.
https://github.com/tailscale/tailscale/pkgs/container/tailscale/versions?filters%5Bversion_type%5D=tagged
https://hub.docker.com/r/tailscale/tailscale/tags

Is it intentional? Or something broke in the pipeline?

**Comment by DentonGentry** [comment]
Because so many sites automate deployment of container images the instant they appear, we routinely wait a bit after release to look for anything unexpected that didn't turn up in testing. I expect to release the container images next week.

**Comment by NLZ** [comment]
Sounds like a weird policy, if someone is pulling `:latest` then they are expecting to get the latest stable version.
I would understand a day of delay, but 2 weeks seems excessive.
Especially because it's already pushed to everywhere else, like all mobile versions and the non-containerized linux package managers via pkgs.tailscale.com.

**Comment by yuha0** [comment]
Even if the team is able to capture some issues during this intentional delay, shouldn't the fix be introduced in a newer version instead of overwriting the existing one? I was under the impression that each release is suppose to be immutable. Historically, [there has been some release tag that failed to release to any platform](https://github.com/tailscale/tailscale/releases/tag/v1.38.0), and the fix was later published in a separate release, and I like that approach.

I don't know how this intentional delayed process is implemented. But on user's end: 

when a new version is available, an org admin can upgrade _all_ their tailscale deployments _but_ the containerized ones. They see the upgrade nudges in admin console all the time but there's nothing they can do, so they have to learn to ignore that. They may set reminders to check dockerhub/ghcr later and hope they don't forget. This is obviously a lot of operational overhead.

**Comment by DentonGentry** [comment]
We have released the 1.48.2 containers.

> shouldn't the fix be introduced in a newer version instead of overwriting the existing one? I

Yes. If a problem in release X is found sufficient to block release of containers, an X+1 release is built and will be the one released for containers.

> an org admin can upgrade all their tailscale deployments but the containerized ones

There is no mechanism by which the Apple App Store, Google Play Store, the various Linux distributions which handle their own packaging, and pkgs.tailscale.com will all release their binaries at the same time. I understand the frustration, but org admins will have to be able to accept some platforms being available before others.
