### ISSUE TITLE
Android Always-On-VPN turns off after a Restart (tailscale changes from Active to Stopped)

### ISSUE THREAD

**Issue by tom-hampton** [tailscale/tailscale#9428]
### What is the issue?

this is not a duplicate of #2481. That issue noted that tailscale was stopped before reboot. This issue specifically notes that tailscale was active prior to the reboot.

1. Tailscale is set as always on VPN in settings
2. Tailscale is active and connected
3. Restart android
4. Tailscale is stopped after reboot.

I get an error in notifications pull down from the VPN system stating "tailscale is setup to stay connected all the time, but it can't connect right now. Your phone will use the public internet until tailscale can connect."

From that dialog I can "change VPN settings" or open the app. If I open the app I can the set tailstale from stopped to active, and everything works fine, until I reboot again....which repeats the experience.

### Steps to reproduce

1. Tailscale is set as always on VPN in settings
2. Tailscale is active and connected
3. Restart android
4. Tailscale is stopped after reboot.

### Are there any recent changes that introduced the issue?

No.   I only recently noticed that it wasn't working anymore.   It was working back in January when I first enabled always-on VPN.   

### OS

Android

### OS version

Samsung Android 12 (S21 Ultra)

### Tailscale version

1.48.2

### Bug report

BUG-674e2f81e675fd5c8ce3d95ccfbb6a003a068c68404263d937d5e0c4f62b5a8b-20230916215324Z-7b370335137689fa

**Comment by Craeckie** [comment]
I have the same problem on Lineage OS 20 (Android 13).
It occurres since the update 1.44.1 -> 1.48.0.

Additionally, the exit node is disabled every time, so I need to open the menu -> Use Exit Node and select one.

It also happens on my second tailscale in a work profile, where I have to re-enable it and the exit node every time I activate the work profile.

**Comment by senses3** [comment]
Same issue as previous posts. Tailscale is connected -> reboot phone -> tailscale is NOT connected -> enter tailscale app -> existing login is not listed, I have to click on 'choose server' and then click 'login' (i'm connecting to my own headscale server) and it will reconnect, but it forgets the previous exit node configuration. 

I'm on tailscale 1.48.2 on grapheneOS (Android 13)

**Comment by Quintasan** [comment]
I just ran into the same issue

BUG-e3182861ba51ed076d489d8d04caf74323d6ced0fcbab0fc49053575986a361c-20230925161828Z-33594889d94f5949

**Comment by SamLMB** [comment]
Exact same issues on Android 11, phone and tablet. Same steps to reproduce and same tailscale verison 1.48.2.

Bug report on phone while android reports issue with always-on VPN and tailscale is STOPPED: `BUG-f2a24b72b6378f254a1bc182407d9af6fab16fc29e169330bf19008afd6145d2-20230921150018Z-ceeeeb5cda22e51d`

Bug report on phone when tailscale is subsequently set to active: `BUG-f2a24b72b6378f254a1bc182407d9af6fab16fc29e169330bf19008afd6145d2-20230921150030Z-089dd2e08459622b`

**Comment by andrius** [comment]
Same with Samsung Note20

**Comment by mtabin89** [comment]
Same with Samsung galaxy s10e (android 12) and Motorola moto g31w (android 11)

**Comment by r01k** [comment]
[Same here](https://github.com/tailscale/tailscale/issues/10013#issuecomment-1872564816).

**Comment by Johnny-Larue** [comment]
Happening on all Android phones, independent of manufacturer OS and Android version. Version 1.44.0 seems to have been the first version with the bug, as 1.42.0 is the last version that did not exhibit this behaviour.

**Comment by catzkorn** [comment]
Hi,

We recently begun work on Android again, we will update related issues when we have further information.

**Comment by tsmoneta** [comment]
That doesn't address the exit node issue though, does it? The exit node times out on open (I suspect an order of operations error), so Tailscale won't reselect it.

**Comment by scientiac** [comment]
If you're rooted.

Using @Immanuel31 's method, just put the following line in a file in the `.termux/boot/' directory after setting up termux and termux:boot.

```
su -c "am broadcast -n com.tailscale.ipn/.IPNReceiver -a com.tailscale.ipn.CONNECT_VPN"
```

(Make sure to update the packages and install `su` inside termux.)

**Comment by sersorrel** [comment]
root is not required for this. just run `am` normally.

**Comment by Casols** [comment]
> Hi,
> 
> We recently begun work on Android again, we will update related issues when we have further information.

@catzkorn any news on this subject or is it possible to install the 1.42.0 version somehow untill a fix is released?

**Comment by mtabin89** [comment]
> > Hi,
> > We recently begun work on Android again, we will update related issues when we have further information.
> 
> @catzkorn any news on this subject or is it possible to install the 1.42.0 version somehow untill a fix is released?

I wasn't target of your question but yes, downgrade will work (I've done it on all of my devices today). Just download apk 1.42.0 from whatever site you use (I used apkmirror), check for viruses (you can use virustotal), install, enable pernament VPN on your phone and turn off autoupdate in google play. 

That's it, you are done.

**Comment by ENTPRESTIGIOUS** [comment]
Same issue and it's very annoying.

**Comment by mdoh66** [comment]
Same issue on a Pixel 6 and Pixel 6 Pro

**Comment by 316filip** [comment]
I received an update two days ago and I haven't noticed this problem since. Also the UI overhaul looks great!

**Comment by ztmr** [comment]
I have very similar issue, but I cannot tell if that is actually a Tailscale itself issue.

Every morning I get plenty of notifications that something cannot fetch calendar, mails, IP telephony cannot register, etc. This basically makes me completely offline until I actually go and fiddle with the Tailscale app. Very annoying. It might be related to OS auto-updates installed overnight followed by a reboot.
What is strange is that irrespective of the Tailscale being connected or not, the Android UI keeps bugging me with a notification that "VPN has disconnected." he only way to get rid of that is to click on the "settings" button in that dialogue, which opens Tailscale app -- and there it looks like it is enabled already! No matter what I do, only then the dialogue disappears.

I would think that the Android system is simply stuck confused while the Tailscale has connected meanwhile, but why would the apps throw so many connectivity-related issues until I do something?

Has anyone seen this before? Is it worth talking to the GrapheneOS team instead?

* Platform: GrapheneOS/Pixel7Pro.
* Settings:
  * Always on VPN: enabled
  * Block connections outside VPN: disabled (because there is no fine-grained control to make exceptions at the Android end)

App info:
```
Version 1.80.0-t4f4686503-gb1405a1d1

com.tailscale.ipn
versionCode 358

targetSdk 34
minSdk 26

Installed: 15 May 2024; 23:48
Updated: 1 Feb 2025; 01:10
```
