### ISSUE TITLE
Windows command line update not working as Adminstrator

### ISSUE THREAD

**Issue by hrcdigital** [tailscale/tailscale#9456]
### What is the issue?

Windows 10 Pro.
Installed as the user: user.
The user is the Administrator and has 100% Administrator rights.
When trying to update Tailscale from command prompt and logged in as an administrator it's not updating.
Message: must run as Administrator.

### Steps to reproduce

1. User Windows 10 Pro.
2. Use a local account
3. Call the user: user
4. Give the the user Adminstrator rights.
5. Always login using password.
6. Install connector as the user (Administrator)
7. Try to update Tailscale via command prompt

### Are there any recent changes that introduced the issue?

No

### OS

Windows

### OS version

10 Pro

### Tailscale version

1.48.1

### Other software

Windows security
![5661](https://github.com/tailscale/tailscale/assets/40270961/1692974f-78da-47b7-ab02-d22d1c96ba24)

**Comment by bradfitz** [comment]
That user is _in_ the Administrator group but by default when you run programs in Windows as an admin user, you don't run _as_ the Administrator. 

For now, when starting `cmd.exe`, right click and start it with "Run as Administrator" instead of just the default "Run".

But we could probably make that error message instead pop up one of those UAC elevation prompts.

/cc @awly @dblohm7

**Comment by hrcdigital** [comment]
Thanks Brad,
Now it's working.
The goal is to automate the updates.
We have done many installs using Acronis backup and security..
This has a silent update system.
Always up to date.

Regards,
Raymond

**Comment by bradfitz** [comment]
Yes, we're working on auto-updates. It's tracked in another bug and making progress.

**Comment by awly** [comment]
I couldn't find a way to execute a simple subprocess on Windows with UAC prompt.
Doing that with `windows.ShellExecute` always creates a brand new window, without an obvious way to pipe output back to our main cmd.exe window. The window also closes right after the command finishes, losing all output.

Since I can't make the UX acceptable with UAC prompt. But I can at least improve the error message: https://github.com/tailscale/tailscale/pull/10043
