### ISSUE TITLE
No connection when using Mullvad exit node on iPhone (iOS)

### ISSUE THREAD

**Issue by SDeLaVida** [tailscale/tailscale#9503]
# What is the issue?

When Tailscale is enabled with a Mullvad exit node, I lose the ability to browse the public internet.

It might be some bug related to dns.

# Things I have tried

Override local dns is enabled in settings

Magic DNS has been enabled and disabled and it has no effect.

# Steps to reproduce

Enable Tailscale with a Mullvad exit node on an iPhone. 

Internet connectivity is confirmed.

Go to an app or the browser and then you can't connect to any website or service

I purchased a subscription to Mullvad through Tailscale and enabled a Mullvad exit node.

Tested on my iPad and it does work on that device.

# OS

iOS

# OS version

Both 17.0 and 16.x (whatever was the newest version) on a iPhone 11 Pro 

# Tailscale version

1.48.2

# Other software

None of the listed programs.

# Bug report

BUG-5b46368a9fc87d75e69745b37454773bb83a3d0860d4ee936b3668b28a163d40-20230921163929Z-1978193863d31169

**Comment by arunsathiya** [comment]
Since you are on Tailscale 1.48.2, you'll have to set up one of these two: https://tailscale.com/kb/1258/mullvad-exit-nodes/#important-dns-considerations

I assume your Tailscale version on the iPad is different?

**Comment by dratner** [comment]
I had the same issue...I originally thought it was because I also use next dns but it persisted after I disabled next dns. I'll try the co fig change above.

**Comment by seborama** [comment]
FWIW, I had this issue too. To resolve it, I deleted my problem device from the registered devices on tailscale.com (web) > Settings > Mullvad VPN - don’t forget to press Save.

After a few minutes, my device kicked me from the Exit Node because it was no longer registered (since I removed it in the previous). Once this had completed, I added my device again and waited another couple of minutes and finally configured the device back to use the Exit node. No more issue.

You may also want to try to switch to Mullvad DNS servers (via the tailscale web interface and then back to NextDNS (if that’s normally your DNS config). Make sure you either enable Allow Local Network Access on the device’s Exit node config, or enable (on the web settings) DNS > Enable override local DNS.
