### ISSUE TITLE
Can't connect when my network has a MITM certificate

### ISSUE THREAD

**Issue by guilhem** [tailscale/tailscale#9570]
### What is the issue?

My daemon fail with:
```
Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=74": x509: certificate signed by unknown authority
```

I expect it to use a cached information, because tailscale tunnel work fine after.

### Steps to reproduce

Hijack certificate of https://controlplane.tailscale.com

### OS

Linux

### Tailscale version

1.50.0

### Bug report

BUG-3434132e99e874ef8600679d70cc2c646c004cd048c2fe277f9131f156d0c2fa-20230928095920Z-6507a3bf8096ac8e

**Comment by DentonGentry** [comment]
> Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=74": x509: certificate signed by unknown authority
> I expect it to use a cached information, because tailscale tunnel work fine after.

That is not how TLS works. It isn't fetching some information once, it verifies that the remote site is who it says it is.
Tailscale works even after this problem because the controlplane is not essential for moment-to-moment operation, nodes make direct connections to each other with the information they have. Inability to contact the control plane means that newly added nodes will not be propogated to the rest of the tailnet, removed nodes will not immediately be removed, etc.

There is a potentially hostile MITM attempting to hijack controlplane.tailscale.com. You need to address that. It might be a Fortinet or other security appliance attempting to inspect traffic by substituting its own certificate.

**Comment by guilhem** [comment]
Yes there is MITM (it's in the title).
I was just thinking that tailscale can just "bypass" this problem and use the nodes and key in cache.
After VPN opened with an exit node, CP can be accessed without MITM problem.
