### ISSUE TITLE
Links in "Welcome To Tailscale" email are insecure

### ISSUE THREAD

**Issue by nmhub** [tailscale/tailscale#9633]
### What is the issue?

- After signing up, an email, "Welcome To Tailscale", is sent.
- All the links in the email point to http://email.tailscale.com/ domain, which is not over HTTPS
- Web browsers will warn users that it is insecure to click through, which is a jarring experience
- Also, MITM attacks are prevalent with HTTP 

### Steps to reproduce

1. Sign up to a new account at https://login.tailscale.com/start
2. Receive email, "Welcome To Tailscale"
3. View links in the email to verify HTTP URLs

### OS

macOS

### Other software

GMail

**Comment by ollytom** [comment]
I have no idea why I replied to this, think I had too strong of a morning coffee on a Saturday lol.

This is because links go through a tracking service [customer.io](https://customer.io/docs/journeys/getting-started-overview/):

	$ host email.tailscale.com
	email.tailscale.com is an alias for e.customeriomail.com.
	e.customeriomail.com is an alias for track.customer.io.
	...

So why not just use HTTPS in the mail links?
The server at customer.io serves a wildcart TLS certificate for `*.customer.io`,
which does not match `email.tailscale.com`.
Speculating: to minimise infra and avoid needing to run a server at `email.tailscale.com` which proxies/redirects requests,
they've just set a CNAME record in DNS and use plain HTTP.

Why use `email.tailscale.com` at all instead of `customer.io` URLs?
Speculating (again): helps portability between service providers.
If at some point in the future you want to swap from `customer.io` to something else,
all the links (and code) still work.

**Comment by bradfitz** [comment]
Sorry, we forgot to reply here. This was a mistake when configuring a third party email tool. We've made sure to ask everybody to watch out for this class of mistake in the future.

We've stopped using that tool and I'm told the new tool we're moving to does this better.
