### ISSUE TITLE
New tailscale Cert does not renew  if old certifact has not expired yet

### ISSUE THREAD

**Issue by TakingTaker** [tailscale/tailscale#9666]
### What is the issue?

Requesting a new certificate using the command Tailscale cert where the new certificate is giving me the same expired dates as the old(in this case the old certificate hasn't expired yet)

### Steps to reproduce

1.) sudo tailscale cert --cert-file <File name>  --key-file <file name> dnsAddress
2.) openssl x509 -in <filename> -noout -dates 

### Tailscale version

1.50.1

**Comment by bradfitz** [comment]
That's intentional by design.

It caches it in tailscaled and always returns the cert immediately if it's still valid. But if it's getting close the expiry time (per https://www.ietf.org/archive/id/draft-aaron-acme-ari-02.html etc) then it'll start an async renewal in the background so a future call to `tailscale cert` gets a new one.

This means you can cron a regular fetch of it every 30 seconds if you wish and it won't exhaust your ACME quota. (or fetch the cert on each incoming HTTP request, even)

Did you have a problem that led you to this?

**Comment by TakingTaker** [comment]
> That's intentional by design.
> 
> It caches it in tailscaled and always returns the cert immediately if it's still valid. But if it's getting close the expiry time (per https://www.ietf.org/archive/id/draft-aaron-acme-ari-02.html etc) then it'll start an async renewal in the background so a future call to `tailscale cert` gets a new one.
> 
> This means you can cron a regular fetch of it every 30 seconds if you wish and it won't exhaust your ACME quota. (or fetch the cert on each incoming HTTP request, even)
> 
> Did you have a problem that led you to this?

Okay I see. Thanks for verifying.
