### ISSUE TITLE
Apple TV - select only some apps to be routed in vpn not all apps with  [Tailscale]

### ISSUE THREAD

**Issue by traian658** [tailscale/tailscale#9760]
### What are you trying to do?

okay seems like is working now vpn on apple tv 
I need find a way to select only some apps to be routed in vpn not all apps with [Tailscale]

### How should we solve this?

have no idea maybe some tulneling solution for individual apps 

### What is the impact of not solving this?

people with connet or disconect the vpn all the time but with this future you can ensure people will stay connected for routing traffic

**Comment by agottardo** [comment]
We cannot build this as part of Tailscale due to Apple limitations, so I am going to close this. What you're requesting is a _per-app VPN_. On iOS, an app must have been installed by the MDM server to use a per-app VPN, and the VPN app itself must have been installed by the MDM server with a VPN configuration listing the per-app VPN rules. Tailscale cannot list the apps available on the device or declare itself as a per-app VPN.

I doubt per-app VPN is supported on Apple TV anyways, as I couldn't find any docs mentioning it. [Officially](https://support.apple.com/en-ca/guide/deployment/depae3d361d0/web), this only works on iOS, iPadOS and macOS. If you really want to give this a try on tvOS, you can setup a MDM server and push down a Tailscale VPN configuration that is per-app, and see whether the Apple TV picks it up. 

Closing.
