### ISSUE TITLE
Tailscale IP registering in Windows DNS regardless of settings

### ISSUE THREAD

**Issue by Rychveldir** [tailscale/tailscale#9775]
### What is the issue?

I have windows domain joined clients (Windows 10 and 11) and when tailscale is active, the tailscale ip is updated in the windows dhcp dns along with the local ip:
![image](https://github.com/tailscale/tailscale/assets/7063808/2f48a601-8c7d-4432-8fdf-c345f51a26af)
The windows adapter setting is off:
![image](https://github.com/tailscale/tailscale/assets/7063808/868c2d3b-261c-46da-a00e-5ce0a91f79e3)
And the registry key is present for this connection:
![image](https://github.com/tailscale/tailscale/assets/7063808/d713d349-3aed-4dd2-9ae0-63e25e46dfea)

Yet still, it registers.

### Steps to reproduce

Install tailscale on any domain joined dhcp enabled windows client, to a lookup for that host.

### OS

Windows

### OS version

Windows 10 and 11

### Tailscale version

1.50.1

### Bug report

BUG-754201b2beca6c18a45191f2323b2e4cb7b18965b20ecdfa603b9499d2c10e71-20231012154622Z-01a9d51c7b82f0cc

**Comment by 2manyvcos** [comment]
We tested a lot of settings to try to fix this issue.
Ultimately, we think that we found a solution.

In the [microsoft documentation](https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/enable-disable-dns-dynamic-registration#other-settings) there is a setting described for changing the maximum number of addresses to be registered per interface:

```
Registry Key:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Adapters\<Interface name>\MaxNumberOfAddressesToRegister
Data type: REG_DWORD
Range: 0x0 - 0xFFFFFFFF
Default value: 0x1
Scope: Affects this adapter only
```

Microsoft states that setting this key to `0x0` will result in not registering any IP addresses for the specified interface, which we did for the Tailscale interface.

However, for the setting to take effect, it is documented that a reboot is required.
Unfortunately, when doing so, the Tailscale interface is reconfigured and the registry key is eventually being removed.

We were able to workaround this case by doing the following:
- Connect to Tailscale
- Change the Registry key `MaxNumberOfAddressesToRegister` for the Tailscale interface to `0x0`
- Open Windows Control Panel
- Go to "Network and Internet" -> "Network and Sharing Center"
- Select the Tailscale Interface
- Click on "Properties" -> "Internet Protocol Version 4"
- Select "Obtain an IP address automatically"
- Click "OK", "OK", "Close"

Now, because the adapter's settings were changed, the previously configured Registry key `MaxNumberOfAddressesToRegister` also takes effect.

You can validate that the setting now works by manually removing the DNS entries for the host from your DNS server and executing the following command on the host:
```sh
ipconfig /registerdns
```

Now, there should be new DNS entries for the host in the DNS server, but none for the Tailscale IP.


I think if the Tailscale service would configure this key when setting up the Interface adapter, the problem should be resolved.
