### ISSUE TITLE
tvOS: No Network Detected when disconnecting Tailnet using Home menu, Tailscale then automaticaly reconnects

### ISSUE THREAD

**Issue by elvisimprsntr** [tailscale/tailscale#9837]
### What is the issue?

Using tvOS VPN status menu to disconnect Tailscale does not function as previous builds
Note: My ATV4Kg2 is wired Ethernet

### Steps to reproduce

1. Connect to Tailnet using the Tailscale app
2. Go to Home Screen
3. Press and hold the Home button, then swipe left over VPN icon.
4. Swipe down and select connection status
5. Observe Tailscale briefly disconnect and reconnects. 

### Are there any recent changes that introduced the issue?

tvOS 17.1b3
Tailscale 1.51.64

### OS

tvOS

### OS version

tvOS 17.1b3 (21K5064b)

### Tailscale version

1.51.64

### Screen Record

https://github.com/tailscale/tailscale/assets/1215508/ec327d6b-421d-4cc7-86d9-9603149e1386

**Comment by elvisimprsntr** [comment]
I Installed a number of previous TS versions back to 1.49.27 on tvOS 17.1 and observed the same symptoms, which did not occur on tvOS 17.0.  So perhaps this is was introduced in tvOS 17.1

**Comment by agottardo** [comment]
Thanks for testing with the older builds. The behaviour on our end has always been the same since the first version, so perhaps this might be something that changed in tvOS. We provide tvOS with an on-demand VPN rule to automatically restart the tunnel if Tailscale crashes, or tvOS terminates it. Based on your report, it _might_ be that tvOS 17.1 started not disabling VPN on-demand when disconnecting from the menu bar, although that does seem strange because it would mean the behaviour in tvOS 17.0 wasn't matching iOS. The proper way to disconnect Tailscale at the moment is to do so from the Tailscale app.

I have also seen the "No Network Detected" notification. It seems like they're much more proactive in pushing notifications during a network change compared to the past (networking seems to go out for a second while Tailscale starts).

I will look into fixing this issue when I get a chance, we should remove the on-demand rule also when triggering a disconnection from the OS, and that should solve this.

**Comment by elvisimprsntr** [comment]
Thanks.  

Just installed tvOS 17.1 RC (21B74) and observed the same behavior

**Comment by agottardo** [comment]
A fix for this issue has been merged, will ping when available in unstable.
