### ISSUE TITLE
DNS resolution fails with DNS pointing to Tailscale IPs and Magic DNS enabled

### ISSUE THREAD

**Issue by itorres** [tailscale/tailscale#993]
I have several Tailscale nodes. I have setup a PiHole DNS server in one of them and it works flawlessly:
![Screenshot_2020-12-05_00-01-05-ok](https://user-images.githubusercontent.com/131128/101224380-b1bad700-368e-11eb-9547-d59ed9aefd1a.png)

```
lissajous ~ % cat /etc/resolv.conf 
# resolv.conf(5) file generated by tailscale
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.110.192.69
search ts.xin.cat
lissajous ~ % dig  cotads.adscale.de +short
0.0.0.0
```

But when I enable Magic DNS resolv.conf changes to 100.100.100.100 and the DNS resolution fails:
![Screenshot_2020-12-05_00-00-21](https://user-images.githubusercontent.com/131128/101224330-9223ae80-368e-11eb-9216-a59bc45b80b4.png)

```
lissajous ~ % cat /etc/resolv.conf         
# resolv.conf(5) file generated by tailscale
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.100.100.100
search itorres.net.beta.tailscale.net. ts.xin.cat
lissajous ~ % dig  cotads.adscale.de +short

; <<>> DiG 9.16.1-Ubuntu <<>> cotads.adscale.de +short
;; global options: +cmd
;; connection timed out; no servers could be reached
```

Furthermore, if  we add  a non-Tailscale server to the nameserver list we get resolution with Magic DNS enabled, but it only queries the external nameserver as can be seen in tcpdump:

Only 100.110.192.69 in the list of nameservers:
```
23:32:27.471652 IP (tos 0x0, ttl 64, id 22322, offset 0, flags [none], proto UDP (17), length 86)
    100.104.35.61.52428 > 100.100.100.100.domain: [udp sum ok] 40096+ [1au] A? cotads.adscale.de. ar: . OPT UDPsize=4096 (58)
```
Adding 1.1.1.1 to the list of nameservers:
```
23:33:48.987167 IP (tos 0x0, ttl 64, id 32968, offset 0, flags [none], proto UDP (17), length 86)
    100.104.35.61.52450 > 100.100.100.100.domain: [udp sum ok] 19306+ [1au] A? cotads.adscale.de. ar: . OPT UDPsize=4096 (58)
23:33:48.997367 IP (tos 0x0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 181)
    100.100.100.100.domain > 100.104.35.61.52450: [udp sum ok] 19306 q: A? cotads.adscale.de. 5/0/1 cotads.adscale.de. CNAME d285sbdaklqe28.cloudfront.net., d285sbdaklqe28.cloudfront.net. A 13.224.119.108, d285sbdaklqe28.cloudfront.net. A 13.224.119.68, d285sbdaklqe28.cloudfront.net. A 13.224.119.43, d285sbdaklqe28.cloudfront.net. A 13.224.119.91 ar: . OPT UDPsize=1232 (153)
```

This is with Ubuntu 20.04.01 TLS in both nodes running Tailscale 1.2.8
```
lissajous ~ % tailscale version
1.2.8
  tailscale commit: cde3a23b6649ed448a9a94bd776043fb09e966d5
  other commit: 1f7ecb611d82fb6f95f6a65fd61fc2265f98dc37
  go version: go1.15.4-tsf9db43b
```

**Comment by arunsathiya** [comment]
I can reproduce the same situation. With magic DNS enabled, mac OS not connected to Tailscale resolves with my router DNS:

```
➜  ~ cat /etc/resolv.conf
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
nameserver 192.168.0.1
```

With magic DNS enabled again, connecting to Tailscale shows 100.100.100.100 to be the DNS resolver:

```
➜  ~ cat /etc/resolv.conf
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
search arun.hey.com.beta.tailscale.net
nameserver 100.100.100.100
```

And queries fail.

**Comment by torenzunza** [comment]
Same thing here. Just a few details of the testbed for the sake of clarity:

1. DNS query enforcement policies have been applied in the internet facing firewall, so that no other machine than the sinkhole (pi-hole) can query external DNS resolvers. A standard machine can only query the sinkhole.

2. Several nameservers have been added in the tailscale management portal, being the first one the pi-hole's tailscale IP address, plus openDNS's public servers.

3. When magic DNS is disabled, tailscale overwrites the resolv.conf file with all the additional DNS resolvers configured in the management portal. No DNS proxy is locally listening on 100.100.100.100, and the queries are routed along the paths suitable for each one of the DNS destinations, meaning that queries for the DNS sinkhole (pi-hole) towards its tailscale network interface IP address are originated also in the local tailscale interface address (and thus, the source IP address matches what the tailscale overlay network expects), and names are properly solved. It works (but remember, no magic DNS :( ).

```
18:33:04.844751 IP 100.116.225.122.58052 > 100.80.249.110.53: 18292+ [1au] A? www.keepersecurity.com. (63)
18:33:04.853303 IP 100.80.249.110.53 > 100.116.225.122.58052: 18292 1/0/1 A 52.204.14.59 (67)
18:33:07.735419 IP 100.116.225.122.53907 > 100.80.249.110.53: 58367+ [1au] A? www.keepersecurity.com. (63)
18:33:07.743009 IP 100.80.249.110.53 > 100.116.225.122.53907: 58367 1/0/1 A 52.204.14.59 (67)
18:33:09.158083 IP 100.116.225.122.44869 > 100.80.249.110.53: 21214+ [1au] A? www.keepersecurity.com. (63)
18:33:09.164213 IP 100.80.249.110.53 > 100.116.225.122.44869: 21214 1/0/1 A 52.204.14.59 (67)
18:33:10.327876 IP 100.116.225.122.52054 > 100.80.249.110.53: 14014+ [1au] A? www.keepersecurity.com. (63)
18:33:10.333495 IP 100.80.249.110.53 > 100.116.225.122.52054: 14014 1/0/1 A 52.204.14.59 (67)
```

4. When magic DNS is enabled, the local tailscale DNS proxy listens on 100.00.100.100 IP address, and forwards any DNS queries not solvable by itself (anything outside the tailscale overlay network) to the DNS servers defined in the portal, BUT, this time it uses its local IP address as the source of the queries, so not even one of the configured servers work (the tailscale interface of pi-hole cannot be reached on LAN, and public DNS queries are blocked by the firewall to enforce the use of the sinkhole). This situation can be solved including a fourth nameserver (pi-hole's LAN interface address) in the management portal, but only works for this specific local LAN; if not on this LAN, queries can only be routed to public servers (as long as pi-hole cannot be reached because the queries' source is local LAN), and if this second LAN also enforces DNS resolution to local DNS resolvers, no DNS queries will be solved until you include the local DNS in the nameserver list also. It requres an ad-hoc configuration for each of the LANs visited when roaming.

``` 
18:59:07.773567 IP 100.116.225.122.34809 > 100.100.100.100.53: 57439+ [1au] A? www.keepersecurity.com. (63)
18:59:07.773693 IP 192.168.215.33.35789 > 100.80.249.110.53: 57439+ [1au] A? www.keepersecurity.com. (63)
18:59:07.773745 IP 192.168.215.33.47082 > 208.67.220.220.53: 57439+ [1au] A? www.keepersecurity.com. (63)
18:59:07.773768 IP 192.168.215.33.35789 > 208.67.222.222.53: 57439+ [1au] A? www.keepersecurity.com. (63)
18:59:12.773024 IP 100.116.225.122.34809 > 100.100.100.100.53: 57439+ [1au] A? www.keepersecurity.com. (63)
18:59:12.773425 IP 192.168.215.33.48222 > 100.80.249.110.53: 57439+ [1au] A? www.keepersecurity.com. (63)
18:59:12.773538 IP 192.168.215.33.34306 > 208.67.220.220.53: 57439+ [1au] A? www.keepersecurity.com. (63)
18:59:12.773591 IP 192.168.215.33.35183 > 208.67.222.222.53: 57439+ [1au] A? www.keepersecurity.com. (63)
18:59:17.772986 IP 100.116.225.122.34809 > 100.100.100.100.53: 57439+ [1au] A? www.keepersecurity.com. (63)
18:59:17.773241 IP 192.168.215.33.48222 > 100.80.249.110.53: 57439+ [1au] A? www.keepersecurity.com. (63)
18:59:17.773367 IP 192.168.215.33.58834 > 208.67.220.220.53: 57439+ [1au] A? www.keepersecurity.com. (63)
18:59:17.773413 IP 192.168.215.33.60351 > 208.67.222.222.53: 57439+ [1au] A? www.keepersecurity.com. (63)

``` 
Queries time out...

```
dig www.keepersecurity.com

; <<>> DiG 9.16.1-Ubuntu <<>> www.keepersecurity.com
;; global options: +cmd
;; connection timed out; no servers could be reached
```
...until a local reachable DNS nameserver (192.168.215.15) is configured:

```
18:57:31.180359 IP 100.116.225.122.45597 > 100.100.100.100.53: 5764+ [1au] A? www.keepersecurity.com. (63)
18:57:31.180551 IP 192.168.215.33.47935 > 100.80.249.110.53: 5764+ [1au] A? www.keepersecurity.com. (63)
18:57:31.180624 IP 192.168.215.33.56626 > 208.67.220.220.53: 5764+ [1au] A? www.keepersecurity.com. (63)
18:57:31.180653 IP 192.168.215.33.60204 > 208.67.222.222.53: 5764+ [1au] A? www.keepersecurity.com. (63)
18:57:31.180681 IP 192.168.215.33.41257 > 192.168.215.15.53: 5764+ [1au] A? www.keepersecurity.com. (63)
18:57:31.222847 IP 192.168.215.15.53 > 192.168.215.33.41257: 5764 1/0/1 A 50.16.125.19 (67)
18:57:31.222990 IP 100.100.100.100.53 > 100.116.225.122.45597: 5764 1/0/1 A 50.16.125.19 (67)
```
Until the fix @bradfitz suggests in [this thread](https://github.com/tailscale/tailscale/issues/1003), it will probably help a lot "just" making the local DNS proxy's forwarded queries when magicDNS is on come from the tailscale address if the destination is also a tailscale address. Unless I'm missing something, this trick should work on any network where we roam, allowing for magicDNS resolution as well as external resolution through the remote sinkhole.

Thanx,

   tor

**Comment by eh8** [comment]
I initially thought that this was a subnet problem, so I tried playing around with `tailscale up --advertise-route=X.X.X.X` to try and diagnose the issue, where `X.X.X.X` is the subnet where my Pi-hole resides. I think there is some kind of unintended loop behavior with `100.100.100.100` thrown into the mix, because the combination of Magic DNS successfully resolves hostnames but not internet hostnames i.e. google.com

**Comment by danderson** [comment]
Should now be fixed, and will roll out in Tailscale 1.8. You can test-drive things with the unstable package on linux, or building from source on macOS/windows. We're still working on applying the polish, so you might hit rough edges, but the situation you ran into should no longer occur.

For curiosity's sake, the root cause was that our in-process forwarding resolver (which we have to use on some OSes/configs to implement split DNS) was marking its UDP sockets with the "bypass tailscale" option, meaning forwarded queries couldn't reach into your Tailscale network.

**Comment by LostKobrakai** [comment]
I'm on 1.8.1 on mac trying to use a custom dns server on the tailscale network. Without magic dns enabled it seems to work just fine. With magic dns enabled I cannot see my custom dns server's ip when running `scutil --dns` and dns resolution fails.

**Comment by 4gra** [comment]
I'm on 1.12.3 (Mac client, Linux exit node) and cannot combine the use of MagicDNS with an exit node.

- If I use one or the other of these features on its own, everything works as expected.
- if I turn on MagicDNS *and* use my exit node, DNS resolution fails and I can only reach my Tailscale peers.

**Comment by ajmeese7** [comment]
Agreed with the above comment, I experience this still on 1.76.6 when running on the latest Windows 11.
